### ISSUE TITLE
Incompatible library version: nokogiri.bundle requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0 

### ISSUE THREAD

**Issue by joedborg** [hashicorp/vagrant#10176]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version
2.1.4

### Host operating system
MacOS

### Guest operating system
CentOS

### Vagrantfile
Not needed

### Debug output
```
/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Users/joe/.vagrant.d/gems/2.4.4/gems/nokogiri-1.8.2/lib/nokogiri/nokogiri.bundle, 9): Library not loaded: @rpath/libxml2.dylib (LoadError)
  Referenced from: /Users/joe/.vagrant.d/gems/2.4.4/gems/nokogiri-1.8.2/lib/nokogiri/nokogiri.bundle
  Reason: Incompatible library version: nokogiri.bundle requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0 - /Users/joe/.vagrant.d/gems/2.4.4/gems/nokogiri-1.8.2/lib/nokogiri/nokogiri.bundle
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/joe/.vagrant.d/gems/2.4.4/gems/nokogiri-1.8.2/lib/nokogiri.rb:32:in `rescue in <top (required)>'
	from /Users/joe/.vagrant.d/gems/2.4.4/gems/nokogiri-1.8.2/lib/nokogiri.rb:28:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/joe/.vagrant.d/gems/2.4.4/gems/fog-xml-0.1.3/lib/fog/xml.rb:2:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/joe/.vagrant.d/gems/2.4.4/gems/fog-1.42.0/lib/fog.rb:13:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/joe/.vagrant.d/gems/2.4.4/gems/vagrant-aws-0.7.2/lib/vagrant-aws/action/connect_aws.rb:1:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/joe/.vagrant.d/gems/2.4.4/gems/vagrant-aws-0.7.2/lib/vagrant-aws/action.rb:97:in `block in action_read_state'
	from /Users/joe/.vagrant.d/gems/2.4.4/gems/vagrant-aws-0.7.2/lib/vagrant-aws/action.rb:95:in `tap'
	from /Users/joe/.vagrant.d/gems/2.4.4/gems/vagrant-aws-0.7.2/lib/vagrant-aws/action.rb:95:in `action_read_state'
	from /Users/joe/.vagrant.d/gems/2.4.4/gems/vagrant-aws-0.7.2/lib/vagrant-aws/provider.rb:16:in `action'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/machine.rb:196:in `block in action'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/machine.rb:190:in `block in action'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/machine.rb:194:in `action'
	from /Users/joe/.vagrant.d/gems/2.4.4/gems/vagrant-aws-0.7.2/lib/vagrant-aws/provider.rb:32:in `state'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/machine.rb:526:in `state'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/machine.rb:146:in `initialize'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/vagrantfile.rb:79:in `new'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/vagrantfile.rb:79:in `machine'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/environment.rb:719:in `machine'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/plugin/v2/command.rb:186:in `each'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/plugins/commands/up/command.rb:87:in `execute'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/cli.rb:54:in `execute'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/environment.rb:294:in `cli'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/bin/vagrant:164:in `<main>'
```

### Expected behavior
Box should have come up.

### Actual behavior
Failure with above message

### Steps to reproduce
1. `vagrant up`

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- https://github.com/Homebrew/homebrew-cask/issues/51632

**Comment by chrisroberts** [comment]
Hi there,

I've done a fresh install of 2.1.4 and have been unable to reproduce the error you are encountering. Would you please try removing all plugins (`vagrant plugin expunge --force`) and installing the vagrant-aws plugin again and see if the error persists.

Thanks!

**Comment by joedborg** [comment]
Hey @chrisroberts,

That's fixed it for me, thanks for the heads up!

**Comment by dec5e** [comment]
@chrisroberts thanks for your comment, it worked!

As far as I remember it's not the first time I have such problem during Vagrant update. And I have to google every time to find solution. It would be nice if Vagrant would be able to fix such problems automatically. Or at least suggest a workaround  to user instead of just throwing out Ruby exception.

**Comment by chrisroberts** [comment]
@dec5e Thanks for the feedback. I'll see what I can do about adding a more helpful error message when the state is encountered so that the solution is more obvious and doesn't require any searching to resolve.

Cheers!
