### ISSUE TITLE
Stderr: VBoxManage.exe: error: Nonexistent host networking interface

### ISSUE THREAD

**Issue by MBalazs90** [hashicorp/vagrant#10294]
### Virtualbox version
`5.2.18`

### Vagrant version
`Vagrant 2.1.5`

### Host operating system
`Windows 10 x64`

### Guest operating system
`ubuntu/xenial64`

### Vagrantfile
```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "base"
  config.vm.network "public_network" , ip: "192.168.1.169"
end
```

### Debug output
```
Stderr: VBoxManage.exe: error: Nonexistent host networking interface, name 'Broadcom 802.11n h├čl╦çzati adapter' (VE                                                           RR_INTERNAL_ERROR)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
>
ERROR vagrant: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "1794e8a1-6c18-41c5-91ed-da6fc23e1d21", "--type", "headless"]

Stderr: VBoxManage.exe: error: Nonexistent host networking interface, name 'Broadcom 802.11n h├čl╦çzati adapter' (VE                                                           RR_INTERNAL_ERROR)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

ERROR vagrant: C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/providers/virtualbox/driver/versi                                                           on_5_0.rb:714:in `block in start'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/util/retryable.rb:17:in `retryable'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/providers/virtualbox/driver/version_5_0.rb:704:i                                                           n `start'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/providers/virtualbox/action/boot.rb:16:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/providers/virtualbox/action/customize.rb:40:in `                                                           call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/providers/virtualbox/action/sane_defaults.rb:38:                                                           in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builtin/set_hostname.rb:16:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/providers/virtualbox/action/forward_ports.rb:31:                                                           in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/providers/virtualbox/action/network_fix_ipv6.rb:                                                           41:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/providers/virtualbox/action/network.rb:123:in `c                                                           all'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/providers/virtualbox/action/clear_network_interf                                                           aces.rb:26:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/providers/virtualbox/action/prepare_nfs_settings                                                           .rb:19:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builtin/synced_folders.rb:87:in `call                                                           '
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:i                                                           n `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/synced_folders/nfs/action_cleanup.rb:19:in `call                                                           '
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/providers/virtualbox/action/prepare_nfs_valid_id                                                           s.rb:12:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builtin/handle_forwarded_port_collisi                                                           ons.rb:49:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/providers/virtualbox/action/prepare_forwarded_po                                                           rt_collision_params.rb:30:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builtin/env_set.rb:19:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builtin/provision.rb:80:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/providers/virtualbox/action/clear_forwarded_port                                                           s.rb:15:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/providers/virtualbox/action/set_name.rb:19:in `c                                                           all'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/providers/virtualbox/action/clean_machine_folder                                                           .rb:17:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/providers/virtualbox/action/check_accessible.rb:                                                           18:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:95:in `block in finalize_ac                                                           tion'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builder.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/util/busy.rb:19:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builtin/call.rb:53:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:95:in `block in finalize_ac                                                           tion'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builder.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/util/busy.rb:19:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builtin/call.rb:53:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:95:in `block in finalize_ac                                                           tion'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builder.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/util/busy.rb:19:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builtin/call.rb:53:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builtin/box_check_outdated.rb:82:in `                                                           call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builtin/config_validate.rb:25:in `cal                                                           l'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/providers/virtualbox/action/check_virtualbox.rb:                                                           26:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:95:in `block in finalize_ac                                                           tion'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:95:in `block in finalize_ac                                                           tion'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builder.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/util/busy.rb:19:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builtin/call.rb:53:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builtin/config_validate.rb:25:in `cal                                                           l'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:95:in `block in finalize_ac                                                           tion'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:95:in `block in finalize_ac                                                           tion'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builder.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/util/busy.rb:19:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builtin/call.rb:53:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/providers/virtualbox/action/check_virtualbox.rb:                                                           26:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builder.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/util/busy.rb:19:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/machine.rb:239:in `action_raw'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/machine.rb:208:in `block in action'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/environment.rb:614:in `lock'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/machine.rb:194:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/machine.rb:194:in `action'
C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/batch_action.rb:82:in `block (2 levels) in r                                                           un'
 INFO interface: error: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "1794e8a1-6c18-41c5-91ed-da6fc23e1d21", "--type", "headless"]

Stderr: VBoxManage.exe: error: Nonexistent host networking interface, name 'Broadcom 802.11n h├čl╦çzati adapter' (VE                                                           RR_INTERNAL_ERROR)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "1794e8a1-6c18-41c5-91ed-da6fc23e1d21", "--type", "headless"]

Stderr: VBoxManage.exe: error: Nonexistent host networking interface, name 'Broadcom 802.11n h├čl╦çzati adapter' (VE                                                           RR_INTERNAL_ERROR)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
 INFO interface: Machine: error-exit ["Vagrant::Errors::VBoxManageError", "There was an error while executing `VBoxM                                                           anage`, a CLI used by Vagrant\nfor controlling VirtualBox. The command and stderr is shown below.\n\nCommand: [\"sta                                                           rtvm\", \"1794e8a1-6c18-41c5-91ed-da6fc23e1d21\", \"--type\", \"headless\"]\n\nStderr: VBoxManage.exe: error: Nonexi                                                           stent host networking interface, name 'Broadcom 802.11n h\u251C\u010Dl\u2566\u00E7zati adapter' (VERR_INTERNAL_ERROR                                                           )\r\nVBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole\r\n"]
```

### References
https://github.com/hashicorp/vagrant/issues/8967
https://github.com/hashicorp/vagrant/issues/8207

I tried to edit the .vbox file with the correct unicode values but it doesnt work.

**Comment by leaveye** [comment]
almost the same error, slightly different versions.

---

### VirtualBox version

- `5.2.16-123759`
-  `6.0.0-127566`

the same error. install new version after completely removing old version.

### Vagrant version

- `1.9.3`
- `2.2.2` ([x86_64.msi](https://releases.hashicorp.com/vagrant/2.2.3/vagrant_2.2.3_x86_64.msi))

first encounter on `1.9.3`, update to `2.2.2` and confirmed with that fix in #8967, do NOT solve it. (not completely uninstalled)

### Host operating system

`Windows 8.1 (zh-cn)`

did not try with another version / machine, since some other guest machines in use on it.

### Guest operating system

`debian stretch64`

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "debian/contrib-stretch64"
  config.vm.network "public_network", ip: "192.168.0.80"
  # or
  # config.vm.network "public_network"
  # produce the same error
end
```

### Debug output
full log [here](https://gist.github.com/leaveye/1d9b0073bfad3e83e0391694963c2d17), and a short version:
```text
Command: ["startvm", "f8f859fd-cdb7-40a6-83be-552789db83ce", "--type", "headless"]

Stderr: VBoxManage.exe: error: Nonexistent host networking interface, name 'Dell 鏃犵嚎 1704 802.11b/g/n (2.4GHz)' (VERR_INTERNAL_ERROR)

VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
```

### Expected behavior

the proper interface name according to VirtualBox GUI should be `Dell 无线 1704 802.11b/g/n (2.4GHz)`

### Actual behavior

we get `Dell 鏃犵嚎 1704 802.11b/g/n (2.4GHz)`

### References

- #8967

**Comment by leaveye** [comment]
No responsed for some days, after upgrading to 2.2.3, this issue persists.
So I have manually fix it in my environment. **NOT a portable way**.

I convert the encoding of interface name in [`virtualbox/driver/version_5_0.rb:read_bridged_interfaces()`](https://github.com/hashicorp/vagrant/blob/7927c39da90dae3f5be79e36ad9df3b4ad834ac1/plugins/providers/virtualbox/driver/version_5_0.rb#L416) in hardcode.

```ruby
            block.split("\n").each do |line|
              if line =~ /^Name:\s+(.+?)$/
                info[:name] = $1.to_s
                # encoding = "windows-#{chcp.scan(/\d+$/)}"  # adviced by google, but error: no chcp
                # encoding = Encoding.default_external  # actrually UTF-8
                encoding = 'GB18030'  # now work for my Windows 8 (zh-cn)
                # encoding = 'cp936'  # error: no converter
                # encoding = 'Unicode'  # error: no converter
                @logger.debug("==> name string:")
                @logger.debug("      was #{info[:name].encoding}: #{info[:name].inspect}")
                @logger.debug("      as #{encoding}: #{info[:name].encode(encoding).inspect}")
                info[:name] = info[:name].encode(encoding)
              elsif line =~ /^IPAddress:\s+(.+?)$/
```

then I got `VBoxManage` call:

```
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "modifyvm", "b93f9b90-a1de-41c0-8e01-45b807582fbd", "--nic1", "nat", "--nic2", "bridged", "--bridgeadapter2", "Dell \x{CEDE}\x{CFDF} 1704 802.11b/g/n (2.4GHz)", "--cableconnected2", "on"]
```

It's clearly that the internal encoding should be unified, which seems to be `UTF-8` for now. So I suspect the proper way is to determine the encoding OS is using and convert arguments just before calling `execute()`. And this idea was **removed** in commit 7b8ab87 by @chrisroberts .

As above code shown, the `Encoding.default_external` is `UTF-8`, should not be used directly. A more robust way to query encoding is necessary.

Thanks for your great work.

**P.S.** this is my first ruby code, apologize for lacking knowledge ahead. :nerd_face:

**Comment by MBalazs90** [comment]
so seems like this issue still persist

**Comment by MBalazs90** [comment]
@leaveye How can I fix it locally? Can you explain it?

**Comment by leaveye** [comment]
@MBalazs90 You may try like me:

- According to some search and try, as code shown in above post, my system (windows 8 zh-cn) use a encoding compatible with `GB18030`.
- VirtualBox 6 is in using, which inherited the interface from `virtualbox/driver/version_5_0.rb`.
- `read_bridged_interfaces()` handles the captured output of `VBoxManage.exe` call. which converted to UTF-8 automatically.

so its clear that a encoding conversion is needed ([original code](https://github.com/hashicorp/vagrant/blob/7927c39da90dae3f5be79e36ad9df3b4ad834ac1/plugins/providers/virtualbox/driver/version_5_0.rb#L416)):

```ruby
            block.split("\n").each do |line|
              if line =~ /^Name:\s+(.+?)$/
                info[:name] = $1.to_s
                info[:name] = info[:name].encode('GB18030')  # add this line is enough
              elsif line =~ /^IPAddress:\s+(.+?)$/
```

You may find the correct encoding and the corresponding provider code for your environment.

**Comment by MBalazs90** [comment]
any update on this issue?

**Comment by Vagrantin** [comment]
I'm getting the same issue with vagrant 2.2.2
As soon as I'm adding a bridged inteface, I'm getting this error message:  

```
Stderr: VBoxManage.exe: error: Nonexistent host networking interface, name '' (VERR_INTERNAL_ERROR)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
```

**Comment by VincentSurelle** [comment]
I'm also getting this issue in 2.2.7.

Any update on this ?
