### ISSUE TITLE
"Could not find 'vagrant_cloud'" after update to 2.2.0

### ISSUE THREAD

**Issue by der-eismann** [hashicorp/vagrant#10307]
### Vagrant version
```
sysop ~ vagrant -v
Vagrant 2.2.0
```

### Host operating system
[Solus 3](https://getsol.us/home/)

### Expected behavior
I was building a package for the Solus package manager and expected it to work fine after the upgrade from 2.1.5 to 2.2.0.

### Actual behavior
Vagrant is complaining that it can't find `vagrant_cloud` and therefore fails to start:
```
sysop ~ vagrant help
/usr/lib64/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'vagrant_cloud' (~> 2.0.0) among 53 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/sysop/.gem/ruby/2.3.0:/usr/lib64/ruby/gems/2.3.0', execute `gem env` for more information
	from /usr/lib64/ruby/2.3.0/rubygems/specification.rb:1442:in `block in activate_dependencies'
	from /usr/lib64/ruby/2.3.0/rubygems/specification.rb:1431:in `each'
	from /usr/lib64/ruby/2.3.0/rubygems/specification.rb:1431:in `activate_dependencies'
	from /usr/lib64/ruby/2.3.0/rubygems/specification.rb:1413:in `activate'
	from /usr/lib64/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
	from /usr/lib64/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /usr/lib64/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /usr/lib64/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /usr/lib64/ruby/gems/2.3.0/gems/vagrant-2.2.0/bin/vagrant:88:in `<top (required)>'
	from /usr/bin/vagrant:22:in `load'
	from /usr/bin/vagrant:22:in `<main>'
```
In the list of gems it is indeed missing, there is only the standard vagrant gem:
```
sysop ~ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.8)
builder (3.2.3)
childprocess (0.6.3)
concurrent-ruby (1.0.5)
did_you_mean (1.0.0)
domain_name (0.5.20170404)
erubis (2.7.0)
ffi (1.9.25)
ffi-win32-extensions (1.0.3)
gssapi (1.2.0)
gyoku (1.3.1)
hashicorp-checkpoint (0.1.5)
http-cookie (1.0.3)
httpclient (2.8.3)
i18n (0.8.0)
io-console (0.4.5)
json (1.8.3.1)
listen (3.1.5)
little-plugger (1.1.4)
log4r (1.1.10)
logging (2.2.2)
mime-types (3.1)
mime-types-data (3.2016.0521)
minitest (5.8.5)
multi_json (1.13.1)
net-scp (1.2.1)
net-sftp (2.1.2)
net-ssh (5.0.2)
net-telnet (0.1.1)
netrc (0.11.0)
nori (2.6.0)
power_assert (0.2.6)
psych (2.1.0.1)
rake (10.4.2)
rb-fsevent (0.10.3)
rb-inotify (0.9.10)
rb-kqueue (0.2.5)
rdoc (4.2.1)
rest-client (2.0.2)
ruby_dep (1.3.1)
rubyntlm (0.6.2)
rubyzip (1.2.2)
test-unit (3.1.5)
unf (0.1.4)
unf_ext (0.0.7.5)
vagrant (2.2.0)
wdm (0.1.1)
win32-file (0.8.2)
win32-file-security (1.0.10)
win32-file-stat (1.5.5)
winrm (2.2.3)
winrm-elevated (1.1.0)
winrm-fs (1.2.0)
```

### Steps to reproduce
1. Build vagrant 2.2.0 with `gem build` and `gem install`
2. Enter `vagrant help`
3. Fail

**Comment by der-eismann** [comment]
Alright, after opening the issue I noticed that `vagrant_cloud` was [added as a dependency](https://github.com/hashicorp/vagrant/blob/master/vagrant.gemspec#L35) and seems to be a [separate project](https://github.com/hashicorp/vagrant_cloud). I guess we will have to add it to the repo.
