### ISSUE TITLE
Vagrant VMWare Plugin Installation Fails with v2.2.0.

### ISSUE THREAD

**Issue by ladar** [hashicorp/vagrant#10312]
It seems that `vagrant plugin install vagrant-vmware-workstation` fails to install. Note this issue didn't occur with version 2.1.5, but does occur with version 2.2.0. 

At first glance, the problem apears to be with IPv6. Note that the host has IPv6 enabled by default, but I disable it using the command `sysctl net.ipv6.conf.all.disable_ipv6=1` before running `packer` or `vagrant` to avoid issues with some of the guest operating systems. The error stack message is:

```
[ladar@host vagrant]$ vagrant plugin install vagrant-vmware-workstation 
Installing the 'vagrant-vmware-workstation' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:811:in `send': Cannot assign requested address - sendto(2) for "2600:1700:3e40:3bb0::1" port 53 (Errno::EADDRNOTAVAIL)
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:811:in `send'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:673:in `request'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:529:in `block in fetch_resource'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:1133:in `block (3 levels) in resolv'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:1131:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:1131:in `block (2 levels) in resolv'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:1130:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:1130:in `block in resolv'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:1128:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:1128:in `resolv'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:520:in `fetch_resource'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:510:in `each_resource'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/resolv.rb:491:in `getresource'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/remote_fetcher.rb:105:in `api_endpoint'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/source.rb:47:in `api_uri'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/source.rb:183:in `load_specs'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/bundler.rb:424:in `block in validate_configured_sources!'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/source_list.rb:98:in `each'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/source_list.rb:98:in `each_source'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/bundler.rb:422:in `validate_configured_sources!'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/bundler.rb:330:in `internal_install'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/bundler.rb:128:in `install'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/plugin/manager.rb:138:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/plugin/manager.rb:148:in `install_plugin'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/commands/plugin/action/install_gem.rb:30:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/commands/plugin/command/install.rb:70:in `block in execute'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/commands/plugin/command/install.rb:69:in `each'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/commands/plugin/command/install.rb:69:in `execute'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/commands/plugin/command/root.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/cli.rb:54:in `execute'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.rb:291:in `cli'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/bin/vagrant:164:in `<main>'
```

The current network configuration is:

```
[ladar@darla vagrant]$ ifconfig 
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 0.0.0.0
        ether 02:42:ad:13:57:db  txqueuelen 0  (Ethernet)
        RX packets 13737  bytes 1179808 (1.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 18740  bytes 123807555 (118.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp0s25: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.210  netmask 255.255.255.0  broadcast 192.168.1.255
        ether 54:ee:75:84:86:87  txqueuelen 1000  (Ethernet)
        RX packets 16697399  bytes 23031042927 (21.4 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3446751  bytes 286566093 (273.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xb3900000-b3920000  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 10420  bytes 1569472 (1.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 10420  bytes 1569472 (1.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
        ether 52:54:00:93:15:68  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vmnet1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.16.255.1  netmask 255.255.255.0  broadcast 172.16.255.255
        ether 00:50:56:c0:00:01  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 51  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

vmnet8: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.16.155.1  netmask 255.255.255.0  broadcast 172.16.155.255
        ether 00:50:56:c0:00:08  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 51  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp3s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.198  netmask 255.255.255.0  broadcast 192.168.1.255
        ether 4c:eb:42:d2:d5:57  txqueuelen 1000  (Ethernet)
        RX packets 1718814  bytes 1629376113 (1.5 GiB)
        RX errors 0  dropped 349  overruns 0  frame 0
        TX packets 230138  bytes 35167845 (33.5 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

### Vagrant version
Vagrant v2.2.0

### Host operating system
CentOS 7.5

### Expected behavior
The vmware plugin should have installed.

### Actual behavior
The vmware plugin installation fails.

### Steps to reproduce
1. vagrant plugin install vagrant-vmware-workstation

**Comment by ladar** [comment]
Note that enabling IPv6 with `sysctl net.ipv6.conf.all.disable_ipv6=0` fixes the issue.

**Comment by briancain** [comment]
Not sure what's going on with your networking, but the vmware plugin is actually:

```
vagrant plugin install vagrant-vmware-desktop
```

**Comment by chrisroberts** [comment]
@ladar Yeah, the plugin is vagrant-vmware-desktop and you'll need the vagrant-vmware-utility service as well. Installation information can be found here: https://www.vagrantup.com/docs/vmware/installation.html

As for the DNS error that was generated, I haven't seen that previously but I'll do a little digging and see what was causing it.

**Comment by chrisroberts** [comment]
@ladar And if at all possible to provide a gist of the output from the plugin install command with the `--debug` flag when it errors out on that lookup, that would be super great.

**Comment by ladar** [comment]
@chrisroberts I uninstalled the vagrant-vmware-workstation plugin, installed the vmware utility package, updated my scripts to use the vagrant-vmware-desktop plugin, and can no longer reproduce issue with either plugin. I have a few other machines which will need updating. Should I test them? Or is the issue moot because the vagrant-vmware-workstation plugin is no longer supported?

**Comment by chrisroberts** [comment]
Well the original error you reported in this issue is a resolv error from within Ruby and related to ipv6. If you don't see it manifest again, then it may have just been transient. If you do encounter it again, and can reproduce it easily, capturing the output with `--debug` would be great so we can isolate the origin and prevent the error in the future.

And you are correct that vagrant-vmware-workstation plugin is no longer supported.
