### ISSUE TITLE
vagrant-vmware-desktop 2.0.2 crashed on halt

### ISSUE THREAD

**Issue by fnordfish** [hashicorp/vagrant#10498]
### Vagrant version
2.2.2

### Host operating system
macOS 10.14.2

### Guest operating system
ubuntu 1804

### Expected behavior
Does not crash

### Actual behavior

<details>
 <summary>`vagrant-vmware-desktop-2.0.2/lib/vagrant-vmware-desktop/driver.rb:749:in `rescue in rescue in stop': undefined local variable or method `state' for #<HashiCorp::VagrantVMwareDesktop::Driver::Base:0x0000000100d89a40> (NameError)`</summary>

```
$ vagrant halt
==> wdn: Running triggers before halt ...
==> wdn: Running trigger...
==> wdn: Unmounting guest from host
There is nothing mounted on /Users/robertschulze/vagrant_projects/wdn/mnt
==> wdn: Attempting graceful shutdown of VM...
    wdn: Guest communication could not be established! This is usually because
    wdn: SSH is not running, the authentication information was changed,
    wdn: or some other networking issue. Vagrant will force halt, if
    wdn: capable.
==> wdn: Stopping the VMware VM...
/Users/robertschulze/.vagrant.d/gems/2.4.4/gems/vagrant-vmware-desktop-2.0.2/lib/vagrant-vmware-desktop/driver.rb:749:in `rescue in rescue in stop': undefined local variable or method `state' for #<HashiCorp::VagrantVMwareDesktop::Driver::Base:0x0000000100d89a40> (NameError)
	from /Users/robertschulze/.vagrant.d/gems/2.4.4/gems/vagrant-vmware-desktop-2.0.2/lib/vagrant-vmware-desktop/driver.rb:741:in `rescue in stop'
	from /Users/robertschulze/.vagrant.d/gems/2.4.4/gems/vagrant-vmware-desktop-2.0.2/lib/vagrant-vmware-desktop/driver.rb:738:in `stop'
	from /Users/robertschulze/.vagrant.d/gems/2.4.4/gems/vagrant-vmware-desktop-2.0.2/lib/vagrant-vmware-desktop/action_farm.rb:580:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/robertschulze/.vagrant.d/gems/2.4.4/gems/vagrant-vmware-desktop-2.0.2/lib/vagrant-vmware-desktop/action_farm.rb:389:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/robertschulze/.vagrant.d/gems/2.4.4/gems/vagrant-vmware-desktop-2.0.2/lib/vagrant-vmware-desktop/action_farm.rb:389:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/robertschulze/.vagrant.d/gems/2.4.4/gems/vagrant-vmware-desktop-2.0.2/lib/vagrant-vmware-desktop/action_farm.rb:158:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/robertschulze/.vagrant.d/gems/2.4.4/gems/vagrant-vmware-desktop-2.0.2/lib/vagrant-vmware-desktop/action_farm.rb:447:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/robertschulze/.vagrant.d/gems/2.4.4/gems/vagrant-auto_network-1.0.3/lib/auto_network/action/request.rb:24:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/robertschulze/.vagrant.d/gems/2.4.4/gems/vagrant-vmware-desktop-2.0.2/lib/vagrant-vmware-desktop/action_farm.rb:305:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/machine.rb:239:in `action_raw'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/machine.rb:208:in `block in action'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/environment.rb:614:in `lock'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/machine.rb:194:in `call'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/machine.rb:194:in `action'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/plugins/commands/halt/command.rb:31:in `block in execute'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/plugin/v2/command.rb:238:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/plugin/v2/command.rb:232:in `each'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/plugins/commands/halt/command.rb:30:in `execute'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/cli.rb:58:in `execute'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/environment.rb:291:in `cli'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/bin/vagrant:164:in `<main>'
```
</details>

### Steps to reproduce
1. `up` a vmware guest
2. `halt` the vmware guest

**Comment by epackorigan** [comment]
with the vagrant-vmware-desktop-2.0.0 and the previous utility version (i'm not quite sure what i had before i upgraded to 1.0.6), i wasn't having issues like this.
(in my case, the guest are various versions of macos guests)

**Comment by epackorigan** [comment]
```
$ vagrant plugin install vagrant-vmware-desktop --plugin-version 2.0.1
Installing the 'vagrant-vmware-desktop --version '2.0.1'' plugin. This can take a few minutes...
Fetching: vagrant-vmware-desktop-2.0.1.gem (100%)
Successfully uninstalled vagrant-vmware-desktop-2.0.2
Installed the plugin 'vagrant-vmware-desktop (2.0.1)'!
```

was sufficient to get back to a more working system.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
