### ISSUE TITLE
vagrant cloud publish fails with cryptic message if specified box doesn't exist on disk

### ISSUE THREAD

**Issue by tas50** [hashicorp/vagrant#10510]
### Vagrant version
2.2.2

### Host operating system
macos 10.14

### Guest operating system
n/a

### Vagrantfile
n/a

### Debug output
https://gist.github.com/tas50/f59ed2fe79c4b3131e6ec432de24a2fb

### Expected behavior
I should get a message that the box I've specified doesn't exist on disk.

### Actual behavior
A rest error from the vagrant_cloud api gem

```
/opt/vagrant/embedded/gems/2.2.2/gems/vagrant_cloud-2.0.1/lib/vagrant_cloud/client.rb:55:in `rescue in request': 422 Unprocessable Entity - box parameter is required! (VagrantCloud::ClientError)
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant_cloud-2.0.1/lib/vagrant_cloud/client.rb:50:in `request'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant_cloud-2.0.1/lib/vagrant_cloud/box.rb:39:in `update'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/plugins/commands/cloud/publish.rb:103:in `rescue in publish_box'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/plugins/commands/cloud/publish.rb:97:in `publish_box'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/plugins/commands/cloud/publish.rb:64:in `execute'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/plugins/commands/cloud/root.rb:73:in `execute'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/cli.rb:58:in `execute'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/environment.rb:291:in `cli'
	from /opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/bin/vagrant:164:in `<main>'
```

### Steps to reproduce
1. vagrant cloud publish bento/opensuseleap-15 201812.15.0 virtualbox bogus.box
2. watch it error with a strange error message

**Comment by briancain** [comment]
Hey there @tas50 - This _should_ be fixed in the next release via https://github.com/hashicorp/vagrant/pull/10468

```
brian@localghost:vagrant-sandbox % be vagrant cloud publish briancain/test123 \                          ±[●][master] --force \
--release \
--description "a Vagrant box for doing things" \
--short-description "stuff" \
0.0.1 \
virtualbox \
../packer-templates/bento/builds/nope.box
The file you are attempting to upload does not exist. Please recheck
that the file exists and was passed in correctly.

File: ../packer-templates/bento/builds/nope.box
```
Cheers! :heart:

**Comment by tas50** [comment]
1 down. Thanks!
