### ISSUE TITLE
Provisioning with Ansible post start-up

### ISSUE THREAD

**Issue by sirtuxalot** [hashicorp/vagrant#10541]
### Vagrant version
Vagrant 2.2.2

### Host operating system
This is the operating system that you run locally.
Gentoo

### Guest operating system
This is the operating system you run in the virtual machine.
CentOS 6 and CentOS 7

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # create backuppc node
  config.vm.define :centos6 do |six_config|
    six_config.vm.box = "centos/6"
    six_config.vm.hostname = "centos6"
    six_config.vm.network :private_network, ip: "192.168.252.50"
    config.vm.provider "libvirt" do |vm|
      vm.cpus = 1
      vm.memory = 1024
    end
  end

  # create backuppc node
  config.vm.define :centos7 do |seven_config|
    seven_config.vm.box = "centos/7"
    seven_config.vm.hostname = "centos7"
    seven_config.vm.network :private_network, ip: "192.168.252.51"
    config.vm.provider "libvirt" do |vm|
      vm.cpus = 2
      vm.memory = 2048
    end
  end

  # Ansible Setup
  config.vm.provision "shell", inline: <<-SHELL
    # Install root public key
    mkdir -m 0700 /root/.ssh
    mv /vagrant/authorized_keys /root/.ssh/authorized_keys
    chmod 0600 /root/.ssh/authorized_keys
    chown -R root. /root/.ssh
  SHELL

  # Use Ansible provisioner, setting the inventory to use and playbook to run
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "ansible/site.yaml"
    ansible.inventory_path = "hosts"
    ansible.extra_vars = {
      ansible_user: "vagrant",
      repos_ip: "192.168.254.104",
      repos_server: "storage",
      domain_name: "domain.net",
    }
  end
end
```

### Debug output
```bash
==> centos7: Running provisioner: ansible...
/home/gjy0724/.vagrant.d/gems/2.4.5/gems/fog-libvirt-0.5.0/lib/fog/libvirt/requests/compute/list_domains.rb:9:in `lookup_domain_by_uuid': Call to virDomainLookupByUUID failed: internal error: client socket is closed (Libvirt::RetrieveError) 
   from /home/gjy0724/.vagrant.d/gems/2.4.5/gems/fog-libvirt-0.5.0/lib/fog/libvirt/requests/compute/list_domains.rb:9:in `list_domains' 
   from /home/gjy0724/.vagrant.d/gems/2.4.5/gems/fog-libvirt-0.5.0/lib/fog/libvirt/models/compute/servers.rb:15:in `get' 
   from /home/gjy0724/.vagrant.d/gems/2.4.5/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/driver.rb:65:in `get_domain' 
   from /home/gjy0724/.vagrant.d/gems/2.4.5/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/driver.rb:79:in `created?' 
   from /home/gjy0724/.vagrant.d/gems/2.4.5/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/provider.rb:101:in `state' 
   from /home/gjy0724/.vagrant.d/gems/2.4.5/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/wait_till_up.rb:105:in `terminate' 
   from /home/gjy0724/.vagrant.d/gems/2.4.5/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/wait_till_up.rb:101:in `recover' 
   from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:67:in `block in recover' 
   from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:64:in `each' 
   from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:64:in `recover' 
   from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-2.2.2/lib/vagrant/action/builtin/call.rb:61:in `recover' 
   from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:67:in `block in recover' 
   from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:64:in `each' 
   from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:64:in `recover' 
   from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:53:in `rescue in call' 
   from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:28:in `call' 
   from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-2.2.2/lib/vagrant/action/builder.rb:116:in `call' 
   from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-2.2.2/lib/vagrant/action/runner.rb:66:in `block in run' 
   from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-2.2.2/lib/vagrant/util/busy.rb:19:in `busy' 
   from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-2.2.2/lib/vagrant/action/runner.rb:66:in `run' 
   from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-2.2.2/lib/vagrant/machine.rb:239:in `action_raw' 
   from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-2.2.2/lib/vagrant/machine.rb:208:in `block in action' 
   from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-2.2.2/lib/vagrant/environment.rb:614:in `lock' 
   from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-2.2.2/lib/vagrant/machine.rb:194:in `call' 
   from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-2.2.2/lib/vagrant/machine.rb:194:in `action' 
   from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-2.2.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'```


### Expected behavior
Vagrant box start up and provisioned by ansible.  There are no issues at all using the same Vagrantfile with the exception of (ansible.compatibility_mode = "2.0") on Scientifiic Linux using v1.9.6.

### Actual behavior
Vagrant box start up but provisioning by ansible fails.  SSH directly into vagrant box also fails using key unless service is stopped with systemd or init script and manually restarted with (/usr/sbin/sshd -D -u0) but (vagrant ssh) still works

### Steps to reproduce
1. Just 'vagrant up centos7' or 'vagrant up centos6'

### References
None found

**Comment by sirtuxalot** [comment]
I do not expect this issue is specific to CentOS, I ran the same test using Ubuntu 16.04 and Debian 9 and the result was the same.  Although SSH into the vagrant box did work on both.

**Comment by briancain** [comment]
Hi there @sirtuxalot - this seems to be an issue with the libvirt plugin (or perhaps libvirt itself). That provider is a third party plugin, which can be found [here](https://github.com/vagrant-libvirt/vagrant-libvirt). I recommend opening an issue with them, as they might be able to provide more guidance. Thanks!
