### ISSUE TITLE
trun off swap cause vagrant up failed

### ISSUE THREAD

**Issue by pain400** [hashicorp/vagrant#10593]
### Vagrant version
```
Vagrant 2.2.0
```

### Host operating system
```
Darwin toto-MacBook-Pro.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
```

### Guest operating system
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### Vagrantfile
```ruby
boxes = [
  {
    :name => "c1",
    :eth1 => "192.168.1.5",
    :mem => "2048",
    :cpu => "2",
    :port => "6666"
  },
  {
    :name => "c2",
    :eth1 => "192.168.1.6",
    :mem => "2048",
    :cpu => "2",
    :port => "7777"
  },
  {
    :name => "c3",
    :eth1 => "192.168.1.7",
    :mem => "2048",
    :cpu => "2",
    :port => "5555"
  }
]

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_check_update = false

  boxes.each do |box|
    config.vm.define box[:name] do |config|
      config.vm.hostname = box[:name]

      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", box[:mem]]
        v.customize ["modifyvm", :id, "--cpus", box[:cpu]]
        v.name = box[:name]
      end

      config.vm.network "private_network", ip: box[:eth1]
    end
  end

end
```

### Expected behavior
What should have happened?

### Actual behavior
```
==> c1: Clearing any previously set forwarded ports...
==> c1: Clearing any previously set network interfaces...
==> c1: Preparing network interfaces based on configuration...
    c1: Adapter 1: nat
    c1: Adapter 2: hostonly
==> c1: Forwarding ports...
    c1: 22 (guest) => 2222 (host) (adapter 1)
==> c1: Running 'pre-boot' VM customizations...
==> c1: Booting VM...
==> c1: Waiting for machine to boot. This may take a few minutes...
    c1: SSH address: 127.0.0.1:2222
    c1: SSH username: vagrant
    c1: SSH auth method: private key
    c1: Warning: Connection reset. Retrying...
==> c1: Machine booted and ready!
==> c1: Checking for guest additions in VM...
    c1: No guest additions were detected on the base box for this VM! Guest
    c1: additions are required for forwarded ports, shared folders, host only
    c1: networking, and more. If SSH fails on this machine, please install
    c1: the guest additions and repackage the box to continue.
    c1: 
    c1: This is not an error message; everything may continue to work properly,
    c1: in which case you may ignore this message.
==> c1: Setting hostname...
==> c1: Configuring and enabling network interfaces...
/opt/vagrant/embedded/gems/2.2.0/gems/net-scp-1.2.1/lib/net/scp.rb:398:in `await_response_state': scp: /tmp/vagrant-network-entry-eth1-1547626036-0: Read-only file system (RuntimeError)
	from /opt/vagrant/embedded/gems/2.2.0/gems/net-scp-1.2.1/lib/net/scp.rb:369:in `block (3 levels) in start_command'
	from /opt/vagrant/embedded/gems/2.2.0/gems/net-ssh-5.0.2/lib/net/ssh/connection/channel.rb:323:in `process'
	from /opt/vagrant/embedded/gems/2.2.0/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:250:in `block in ev_preprocess'
	from /opt/vagrant/embedded/gems/2.2.0/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:540:in `each'
	from /opt/vagrant/embedded/gems/2.2.0/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:540:in `each_channel'
	from /opt/vagrant/embedded/gems/2.2.0/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:250:in `ev_preprocess'
	from /opt/vagrant/embedded/gems/2.2.0/gems/net-ssh-5.0.2/lib/net/ssh/connection/event_loop.rb:101:in `each'
	from /opt/vagrant/embedded/gems/2.2.0/gems/net-ssh-5.0.2/lib/net/ssh/connection/event_loop.rb:101:in `ev_preprocess'
	from /opt/vagrant/embedded/gems/2.2.0/gems/net-ssh-5.0.2/lib/net/ssh/connection/event_loop.rb:29:in `process'
	from /opt/vagrant/embedded/gems/2.2.0/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:228:in `process'
	from /opt/vagrant/embedded/gems/2.2.0/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:181:in `block in loop'
	from /opt/vagrant/embedded/gems/2.2.0/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:181:in `loop'
	from /opt/vagrant/embedded/gems/2.2.0/gems/net-ssh-5.0.2/lib/net/ssh/connection/session.rb:181:in `loop'
	from /opt/vagrant/embedded/gems/2.2.0/gems/net-ssh-5.0.2/lib/net/ssh/connection/channel.rb:272:in `wait'
	from /opt/vagrant/embedded/gems/2.2.0/gems/net-scp-1.2.1/lib/net/scp.rb:284:in `upload!'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/communicators/ssh/communicator.rb:298:in `block in upload'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/communicators/ssh/communicator.rb:691:in `block in scp_connect'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/communicators/ssh/communicator.rb:339:in `connect'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/communicators/ssh/communicator.rb:689:in `scp_connect'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/communicators/ssh/communicator.rb:292:in `upload'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/guests/redhat/cap/configure_networks.rb:60:in `block (2 levels) in configure_networks'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/tempfile.rb:295:in `open'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/guests/redhat/cap/configure_networks.rb:55:in `block in configure_networks'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/guests/redhat/cap/configure_networks.rb:22:in `each'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/guests/redhat/cap/configure_networks.rb:22:in `with_index'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/guests/redhat/cap/configure_networks.rb:22:in `configure_networks'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/capability_host.rb:111:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/capability_host.rb:111:in `capability'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/guest.rb:43:in `capability'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/action/network.rb:134:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/action/clear_network_interfaces.rb:26:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/action/prepare_nfs_settings.rb:19:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/action/prepare_nfs_valid_ids.rb:12:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:49:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/env_set.rb:19:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/action/set_name.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/box_check_outdated.rb:23:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine.rb:239:in `action_raw'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine.rb:208:in `block in action'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.rb:614:in `lock'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine.rb:194:in `call'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/machine.rb:194:in `action'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

### Steps to reproduce
1. vagrant ssh c1
2. vim /etc/fstab and comment last two lines and save the file
3. vagrant halt and vagrant up again

**Comment by briancain** [comment]
Hello @pain400 - commenting out partitions is generally not recommended, and will likely break lots of things in various ways. I recommend not doing this. I'm leaving this issue open so that we can fixup that exception and catch it and give a proper error to the user. Thanks!

**Comment by WangWenchao** [comment]
is this problem is fix , I met same error output msg  today on vagrant 2.2.9 and  Virtualbox 6.1
