### ISSUE TITLE
RSyncError, but I don't want to use it.

### ISSUE THREAD

**Issue by quoidautre** [hashicorp/vagrant#10732]
Hi,

I do a simple VagrantFile, and ofr the synchronizing type, **I don't want to use "rsync**", but it's not working. 
Rsync running anyway :(. 
I've use PuPHPet (there's no Debian VM), and I can change the type synchro. But with Vagrant "alone", I can't

Anybody can help me please ? :)

### Vagrant version
2.2.3

### Host operating system
Windows 10

### Guest operating system
Debian Jessie 8.10

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.box_version = "8.10.0"
  
  config.vm.box_check_update = false

  config.vm.network "private_network", ip: "192.168.56.222"
 
  config.vm.synced_folder "C:/Users/my-user/www/apache.vm/www/", "/var/www", type: "virtualbox"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4048"
  end
  
  #config.vm.provision :shell, path: "bootstrap.sh"
end
```

### Debug output
Here the debug log, [here](https://framabin.org/p/?1c6674c0a0070452#HjPTlsytAL0NppOXOUJhHK0glLu1e23PJG5VmynXHbY=).

### Actual behavior
```shell
C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/machine.rb:194:in `call'
C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/machine.rb:194:in `action'
C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /cygdrive/c/Users/my_user/boxes-puphpet/debian/
Guest path: /vagrant
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--chmod=ugo=rwX" "--no-perms" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2222 -o LogLevel=FATAL    -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i 'C:/Users/my_user/boxes-puphpet/debian/.vagrant/machines/default/virtualbox/private_key'" "--exclude" ".vagrant/" "/cygdrive/c/Users/my_user/boxes-puphpet/debian/" "vagrant@127.0.0.1:/vagrant"
Error: rsync: pipe: Connection timed out (116)
rsync error: error in IPC code (code 14) at pipe.c(59) [sender=3.1.3]

There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /cygdrive/c/Users/my_user/boxes-puphpet/debian/
Guest path: /vagrant
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--chmod=ugo=rwX" "--no-perms" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2222 -o LogLevel=FATAL    -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i 'C:/Users/my_user/boxes-puphpet/debian/.vagrant/machines/default/virtualbox/private_key'" "--exclude" ".vagrant/" "/cygdrive/c/Users/my_user/boxes-puphpet/debian/" "vagrant@127.0.0.1:/vagrant"
Error: rsync: pipe: Connection timed out (116)
rsync error: error in IPC code (code 14) at pipe.c(59) [sender=3.1.3]
 INFO interface: Machine: error-exit ["Vagrant::Errors::RSyncError", "There was an error when attempting to rsync a synced folder.\nPlease inspect the error message below for more info.\n\nHost path: /cygdrive/c/Users/my_user/boxes-puphpet/debian/\nGuest path: /vagrant\nCommand: \"rsync\" \"--verbose\" \"--archive\" \"--delete\" \"-z\" \"--copy-links\" \"--chmod=ugo=rwX\" \"--no-perms\" \"--no-owner\" \"--no-group\" \"--rsync-path\" \"sudo rsync\" \"-e\" \"ssh -p 2222 -o LogLevel=FATAL    -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i 'C:/Users/my_user/boxes-puphpet/debian/.vagrant/machines/default/virtualbox/private_key'\" \"--exclude\" \".vagrant/\" \"/cygdrive/c/Users/my_user/boxes-puphpet/debian/\" \"vagrant@127.0.0.1:/vagrant\"\nError: rsync: pipe: Connection timed out (116)\nrsync error: error in IPC code (code 14) at pipe.c(59) [sender=3.1.3]\n"]
```

### Steps to reproduce
1. vagrant up

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- #10667 

Thanks :)
F.

**Comment by briancain** [comment]
Vagrant by default will always sync your current working directory to `/vagrant` on the guest. If you want to disable it, or use a different method, you must specify it in your Vagrantfile:

```ruby
config.vm.synced_folder ".", "/vagrant", disabled: true
```

Or change the type to something else. Thanks!
