### ISSUE TITLE
in v2.2.5 rsync__exclude broken

### ISSUE THREAD

**Issue by tanaydin** [hashicorp/vagrant#10974]
### Vagrant version
2.2.5

### Host operating system
macOS Mojave

10.14.5 (18F132)
### Guest operating system
ubuntu/trusty64

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
DATA_FOLDER     = '/data'
PROJECTS_FOLDER = File.join(DATA_FOLDER, 'projects')
SSH_FOLDER      = File.join(ENV['HOME'], '.ssh')
# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  config.ssh.forward_agent = true
  # Check required plugins

  %w(gatling-rsync hostmanager host-shell).each do |req|
    plugin = "vagrant-#{req}"
    unless Vagrant.has_plugin?(plugin)
      puts <<-ERROR
        FATAL: #{plugin.capitalize} plugin not detected. Please install the plugin with
        'vagrant plugin install #{plugin}'
      ERROR
      exit
    end
  end


  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/trusty64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.define 'default' do |node|
    node.hostmanager.aliases = [
        'localhost.dev.xxxx.local',
        'xxxx.dev.xxxx.local',

        # xxxx/xxxx',
        'xxxx.dev.xxxx.local',
        'xml.xxxx.dev.xxxx.local',

        # xxxx',
        'xxxx.dev.xxxx.local',
        'xxxx.test.xxxx.local',
    ]
  end


  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder PROJECTS_FOLDER, '/vagrant'

  if File.exists?(SSH_FOLDER)
    config.vm.synced_folder SSH_FOLDER, "/home/vagrant/.ssh", type: "rsync",
      owner: "vagrant",
      group: "vagrant",
      rsync__args: ["--verbose", "--archive", "-z"]
  end

  [
    File.join(PROJECTS_FOLDER, 'xxxx'),
    File.join(PROJECTS_FOLDER, 'xxxx_old'),
    File.join(PROJECTS_FOLDER, 'xxxx_altr')
  ].each do |sharedFolder|
    config.vm.synced_folder sharedFolder, sharedFolder, type: "rsync",
      owner: "vagrant",
      group: "vagrant",
      rsync__args: ["--verbose", "--archive", "-z", '--include="src/xxx/UiBundle/Resources/public/js/vendor/*.js"'],
      rsync__verbose: true,
      rsync__exclude: [
        ".idea",
        ".settings",
        ".buildpath",
        ".project",
        "node_modules",
        "app/cache",
        "app/logs"
      ]
  end

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    host = RbConfig::CONFIG['host_os']

    # Give VM 1/4 system memory & access to half cpu cores on the host
    if host =~ /darwin/
      cpus = `sysctl -n hw.ncpu`.to_i / 2
      # sysctl returns Bytes and we need to convert to MB
      mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 4
    elsif host =~ /linux/
      cpus = `nproc`.to_i / 2
      # meminfo shows KB and we need to convert to MB
      mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 4
    else # sorry Windows folks, I can't help you
      cpus = 2
      mem = 1024
    end

    if mem < 4096
        mem = 4096
    end

    #vb.customize ["modifyhd", "disk id", "--resize", 60000]
    vb.customize ["modifyvm", :id, "--memory", mem]
    vb.customize ["modifyvm", :id, "--cpus", cpus]
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
  config.vm.provision "shell", inline: <<-SHELL

    # Tweeks
    ln -s /data/projects/xxxx/resources/vagrant/files/.bash_aliases /home/vagrant/.bash_aliases
    ln -s /data/projects/xxxx/resources/vagrant/files/dircolors.ansi-dark /home/vagrant/.dircolors

    # Update / Upgrade box
    sudo apt-get update
    sudo apt-get upgrade -y

    # Set mysql password to enable automated installation
    sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
    sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'

    # Install required packages
    sudo apt-get install -y ssh \
    apache2 \
    mysql-client \
    mysql-server \
    git \
    curl \
    npm \
    php5 \
    php5-cli \
    php5-dev \
    php5-curl \
    php5-mysql \
    php5-xsl \
    php5-gd \
    php5-intl \
    gearman-job-server \
    libgearman-dev \
    php5-gearman \
    gearman-tools \
    openjdk-7-jdk \
    gettext \
    unzip \
    mc \
    htop \
    mlocate


    #Add ServerName to the default config because it prevents a notice when restarting apache
    sudo echo -e "ServerName vagrant-ubuntu-trusty-64\n" | sudo tee -a /etc/apache2/apache2.conf

    # Locale
    sudo locale-gen nl_NL

    # Node
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
    nvm install 0.10.26
    nvm use 0.10.26

    # Gulp
    sudo npm install -g gulp

    # Bower
    sudo npm install -g bower

    # We need this because gulp will throw
    # /usr/bin/env: node: No such file or directory
    sudo ln -nfs /usr/bin/nodejs /usr/bin/node

    # Enable Apache modules
    sudo a2enmod rewrite
    sudo a2enmod ssl

    # run apache als vagrant user
    sudo sed -i 's/www-data/vagrant/g' /etc/apache2/envvars

    # copy the vhosts
    sudo cp /data/projects/xxxx/resources/vagrant/files/vhosts/xxxx.conf /etc/apache2/sites-available/xxxx.conf
    sudo cp /data/projects/xxxx2/resources/vagrant/files/vhosts/xxxx2.conf /etc/apache2/sites-available/xxxx2.conf
    sudo cp /data/projects/xxxx3/resources/vagrant/files/vhosts/xxxx3.conf /etc/apache2/sites-available/xxxx3.conf

    sudo a2dissite 000-default
    sudo a2ensite xxxx xxxx2 xxxx3


    # MySQL no bind to localhost
    sudo echo "[mysqld]" >/etc/mysql/conf.d/vagrant.cnf
    sudo echo "bind-address	= 0.0.0.0" >>/etc/mysql/conf.d/vagrant.cnf

    # Create user and allow all
    mysql -uroot -proot -e "grant all on xxxx_dev.* to xxxx@'%' identified by 'xxxx';"
    mysql -uroot -proot -e "create schema xxxx_dev default character set latin1;"

    mysql -uroot -proot -e "grant all on xxxx_test.* to xxxx@'%' identified by 'xxxx';"
    mysql -uroot -proot -e "create schema xxxx_test default character set latin1;"

    mysql -uroot -proot -e "grant all on xxxx_dev.* to xxxx@'%' identified by 'xxxx_dev';"
    mysql -uroot -proot -e "create schema xxxx_dev default character set latin1;"

    mysql -uroot -proot -e "grant all on xxxx_test.* to xxxx@'%' identified by 'xxxx_dev';"
    mysql -uroot -proot -e "create schema xxxx_test default character set latin1;"

    # SOLR Install
    sudo wget -c -N https://archive.apache.org/dist/lucene/solr/5.2.1/solr-5.2.1.tgz -O /tmp/solr-5.2.1.tgz >/dev/null 2>&1
    cd /tmp && sudo tar -xzf /tmp/solr-5.2.1.tgz solr-5.2.1/bin/install_solr_service.sh --strip-components=2
    sudo /bin/bash /tmp/install_solr_service.sh /tmp/solr-5.2.1.tgz -u vagrant

    # SOLR Configure
    sudo ln -s /data/projects/xxxx/solr/product-core-xxxx/ /var/solr/data/product-core-xxxx
    sudo ln -s /data/projects/xxxx/solr/product-core-xxxx-test/ /var/solr/data/product-core-xxxx-test
    sudo ln -s /data/projects/xxxx/solr/xxxx-core-xxx2/ /var/solr/data/xxxx-core-xxx2
    sudo ln -s /data/projects/xxxx/solr/xxxx-core-xxx2-test/ /var/solr/data/xxxx-core-xxx2-test


    # Composer
    sudo curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

    # Some required directories
    sudo mkdir -p /data/projects/xxxx/logs \
                  /data/projects/xxxx/cache \
                  /data/projects/xxxx/cache \
                  /data/projects/xxxx/logs \
                  /data/projects/_logs/xxxx \
                  /data/projects/_logs/xxxx

    # xxxx required folders
    mkdir -p /data/projects/xxxx/cache \
             /data/projects/xxxx/logs \
             /data/projects/xxxx/cache/gacl \
             /data/projects/xxxx/cache/smarty \
             /data/projects/xxxx/cache/magpie \
             /data/projects/xxxx/smarty/templates_c \
             /data/projects/xxxx/uploads \
             /data/projects/xxxx/uploads/help \
             /data/projects/xxxx/uploads/fckeditor \
             /data/projects/xxxx/uploads/forms \
             /data/projects/xxxx/uploads/statistics \
             /data/projects/_logs/xxxx

    touch /data/projects/xxxx/logs/propel.log
    touch /data/projects/_logs/xxxx/secure.xxxx.nl-error.log


    # xxx2 required files
    touch /data/projects/xxxx/logs/propel.log

    sudo chown -R vagrant:vagrant /data/projects
    # some sudo commands creates root folder here
    sudo chown -R vagrant:vagrant /home/vagrant


    # Make sure we delay as much as possible services restart, because they depend on file permissions
    sudo service solr restart
    sudo service apache2 restart
    sudo service mysql restart


  SHELL

  config.vm.provision :host_shell do |host_shell|
    host_shell.inline = 'cd /data/projects/xxxx && composer install && cd /data/projects/xxxx2 && composer install'
  end

  # Initalitation of Sontara project
  config.vm.provision "shell", inline: <<-SHELL
    cd /data/projects/xxxx
    php app/console doctrine:schema:update --force
    php app/console doctrine:fixtures:load --fixtures="/data/projects/xxxx/src/Generic/SonataBundle/PageBundle/DataFixtures/ORM" --no-interaction
    php app/console sonata:page:update-core-routes --site=all
    php app/console sonata:page:create-snapshots --site=all

    ./resources/scripts/project-permissions-linux.sh

    cd /data/projects/xxxx
    php app/console propel:model:build
    php app/console propel:sql:insert --force

    ./resources/scripts/project-permissions-linux.sh

    php app/console assets:install
    php app/console cache:clear


    cd /data/projects/xxxx
    /bin/bash /data/projects/xxxx/resources/scripts/import-database.sh
    /bin/bash /data/projects/xxxx/resources/scripts/import-clean-data.sh


    cd /data/projects/xxxx
    php app/console doctrine:schema:update --force
    php app/console doctrine:fixtures:load
    php app/console sonata:page:create-snapshots --site=all
    php app/console sonata:page:update-core-routes --site=all
    php app/console sonata:page:create-snapshots --site=all
    php app/console sonata:easy-extends:generate SonataPageBundle

    php app/console  assets:install
    php app/console cache:clear


  SHELL

  config.vm.provision "shell", inline: "sudo apache2ctl restart", run: "always"

  # Automatically sync when machines with rsync folders come up.
  config.gatling.latency = 1.5
  config.gatling.time_format = "%H:%M:%S"
  config.gatling.rsync_on_startup = true
end
```

### Expected behavior
It should run without any problem, I make it run I've downgraded to 2.2.4

### Actual behavior
It gives an error:

```
/opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/synced_folders/rsync/helper.rb:25:in `exclude_to_regexp': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /Users/tsirin/.vagrant.d/gems/2.4.6/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:70:in `block (3 levels) in execute'
	from /Users/tsirin/.vagrant.d/gems/2.4.6/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:69:in `each'
	from /Users/tsirin/.vagrant.d/gems/2.4.6/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:69:in `block (2 levels) in execute'
	from /Users/tsirin/.vagrant.d/gems/2.4.6/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:54:in `each'
	from /Users/tsirin/.vagrant.d/gems/2.4.6/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:54:in `block in execute'
	from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/plugin/v2/command.rb:238:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/plugin/v2/command.rb:232:in `each'
	from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
	from /Users/tsirin/.vagrant.d/gems/2.4.6/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:38:in `execute'
	from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/cli.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/environment.rb:290:in `cli'
	from /Users/tsirin/.vagrant.d/gems/2.4.6/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/action/startup_rsync.rb:40:in `block in call'
```

### Steps to reproduce
1. Add some folders to rsync__exclude
2. up your machine

**Comment by tanaydin** [comment]
Same as https://github.com/hashicorp/vagrant/issues/10966

**Comment by briancain** [comment]
Hi @tanaydin - this actually looks like a bug with the vagrant gatling rsync plugin based on the stack trace you shared.

**Comment by mattwellss** [comment]
Maybe I don't quite understand Vagrant's BC policy, but it looks like less of a bug in the gatling-rsync plugin and more of a BC break in Vagrant, introduced here: https://github.com/hashicorp/vagrant/pull/10902/files#diff-9e332e84f310f01ef491b96b33da75b8L19-R25
