### ISSUE TITLE
macOS 10.14.6 Vagrant 2.2.5 /Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/x86_64-darwin13/openssl.bundle, 9): Library not loaded: /opt/vagrant/embedded/lib/libssl.1.1.dylib (LoadError)

### ISSUE THREAD

**Issue by Ethns** [hashicorp/vagrant#11018]
host OS: macOS Mojave 10.14.6
$ vagrant -v: Vagrant 2.2.5
The encountered issue is the following, after I installed the Vagrant 2.2.5 on my macOS, and then typed `vagrant init` it showed some issue about the embedded ruby. This issue seems similar with the one resolved in [issue #9136](https://github.com/hashicorp/vagrant/issues/9136)
$ vagrant init:
```bash
/Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/x86_64-darwin13/openssl.bundle, 9): Library not loaded: /opt/vagrant/embedded/lib/libssl.1.1.dylib (LoadError)
  Referenced from: /Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/x86_64-darwin13/openssl.bundle
  Reason: image not found - /Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/x86_64-darwin13/openssl.bundle
	from /Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/openssl.rb:13:in `<top (required)>'
	from /Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/security.rb:12:in `<top (required)>'
	from /Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/package.rb:44:in `<top (required)>'
	from /Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Volumes/e/opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/bundler.rb:8:in `<top (required)>'
	from /Volumes/e/opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/plugin/manager.rb:4:in `require_relative'
	from /Volumes/e/opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/plugin/manager.rb:4:in `<top (required)>'
	from /Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Volumes/e/opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant.rb:15:in `<top (required)>'
	from /Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /Volumes/e/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Volumes/e/opt/vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/bin/vagrant:88:in `<main>'
```

**Comment by briancain** [comment]
Hello @Ethns - I recommend uninstalling Vagrant and then reinstalling 2.2.5 and see if that works.

You might also want to make sure your `/Volumes/e` volume is actually mounted and accessible by the user executing Vagrant

**Comment by Ethns** [comment]
thanks @briancain - my /Volumes/e is mounted and accessible by the yser executing Vagrant, after I reinstalled the 2.2.5 above issue still exists

**Comment by morphatic** [comment]
I had this same problem. I was able to fix it by creating a symlink to `/Volumes/myVolume/opt/vagrant` from `/opt/vagrant`. The command was:

```bash
sudo ln -s /Volumes/myVolume/opt/vagrant vagrant
```

NOTE: you should replace `myVolume` with the name of the volume where you have vagrant installed. In your case that appears that should be:

```bash
sudo ln -s /Volumes/e/opt/vagrant vagrant
```

Also, after that I had to run:

```bash
vagrant plugin update
```

to update plugins before I could actually get `vagrant up` to run.

I think this is caused by having a non-standard Volumes structure. HTH!

**Comment by Ethns** [comment]
thank @morphatic I followed the exact steps in you comment and the issue still there with the same stack trace I attached in my first comment.
But your answer really enlightened me that the issue maybe caused by me installed Vagrant in my transcend JetDrive(aka, the `Volume`).
So I uninstalled Vagrant from that drive and re-installed into the origin Macintosh drive, everything works fine now 💃

**Comment by Isaac-SwiftOtter** [comment]
Thanks, @morphatic!  Just adding the symlink fixed it for me.  This problem had been bugging me for a while.  Now it's fixed and I'm up and running!
