### ISSUE TITLE
Vagrant Plugin Update Command Broke My Vagrant

### ISSUE THREAD

**Issue by glennthehuman** [hashicorp/vagrant#11054]
### Vagrant version
2.2.5

### Host operating system
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free

### Guest operating system
Ubuntu 18.04

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true
    config.hostmanager.aliases = %w(xxx.xxxxx.xxx)
  end

  config.vm.box = "bento/ubuntu-18.04"
  config.vm.hostname = "xxxxx.xxx"
  config.vm.boot_timeout = 360
  config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
  config.vm.network "forwarded_port", guest: 443, host: 8443, auto_correct: true
  config.vm.network "private_network", ip: "192.168.33.18"
  config.vm.network "private_network", type: "dhcp"
  #config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777","fmode=777"]
  config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=777"] }
  config.ssh.insert_key = false

  config.vm.provision "shell", inline: <<-SHELL
    echo "Fixing encoding..."
    apt-get install dos2unix
    dos2unix /var/www/.provision/*.sh
  SHELL
  config.vm.provision "shell", path: ".provision/setup.sh", privileged: false

  # VirtualBox customizations
  config.vm.provider "virtualbox" do |v|
    # Enable if having issues with symbolic links; only needed on older vagrant versions
    v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
end

```

### Debug output
using vagrant up --debug: https://gist.github.com/glennthehuman/b375e7171c20d245d076800a2cd5dbcd

using the repair commands: https://gist.github.com/glennthehuman/7ed1e3e9c6d09eed8115ff264b21ffaa

### Expected behavior
My plugins should have been updated properly.

### Actual behavior
Any vagrant command now has an error

### Steps to reproduce
1. Go to your vagrant box.
2. vagrant up
```
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.2.8
VBoxService inside the vm claims: 6.0.10
Going on, assuming VBoxService is correct...
```
3. vagrant plugin update
```
Updating installed plugins...
D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/package.rb:383:in `initialize': Permission denied @ rb_sysopen - D:/.vagrant.d/gems/2.4.6/gems/vagrant-winnfsd-1.4.0/bin/winnfsd.exe (Errno::EACCES)
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/package.rb:383:in `open'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/package.rb:383:in `block (2 levels) in extract_tar_gz'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/package/tar_reader.rb:65:in `each'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/package.rb:365:in `block in extract_tar_gz'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/package.rb:492:in `block in open_tar_gz'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/package.rb:489:in `wrap'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/package.rb:489:in `open_tar_gz'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/package.rb:364:in `extract_tar_gz'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/package.rb:345:in `block (2 levels) in extract_files'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/package/tar_reader.rb:65:in `each'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/package.rb:342:in `block in extract_files'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/package/file_source.rb:30:in `open'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/package/file_source.rb:30:in `with_read_io'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/package.rb:339:in `extract_files'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/installer.rb:801:in `extract_files'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/installer.rb:302:in `install'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/resolver/specification.rb:97:in `install'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/request_set.rb:260:in `block in install_into'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/request_set.rb:252:in `each'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/request_set.rb:252:in `install_into'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/bundler.rb:388:in `internal_install'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/bundler.rb:172:in `update'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/plugin/manager.rb:213:in `update_plugins'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/commands/plugin/action/update_gems.rb:23:in `call'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/action/warden.rb:50:in `call'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/action/warden.rb:50:in `call'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/action/builder.rb:116:in `call'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/action/runner.rb:102:in `block in run'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/util/busy.rb:19:in `busy'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/action/runner.rb:102:in `run'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/commands/plugin/command/base.rb:14:in `action'

        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/commands/plugin/command/update.rb:28:in `execute'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/commands/plugin/command/root.rb:66:in `execute'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/cli.rb:66:in `execute'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/environment.rb:290:in `cli'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/bin/vagrant:182:in `<main>'
```
4. vagrant ssh
```
Vagrant failed to initialize at a very early stage:

The plugins failed to initialize correctly. This may be due to manual
modifications made within the Vagrant home directory. Vagrant can
attempt to automatically correct this issue by running:

  vagrant plugin repair

If Vagrant was recently updated, this error may be due to incompatible
versions of dependencies. To fix this problem please remove and re-install
all plugins. Vagrant can attempt to do this automatically by running:

  vagrant plugin expunge --reinstall

Or you may want to try updating the installed plugins to their latest
versions:

  vagrant plugin update

Error message given during initialization: Unable to resolve dependency: user requested 'vagrant-winnfsd (= 1.4.0)'
```

4. vagrant halt
```
Vagrant failed to initialize at a very early stage:

The plugins failed to initialize correctly. This may be due to manual
modifications made within the Vagrant home directory. Vagrant can
attempt to automatically correct this issue by running:

  vagrant plugin repair

If Vagrant was recently updated, this error may be due to incompatible
versions of dependencies. To fix this problem please remove and re-install
all plugins. Vagrant can attempt to do this automatically by running:

  vagrant plugin expunge --reinstall

Or you may want to try updating the installed plugins to their latest
versions:

  vagrant plugin update

Error message given during initialization: Unable to resolve dependency: user requested 'vagrant-winnfsd (= 1.4.0)'
```

5. vagrant plugin repair
```
Repairing currently installed global plugins. This may take a few minutes...
Failed to automatically repair installed Vagrant plugins. To fix this
problem remove all user installed plugins and reinstall. Vagrant can
do this for you automatically by running the following command:

  vagrant plugin expunge --reinstall

Failure message received during repair:

No such file or directory @ rb_sysopen - D:/.vagrant.d/gems/2.4.6/gems/micromachine-3.0.0/micromachine.gemspec
```

6. vagrant plugin expunge --reinstall
```
This command permanently deletes all currently installed user plugins. It
should only be used when a repair command is unable to properly fix the
system.

Continue? [N]: y
D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:1335:in `rmdir': Directory not empty @ dir_s_rmdir - D:/.vagrant.d/gems/2.4.6 (Errno::ENOTEMPTY)
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:1335:in `block in remove_dir1'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:1349:in `platform_support'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:1334:in `remove_dir1'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:1327:in `remove'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:689:in `block in remove_entry'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:1384:in `ensure in postorder_traverse'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:1384:in `postorder_traverse'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:687:in `remove_entry'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:555:in `block in rm_r'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:551:in `each'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:551:in `rm_r'
        from D:/apps/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/pathname.rb:587:in `rmtree'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/commands/plugin/action/expunge_plugins.rb:62:in `map'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/commands/plugin/action/expunge_plugins.rb:62:in `call'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/action/warden.rb:50:in `call'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/action/warden.rb:50:in `call'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/action/builder.rb:116:in `call'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/action/runner.rb:102:in `block in run'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/util/busy.rb:19:in `busy'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/action/runner.rb:102:in `run'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/commands/plugin/command/base.rb:14:in `action'

        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/commands/plugin/command/expunge.rb:65:in `execute'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/commands/plugin/command/root.rb:66:in `execute'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/cli.rb:66:in `execute'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/environment.rb:290:in `cli'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/bin/vagrant:182:in `<main>'
```

7. vagrant plugin update
```
Updating installed plugins...
D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/bundler.rb:495:in `write': No such file or directory @ rb_sysopen - D:/.vagrant.d/gems/2.4.6/gems/micromachine-3.0.0/micromachine.gemspec (Errno::ENOENT)
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/bundler.rb:495:in `block in generate_plugin_set'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/bundler.rb:489:in `each'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/bundler.rb:489:in `generate_plugin_set'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/bundler.rb:364:in `internal_install'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/bundler.rb:172:in `update'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/plugin/manager.rb:213:in `update_plugins'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/commands/plugin/action/update_gems.rb:23:in `call'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/action/warden.rb:50:in `call'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/action/warden.rb:50:in `call'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/action/builder.rb:116:in `call'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/action/runner.rb:102:in `block in run'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/util/busy.rb:19:in `busy'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/action/runner.rb:102:in `run'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/commands/plugin/command/base.rb:14:in `action'

        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/commands/plugin/command/update.rb:28:in `execute'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/commands/plugin/command/root.rb:66:in `execute'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/cli.rb:66:in `execute'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/lib/vagrant/environment.rb:290:in `cli'
        from D:/apps/HashiCorp/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/bin/vagrant:182:in `<main>'
```

**Comment by briancain** [comment]
Hi @glennthehuman - It's possible that when you originally installed the plugins you are trying to update, it was installed with administartor, and then your local user didn't have the proper permissions to update the plugin. I recommend running `vagrant plugin expunge` to remove all the plugins from your system, then reinstall your plugins yourself after that command completes. If that doesn't work, you should be able to uninstall Vagrant and reinstall Vagrant and try to install plugins again after that. Thanks!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
