### ISSUE TITLE
vagrant cloud publish throws VagrantCloud::ClientError error

### ISSUE THREAD

**Issue by tas50** [hashicorp/vagrant#11138]
### Vagrant version
2.2.6

### Host operating system
macOS 10.15

### Guest operating system
n/a

### Vagrantfile
n/a

### Debug output
n/a

### Expected behavior
when running vagrant cloud publish any exist boxes/providers/versions should be updated

### Actual behavior
vagrant throws an error

### Steps to reproduce
```
vagrant cloud publish bento/test 1.2.3 virtualbox builds/centos-6.10-201910.03.0.virtualbox.box --release
You are about to publish a box on Vagrant Cloud with the following options:
bento/test:   (v1.2.3) for provider 'virtualbox'
Automatic Release:     true
Do you wish to continue? [y/N] y
==> cloud: Creating a box entry...
==> cloud: Box already exists, updating instead...
==> cloud: Creating a version entry...
==> cloud: Version already exists, updating instead...
==> cloud: Creating a provider entry...
==> cloud: Provider already exists, updating instead...
/opt/vagrant/embedded/gems/2.2.6/gems/vagrant_cloud-2.0.3/lib/vagrant_cloud/client.rb:56:in `rescue in request': 422 Unprocessable Entity - provider parameter is required! (VagrantCloud::ClientError)
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant_cloud-2.0.3/lib/vagrant_cloud/client.rb:51:in `request'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant_cloud-2.0.3/lib/vagrant_cloud/provider.rb:86:in `update'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/commands/cloud/publish.rb:149:in `rescue in publish_box'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/commands/cloud/publish.rb:143:in `publish_box'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/commands/cloud/publish.rb:77:in `execute'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/commands/cloud/root.rb:73:in `execute'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/cli.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:290:in `cli'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/bin/vagrant:182:in `<main>'
```

**Comment by tas50** [comment]
Seems that this is caused by https://github.com/hashicorp/vagrant_cloud/blob/master/lib/vagrant_cloud/provider.rb#L84 lacking ```provider: provider_name``` in the hash. Once you add that the API response is valid and this command actually works.

**Comment by chrisroberts** [comment]
Hi! Thanks for the report and apologies for the trouble. This has been fixed (on the vagrant cloud side). I'm going to close up this issue but if you experience any other issues with the publish command just let me know.

Cheers!

**Comment by tas50** [comment]
@chrisroberts vagrant cloud the gem or the actual API service?

**Comment by chrisroberts** [comment]
@tas50 the actual API service
