### ISSUE TITLE
non ascii chars in paths

### ISSUE THREAD

**Issue by ibraheemalayan** [hashicorp/vagrant#11153]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### 2.2.6
Run vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

### windows 10
This is the operating system that you run locally.

### ubuntu
This is the operating system you run in the virtual machine.

### the problem is in the installation and I don't have such file
```ruby
# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
What should have happened?
it should work 

### Actual behavior
What actually happened?
I got this error `C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:230:in `mkdir': Invalid argument @ dir_s_mkdir - C:/Users/????????? (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:230:in `fu_mkdir'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:208:in `block (2 levels) in mkdir_p'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:206:in `reverse_each'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:206:in `block in mkdir_p'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:191:in `each'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:191:in `mkdir_p'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:823:in `block in setup_home_path'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:818:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:818:in `setup_home_path'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:135:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/bin/vagrant:145:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/bin/vagrant:145:in `<main>'

`

### Steps to reproduce
1. Make a windows user and name the user in non-ascii characters like Arabic  (you can do this in a virtual machine of windows it will produce the same error)
2.try installing vagrant and it is not gone work
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by ibraheemalayan** [comment]
any updates on this ?
