### ISSUE TITLE
Invalid: sshfs (RuntimeError)

### ISSUE THREAD

**Issue by littlesandra88** [hashicorp/vagrant#11176]
### Vagrant version
Vagrant 2.2.5
```
➜  ~ rpm -qa|grep -i vagrant
vagrant-libvirt-0.0.45-1.fc30.noarch
vagrant-2.2.5-1.fc30.noarch
kubernetes-ansible-vagrant-0.7.0-0.8.git1958461.fc30.noarch

➜  ~ rpm -qa|grep -i virtualbox
VirtualBox-6.0.14-1.fc30.x86_64
kmod-VirtualBox-5.3.7-200.fc30.x86_64-6.0.14-2.fc30.x86_64
VirtualBox-kmodsrc-6.0.14-1.fc30.noarch
akmod-VirtualBox-6.0.14-2.fc30.x86_64
VirtualBox-server-6.0.14-1.fc30.x86_64
virtualbox-guest-additions-6.0.14-1.fc30.x86_64
```

### Host operating system
Fedora 30

### Guest operating system
CentOS 7

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define "test1" do |vm1|
     vm1.vm.hostname = "vm1.example.com"
     vm1.vm.synced_folder "src/", "/src", type: "sshfs", sshfs_opts_append: "-o nonempty"

     vm1.vm.provider 'virtualbox' do |domain|
       domain.memory = 1024
       domain.cpus = 1
     end

     vm1.vm.network 'private_network', ip: "192.168.234.229"
  end

end
```
### Debug output
https://gist.github.com/littlesandra88/17593dc334d1369db375f27a0d9d53b2

### Expected behavior
`vagrant up`

### Actual behavior
Vagrant crashed with `Internal error. Report this as a bug. Invalid: sshfs (RuntimeError)`

### Steps to reproduce
1. `vagrant up`
2.
3.

### References
None

**Comment by briancain** [comment]
Hey there @littlesandra88 - Thanks for opening an issue with Vagrant.

It looks like you're trying to use a synced_folder type that isn't a valid default type with Vagrant. You probably need to install the [vagrant-sshfs](https://github.com/dustymabe/vagrant-sshfs) plugin to use that kind of synced_folder. Installing that should resolve the issue!

That being said, I think we should try to catch this exception and print a better error message to the user.

**Comment by vrubiolo** [comment]
Hi there,

I second that approach as I encountered the same error today with Vagrant 2.2.6 on Fedora 30 (I am using the binary from Github, not the distro RPM). For some reason, the vagrant-sshfs plugin disappeared (I used to have it alongside vagrant-libvirt installed on my setup) and that what was causing the issue. 

The backtrace/lack of information let me wonder what was going on. Moving to another clean Vagrant directory after copying my Vagrantfile did not allow me to proceed/start afresh so this was a blocking issue (I searched without success for some leftover in the caches under `~/.vagrant`).

Thanks for your support, Vagrant is really a fantastic tool!

**Comment by vrubiolo** [comment]
Hi there,

I support that approach as I encountered this issue today with Vagrant 2.2.6 (from Github, not from the Fedora 30 RPM distro I am using).
For some reason, my Vagrant plugins vanished (I used to have vagrant-sshfs alongside vagrant-libvirt but `vagrant plugin list` now reports nothing) and the error popped up. Because of the lack of error/information, this was very confusing and impossible to get out of (moving to a new dir + Vagrantfile did not solve the problem).

Thanks for your support, Vagrant is a fantastic tool!

**Comment by vrubiolo** [comment]
I stumbled upon the issue again today w/ Vagrant 2.2.14. I had a VM running using the `vagrant-sshfs` plugin and removed the plugin before halting/destroying the machine. Then the issue showed up, I could not even destroy the machine anymore:
```
$ vagrant destroy                                                                                                                                                                                                   
    default: Are you sure you want to destroy the 'default' VM? [y/N] y                                                                                                                                                                       
Traceback (most recent call last):                                                                                     
        37: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'   
        36: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `action'   
        35: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `call'                                                                                                                              
        34: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/environment.rb:613:in `lock'                                                                                                                          
        33: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/machine.rb:215:in `block in action'
        32: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/machine.rb:246:in `action_raw'                                                                                                                        
        31: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'                                                                                                                          
        30: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'                                                                                                                             
        29: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'                         
        28: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'                     
        27: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'                                                                                                                         
        26: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
        25: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
        24: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/builtin/call.rb:53:in `call'
        23: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
        22: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
        21: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
        20: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call' 
        19: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
        18: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
        17: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'                                                                                                                         
        16: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/builtin/call.rb:53:in `call'
        15: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
        14: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
        13: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
        12: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call' 
        11: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
        10: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
         9: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
         8: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/builtin/config_validate.rb:15:in `call'
         7: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/config/v2/root.rb:66:in `validate'
         6: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/config/v2/root.rb:66:in `each'
         5: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/config/v2/root.rb:71:in `block in validate'
         4: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/plugins/kernel_v2/config/vm.rb:730:in `validate'
         3: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/machine.rb:631:in `synced_folders'
         2: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/builtin/mixin_synced_folders.rb:128:in `synced_folders'
         1: from /tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/builtin/mixin_synced_folders.rb:128:in `each'
/tmp/.mount_vagranhFthpF/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/action/builtin/mixin_synced_folders.rb:140:in `block in synced_folders': Internal error. Report this as a bug. Invalid: sshfs (RuntimeError)
```

The workaround was to reinstall the plugin to make things work again (destroy the machine), then uninstall it.

**Comment by ghominejad** [comment]
Recently I also have the same problem in `PowerShell` but in `CMD` still working!

**Comment by ghominejad** [comment]
Fixed by installing `vagrant-sshfs`!

```BASH
vagrant plugin install vagrant-sshfs
```
