### ISSUE TITLE
Vagrant up builds the VM and then forces shutdown after connection reset and destroys VM.

### ISSUE THREAD

**Issue by srg9000** [hashicorp/vagrant#11172]
I am trying installation of VVV as instructed [here](https://varyingvagrantvagrants.org/docs/en-US/installation/)

Vagrant version: vagrant 2.2.6

 Host operating system:  Windows 10 pro

### Guest operating system
ubuntu/bionic64 (

### Vagrantfile
The vagrant file used can be found [here](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile)

### Expected behavior
It should have installed everything as per vagrantfile

### Actual behavior
```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/bionic64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/bionic64' version '20191030.0.0' is up to date...
==> default: Setting the name of the VM: vagrant-local3_83fc799d850
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
F:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/net-ssh-5.1.0/lib/net/ssh/transport/server_version.rb:46:in `write': Broken pipe (Errno::EPIPE)
        from F:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/net-ssh-5.1.0/lib/net/ssh/transport/server_version.rb:46:in `negotiate!'
        from F:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/net-ssh-5.1.0/lib/net/ssh/transport/server_version.rb:34:in `initialize'
        from F:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/net-ssh-5.1.0/lib/net/ssh/transport/session.rb:86:in `new'           from F:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/net-ssh-5.1.0/lib/net/ssh/transport/session.rb:86:in `initialize'
        from F:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/net-ssh-5.1.0/lib/net/ssh.rb:242:in `new'
        from F:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/net-ssh-5.1.0/lib/net/ssh.rb:242:in `start'
        from F:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/communicators/ssh/communicator.rb:466:in `block (2 levels) in connect'
        from F:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
        from F:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
        from F:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from F:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from F:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
        from F:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/communicators/ssh/communicator.rb:432:in `block in connect'
        from F:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/util/retryable.rb:17:in `retryable'        from F:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/communicators/ssh/communicator.rb:431:in `connect'
        from F:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/communicators/ssh/communicator.rb:86:in `block in wait_for_ready'
        from F:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
        from F:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
        from F:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from F:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from F:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
        from F:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/communicators/ssh/communicator.rb:62:in `wait_for_ready'
        from F:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'
```

### Steps to reproduce
I followed the steps as mentioned [here](https://varyingvagrantvagrants.org/docs/en-US/installation/). 

I tried installation by adding a box and then generating a vagrant file using init for which vagrant up worked.

### References
1)I tried some steps as mentioned in [this](https://github.com/wckr/wocker/issues/66) issue after which it worked but while recreating it, I cannot get it to work again.
2)(https://github.com/hashicorp/vagrant/issues/10119)

**Comment by tomjn** [comment]
@srg9000 There's information here we didn't get over at VVV, it looks like the VM didn't boot within a timeout threshold, so the SSH timed out and Vagrant crashed during cleanup.

That's still a vagrant issue, but it would have meant debugging things at the VVV end would have been significantly easier if we'd known.

The TLDR, if you git clone a vagrant setup, and run `vagrant up --provision` it should download the box. It was originally reported that a bug happened instead that's fixed by running `vagrant box update` prior to `vagrant up`. I don't know why this is the case

**Comment by masood242** [comment]
hi,
I am using wondows 10 home edition, vagrant 2.2.6, virtualbox 6.0 and got issue almost the same. as soon as i am doing vagrant up, the machine gets impoorted and right after the MAC address and NAT checking, machine gets destroyed itself, 
so i ran vagran up --debug and i am attaching all  info in a file, if any one can be helpful.
thank you.
[vagrantissue.txt](https://github.com/hashicorp/vagrant/files/4152250/vagrantissue.txt)

**Comment by CedBau** [comment]
I guess there hasn't been an update to this problem? I'm currently encountering the same issue, only that i try to connect via winrm.

**Comment by tsunamifi** [comment]
Also having this very annoying issue. Everything seems to be fine and then the VM destroys itself. Also after it tries to connect via winrm
