### ISSUE TITLE
 in v2.2.6 rsync__exclude still broken (broken API)

### ISSUE THREAD

**Issue by ostrolucky** [hashicorp/vagrant#11229]
### Vagrant version
2.2.6

### Host operating system
MacOS Mojave

### Guest operating system
Ubuntu 16.04

### Vagrantfile

relevant parts:
```ruby
config.vm.synced_folder ".", "/calida", type: "rsync",
    rsync__exclude: [
      ".bash*", ".git/", ".idea/", ".cache/", ".dbshell", ".mysql_history", ".installed", ".phpcs-cache", ".vagrant", "vagrant-overwrites.yml",
      "npm-debug.log", "var/build", "var/cache", "var/sessions", "var/logs", "web-app/src", "node_modules", "community/*.pid"
    ],
    rsync__args: ["--verbose", "--archive", "--delete", "-z", "--links", "--ignore-missing-args"]

if Vagrant.has_plugin?("vagrant-gatling-rsync")
    config.gatling.time_format = "%H:%M:%S"
    config.gatling.latency = 0.5
    config.gatling.rsync_on_startup = false
  end
```

### Output
```
==> default:   - Exclude: [".vagrant/", ".bash*", ".git/", ".idea/", ".cache/", ".dbshell", ".mysql_history", ".installed", ".phpcs-cache", ".vagrant", "vagrant-overwrites.yml", "npm-debug.log", "var/build", "var/cache", "var/sessions", "var/logs", "web-app/src", "node_modules", "community/*.pid"]
/opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/synced_folders/rsync/helper.rb:25:in `exclude_to_regexp': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /Users/mfadieieva/.vagrant.d/gems/2.4.9/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:70:in `block (3 levels) in execute'
	from /Users/mfadieieva/.vagrant.d/gems/2.4.9/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:69:in `each'
	from /Users/mfadieieva/.vagrant.d/gems/2.4.9/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:69:in `block (2 levels) in execute'
	from /Users/mfadieieva/.vagrant.d/gems/2.4.9/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:54:in `each'
	from /Users/mfadieieva/.vagrant.d/gems/2.4.9/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:54:in `block in execute'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/command.rb:238:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/command.rb:232:in `each'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
	from /Users/mfadieieva/.vagrant.d/gems/2.4.9/gems/vagrant-gatling-rsync-0.9.0/lib/vagrant-gatling-rsync/command/rsync_auto.rb:38:in `execute'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/cli.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:290:in `cli'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/bin/vagrant:182:in `<main>'
```

### Reproducer
1. Run `vagrant gatling-rsync-auto`

### References
- #10974

**Comment by briancain** [comment]
Hi there @ostrolucky - Thanks for opening an issue on Vagrant! According to the stacktrace you shared, the error origininates from the [vagrant-gatling](https://github.com/smerrill/vagrant-gatling-rsync) plugin. I just tried a Vagrantfile with the same rsync args and exclude, and rsync-auto works fine without the plugin:

```
brian@localghost:vagrant-sandbox % be vagrant up bork                                                    ±[●][master]
Bringing machine 'bork' up with 'virtualbox' provider...
==> bork: Importing base box 'bento/ubuntu-18.04'...
==> bork: Matching MAC address for NAT networking...
==> bork: Checking if box 'bento/ubuntu-18.04' version '201910.20.0' is up to date...
==> bork: Setting the name of the VM: vagrant-sandbox_bork_1575391472524_51859
==> bork: Clearing any previously set network interfaces...
==> bork: Preparing network interfaces based on configuration...
    bork: Adapter 1: nat
==> bork: Forwarding ports...
    bork: 22 (guest) => 2222 (host) (adapter 1)
==> bork: Guest provider 'virtualbox' does not support the disk feature, and will not use the disk configuration defined.
==> bork: Booting VM...
==> bork: Waiting for machine to boot. This may take a few minutes...
    bork: SSH address: 127.0.0.1:2222
    bork: SSH username: vagrant
    bork: SSH auth method: private key
    bork:
    bork: Vagrant insecure key detected. Vagrant will automatically replace
    bork: this with a newly generated keypair for better security.
    bork:
    bork: Inserting generated public key within guest...
    bork: Removing insecure key from the guest if it's present...
    bork: Key inserted! Disconnecting and reconnecting using new SSH key...
==> bork: Machine booted and ready!
==> bork: Checking for guest additions in VM...
==> bork: Rsyncing folder: /home/brian/code/vagrant-sandbox/scripts/ => /vagrant
==> bork:   - Exclude: [".vagrant/", ".bash*", ".git/", ".idea/", ".cache/", ".dbshell", ".mysql_history", ".installed", ".phpcs-cache", ".vagrant", "vagrant-overwrites.yml", "npm-debug.log", "var/build", "var/cache", "var/sessions", "var/logs", "web-app/src", "node_modules", "community/*.pid"]
==> bork: Running provisioner: Sandbox (file)...
    bork: linux-sandbox/Vagrantfile => /home/vagrant/test/Vagrantfile
brian@localghost:vagrant-sandbox % be vagrant rsync-auto                                                 ±[●][master]
==> bork: Doing an initial rsync...
==> bork: Rsyncing folder: /home/brian/code/vagrant-sandbox/scripts/ => /vagrant
==> bork:   - Exclude: [".vagrant/", ".bash*", ".git/", ".idea/", ".cache/", ".dbshell", ".mysql_history", ".installed", ".phpcs-cache", ".vagrant", "vagrant-overwrites.yml", "npm-debug.log", "var/build", "var/cache", "var/sessions", "var/logs", "web-app/src", "node_modules", "community/*.pid"]
==> bork: Watching: /home/brian/code/vagrant-sandbox/scripts
```

Please open an issue with their project instead, thanks!

**Comment by ostrolucky** [comment]
You broke API though. It was working before.
