### ISSUE TITLE
Windows reboot is unreliable

### ISSUE THREAD

**Issue by rgl** [hashicorp/vagrant#11238]
### Vagrant version
Vagrant 2.2.6

### Host operating system
Ubuntu 18.04 with the libvirt provider.

### Guest operating system
Windows 2019

### Vagrantfile
```ruby
config.vm.provision "shell", path: "ps.ps1", args: "provision.ps1", reboot: true
```

The full file is at https://github.com/rgl/visual-studio-community-vagrant/blob/master/Vagrantfile.

### Expected behavior
Reboot should work while ignoring transient errors (like `Errno::ECONNREFUSED`) until it can prove the reboot is done.

### Actual behavior
It crashed with the following stacktrace:

```
==> default: Waiting for machine to reboot...
==> default: Clearing any previously set forwarded ports...
==> default: Removing domain...
/opt/vagrant/embedded/gems/2.2.6/gems/httpclient-2.8.3/lib/httpclient/session.rb:623:in `rescue in create_socket': Connection refused - Connection refused - connect(2) for "192.168.121.195" port 5985 (192.168.121.195:5985) (Errno::ECONNREFUSED)
	from /opt/vagrant/embedded/gems/2.2.6/gems/httpclient-2.8.3/lib/httpclient/session.rb:607:in `create_socket'
	from /opt/vagrant/embedded/gems/2.2.6/gems/httpclient-2.8.3/lib/httpclient/session.rb:755:in `block in connect'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
	from /opt/vagrant/embedded/gems/2.2.6/gems/httpclient-2.8.3/lib/httpclient/session.rb:748:in `connect'
	from /opt/vagrant/embedded/gems/2.2.6/gems/httpclient-2.8.3/lib/httpclient/session.rb:511:in `query'
	from /opt/vagrant/embedded/gems/2.2.6/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
	from /opt/vagrant/embedded/gems/2.2.6/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
	from /opt/vagrant/embedded/gems/2.2.6/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
	from /opt/vagrant/embedded/gems/2.2.6/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
	from /opt/vagrant/embedded/gems/2.2.6/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
	from /opt/vagrant/embedded/gems/2.2.6/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
	from /opt/vagrant/embedded/gems/2.2.6/gems/httpclient-2.8.3/lib/httpclient.rb:765:in `post'
	from /opt/vagrant/embedded/gems/2.2.6/gems/winrm-2.3.2/lib/winrm/http/transport.rb:176:in `send_request'
	from /opt/vagrant/embedded/gems/2.2.6/gems/winrm-2.3.2/lib/winrm/shells/power_shell.rb:42:in `close_shell'
	from /opt/vagrant/embedded/gems/2.2.6/gems/winrm-2.3.2/lib/winrm/shells/base.rb:89:in `close'
	from /opt/vagrant/embedded/gems/2.2.6/gems/winrm-2.3.2/lib/winrm/connection.rb:44:in `ensure in shell'
	from /opt/vagrant/embedded/gems/2.2.6/gems/winrm-2.3.2/lib/winrm/connection.rb:44:in `shell'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/communicators/winrm/shell.rb:62:in `powershell'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/communicators/winrm/communicator.rb:152:in `execute'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/guests/windows/cap/reboot.rb:44:in `wait_for_reboot'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/guests/windows/cap/reboot.rb:30:in `reboot'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/capability_host.rb:111:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/capability_host.rb:111:in `capability'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/guest.rb:43:in `capability'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/provisioners/shell/provisioner.rb:35:in `provision'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/provision.rb:138:in `run_provisioner'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:121:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:121:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `run'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:525:in `hook'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/provision.rb:126:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/provision.rb:126:in `block in call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/provision.rb:103:in `each'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/provision.rb:103:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /home/rgl/.vagrant.d/gems/2.4.9/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_domain.rb:333:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /home/rgl/.vagrant.d/gems/2.4.9/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_domain_volume.rb:83:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /home/rgl/.vagrant.d/gems/2.4.9/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/handle_box_image.rb:146:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /home/rgl/.vagrant.d/gems/2.4.9/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/handle_storage_pool.rb:57:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /home/rgl/.vagrant.d/gems/2.4.9/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:121:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `run'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/box_check_outdated.rb:36:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `run'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/machine.rb:238:in `action_raw'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/machine.rb:209:in `block in action'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/environment.rb:613:in `lock'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/machine.rb:195:in `call'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/machine.rb:195:in `action'
	from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
	from /opt/vagrant/embedded/gems/2.2.6/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

### Steps to reproduce

1. vagrant up

**Comment by rgl** [comment]
I've applied the following rude patch, and its now working:

```patch
--- reboot.rb.orig	2019-12-06 20:14:09.270064780 +0000
+++ /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/plugins/guests/windows/cap/reboot.rb	2019-12-06 20:14:23.878157107 +0000
@@ -28,9 +28,9 @@
           wait_remaining = MAX_REBOOT_RETRY_DURATION
           begin
             wait_for_reboot(machine)
-          rescue HTTPClient::ConnectTimeoutError, Vagrant::Errors::MachineGuestNotReady, WinRM::WinRMHTTPTransportError => e
+          rescue Exception => e
             raise if wait_remaining < 0
-            @logger.warn("Machine not ready, cannot start reboot yet. Trying again")
+            @logger.warn("Machine not yet ready (#{e}). Trying again...")
             sleep(5)
             wait_remaining -= 5
             retry
```

**Comment by briancain** [comment]
Hi there! Thanks for opening an issue with Vagrant. We shouldn't be capturing a blanket Exception here (as it would prevent other errors from surfacing not relating to rebooting), but we can catch things like `Errno::ECONNREFUSED` in this case to make sure we're not missing any exceptions related to waiting for the reboot.

**Comment by rgl** [comment]
I'm not seeing a way to known which transient exceptions exist in this code path, so I would suggest catching `StandardError` (if it really just catches the non-internal-ruby exceptions, which should not prevent the ruby runtime from working correctly) because that seems a reasonable compromise vs knowing all the possible transient exceptions.

At the end-of-the-day, if we catch that exception and if things are really broken with a non-transient error, the code already has a timeout/give-up mechanism.

BTW, its not the first time that this code path halts with a transient error. These transient errors are very frustrating because they mean we have just wasted a lot of hours and we have to do it again (and hope for the best).

**Comment by chrisroberts** [comment]
@rgl I agree with you that just catching `StandardError` is acceptable here, especially since the loop is time boxed and it will still propagate up if the error is originating from something unrelated. #11428 will resolve this issue and be in the next release, so from then on you should stop getting these transient or unexpected errors breaking the wait.

Cheers!
