### ISSUE TITLE
Executing "vagrant up" through NPM causes a RubyGems-related error

### ISSUE THREAD

**Issue by thijsputman** [hashicorp/vagrant#11315]
### Vagrant version
2.2.6

### Host operating system
Windows 10 (1903)

### Guest operating system
N/A

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/xenial64"
    config.vm.define "XXX"

    config.vm.network "forwarded_port", guest: 443, host: 8443

    config.vm.provision :shell, :path => "vagrant/bash/bootstrap.sh"
    config.vm.provision :shell, :path => "vagrant/bash/start.sh", run: 'always'

    config.vm.synced_folder ".", "/XXX"

end
```
### Debug output
N/A

### Expected behavior
Executing `vagrant up` as part of an NPM-script should bring up the Vagrant-box.

### Actual behavior
Upon trying to execute `vagrant up` inside an NPM-script, the following error is raised:

```
C:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/bundler.rb:54:in `[]=': Invalid argument - ruby_setenv(GEMRC) (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/bundler.rb:54:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/bundler.rb:32:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/bundler.rb:32:in `instance'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/bin/vagrant:95:in `<main>'
```

Running `vagrant up` directly on the console (i.e. executing `vagrant up` instead of `npm run vagrant`) does not give the error &ndash; Vagrant starts the VM just fine.

### Steps to reproduce
1. `npm init`
2. In the `scripts`-section of `package.json`, add  `"vagrant": "vagrant up"`
3. Exectue `npm run vagrant`

### References
It appears a workaround for a Windows-related `ENV['GEMRC']` problem in RubyGems is causing this behaviour. Removing the workaround code solves the issue described above. See the below pull-request and the original RubyGems issue for more details.

 - https://github.com/hashicorp/vagrant/pull/11306
 - https://github.com/rubygems/rubygems/pull/2735

**Comment by tsteuwer-accesso** [comment]
Same issue is happening on my coworkers computer using windows.

**Comment by tsteuwer-accesso** [comment]
We are having the same exact issue with many of our Windows users.
