### ISSUE TITLE
synched folder fails for python shutil.rmtree

### ISSUE THREAD

**Issue by PeterFromSweden** [hashicorp/vagrant#11321]
Vagrant 2.2.6
Host: Windows 7 64-bit
Guest: Ubuntu 18.04 (Python 3.6.9)

# Problem
python3 -c 'import shutil; shutil.rmtree("1a")'

# Error message
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/shutil.py", line 486, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.6/shutil.py", line 424, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.6/shutil.py", line 424, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.6/shutil.py", line 428, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 426, in _rmtree_safe_fd
    os.rmdir(name, dir_fd=topfd)
OSError: [Errno 26] Text file busy: '4a'
# Expected behaviour
Just as `rm -r 1a`
# Reproduction steps
[1.Windows 7 commands.txt](https://github.com/hashicorp/vagrant/files/4058560/1.Windows.7.commands.txt)
[2.CreateSomeFolders.cmd.txt](https://github.com/hashicorp/vagrant/files/4058565/2.CreateSomeFolders.cmd.txt)
[3.Vagrant ssh commands.txt](https://github.com/hashicorp/vagrant/files/4058558/3.Vagrant.ssh.commands.txt)
[4.Error message.txt](https://github.com/hashicorp/vagrant/files/4058559/4.Error.message.txt)

**Comment by briancain** [comment]
Hey there! Thanks for opening an issue on Vagrant. This seems to just be an issue with shared folders and virtualbox. You can read more about it on the open ticket here: https://www.virtualbox.org/ticket/19004?cversion=0&cnum_hist=2

You might be able to get around it by using a different type for your synced folders other than the default virtualbox type. Thanks!
