### ISSUE TITLE
Configuring and enabling network interfaces... `await_response_state': Agent pid 3330 (RuntimeError)

### ISSUE THREAD

**Issue by ryancwalsh** [hashicorp/vagrant#11456]
I realize you might not be able to help since I'm using Homestead, and I don't have reliable steps to reproduce this yet, but this has been happening very very frequently for me over the past few days whenever I run `cd /c/code/Homestead/ && vagrant up` or `cd /c/code/Homestead/ && vagrant reload --provision` so I figured I'd report it in case other people have been mentioning this too.

### Vagrant version

2.2.7

### Host operating system

Windows 10

### Guest operating system

Ubuntu 18.04 https://laravel.com/docs/7.x/homestead#introduction

### Actual behavior

```
==> vboxHomestead: Machine booted and ready!
==> vboxHomestead: Checking for guest additions in VM...
    vboxHomestead: The guest additions on this VM do not match the installed version of
    vboxHomestead: VirtualBox! In most cases this is fine, but in rare cases it can
    vboxHomestead: prevent things such as shared folders from working properly. If you see
    vboxHomestead: shared folder errors, please make sure the guest additions within the
    vboxHomestead: virtual machine match the version of VirtualBox you have installed on
    vboxHomestead: your host and reload your VM.
    vboxHomestead:
    vboxHomestead: Guest Additions Version: 6.0.0 r127566
    vboxHomestead: VirtualBox Version: 6.1
==> vboxHomestead: Setting hostname...
==> vboxHomestead: Configuring and enabling network interfaces...
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-scp-1.2.1/lib/net/scp.rb:398:in `await_response_state': Agent pid 3330 (RuntimeError)
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-scp-1.2.1/lib/net/scp.rb:369:in `block (3 levels) in start_command'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/channel.rb:323:in `process'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:250:in `block in ev_preprocess'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:540:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:540:in `each_channel'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:250:in `ev_preprocess'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/event_loop.rb:101:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/event_loop.rb:101:in `ev_preprocess'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/event_loop.rb:29:in `process'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:228:in `process'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:181:in `block in loop'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:181:in `loop'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/session.rb:181:in `loop'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-ssh-5.1.0/lib/net/ssh/connection/channel.rb:272:in `wait'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-scp-1.2.1/lib/net/scp.rb:284:in `upload!'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/communicators/ssh/communicator.rb:327:in `block (2 levels) in upload'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/communicators/ssh/communicator.rb:333:in `block in upload'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/communicators/ssh/communicator.rb:742:in `block in scp_connect'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/communicators/ssh/communicator.rb:382:in `connect'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/communicators/ssh/communicator.rb:740:in `scp_connect'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/communicators/ssh/communicator.rb:303:in `upload'
```

Additionally, trying to destroy the box causes a similar error:

```
vagrant destroy
==> vboxHomestead: Running action triggers before destroy ...
==> vboxHomestead: Running trigger...
==> vboxHomestead: Backing up mysql database homestead...
==> vboxHomestead: Trigger run failed
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-scp-1.2.1/lib/net/scp.rb:398:in `await_response_state': Agent pid 4861 (RuntimeError)
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/net-scp-1.2.1/lib/net/scp.rb:369:in `block (3 le...
```
unless and until I comment out `backup: true` in the Homestead.yaml. Then `vagrant destroy` works, and then `vagrant up` works, and I use the machine for a while, and eventually I run into this problem all over again later.

**Comment by briancain** [comment]
Hey there @ryancwalsh - Have you opened an issue with the Homestead maintainers yet? Or tried using a previous version of Vagrant to see if that helps? And does it matter if you use a different Vagrant box? Also, please provide us with the full debug log from running `vagrant up --debug`...thanks!

**Comment by ryancwalsh** [comment]
@briancain I may not have reported it to Homestead yet. Thanks for these tips. Next time I'm looking at this, I'll try an older version at https://releases.hashicorp.com/vagrant/ and will use `--debug`. Thanks.

**Comment by ryancwalsh** [comment]
@briancain  I downgraded to 2.26 but then got:

> Vagrant has detected that you have a version of VirtualBox installed
> that is not supported by this version of Vagrant. Please install one of
> the supported versions listed below to use Vagrant:
> 
> 4.0, 4.1, 4.2, 4.3, 5.0, 5.1, 5.2, 6.0

It was worth a shot, but unfortunately that didn't help. I've submitted: https://github.com/laravel/homestead/issues/1394

**Comment by chrisroberts** [comment]
Closing as this was resolved in issue linked above
