### ISSUE TITLE
Running plugin expunge causes a NoMethodError

### ISSUE THREAD

**Issue by konstruktoid** [hashicorp/vagrant#11590]
### Vagrant version

```
$ vagrant -v
Vagrant 2.2.8
$ vagrant plugin list
vagrant-scp (0.5.7, global)
vagrant-vbguest (0.24.0, global)
```

### Host operating system

```
ProductName:    Mac OS X
ProductVersion: 10.15.4
BuildVersion:   19E287
```

### Debug output

https://gist.github.com/konstruktoid/c6f12fa7634ea55e8d9d319bba2b0ea3

### Expected behavior

Plugins removed and reinstalled.

### Actual behavior

Reinstallation quits with a `NoMethodError`.

### Steps to reproduce

```
$ vagrant plugin expunge --reinstall

This command permanently deletes all currently installed user plugins. It
should only be used when a repair command is unable to properly fix the
system.

Continue? [N]: y

All user installed plugins have been removed from this Vagrant environment!

Vagrant will now attempt to reinstall user plugins that were removed.
Installing the 'vagrant-scp' plugin. This can take a few minutes...
Fetching vagrant-scp-0.5.7.gem
Fetching micromachine-3.0.0.gem
Fetching vagrant-vbguest-0.24.0.gem
Installed the plugin 'vagrant-scp (0.5.7)'!
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Traceback (most recent call last):
        14: from /opt/vagrant/embedded/gems/2.2.8/gems/vagrant-2.2.8/bin/vagrant:205:in `<main>'
        13: from /opt/vagrant/embedded/gems/2.2.8/gems/vagrant-2.2.8/lib/vagrant/environment.rb:290:in `cli'
        12: from /opt/vagrant/embedded/gems/2.2.8/gems/vagrant-2.2.8/lib/vagrant/cli.rb:67:in `execute'
        11: from /opt/vagrant/embedded/gems/2.2.8/gems/vagrant-2.2.8/plugins/commands/plugin/command/root.rb:66:in `execute'
        10: from /opt/vagrant/embedded/gems/2.2.8/gems/vagrant-2.2.8/plugins/commands/plugin/command/expunge.rb:69:in `execute'
         9: from /opt/vagrant/embedded/gems/2.2.8/gems/vagrant-2.2.8/plugins/commands/plugin/command/expunge.rb:69:in `each'
         8: from /opt/vagrant/embedded/gems/2.2.8/gems/vagrant-2.2.8/plugins/commands/plugin/command/expunge.rb:77:in `block in execute'
         7: from /opt/vagrant/embedded/gems/2.2.8/gems/vagrant-2.2.8/plugins/commands/plugin/command/base.rb:14:in `action'
         6: from /opt/vagrant/embedded/gems/2.2.8/gems/vagrant-2.2.8/lib/vagrant/action/runner.rb:89:in `run'
         5: from /opt/vagrant/embedded/gems/2.2.8/gems/vagrant-2.2.8/lib/vagrant/util/busy.rb:19:in `busy'
         4: from /opt/vagrant/embedded/gems/2.2.8/gems/vagrant-2.2.8/lib/vagrant/action/runner.rb:89:in `block in run'
         3: from /opt/vagrant/embedded/gems/2.2.8/gems/vagrant-2.2.8/lib/vagrant/action/builder.rb:116:in `call'
         2: from /opt/vagrant/embedded/gems/2.2.8/gems/vagrant-2.2.8/lib/vagrant/action/warden.rb:48:in `call'
         1: from /opt/vagrant/embedded/gems/2.2.8/gems/vagrant-2.2.8/plugins/commands/plugin/action/install_gem.rb:30:in `call'
/opt/vagrant/embedded/gems/2.2.8/gems/vagrant-2.2.8/lib/vagrant/plugin/manager.rb:156:in `install_plugin': undefined method `name' for nil:NilClass (NoMethodError)
$ vagrant plugin install vagrant-scp
Installing the 'vagrant-scp' plugin. This can take a few minutes...
Installed the plugin 'vagrant-scp (0.5.7)'!
$ vagrant plugin install vagrant-vbguest
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Installed the plugin 'vagrant-vbguest (0.24.0)'!
$ 
```

**Comment by codekandis** [comment]
Jarp! Same here.

**Comment by chrisroberts** [comment]
@codekandis Did the error occur on the same plugin (vagrant-vbguest) or a different one?
