### ISSUE TITLE
VagrantPlugins::DockerProvisioner::Installer#ensure_installed is failing

### ISSUE THREAD

**Issue by pvalena** [hashicorp/vagrant#11606]
### Vagrant version
2.2.9

### Host operating system
Fedora

### Debug output
On executing the test suite, the newly added test fails, as it tries to detect arch:
(exporting VAGRANT_DETECTED_OS didn't help)

```console
  1) VagrantPlugins::DockerProvisioner::Installer#ensure_installed installs docker if not present
     Failure/Error: expect {subject.ensure_installed()}.to raise_error(VagrantPlugins::DockerProvisioner::DockerError)

       expected VagrantPlugins::DockerProvisioner::DockerError, got #<RSpec::Mocks::MockExpectationError: #<Double "comm"> received :test with unexpected arguments
         exp...do=>true}]
       +["[ -x /usr/bin/lsb_release ] && /usr/bin/lsb_release -i 2>/dev/null | grep Trisquel"]
       > with backtrace:
         # ./plugins/guests/trisquel/guest.rb:5:in `detect?'
         # ./lib/vagrant/capability_host.rb:148:in `block (2 levels) in autodetect_capability_host'
         # ./lib/vagrant/capability_host.rb:143:in `each'
         # ./lib/vagrant/capability_host.rb:143:in `block in autodetect_capability_host'
         # ./lib/vagrant/capability_host.rb:142:in `each'
         # ./lib/vagrant/capability_host.rb:142:in `autodetect_capability_host'
         # ./lib/vagrant/capability_host.rb:36:in `initialize_capabilities!'
         # ./lib/vagrant/guest.rb:34:in `detect!'
         # ./lib/vagrant/machine.rb:276:in `guest'
         # ./plugins/provisioners/docker/installer.rb:12:in `ensure_installed'
         # ./test/unit/plugins/provisioners/docker/installer_test.rb:43:in `block (4 levels) in <top (required)>'
         # ./test/unit/plugins/provisioners/docker/installer_test.rb:43:in `block (3 levels) in <top (required)>'
     # ./test/unit/plugins/provisioners/docker/installer_test.rb:43:in `block (3 levels) in <top (required)>'
```

_Note: we're running the test suite using rack, but without bundler, to test vagrant with the OS it will be used on._

**Comment by briancain** [comment]
@pvalena - Thanks for bringing this to our attention! It wasn't failing on our CI, but I was able to reproduce it on my machine. Either way the fix has been merged.
