### ISSUE TITLE
vagrant version  2.2.9 on CentOS 7

### ISSUE THREAD

**Issue by nohtyp** [hashicorp/vagrant#11624]
### Vagrant version

Vagrant 2.2.9

### Host operating system

CentOS Linux release 7.8.2003 (Core)

### Guest operating system

centos 7

### Expected behavior

```
vagrant status

Current machine states:

wazuhmanager              not created (aws)

The EC2 instance is not created. Run `vagrant up` to create it.
```

### Actual behavior

```
vagrant status
Traceback (most recent call last):
        27: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/bin/vagrant:23:in `<main>'
        26: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/bin/vagrant:23:in `load'
        25: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/bin/vagrant:205:in `<top (required)>'
        24: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/environment.rb:290:in `cli'
        23: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/cli.rb:67:in `execute'
        22: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/plugins/commands/status/command.rb:20:in `execute'
        21: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/plugin/v2/command.rb:212:in `with_target_vms'
        20: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/plugin/v2/command.rb:212:in `map'
        19: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/plugin/v2/command.rb:213:in `block in with_target_vms'
        18: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
        17: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/environment.rb:715:in `machine'
        16: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/vagrantfile.rb:81:in `machine'
        15: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/vagrantfile.rb:81:in `new'
        14: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/machine.rb:151:in `initialize'
        13: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/machine.rb:535:in `state'
        12: from /home/centos/.vagrant.d/gems/2.6.2/gems/vagrant-aws-0.7.2/lib/vagrant-aws/provider.rb:32:in `state'
        11: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/machine.rb:198:in `action'
        10: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/machine.rb:194:in `block in action'
         9: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/machine.rb:212:in `block in action'
         8: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/machine.rb:240:in `action_raw'
         7: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/action/runner.rb:89:in `run'
         6: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/util/busy.rb:19:in `busy'
         5: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/action/runner.rb:89:in `block in run'
         4: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/action/builder.rb:116:in `call'
         3: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
         2: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
         1: from /tmp/.mount_vagran8gm3oZ/usr/gembundle/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
/home/centos/.vagrant.d/gems/2.6.2/gems/vagrant-aws-0.7.2/lib/vagrant-aws/action/connect_aws.rb:42:in `call': undefined method `except' for #<Hash:0x0000000003c24400> (NoMethodError)
```

What actually happened?

I have looked at line 42 in the connect_aws.rb file and currently the value for [:aws_elb] is null or not present and fails with command.  I added an if conditional to check for the value, after the conditional was added I was able to spin up my machine in AWS.

### Steps to reproduce

1. download vagrant version 2.2.9 on CentOS 7 machine
2. added steps listed in https://github.com/mitchellh/vagrant-aws
3. vagrant status

**Comment by briancain** [comment]
Hey there @nohtyp - thanks for opening an issue with Vagrant. Unfortunately, that provider plugin is no longer officially supported in any capacity. I'm glad you found a fix that works though!

**Comment by briancain** [comment]
It looks like this comment might solve your problem: https://github.com/mitchellh/vagrant-aws/issues/566#issuecomment-580812210
