### ISSUE TITLE
Encoding::UndefinedConversionError

### ISSUE THREAD

**Issue by hxingpax** [hashicorp/vagrant#11637]
Traceback (most recent call last):
        30: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/bin/vagrant:168:in `<main>'
        29: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/bin/vagrant:168:in `new'
        28: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/environment.rb:178:in `initialize'
        27: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/environment.rb:983:in `process_configured_plugins'
        26: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/environment.rb:955:in `find_configured_plugins'
        25: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/environment.rb:943:in `guess_provider'
        24: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/environment.rb:347:in `default_provider'
        23: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/registry.rb:48:in `each'
        22: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/registry.rb:48:in `each'
        21: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/registry.rb:49:in `block in each'
        20: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/environment.rb:361:in `block in default_provider'
        19: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/plugins/providers/hyperv/provider.rb:20:in `usable?'
        18: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/platform.rb:84:in `windows_admin?'
        17: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/platform.rb:82:in `block in windows_admin?'
        16: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/powershell.rb:96:in `execute_cmd'
        15: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/powershell.rb:195:in `validate_install!'
        14: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/powershell.rb:174:in `version'
        13: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/subprocess.rb:22:in `execute'
        12: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/subprocess.rb:152:in `execute'
        11: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/safe_chdir.rb:24:in `safe_chdir'
        10: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/safe_chdir.rb:24:in `synchronize'
         9: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/safe_chdir.rb:25:in `block in safe_chdir'
         8: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/safe_chdir.rb:25:in `chdir'
         7: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/safe_chdir.rb:26:in `block (2 levels) in safe_chdir'
         6: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/subprocess.rb:153:in `block in execute'
         5: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/childprocess-3.0.0/lib/childprocess/abstract_process.rb:81:in `start'
         4: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/childprocess-3.0.0/lib/childprocess/windows/process.rb:70:in `launch_process'
         3: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/childprocess-3.0.0/lib/childprocess/windows/process_builder.rb:28:in `start'
         2: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/childprocess-3.0.0/lib/childprocess/windows/process_builder.rb:67:in `create_environment_pointer'
         1: from E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/childprocess-3.0.0/lib/childprocess/windows/process_builder.rb:44:in `to_wide_string'
E:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/childprocess-3.0.0/lib/childprocess/windows/process_builder.rb:44:in `encode!': "\xE8" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to UTF-16LE (Encoding::UndefinedConversionError)

### Vagrant version

Vagrant 2.2.9

### Host operating system

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362

### Guest operating system

None

### Vagrantfile

```ruby
# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output

Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior

What should have happened?

### Actual behavior

What actually happened?

### Steps to reproduce

1. run `vagrant` in terminal
2.
3.

### References

Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by hxingpax** [comment]
Solved by [following way from Stackoverflow](https://stackoverflow.com/questions/26086424/vagrant-windows-1251-encoding-error):

go to : c:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.6.3\bin\vagrant

And edit the vagrant (file) and put after this :

~~~
#!/usr/bin/env ruby
~~~

this 2 lines

~~~
Encoding.default_external = Encoding.find('Windows-1250')
Encoding.default_internal = Encoding.find('Windows-1250')
~~~

**Comment by lunluen** [comment]
Same problem here for having a `chcp 65001` in my powershell start script.
Solved after simply removing it, though some fonts are invalid now.
