### ISSUE TITLE
check_hyperv_access.ps1 fails when provisioning VM from WSL 2 on Hyper-V.

### ISSUE THREAD

**Issue by Markd-One** [hashicorp/vagrant#11724]
### Vagrant version

Vagrant 2.2.9

### Host operating system

WSL 2: Ubuntu 20.04
Base OS: Windows 10 Version 2004

### Guest operating system

generic/centos8

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8"
end
```

### Debug output

https://gist.github.com/Markd-One/deaf13f576b204c07047cf23b44b8938

### Expected behavior

VM is proivisioned on Windows 10 Hyper-V when executing `vagrant up --provider hyperv` from WSL2 environment.

### Actual behavior
Vagrant crashed when running check_hyperv_access.ps1 script.
```
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: check_hyperv_access.ps1
Error:

Get-ACL : Method failed with unexpected error code 1.
At \\wsl$\Ubuntu\opt\vagrant\embedded\gems\2.2.9\gems\vagrant-2.2.9\plugins\providers\hyperv\scripts\utils\VagrantVM\VagrantVM.psm1:723 char:12
+     $acl = Get-ACL -Path $Path
+            ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Acl], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.GetAclCommand
```
On base Windows 10 VM without using WSL2 is provisioned successfully.

### Steps to reproduce

1. Install Vagrant 2.2.9 both on WSL2 instance and on Win 10. 
2. Install Hyper-V on Win 10.
3. Run export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1" on WSL 2.
4. Run `vagrant up --provider hyperv `with provided Vagrant file on WSL 2.

**Comment by juliangiuca** [comment]
I was able to solve this problem by following this guide: https://github.com/deluxebrain/wsl-vagrant-hyperv-setup

Specifically, the Sync Folder step - making sure your Vagrant project is in your Windows user path (`ln -s /mnt/c/Users/<username>/source ~/source`)

It's referenced here: https://www.vagrantup.com/docs/other/wsl.html#synced-folders, 

I assumed I wouldn't need to do this since I had disabled synced_folders in my Vagrantfile:
`config.vm.synced_folder ".", "/vagrant", disabled: true`

**Comment by Markd-One** [comment]
Thanks for the tip. I did not try running it from windows filesystem due to performance issues accessing windows filesystem on WSL 2. 
It only partially worked as I have run now into network issue probably due to changes introduced by WSL 2. 

As WSL 2 now lives in the "invisible" virtual machine in Hyper-V it also uses separate network switch called WSL so when provisioning new VM they must use same network switch - WSL in this case otherwise Vagrant will timeout when attempting to set secure ssh key.
But even when provisioning on the same switch I am getting errors when Vagrant attempts to connect to the newly provisioned VM to replace key. Not sure why it attempts to connect over IPv6 address and I do not know whether that is the root case for the network issue.

```
Bringing machine 'master' up with 'hyperv' provider...
==> master: Verifying Hyper-V is enabled...
==> master: Verifying Hyper-V is accessible...
==> master: Importing a Hyper-V instance
    master: Creating and registering the VM...
    master: Successfully imported VM
    master: Configuring the VM...
==> master: Starting the machine...
==> master: Waiting for the machine to report its IP address...
    master: Timeout: 120 seconds
    master: IP: fe80::215:5dff:fe01:af27
==> master: Waiting for machine to boot. This may take a few minutes...
    master: SSH address: fe80::215:5dff:fe01:af27:22
    master: SSH username: vagrant
    master: SSH auth method: private key
Traceback (most recent call last):
        27: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'
        26: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/plugins/communicators/ssh/communicator.rb:63:in `wait_for_ready'
        25: from /opt/vagrant/embedded/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
        24: from /opt/vagrant/embedded/lib/ruby/2.6.0/timeout.rb:33:in `catch'
        23: from /opt/vagrant/embedded/lib/ruby/2.6.0/timeout.rb:33:in `catch'
        22: from /opt/vagrant/embedded/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
        21: from /opt/vagrant/embedded/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
        20: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/plugins/communicators/ssh/communicator.rb:87:in `block in wait_for_ready'
        19: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/plugins/communicators/ssh/communicator.rb:431:in `connect'
        18: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/util/retryable.rb:17:in `retryable'
        17: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/plugins/communicators/ssh/communicator.rb:432:in `block in connect'
        16: from /opt/vagrant/embedded/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
        15: from /opt/vagrant/embedded/lib/ruby/2.6.0/timeout.rb:33:in `catch'
        14: from /opt/vagrant/embedded/lib/ruby/2.6.0/timeout.rb:33:in `catch'
        13: from /opt/vagrant/embedded/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
        12: from /opt/vagrant/embedded/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
        11: from /opt/vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/plugins/communicators/ssh/communicator.rb:466:in `block (2 levels) in connect'
        10: from /opt/vagrant/embedded/gems/2.2.9/gems/net-ssh-5.2.0/lib/net/ssh.rb:246:in `start'
         9: from /opt/vagrant/embedded/gems/2.2.9/gems/net-ssh-5.2.0/lib/net/ssh.rb:246:in `new'
         8: from /opt/vagrant/embedded/gems/2.2.9/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:73:in `initialize'
         7: from /opt/vagrant/embedded/lib/ruby/2.6.0/socket.rb:631:in `tcp'
         6: from /opt/vagrant/embedded/lib/ruby/2.6.0/socket.rb:227:in `foreach'
         5: from /opt/vagrant/embedded/lib/ruby/2.6.0/socket.rb:227:in `each'
         4: from /opt/vagrant/embedded/lib/ruby/2.6.0/socket.rb:641:in `block in tcp'
         3: from /opt/vagrant/embedded/lib/ruby/2.6.0/socket.rb:137:in `connect'
         2: from /opt/vagrant/embedded/lib/ruby/2.6.0/socket.rb:56:in `connect_internal'
         1: from /opt/vagrant/embedded/lib/ruby/2.6.0/socket.rb:1213:in `connect_nonblock'
/opt/vagrant/embedded/lib/ruby/2.6.0/socket.rb:1213:in `__connect_nonblock': Invalid argument - connect(2) for [fe80::215:5dff:fe01:af27]:22 (Errno::EINVAL)
```

**Comment by p1-ra** [comment]
I'm using WSL2 with vagrant. I've got the same issue as you. I've followed this how to: https://gist.github.com/savishy/8ed40cd8692e295d64f45e299c2b83c9
After having configured an other internal vswitch, and assigned it to my vagrant box (instead of WSL2 vswitch), everything is now working like a charm.

Btw, I've re-configured the VM vswitch directly from the Hyper-V manager, we could probably ask vagrant to reconfigure it, but I'm just discovering vagrant so don't really now how to do it.

Also, you will probably have an right issue on the ssh key used by vagrant (since it's save under the ntfs), I've mitigated it by:
```
$ mv .vagrant/machines/default/hyperv/private_key ~/.ssh/vagrant_private_key
$ sudo chmod 600 ~/.ssh/vagrant_private_key
$ ln -s /home/yourusername/.ssh/vagrant_private_key .vagrant/machines/default/hyperv/private_key
```

**Comment by AMoghrabi** [comment]
Hey @p1-ra , thanks for the instructions on how to get going. Really helpful.

I'm also new to with Vagrant. I'm tearing down my vagrant box and re-building often, so that means I need to execute the SSH key steps every time. Have you found a way to get around that?

Thanks!

**Comment by piotrkochan** [comment]
```╰─$ vagrant up                                                                                                    1 ↵
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: check_hyperv.ps1
Error:

& : The term '\\wsl$\Debian\tmp\.mount_vagraniyenME\usr\gembundle\gems\vagrant-2.2.10\plugins\providers\hyperv\scripts\
check_hyperv.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spel
ling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:153
+ ... ts\utils'; &('\\wsl$\Debian\tmp\.mount_vagraniyenME\usr\gembundle\gem ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (\\wsl$\Debian\t...heck_hyperv.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by devjack** [comment]
I'm experiencing the same/similar issue with a similar environment.
 - No synced directories.
 - Ubuntu 20.04 LTS, WSL2 and Hyper-V
 - Windows 10 Pro - Build 19041
 - Vagrant 2.2.10 (installed from .deb in Ubuntu)

**Sudo Vagrant (WSL2 as Administrator)**
```
─➤  sudo /opt/vagrant/bin/vagrant up --provider=hyperv
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: check_hyperv.ps1
Error:

& : The script 'check_hyperv.ps1' cannot be run because the following modules that are specified by the "#requires"
statements of the script are missing: VagrantMessages.
At line:1 char:135
+ ... ts\utils'; &('\opt\vagrant\embedded\gems\2.2.10\gems\vagrant-2.2.10\p ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (check_hyperv.ps1:String) [], ScriptRequiresException
    + FullyQualifiedErrorId : ScriptRequiresMissingModules
```

**When vagrant is not run with sudo (WSL2 as Administrator)**
```
─➤  /opt/vagrant/bin/vagrant up --provider=hyperv                                                                  
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Verifying Hyper-V is accessible...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: check_hyperv_access.ps1
Error:

Get-ACL : Method failed with unexpected error code 1.
At \\wsl$\Ubuntu-20.04\opt\vagrant\embedded\gems\2.2.10\gems\vagrant-2.2.10\plugins\providers\hyperv\scripts\utils\Vagr
antVM\VagrantVM.psm1:731 char:12
+     $acl = Get-ACL -Path $Path
+            ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-Acl], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.PowerShell.Commands.GetAclCommand

```

For comparison, when **WSL2 is not run as Administrator** (not surprisingly) sudo has no effect:
```
╰─➤  /opt/vagrant/bin/vagrant up --provider=hyperv
The provider 'hyperv' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

The Hyper-V provider requires that Vagrant be run with
administrative privileges. This is a limitation of Hyper-V itself.
Hyper-V requires administrative privileges for management
commands. Please restart your console with administrative
privileges and try again.
```

## Steps to reproduce:
 - `export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"`
 - `/opt/vagrant/bin/vagrant up --provider=hyperv` 

Vagrantfile:
```
Vagrant.configure("2") do |config|
  config.vm.box = "hasicorp/bionic64"
end
```

**Comment by p1-ra** [comment]
> Hey @p1-ra , thanks for the instructions on how to get going. Really helpful.
> 
> I'm also new to with Vagrant. I'm tearing down my vagrant box and re-building often, so that means I need to execute the SSH key steps every time. Have you found a way to get around that?
> 
> Thanks!

Kinda old, but if needed, I think you should be able to move all your `.vagrant` from ntfs to your linux FS, then create a syslink toward it:

```
mv .vagrant ~/
ln -s ~/.vagrant .
```

Thus, it will be able to properly set the access right on it (since the FS won't be NTFS anymore)

Best regards

**Comment by maroskukan** [comment]
@p1-ra , you  likely need to do some additional steps, otherwise you end up with same error as @Markd-One reported.

An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: check_hyperv_access.ps1
Error:

Get-ACL : Method failed with unexpected error code 1.
At \\wsl$\Ubuntu-20.04\opt\vagrant\embedded\gems\2.2.14\gems\vagrant-2.2.14\plugins\providers\hyperv\scripts\utils\VagrantVM\VagrantVM.ps
m1:731 char:12

So in general permissions on these shared folders that live on windows side is an issues, e.g. ansible will complain that private key is 077 and will refuse to use it.
