### ISSUE TITLE
'parse': 767: Unexpected token at '' (JSON::ParserError) 

### ISSUE THREAD

**Issue by vulongtran** [hashicorp/vagrant#11864]
### Vagrant version
Vagrant 2.2.10

### Host operating system
Windows 10 Pro

### Guest operating system
Debian Ubuntu

### Vagrantfile

```ruby

# -*- mode: ruby -*-
# vi: set ft=ruby :

# Configure VM box
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
    end

    # Enable provisioning with a shell script. 
    config.vm.provision :shell, path: "jenkins.sh"
    # 
end
`````

### Expected behavior
vagrant up is meant to load up Vagrant image. 
What should have happened?
Instead it presented this error messaged.

### Actual behavior
![vagrant error](https://user-images.githubusercontent.com/11552027/91659636-a0988200-eb03-11ea-8691-dbc4d114e191.png)

```
PS C:\Users\USERNAME\OneDrive\Documents\Projects\Vagrant> vagrant -v
Vagrant 2.2.10
PS C:\Users\USERNAME\OneDrive\Documents\Projects\Vagrant> vagrant up
Traceback (most recent call last):
        9: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/bin/vagrant:168:in `<main>'
        8: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/bin/vagrant:168:in `new'
        7: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/environment.rb:178:in `initialize'
        6: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/environment.rb:983:in `process_configured_plugins'
        5: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/environment.rb:956:in `find_configured_plugins'
        4: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/environment.rb:956:in `each'
        3: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/environment.rb:958:in `block in find_configured_plugins'
        2: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/vagrantfile.rb:187:in `machine_config'
        1: from C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.6.0/json/common.rb:156:in `parse'
C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.6.0/json/common.rb:156:in `parse': 767: unexpected token at '' (JSON::ParserError)

```
### Steps to reproduce
1. typed in 'vagrant v'
2. error message popped up (per screenshot attached)
3. restarted computer, no change
4. uninstalled, downloaded and reinstalled vagrant and restarted computer and then typed in 'vagrant up'
4. error message popped up (per the above text dump)

### References
- #10863 https://github.com/hashicorp/vagrant/issues/10863

**Comment by vulongtran** [comment]
Okay, I have this working now.

I deleted the .Vagrant folder and it regenerated a new .Vagrant folder. For future readers, you can try that if you also see a similar error to what I have faced.
