### ISSUE TITLE
VAGRANT_EXPERIMENTAL 'disks' not working with VirtualBox 6.1.14

### ISSUE THREAD

**Issue by scoiatael** [hashicorp/vagrant#11883]
Hello,

today I upgraded Vagrant and VirtualBox to newest versions via Homebrew on macOS.

It seems the 'disks' feature started throwing following error after the upgrade when creating new VM:

```
==> vagrant: You have requested to enabled the experimental flag with the following features:
==> vagrant:
==> vagrant: Features:  disks
==> vagrant:
==> vagrant: Please use with caution, as some of the features may not be fully
==> vagrant: functional yet.
Bringing machine 'pube' up with 'virtualbox' provider...
==> pube: Importing base box 'debian/buster64'...
==> pube: Matching MAC address for NAT networking...
==> pube: Checking if box 'debian/buster64' version '10.4.0' is up to date...
==> pube: Setting the name of the VM: puppet_pube_1599552640679_18428
==> pube: Clearing any previously set network interfaces...
==> pube: Preparing network interfaces based on configuration...
    pube: Adapter 1: nat
    pube: Adapter 2: hostonly
==> pube: Forwarding ports...
    pube: 443 (guest) => 8443 (host) (adapter 1)
    pube: 22 (guest) => 2222 (host) (adapter 1)
==> pube: Configuring storage mediums...
==> pube: Destroying VM and associated drives...
Traceback (most recent call last):
	145: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
	144: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine.rb:201:in `action'
	143: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine.rb:201:in `call'
	142: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/environment.rb:613:in `lock'
	141: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine.rb:215:in `block in action'
	140: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine.rb:243:in `action_raw'
	139: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `run'
	138: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/util/busy.rb:19:in `busy'
	137: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `block in run'
	136: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builder.rb:149:in `call'
	135: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	134: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	133: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	132: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/call.rb:53:in `call'
	131: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `run'
	130: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/util/busy.rb:19:in `busy'
	129: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `block in run'
	128: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builder.rb:149:in `call'
	127: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	126: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	125: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	124: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	123: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	122: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	121: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	120: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	119: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	118: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/call.rb:53:in `call'
	117: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `run'
	116: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/util/busy.rb:19:in `busy'
	115: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `block in run'
	114: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builder.rb:149:in `call'
	113: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	112: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	111: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	110: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	109: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	108: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/customize.rb:40:in `call'
	107: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	106: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/prepare_clone.rb:15:in `call'
	105: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	104: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/prepare_clone_snapshot.rb:17:in `call'
	103: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	102: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/import.rb:13:in `call'
	101: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/import.rb:78:in `import'
	100: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 99: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/discard_state.rb:15:in `call'
	 98: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 97: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/match_mac_address.rb:22:in `call'
	 96: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 95: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 94: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 93: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/env_set.rb:19:in `call'
	 92: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 91: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	 90: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 89: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	 88: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 87: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/box_check_outdated.rb:92:in `call'
	 86: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 85: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/call.rb:53:in `call'
	 84: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `run'
	 83: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/util/busy.rb:19:in `busy'
	 82: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `block in run'
	 81: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builder.rb:149:in `call'
	 80: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 79: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 78: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 77: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/call.rb:53:in `call'
	 76: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `run'
	 75: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/util/busy.rb:19:in `busy'
	 74: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `block in run'
	 73: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builder.rb:149:in `call'
	 72: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 71: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 70: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 69: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/call.rb:53:in `call'
	 68: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `run'
	 67: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/util/busy.rb:19:in `busy'
	 66: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `block in run'
	 65: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builder.rb:149:in `call'
	 64: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 63: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 62: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 61: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	 60: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 59: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/clean_machine_folder.rb:26:in `call'
	 58: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 57: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/set_name.rb:50:in `call'
	 56: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 55: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
	 54: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 53: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/provision.rb:80:in `call'
	 52: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 51: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/env_set.rb:19:in `call'
	 50: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 49: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in `call'
	 48: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 47: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:52:in `call'
	 46: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 45: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/prepare_nfs_valid_ids.rb:12:in `call'
	 44: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 43: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
	 42: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 41: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
	 40: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 39: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/delayed.rb:19:in `call'
	 38: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 37: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
	 36: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 35: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/prepare_nfs_settings.rb:19:in `call'
	 34: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 33: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/set_default_nic_type.rb:64:in `call'
	 32: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 31: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/clear_network_interfaces.rb:26:in `call'
	 30: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 29: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/network.rb:123:in `call'
	 28: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 27: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/network_fix_ipv6.rb:41:in `call'
	 26: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 25: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/forward_ports.rb:31:in `call'
	 24: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 23: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/set_hostname.rb:17:in `call'
	 22: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 21: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/sane_defaults.rb:38:in `call'
	 20: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 19: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/call.rb:53:in `call'
	 18: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `run'
	 17: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/util/busy.rb:19:in `busy'
	 16: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `block in run'
	 15: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builder.rb:149:in `call'
	 14: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 13: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 12: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	 11: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/cloud_init_setup.rb:29:in `call'
	 10: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	  9: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	  8: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	  7: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/cleanup_disks.rb:30:in `call'
	  6: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	  5: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/disk.rb:20:in `call'
	  4: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/capability_host.rb:111:in `capability'
	  3: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/capability_host.rb:111:in `call'
	  2: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/cap/configure_disks.rb:46:in `configure_disks'
	  1: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/model/storage_controller_array.rb:30:in `get_primary_controller'
/opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/model/storage_controller_array.rb:30:in `sort': comparison of VagrantPlugins::ProviderVirtualBox::Model::StorageController with VagrantPlugins::ProviderVirtualBox::Model::StorageController failed (ArgumentError)
```

### Vagrant version

2.2.10

### Host operating system

macOS: 10.15.6 w/ VirtualBox: 6.1.14

### Guest operating system

`debian/buster64`

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_EXPERIMENTAL'] = "disks"

Vagrant.configure("2") do |config|
    config.vm.box = "debian/buster64"
    config.vm.network "private_network", ip: "192.168.50.100"

    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.disk :disk, size: "40GB", primary: true

    config.vm.provision "shell", inline: <<~BASH
        lsblk /dev/sda3 || parted /dev/sda mkpart primary ext4 21GB 100%
        lsblk -f /dev/sda3 | grep ext4 || mkfs.ext4 -U 07288e65-9ab3-4726-99df-b188326bdb7f /dev/sda3
        grep "07288e65-9ab3-4726-99df-b188326bdb7f" /etc/fstab || echo -e 'UUID=07288e65-9ab3-4726-99df-b188326bdb7f\t/var/lib/docker\text4\tdefaults\t0\t0' >> /etc/fstab
        mkdir -p /var/lib/docker
        mount -a
    BASH
end
```

### Debug output

https://gist.github.com/scoiatael/4930d935b08c0ecc8d677ec4b8c9ca59

### Potential cause and fix

This looks like a series of bugs one on top of each other. First of all, `sort`doesn't take block argument. Then `boot_priority` might be nil.
For example, when dealing with Floppy controller (type `I82078`) - `boot_priority` won't be assigned properly on https://github.com/scoiatael/vagrant/blob/master/plugins/providers/virtualbox/model/storage_controller.rb#L80 .
All in all, it can be fixed by allowing https://github.com/scoiatael/vagrant/blob/master/plugins/providers/virtualbox/model/storage_controller_array.rb#L65 to properly sort devices with nil boot priority, although it's not likely to be the best solution :)

```diff
-          ordered = sort { |a, b| a.boot_priority <=> b.boot_priority }
+          ordered = sort_by { |x| x.boot_priority || 0 }
```

Cheers and thanks for Vagrant, it's a very handy piece of tech :)

**Comment by chrisroberts** [comment]
Fixed via #11867
