### ISSUE TITLE
2.2.10 crashing on initial configuration

### ISSUE THREAD

**Issue by l0b0** [hashicorp/vagrant#11891]
### Vagrant version

```
$ vagrant --version
Vagrant 2.2.10
```

### Host operating system

Arch Linux, fully up to date.

### Guest operating system

Ubuntu 18.04.

### Debug output

[Gist](https://gist.github.com/l0b0/f7dd75fce16acd75c900076daf72743b)

### Expected behavior

Vagrant should not crash

### Actual behavior

See steps below.

### Steps to reproduce

```
$ cd "$(mktemp --directory)"
$ vagrant init
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
$ vagrant up
Traceback (most recent call last):
	38: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/bin/vagrant:205:in `<main>'
	37: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/environment.rb:290:in `cli'
	36: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/cli.rb:67:in `execute'
	35: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/commands/up/command.rb:87:in `execute'
	34: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
	33: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/plugin/v2/command.rb:186:in `each'
	32: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
	31: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
	30: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/environment.rb:715:in `machine'
	29: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/vagrantfile.rb:81:in `machine'
	28: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/vagrantfile.rb:81:in `new'
	27: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine.rb:154:in `initialize'
	26: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine.rb:538:in `state'
	25: from /home/victorengmark/.vagrant.d/gems/2.7.1/gems/vagrant-lxd-0.4.5/lib/vagrant-lxd/provider.rb:33:in `state'
	24: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine.rb:201:in `action'
	23: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine.rb:197:in `block in action'
	22: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine.rb:215:in `block in action'
	21: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine.rb:243:in `action_raw'
	20: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `run'
	19: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/util/busy.rb:19:in `busy'
	18: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `block in run'
	17: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builder.rb:149:in `call'
	16: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
	15: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/config_validate.rb:15:in `call'
	14: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/config/v2/root.rb:66:in `validate'
	13: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/config/v2/root.rb:66:in `each'
	12: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/config/v2/root.rb:71:in `block in validate'
	11: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/kernel_v2/config/vm.rb:729:in `validate'
	10: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine.rb:628:in `synced_folders'
	 9: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/mixin_synced_folders.rb:168:in `synced_folders'
	 8: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/mixin_synced_folders.rb:38:in `default_synced_folder_type'
	 7: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/mixin_synced_folders.rb:38:in `each'
	 6: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/mixin_synced_folders.rb:39:in `block in default_synced_folder_type'
	 5: from /home/victorengmark/.vagrant.d/gems/2.7.1/gems/vagrant-lxd-0.4.5/lib/vagrant-lxd/synced_folder.rb:30:in `usable?'
	 4: from /home/victorengmark/.vagrant.d/gems/2.7.1/gems/vagrant-lxd-0.4.5/lib/vagrant-lxd/driver.rb:173:in `synced_folders_usable?'
	 3: from /home/victorengmark/.vagrant.d/gems/2.7.1/gems/vagrant-lxd-0.4.5/lib/vagrant-lxd/driver.rb:460:in `container'
	 2: from /home/victorengmark/.vagrant.d/gems/2.7.1/gems/hyperkit-1.2.0/lib/hyperkit/client/containers.rb:65:in `container'
	 1: from /home/victorengmark/.vagrant.d/gems/2.7.1/gems/hyperkit-1.2.0/lib/hyperkit/client/containers.rb:1026:in `container_path'
/home/victorengmark/.vagrant.d/gems/2.7.1/gems/hyperkit-1.2.0/lib/hyperkit/client/containers.rb:1026:in `join': no implicit conversion of nil into String (TypeError)
```

**Comment by l0b0** [comment]
It looks like this is a [vagrant-lxd](https://gitlab.com/catalyst-it/devtools/vagrant-lxd/) issue, so I'll try reporting it there.
