### ISSUE TITLE
Vagrant builder is broken

### ISSUE THREAD

**Issue by zilti** [hashicorp/vagrant#11954]
#### Overview of the Issue

It is not possible to build a box using the Vagrant builder.

#### Reproduction Steps

Use the Vagrant builder on Linux.

### Packer version

Packer v1.6.4

### Simplified Packer Buildfile

```hcl
source "vagrant" "libvirt" {
	communicator =		"ssh"
	source_path =		"opensuse/Leap-15.2.x86_64"
	provider =			"libvirt"
	add_force =			true
}

build {
	sources = 	["source.vagrant.libvirt"]
	provisioner "ansible" {
		playbook_file =		"./playbook.yaml"
		ansible_env_vars =	["sompani_target=gcloud"]
	}
	post-processors {
		post-processor "compress" {
			keep_input_artifact =	true
			compression_level = 	6
			output =				"output/disk.raw.tar.gz"
		}
	}
}
```

### Operating system and Environment details

openSUSE Leap 15.2 x86_64 with latest updates

### Log Fragments and crash.log files

```
==> vagrant.libvirt: Packaging box...
2020/10/10 16:31:45 packer-builder-vagrant plugin: Calling Vagrant CLI: []string{"package", "source", "--output", "package.box"}
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stdout: ==> source: Packaging domain...
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr: ==> source: Require set read access to /var/lib/libvirt/images/output-libvirt_source.img. sudo chmod a+r /var/lib/libvirt/images/output-libvirt_source.img
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr: /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/package_domain.rb:34:in `call': Have no access (RuntimeError)
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /home/zilti/.vagrant.d/gems/2.5.8/gems/vagrant-sshfs-1.3.5/lib/vagrant-sshfs/action_hostpath_fixup.rb:125:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /home/zilti/.vagrant.d/gems/2.5.8/gems/vagrant-sshfs-1.3.5/lib/vagrant-sshfs/action_hostpath_fixup.rb:102:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/builder.rb:116:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/runner.rb:102:in `block in run'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/util/busy.rb:19:in `busy'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/action/runner.rb:102:in `run'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/machine.rb:238:in `action_raw'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/machine.rb:209:in `block in action'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/environment.rb:613:in `lock'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/machine.rb:195:in `call'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/machine.rb:195:in `action'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/plugins/commands/package/command.rb:90:in `package_vm'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/plugins/commands/package/command.rb:79:in `block in package_target'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/plugin/v2/command.rb:238:in `block in with_target_vms'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/plugin/v2/command.rb:232:in `each'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/plugins/commands/package/command.rb:77:in `package_target'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/plugins/commands/package/command.rb:45:in `execute'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/cli.rb:66:in `execute'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/lib/vagrant/environment.rb:290:in `cli'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/gems/vagrant-2.2.7/bin/vagrant:166:in `<top (required)>'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/bin/vagrant:23:in `load'
2020/10/10 16:31:45 packer-builder-vagrant plugin: [vagrant driver] stderr:     from /usr/share/vagrant/gems/bin/vagrant:23:in `<main>'
==> vagrant.libvirt: destroying Vagrant box...
2020/10/10 16:31:45 packer-builder-vagrant plugin: Calling Vagrant CLI: []string{"destroy", "-f", "source"}
```

**Comment by zilti** [comment]
Thanks. My user definitely does have permission. The folder is writable and in the libvirt group, which my user is also in. I can easily create a packer image on libvirt/qemu when not using the vagrant builder, and I can easily create libvirt VMs myself, without needing privilege escalation.

I even tried having a `while` loop running in a second terminal that does `chmod a+rw /var/lib/libvirt/images/output-libvirt_source.img`, but when doing that, I get an error instead about vagrant driver not being able to get shared write access.

**Comment by chrisroberts** [comment]
Hi there,

This error is originating from a third party provider plugin (the `vagrant-libvirt` plugin) that we do not maintain. You can find the GitHub repository for the plugin where you can create an issue here: https://github.com/vagrant-libvirt/vagrant-libvirt

Cheers!
