### ISSUE TITLE
C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/win32/registry.rb:72:in `find': unknown encoding name - CP20127 (ArgumentError)

### ISSUE THREAD

**Issue by ap-coder** [hashicorp/vagrant#11969]
### Vagrant version
Vagrant 2.2.10

### Host operating system
Windows 10 Pro
OS Build 19041.388

### Guest operating system

Homestead

### Vagrantfile

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION ||= "2"
confDir = $confDir ||= File.expand_path(File.dirname(__FILE__))

homesteadYamlPath = confDir + "/Homestead.yaml"
homesteadJsonPath = confDir + "/Homestead.json"
afterScriptPath = confDir + "/after.sh"
customizationScriptPath = confDir + "/user-customizations.sh"
aliasesPath = confDir + "/aliases"

require File.expand_path(File.dirname(__FILE__) + '/scripts/homestead.rb')

Vagrant.require_version '>= 2.2.4'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if File.exist? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "/tmp/bash_aliases"
        config.vm.provision "shell" do |s|
            s.inline = "awk '{ sub(\"\r$\", \"\"); print }' /tmp/bash_aliases > /home/vagrant/.bash_aliases && chown vagrant:vagrant /home/vagrant/.bash_aliases"
        end
    end

    if File.exist? homesteadYamlPath then
        settings = YAML::load(File.read(homesteadYamlPath))
    elsif File.exist? homesteadJsonPath then
        settings = JSON::parse(File.read(homesteadJsonPath))
    else
        abort "Homestead settings file not found in #{confDir}"
    end

    Homestead.configure(config, settings)

    if File.exist? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath, privileged: false, keep_color: true
    end

    if File.exist? customizationScriptPath then
        config.vm.provision "shell", path: customizationScriptPath, privileged: false, keep_color: true
    end

    if Vagrant.has_plugin?('vagrant-hostsupdater')
        config.hostsupdater.remove_on_suspend = false
        config.hostsupdater.aliases = settings['sites'].map { |site| site['map'] }
    elsif Vagrant.has_plugin?('vagrant-hostmanager')
        config.hostmanager.enabled = true
        config.hostmanager.manage_host = true
        config.hostmanager.aliases = settings['sites'].map { |site| site['map'] }
    end

    if Vagrant.has_plugin?('vagrant-notify-forwarder')
        config.notify_forwarder.enable = true
    end
end
```

 

### Debug output
```
 $ vagrant up
Bringing machine 'homestead' up with 'virtualbox' provider...
==> homestead: Importing base box 'laravel/homestead'...
==> homestead: Matching MAC address for NAT networking...
==> homestead: Checking if box 'laravel/homestead' version '10.1.1' is up to date...
==> homestead: Destroying VM and associated drives...
Traceback (most recent call last):
        96: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
        95: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine.rb:201:in `action'
        94: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine.rb:201:in `call'
        93: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/environment.rb:613:in `lock'
        92: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine.rb:215:in `block in action'
        91: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine.rb:243:in `action_raw'
        90: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `run'
        89: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/util/busy.rb:19:in `busy'
        88: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `block in run'
        87: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builder.rb:149:in `call'
        86: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        85: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
        84: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        83: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/call.rb:53:in `call'
        82: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `run'
        81: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/util/busy.rb:19:in `busy'
        80: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `block in run'
        79: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builder.rb:149:in `call'
        78: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        77: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
        76: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        75: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
        74: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        73: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
        72: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        71: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        70: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        69: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/call.rb:53:in `call'
        68: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `run'
        67: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/util/busy.rb:19:in `busy'
        66: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `block in run'
        65: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builder.rb:149:in `call'
        64: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        63: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
        62: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        61: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
        60: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        59: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/customize.rb:40:in `call'
        58: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        57: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/prepare_clone.rb:15:in `call'
        56: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        55: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/prepare_clone_snapshot.rb:17:in `call'
        54: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        53: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/import.rb:13:in `call'
        52: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/import.rb:78:in `import'
        51: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        50: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/discard_state.rb:15:in `call'
        49: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        48: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/match_mac_address.rb:22:in `call'
        47: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        46: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
        45: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        44: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/env_set.rb:19:in `call'
        43: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        42: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
        41: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        40: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        39: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        38: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/box_check_outdated.rb:92:in `call'
        37: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        36: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/call.rb:53:in `call'
        35: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `run'
        34: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/util/busy.rb:19:in `busy'
        33: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `block in run'
        32: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builder.rb:149:in `call'
        31: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        30: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
        29: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        28: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/call.rb:53:in `call'
        27: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `run'
        26: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/util/busy.rb:19:in `busy'
        25: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/runner.rb:89:in `block in run'
        24: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builder.rb:149:in `call'
        23: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        22: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
        21: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
        20: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/call.rb:47:in `call'
        19: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action.rb:356:in `block (4 levels) in action_start'
        18: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action.rb:62:in `action_boot'
        17: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action.rb:62:in `tap'
        16: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action.rb:77:in `block in action_boot'
        15: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        14: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        13: from C:/HashiCorp/Vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/network.rb:2:in `<top (required)>'
        12: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        11: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        10: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/resolv.rb:38:in `<top (required)>'
         9: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/resolv.rb:168:in `<class:Resolv>'
         8: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/resolv.rb:171:in `<class:Hosts>'
         7: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         6: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         5: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/win32/resolv.rb:7:in `<top (required)>'
         4: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         3: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         2: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/win32/registry.rb:4:in `<top (required)>'
         1: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/win32/registry.rb:72:in `<module:Win32>'
C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/win32/registry.rb:72:in `find': unknown encoding name - CP20127 (ArgumentError)


```
### Expected behavior

What should have happened?

### Actual behavior

What actually happened?

### Steps to reproduce

1. run vagrant up
 

### References

Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- https://github.com/hashicorp/vagrant/issues/5869

**Comment by ap-coder** [comment]
Anything?

**Comment by ap-coder** [comment]
What is you turn around on these tickets? Just wondering because i cannot get my local up and running until this is fixed. Thank for your help also.

**Comment by ap-coder** [comment]
Hi any chance you can give me an update?

**Comment by ap-coder** [comment]
Hi you guys around??

**Comment by ap-coder** [comment]
wow thanks for the help

**Comment by ap-coder** [comment]
wow you guys are on it. good job

**Comment by Uriziel47** [comment]
I have also do have this issue when calling ' vagrant up ' in a tmux session, but not in a mingw64 terminal.
However I changed Vagrant/embedded/mingw64/lib/ruby/2.6.0/win32/registry.rb line 72 from:
LOCALE = Encoding.find(Encoding.locale_charmap)
into:
LOCALE = Encoding.find("CP65001")
And now it also works in tmux. But I consider this as a hack, to get back to work.

**Comment by deogracia** [comment]
got the same today by:
*  cloning https://github.com/chocolatey/chocolatey-workshop
*  use bash provided with git on windows
* found #6736 which led me to try using `chcp` which says not found on git bash
* try powershell command with `vagrant up` again and the vm booted up ^^

using vagrant 2.2.14 & virtualbox 6.1 on win10 20h2
