### ISSUE TITLE
Vagrant fails to call VBoxManage

### ISSUE THREAD

**Issue by Nohzoh** [hashicorp/vagrant#12088]
Hello,

OS: Ubuntu 20.10
VirtualBox: 6.1.16
Vagrant: 2.2.14

When I launch any command using VBoxManage, the commands fails with this kind of error:
```
$ VAGRANT_LOG=info vagrant global-status 
 INFO global: Vagrant version: 2.2.14
 INFO global: Ruby version: 2.6.2
 INFO global: RubyGems version: 3.0.3
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_APPIMAGE_LD_LIBRARY_PATH="/tmp/.mount_vagran5UDuNE/usr/lib/:/tmp/.mount_vagran5UDuNE/usr/lib/i386-linux-gnu/:/tmp/.mount_vagran5UDuNE/usr/lib/x86_64-linux-gnu/:/tmp/.mount_vagran5UDuNE/usr/lib32/:/tmp/.mount_vagran5UDuNE/usr/lib64/:/tmp/.mount_vagran5UDuNE/lib/:/tmp/.mount_vagran5UDuNE/lib/i386-linux-gnu/:/tmp/.mount_vagran5UDuNE/lib/x86_64-linux-gnu/:/tmp/.mount_vagran5UDuNE/lib32/:/tmp/.mount_vagran5UDuNE/lib64/:"
 INFO global: VAGRANT_RUBYLIB="/tmp/.mount_vagran5UDuNE/usr/local/lib/site_ruby/2.6.0:/tmp/.mount_vagran5UDuNE/usr/local/lib/x86_64-linux-gnu/site_ruby:/tmp/.mount_vagran5UDuNE/usr/local/lib/site_ruby:/tmp/.mount_vagran5UDuNE/usr/lib/ruby/vendor_ruby/2.6.0:/tmp/.mount_vagran5UDuNE/usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.6.0:/tmp/.mount_vagran5UDuNE/usr/lib/ruby/vendor_ruby:/tmp/.mount_vagran5UDuNE/usr/lib/ruby/2.6.0:/tmp/.mount_vagran5UDuNE/usr/lib/x86_64-linux-gnu/ruby/2.6.0"
 INFO global: VAGRANT_USR_DIR="/tmp/.mount_vagran5UDuNE/usr"
 INFO global: VAGRANT_APPIMAGE_HOST_LD_LIBRARY_PATH=":/tmp/.mount_vagran5UDuNE/usr/lib/:/tmp/.mount_vagran5UDuNE/usr/lib/i386-linux-gnu/:/tmp/.mount_vagran5UDuNE/usr/lib/x86_64-linux-gnu/:/tmp/.mount_vagran5UDuNE/usr/lib32/:/tmp/.mount_vagran5UDuNE/usr/lib64/:/tmp/.mount_vagran5UDuNE/lib/:/tmp/.mount_vagran5UDuNE/lib/i386-linux-gnu/:/tmp/.mount_vagran5UDuNE/lib/x86_64-linux-gnu/:/tmp/.mount_vagran5UDuNE/lib32/:/tmp/.mount_vagran5UDuNE/lib64/:"
 INFO global: VAGRANT_ROOT_DIR="/tmp/.mount_vagran5UDuNE"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/tmp/.mount_vagran5UDuNE"
 INFO global: VAGRANT_LOG="info"
 INFO global: VAGRANT_PKG_CONFIG_PATH="/tmp/.mount_vagran5UDuNE/usr/lib/x86_64-linux-gnu/pkgconfig-int::/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig"
 INFO global: VAGRANT_APPIMAGE="1"
 INFO global: VAGRANT_BIN_DIR="/tmp/.mount_vagran5UDuNE/usr/bin"
 WARN global: resolv replacement has not been enabled!
 INFO manager: Registered plugin: autocomplete command
(...)
 INFO vagrant: `vagrant` invoked: ["global-status"]
 INFO environment: Environment initialized (#<Vagrant::Environment:0x0000000002531040>)
 INFO environment:   - cwd: /home/tarnaud/Téléchargements
 INFO environment: Home path: /home/tarnaud/.vagrant.d
 WARN environment: No local data path is set. Local data cannot be stored.
 INFO manager: Plugins:
 INFO manager:   - vagrant-vbguest = [installed: 0.28.0 constraint: > 0]
 INFO manager: Loading plugins...
 INFO manager: Loading plugin `vagrant-vbguest` with default require: `vagrant-vbguest`
 INFO manager: Registered plugin: vagrant-vbguest
 INFO loader: Loading configuration in order: [:home, :root]
 INFO base: VBoxManage path: VBoxManage
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "--version"]
 INFO subprocess: Command not in installer, restoring original environment...
 INFO subprocess: Detected AppImage environment and request to external binary. Updating library path.
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["--version"]

Stderr: /usr/lib/virtualbox/VBoxManage: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgnutls.so.30: undefined symbol: __gmpz_limbs_write
>
ERROR vagrant: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["--version"]

Stderr: /usr/lib/virtualbox/VBoxManage: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgnutls.so.30: undefined symbol: __gmpz_limbs_write

ERROR vagrant: /tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/plugins/providers/virtualbox/driver/base.rb:440:in `block in execute'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/util/retryable.rb:17:in `retryable'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/plugins/providers/virtualbox/driver/base.rb:398:in `execute'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/plugins/providers/virtualbox/driver/meta.rb:177:in `block in read_version'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/util/retryable.rb:17:in `retryable'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/plugins/providers/virtualbox/driver/meta.rb:176:in `read_version'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/plugins/providers/virtualbox/driver/meta.rb:46:in `block in initialize'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/plugins/providers/virtualbox/driver/meta.rb:41:in `synchronize'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/plugins/providers/virtualbox/driver/meta.rb:41:in `initialize'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/plugins/providers/virtualbox/provider.rb:21:in `new'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/plugins/providers/virtualbox/provider.rb:21:in `usable?'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/environment.rb:361:in `block in default_provider'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/registry.rb:49:in `block in each'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/registry.rb:48:in `each'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/registry.rb:48:in `each'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/environment.rb:347:in `default_provider'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/environment.rb:943:in `guess_provider'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/environment.rb:955:in `find_configured_plugins'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/environment.rb:983:in `process_configured_plugins'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/environment.rb:178:in `initialize'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/bin/vagrant:168:in `new'
/tmp/.mount_vagran5UDuNE/usr/gembundle/gems/vagrant-2.2.14/bin/vagrant:168:in `<top (required)>'
/tmp/.mount_vagran5UDuNE/usr/gembundle/bin/vagrant:23:in `load'
/tmp/.mount_vagran5UDuNE/usr/gembundle/bin/vagrant:23:in `<main>'
Vagrant failed to initialize at a very early stage:

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["--version"]

Stderr: /usr/lib/virtualbox/VBoxManage: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgnutls.so.30: undefined symbol: __gmpz_limbs_write
```

Launching `VBoxManage --version` from the same shell is successful.

**Comment by rushikeshkoli** [comment]
I am also facing the issue.

**Comment by alexanderBendo** [comment]
I'm having a similar issue. When I try to add a box, it returns the same symbol lookup error

`/usr/bin/curl: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgnutls.so.30: undefined symbol: __gmpz_limbs_write`

Vagrant: 2.2.14
OS: debian 10

**Comment by darxkies** [comment]
Me too on Ubuntu 20.10, VirtualBox 6.1.16 and Vagrant 2.2.14

**Comment by qprichard** [comment]
> I'm having a similar issue. When I try to add a box, it returns the same symbol lookup error
> 
> `/usr/bin/curl: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgnutls.so.30: undefined symbol: __gmpz_limbs_write`
> 
> Vagrant: 2.2.14
> OS: debian 10

Installing via .deb file worked for me.

**Comment by rushikeshkoli** [comment]
@qprichard Yep. .deb worked for me as well. Thanks. Now I can learn ansible peacefully

**Comment by Nohzoh** [comment]
Also works for me with .deb under Ubuntu.
Thank you @qprichard !

**Comment by drewbailey** [comment]
Installing via the .deb didn't work for me unfortunately, 

<details>
  <summary>output</summary>

```
ERROR vagrant: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["--version"]

Stderr: /usr/lib/virtualbox/VBoxManage: symbol lookup error: /lib/x86_64-linux-gnu/libgnutls.so.30: undefined symbol: __gmpz_limbs_write

ERROR vagrant: /tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/plugins/providers/virtualbox/driver/base.rb:440:in `block in execute'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/util/retryable.rb:17:in `retryable'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/plugins/providers/virtualbox/driver/base.rb:398:in `execute'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/plugins/providers/virtualbox/driver/meta.rb:177:in `block in read_version'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/util/retryable.rb:17:in `retryable'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/plugins/providers/virtualbox/driver/meta.rb:176:in `read_version'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/plugins/providers/virtualbox/driver/meta.rb:46:in `block in initialize'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/plugins/providers/virtualbox/driver/meta.rb:41:in `synchronize'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/plugins/providers/virtualbox/driver/meta.rb:41:in `initialize'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/plugins/providers/virtualbox/provider.rb:21:in `new'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/plugins/providers/virtualbox/provider.rb:21:in `usable?'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/environment.rb:361:in `block in default_provider'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/registry.rb:49:in `block in each'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/registry.rb:48:in `each'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/registry.rb:48:in `each'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/environment.rb:347:in `default_provider'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/environment.rb:943:in `guess_provider'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/environment.rb:955:in `find_configured_plugins'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/environment.rb:983:in `process_configured_plugins'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/lib/vagrant/environment.rb:178:in `initialize'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/bin/vagrant:168:in `new'
/tmp/.mount_vagran5FVw9o/usr/gembundle/gems/vagrant-2.2.14/bin/vagrant:168:in `<top (required)>'
/tmp/.mount_vagran5FVw9o/usr/gembundle/bin/vagrant:23:in `load'
/tmp/.mount_vagran5FVw9o/usr/gembundle/bin/vagrant:23:in `<main>'
Vagrant failed to initialize at a very early stage:

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["--version"]

Stderr: /usr/lib/virtualbox/VBoxManage: symbol lookup error: /lib/x86_64-linux-gnu/libgnutls.so.30: undefined symbol: __gmpz_limbs_write

```
</details>

**Comment by anjuls** [comment]
same error on ubuntu 20.10

VBoxManage --version
6.1.16r140961

**Comment by drewbailey** [comment]
My issue is resolved, it was not immediately obvious to me but it's necessary to install vagrant using the .deb, not virtualbox which I had been doing 😅

**Comment by anjuls** [comment]
I am still having same issue, I have tried installing Vagrant using the .deb file and also the virtualbox. 

vagrant --version
Vagrant 2.2.13

**Comment by kpanuragh** [comment]
try to downgrade the virtualbox version ,I just installed virtualbox 5.1.14r112924 its worked

**Comment by zigarn** [comment]
Same issue here, vagrant installed by extracting the binary from the released zip file:

```
$ vagrant --version
Vagrant 2.2.14

$ VBoxManage --version
6.1.16_Ubuntur140961

$ vagrant status
Vagrant failed to initialize at a very early stage:

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["--version"]

Stderr: /usr/lib/virtualbox/VBoxManage: symbol lookup error: /lib/x86_64-linux-gnu/libgnutls.so.30: undefined symbol: __gmpz_limbs_write
```

I can confirm that installing from the Vagrant .deb file solves the issue (but shouldn't be necessary).

**Comment by brittonhayes** [comment]
Confirming same issue on PopOS solved by installing Vagrant .deb

```shell
❯ vagrant --version
Vagrant 2.2.14

❯ VBoxManage --version
6.1.16_Ubuntur140961

❯ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.10"
```

**Comment by anjuls** [comment]
I had two versions of Vagrant installed, one by directly downloading the executable and another one using *.deb. I have removed the manual installation and it worked after that.  Thanks for the guidance.

**Comment by alexpop** [comment]
@anjuls that fixed it for me as well. You are a rockstar :guitar:

**Comment by BrunoCarvalhoAlvim** [comment]
I had downloaded the zip file from the official Vagrant website and after unzipping the file and placing Vagrant in Path, I was getting the same error.

```
❯ vagrant init hashicorp/bionic64
Vagrant failed to initialize at a very early stage:

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["--version"]

Stderr: /usr/lib/virtualbox/VBoxManage: symbol lookup error: /lib/x86_64-linux-gnu/libgnutls.so.30: undefined symbol: __gmpz_limbs_write

```
I solved this by removing that version of Vagrant and reinstalling it via apt 

```
sudo apt install vagrant`
```
After that its working now.

```
❯ vagrant init hashicorp/bionic64
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.

```

```
❯ ls
Vagrantfile

```
```
❯ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'hashicorp/bionic64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'hashicorp/bionic64'
    default: URL: https://vagrantcloud.com/hashicorp/bionic64
==> default: Adding box 'hashicorp/bionic64' (v1.0.282) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/hashicorp/boxes/bionic64/versions/1.0.282/providers/virtualbox.box
Download redirected to host: vagrantcloud-files-production.s3-accelerate.amazonaws.com
==> default: Successfully added box 'hashicorp/bionic64' (v1.0.282) for 'virtualbox'!
==> default: Importing base box 'hashicorp/bionic64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'hashicorp/bionic64' version '1.0.282' is up to date...
==> default: Setting the name of the VM: ambiente_dev_default_1617190635271_29861
Vagrant is currently configured to create VirtualBox synced folders with
the `SharedFoldersEnableSymlinksCreate` option enabled. If the Vagrant
guest is not trusted, you may want to disable this option. For more
information on this option, please refer to the VirtualBox manual:

  https://www.virtualbox.org/manual/ch04.html#sharedfolders

This option can be disabled globally with an environment variable:

  VAGRANT_DISABLE_VBOXSYMLINKCREATE=1

or on a per folder basis within the Vagrantfile:

  config.vm.synced_folder '/host/path', '/guest/path', SharedFoldersEnableSymlinksCreate: false
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 6.0.10
    default: VirtualBox Version: 6.1
==> default: Mounting shared folders...
    default: /vagrant => /home/bruno/Projects/ambiente_dev



```

```
❯ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'hashicorp/bionic64' version '1.0.282' is up to date...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

```

```
❯ vagrant ssh
Welcome to Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-58-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed Mar 31 20:18:24 UTC 2021

  System load:  0.0               Processes:           89
  Usage of /:   2.5% of 61.80GB   Users logged in:     0
  Memory usage: 11%               IP address for eth0: 10.0.2.15
  Swap usage:   0%

 * Introducing self-healing high availability clusters in MicroK8s.
   Simple, hardened, Kubernetes for production, from RaspberryPi to DC.

     https://microk8s.io/high-availability

0 packages can be updated.
0 updates are security updates.


vagrant@vagrant:~$ 
```

**Comment by chrisroberts** [comment]
Fixed via https://github.com/hashicorp/vagrant-installers/pull/301
