### ISSUE TITLE
vagrant-libvirt plugin build fails on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by electrocucaracha** [hashicorp/vagrant#12138]
### Vagrant version
`Vagrant 2.2.14`

### Host operating system

```
cat /etc/os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20210110"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20210110"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20210110"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo"
````

### Guest operating system

NA

### Vagrantfile

NA

### Debug output

```
vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Building native extensions. This could take a while...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

ERROR: Failed to build gem native extension.

    current directory: /home/vagrant/.vagrant.d/gems/2.6.6/gems/racc-1.5.2/ext/racc/cparse
/opt/vagrant/embedded/bin/ruby -I /opt/vagrant/embedded/lib/ruby/2.6.0 -r ./siteconf20210113-2390-8csnb8.rb extconf.rb
checking for rb_ary_subseq()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
/opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:552:in `try_link0'
        from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
        from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:782:in `try_func'
        from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:1069:in `block in have_func'
        from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
        from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
        from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
        from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
        from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
        from /opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:1068:in `have_func'
        from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/vagrant/.vagrant.d/gems/2.6.6/extensions/x86_64-linux/2.6.0/racc-1.5.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/vagrant/.vagrant.d/gems/2.6.6/gems/racc-1.5.2 for inspection.
Results logged to /home/vagrant/.vagrant.d/gems/2.6.6/extensions/x86_64-linux/2.6.0/racc-1.5.2/gem_make.out
```

### Expected behavior

What should have happened?
The plugin should be installed successfully.

### Actual behavior

What actually happened?
It's raising an error

### Steps to reproduce

1. Install vagrant  2.2.14 version
2. Install vagrant-libvirt plugin

### References

Are there any other GitHub issues (open or closed) that should be linked here?
- GH-10019

**Comment by chrisroberts** [comment]
Hi there,

Looking at the error message received, it includes this text:

```
/opt/vagrant/embedded/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
```

It looks like you need to install development tools on your local machine so you can properly build the plugin.

Cheers!

**Comment by electrocucaracha** [comment]
Maybe the `vagrant-libvirt` documentation requires to update its [installation](https://github.com/vagrant-libvirt/vagrant-libvirt#installation) process

This is the error in the log file:

```
vagrant@localhost:~> cat /home/vagrant/.vagrant.d/gems/2.6.6/extensions/x86_64-linux/2.6.0/racc-1.5.2/mkmf.log
"gcc -o conftest -I/opt/vagrant/embedded/include/ruby-2.6.0/x86_64-linux -I/opt/vagrant/embedded/include/ruby-2.6.0/ruby/backward -I/opt/vagrant/embedded/include/ruby-2.6.0 -I. -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include   -I/opt/vagrant/embedded/include -fPIC conftest.c  -L. -L/opt/vagrant/embedded/lib -Wl,-rpath,/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib -Wl,-rpath,/opt/vagrant/embedded/lib -L. -L/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib64 -Wl,-rpath=/opt/vagrant/embedded/lib:/opt/vagrant/embedded/lib64 -fstack-protector-strong -rdynamic -Wl,-export-dynamic -L/opt/vagrant/embedded/lib  -Wl,-rpath,/opt/vagrant/embedded/lib     -Wl,-rpath,'/../lib' -Wl,-rpath,'/../lib' -lruby  -lm   -lc"
sh: /opt/vagrant/embedded/lib/libreadline.so.8: no version information available (required by sh)
sh: symbol lookup error: /opt/vagrant/embedded/lib/libreadline.so.8: undefined symbol: UP
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

```
