### ISSUE TITLE
net-ssh issue in MacOS BigSur

### ISSUE THREAD

**Issue by imyelmo** [hashicorp/vagrant#12194]
### Host operating system: MacOS BigSUR 11.2.1

This is the operating system that you run locally.

### Actual behavior: Error

```
Traceback (most recent call last):
	130: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
	129: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `action'
	128: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `call'
	127: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/environment.rb:613:in `lock'
	126: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:215:in `block in action'
	125: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:246:in `action_raw'
	124: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
	123: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
	122: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
	121: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
	120: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	119: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	118: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	117: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/call.rb:53:in `call'
	116: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
	115: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
	114: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
	113: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
	112: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	111: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	110: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	109: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	108: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	107: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	106: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	105: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	104: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	103: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/call.rb:53:in `call'
	102: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
	101: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
	100: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
	 99: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
	 98: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 97: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 96: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 95: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	 94: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 93: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/customize.rb:40:in `call'
	 92: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 91: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/prepare_clone.rb:15:in `call'
	 90: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 89: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/prepare_clone_snapshot.rb:17:in `call'
	 88: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 87: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/import.rb:13:in `call'
	 86: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/import.rb:78:in `import'
	 85: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 84: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/discard_state.rb:15:in `call'
	 83: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 82: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/match_mac_address.rb:22:in `call'
	 81: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 80: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 79: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 78: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/env_set.rb:19:in `call'
	 77: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 76: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	 75: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 74: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	 73: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 72: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/box_check_outdated.rb:92:in `call'
	 71: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 70: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/call.rb:53:in `call'
	 69: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
	 68: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
	 67: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
	 66: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
	 65: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 64: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 63: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 62: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/call.rb:53:in `call'
	 61: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
	 60: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
	 59: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
	 58: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
	 57: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 56: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 55: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 54: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/call.rb:53:in `call'
	 53: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
	 52: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
	 51: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
	 50: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
	 49: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 48: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 47: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 46: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	 45: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 44: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/clean_machine_folder.rb:26:in `call'
	 43: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 42: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/set_name.rb:50:in `call'
	 41: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 40: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
	 39: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 38: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/provision.rb:103:in `call'
	 37: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/provision.rb:103:in `each'
	 36: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/provision.rb:126:in `block in call'
	 35: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/provision.rb:126:in `call'
	 34: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/environment.rb:525:in `hook'
	 33: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
	 32: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
	 31: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
	 30: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
	 29: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 28: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 27: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:127:in `call'
	 26: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/provision.rb:138:in `run_provisioner'
	 25: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/provisioners/shell/provisioner.rb:35:in `provision'
	 24: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/provisioners/shell/provisioner.rb:96:in `provision_ssh'
	 23: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/provisioners/shell/provisioner.rb:335:in `with_script_file'
	 22: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/provisioners/shell/provisioner.rb:98:in `block in provision_ssh'
	 21: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/provisioners/shell/provisioner.rb:98:in `tap'
	 20: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/provisioners/shell/provisioner.rb:107:in `block (2 levels) in provision_ssh'
	 19: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/communicators/ssh/communicator.rb:278:in `sudo'
	 18: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/communicators/ssh/communicator.rb:240:in `execute'
	 17: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/communicators/ssh/communicator.rb:392:in `connect'
	 16: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/communicators/ssh/communicator.rb:247:in `block in execute'
	 15: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/communicators/ssh/communicator.rb:703:in `shell_execute'
	 14: from /opt/vagrant/embedded/gems/2.2.14/gems/net-ssh-6.2.0.rc1/lib/net/ssh/connection/channel.rb:272:in `wait'
	 13: from /opt/vagrant/embedded/gems/2.2.14/gems/net-ssh-6.2.0.rc1/lib/net/ssh/connection/session.rb:180:in `loop'
	 12: from /opt/vagrant/embedded/gems/2.2.14/gems/net-ssh-6.2.0.rc1/lib/net/ssh/connection/session.rb:180:in `loop'
	 11: from /opt/vagrant/embedded/gems/2.2.14/gems/net-ssh-6.2.0.rc1/lib/net/ssh/connection/session.rb:180:in `block in loop'
	 10: from /opt/vagrant/embedded/gems/2.2.14/gems/net-ssh-6.2.0.rc1/lib/net/ssh/connection/session.rb:227:in `process'
	  9: from /opt/vagrant/embedded/gems/2.2.14/gems/net-ssh-6.2.0.rc1/lib/net/ssh/connection/event_loop.rb:28:in `process'
	  8: from /opt/vagrant/embedded/gems/2.2.14/gems/net-ssh-6.2.0.rc1/lib/net/ssh/connection/event_loop.rb:100:in `ev_preprocess'
	  7: from /opt/vagrant/embedded/gems/2.2.14/gems/net-ssh-6.2.0.rc1/lib/net/ssh/connection/event_loop.rb:100:in `each'
	  6: from /opt/vagrant/embedded/gems/2.2.14/gems/net-ssh-6.2.0.rc1/lib/net/ssh/connection/session.rb:248:in `ev_preprocess'
	  5: from /opt/vagrant/embedded/gems/2.2.14/gems/net-ssh-6.2.0.rc1/lib/net/ssh/connection/session.rb:545:in `dispatch_incoming_packets'
	  4: from /opt/vagrant/embedded/gems/2.2.14/gems/net-ssh-6.2.0.rc1/lib/net/ssh/transport/session.rb:190:in `poll_message'
	  3: from /opt/vagrant/embedded/gems/2.2.14/gems/net-ssh-6.2.0.rc1/lib/net/ssh/transport/session.rb:190:in `loop'
	  2: from /opt/vagrant/embedded/gems/2.2.14/gems/net-ssh-6.2.0.rc1/lib/net/ssh/transport/session.rb:193:in `block in poll_message'
	  1: from /opt/vagrant/embedded/gems/2.2.14/gems/net-ssh-6.2.0.rc1/lib/net/ssh/transport/packet_stream.rb:100:in `next_packet'
/opt/vagrant/embedded/gems/2.2.14/gems/net-ssh-6.2.0.rc1/lib/net/ssh/transport/packet_stream.rb:264:in `poll_next_packet': corrupted hmac detected Net::SSH::Transport::HMAC::SHA2_512 (Net::SSH::Exception)
```

### Steps to reproduce

1. vagrant up --debug &> vagrant.log
or
1. vagrant up

**Comment by lupusellobo** [comment]
The same thing happened to me. Suddenly my machines stopped working on BigSur

**Comment by jourdon** [comment]
same thing

**Comment by chrisroberts** [comment]
Were these previously working guests that are now failing? Did the error start to occur after doing a box update and creating a new guest, or did the error start to appear when attempting to connect to an already existing guest?

**Comment by lupusellobo** [comment]
Happened out of the blue. One day was working and the other started failing

**Comment by imyelmo** [comment]
In my case, out of the blue from previous deployed machines and also deploying a new setup from scratch

**Comment by imyelmo** [comment]
I have done what you suggested in different tries. I do not always get the same behaviour but in any case the created machine starts, it always fails.

Sometimes Virtualbox says:

Netsniffer cannot open 'bind9_trace2.pcap' for writing. The directory must exist and it must be writable for the current user (VERR_WRITE_PROTECT).
Failed to attach the network LUN (VERR_WRITE_PROTECT).


Result Code: | NS_ERROR_FAILURE (0x80004005)
-- | --
Component: | ConsoleWrap
Interface: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed}


Other times, Virtualbox closes because of an error. The trace file generated by MacOS is:

https://gist.github.com/imyelmo/1a497820fb0af03c43ff9eb727008dd6

Sorry, but the VM does not start normally to check the logs

**Comment by chrisroberts** [comment]
Hi, thanks for providing the extra information! The underlying cause of the error you are encountering is from VirtualBox and not Vagrant (which means there's not really anything we can do to fix it, unfortunately). The first error you encounter is an access error but my guess is that is likely a red herring. Given that your configuration calls for the pcap file to be written to the working directory, and you are in the working directory, it's obviously there and my assumption is that it would be writable by your current user.

The second error is more interesting and provides a better clue with the trace provided. We can see an error in there:

> Exception Type:        EXC_CRASH (Code Signature Invalid)

So it appears that that macOS is seeing the `VirtualBoxVM` executable as not having a valid signature and halting it which causes the crash. We can see the path of the process that it is complaining about here:

> Analyzing process: VirtualBoxVM[23584], path: /Applications/VirtualBox.app/Contents/Resources/VirtualBoxVM.app/Contents/MacOS/VirtualBoxVM; parent process: VBoxSVC[22170], path: /Applications/VirtualBox.app/Contents/MacOS/VBoxSVC

So it appears that the root cause is a codesign issue with VirtualBox, and this would explain why the guest does not actually start up. For my testing I was using Big Sur 11.2.3 and VirtualBox 6.1.18 and experienced no issues. Comparing the version output on my test environment with the output in your debug file, it appears they match (with the same revision number for both `r142142`). So I'm unsure why their would be a difference unless their macOS package was updated with just codesigning modifications. 

The best recommendation I have would be to remove VirtualBox from your system, re-download the macOS package, and then re-install. If the same error is still encountered, then it will likely be something that needs to be resolved on the VirtualBox side.

Given that the root cause of this issue is being caused by VirtualBox and not Vagrant itself, I'm going to close up this issue.

Cheers!
