### ISSUE TITLE
Vagrant guest/fedora plugin broken in 2.2.15

### ISSUE THREAD

**Issue by appelit-user** [hashicorp/vagrant#12265]
### Vagrant version

2.2.15

### Host operating system

Ubuntu Focal Fossa (20.04)

### Guest operating system

Ubuntu Focal Fossa (20.04)

### Expected behavior

Vagrant command completes

### Actual behavior

Vagrant command throws, see stacktrace below:
```
Traceback (most recent call last):
	62: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/bin/vagrant:231:in `<main>'
	61: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/environment.rb:290:in `cli'
	60: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/cli.rb:67:in `execute'
	59: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/commands/halt/command.rb:30:in `execute'
	58: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
	57: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/plugin/v2/command.rb:232:in `each'
	56: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/plugin/v2/command.rb:243:in `block in with_target_vms'
	55: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/commands/halt/command.rb:31:in `block in execute'
	54: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:201:in `action'
	53: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:201:in `call'
	52: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/environment.rb:614:in `lock'
	51: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:215:in `block in action'
	50: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:246:in `action_raw'
	49: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	48: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	47: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	46: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	45: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	44: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	43: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	42: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/call.rb:53:in `call'
	41: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	40: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	39: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	38: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	37: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	36: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	35: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	34: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	33: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	32: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/discard_state.rb:15:in `call'
	31: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	30: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/call.rb:53:in `call'
	29: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	28: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	27: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	26: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	25: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	24: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	23: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	22: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	21: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	20: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/call.rb:43:in `call'
	19: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	18: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	17: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	16: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	15: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	14: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/graceful_halt.rb:50:in `call'
	13: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:282:in `guest'
	12: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/guest.rb:34:in `detect!'
	11: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/capability_host.rb:36:in `initialize_capabilities!'
	10: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/capability_host.rb:122:in `autodetect_capability_host'
	 9: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/registry.rb:48:in `each'
	 8: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/registry.rb:48:in `each'
	 7: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/registry.rb:49:in `block in each'
	 6: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/registry.rb:27:in `get'
	 5: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/plugin/v2/plugin.rb:143:in `block in guest'
	 4: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/guests/fedora/plugin.rb:10:in `block in <class:Plugin>'
	 3: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/guests/fedora/plugin.rb:10:in `require_relative'
	 2: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/guests/fedora/guest.rb:3:in `<top (required)>'
	 1: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/guests/fedora/guest.rb:4:in `<module:VagrantPlugins>'
/opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/guests/fedora/guest.rb:5:in `<module:GuestFedora>': uninitialized constant VagrantPlugins::GuestLinux::Guest (NameError)
```

### Hint for solution

Comparing guest/ubuntu to guest/fedora, it seems that the fedora `guest.rb` file is using a wrong import, causing it to not find and/or initialize the constant and thus throwing an error.

### Workaround

Downgrade to 2.2.14

**Comment by logan-reynolds** [comment]
I'm also seeing this problem, and can confirm that the issue seems to be with the host and not the guests, as it's affecting both my CentOS and Ubuntu guest boxes.  Main symptom I see is that the box can technically start and you can 'vagrant ssh' into it, however shared directories from the host are not available.  Host is Ubuntu 16.04.7 LTS, and guests are CentOS 7 and Ubuntu Server 16.04.7 LTS.

Just curious @appelit-user were there instructions posted somewhere for downgrading Vagrant to 2.2.14 without loosing existing boxes?  I see most people are just uninstalling Vagrant 2.2.15 and then installing the 2.2.14 version, but I can't find info about if this will destroy existing boxes that are listed in my VirtualBox Manager, as I cannot afford to loose these and their associated snapshots.

**Comment by chancezeus** [comment]
@logan-reynolds I posted the previous message accidentally under a secondary account, but regarding downgrading, I'm using Ubuntu with the official repo and used ```apt install vagrant=2.2.14``` which will force the specified version to be installed, however unless you also ```apt-mark hold vagrant``` it will upgrade itself again (this will hold it until you ```apt-mark unhold vagrant```, so as soon as a working version is released you must unhold it otherwise it will not upgrade to that version)
