### ISSUE TITLE
Cannot load such file -- erubis

### ISSUE THREAD

**Issue by jeremyfix** [hashicorp/vagrant#12289]
Hello,

I'm running  vagrant 2.2.14 on ubuntu 18.04 ; I waned to try the [nvidia deepops virtual servers](https://github.com/NVIDIA/deepops/tree/master/virtual) but it failed complaining that `cannot loach such file -- erubis`

```
cd nvidia/deepops/virtual
./vagrant_startup.sh
```

returned several blocks like 

```
An unexpected error occurred when executing the action on the
'virtual-gpu01' machine. Please report this as a bug:

cannot load such file -- erubis

/opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/fix_jer/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/util/erb_template.rb:1:in `<top (required)>'
/opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/fix_jer/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/cap/synced_folder.rb:15:in `<class:SyncedFolder>'
/home/fix_jer/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/cap/synced_folder.rb:13:in `<module:SyncedFolder9p>'
/home/fix_jer/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/cap/synced_folder.rb:12:in `<module:VagrantPlugins>'
/home/fix_jer/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/cap/synced_folder.rb:11:in `<top (required)>'
/home/fix_jer/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/plugin.rb:45:in `require_relative'
/home/fix_jer/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/plugin.rb:45:in `block in <class:Plugin>'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/plugin/v2/plugin.rb:244:in `block in synced_folder'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/registry.rb:27:in `get'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/registry.rb:49:in `block in each'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/registry.rb:48:in `each'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/registry.rb:48:in `each'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/mixin_synced_folders.rb:18:in `default_synced_folder_type'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/mixin_synced_folders.rb:168:in `synced_folders'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:631:in `synced_folders'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/kernel_v2/config/vm.rb:730:in `validate'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/config/v2/root.rb:71:in `block in validate'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/config/v2/root.rb:66:in `each'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/config/v2/root.rb:66:in `validate'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/config_validate.rb:15:in `call'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:246:in `action_raw'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:215:in `block in action'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/environment.rb:613:in `lock'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `call'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `action'
/opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'

```

I should probably mention that the first run of the script complained about the `libvirt` provider not available that I "fixed" by 

```
git clone https://github.com/jcf/vagrant-libvirt
cd ./vagrant-libvirt/
git checkout upgrade-nokogiri
gem build vagrant-libvirt.gemspec
vagrant plugin install  ~/tmp/vagrant-libvirt/vagrant-libvirt-0.0.45.gem
```

Thank you for your help.

**Comment by jeremyfix** [comment]
Oh sorry for the issue, actually, that was solved by running

```
vagrant plugin install  erubis
```

I therefore close my issue.
