### ISSUE TITLE
vagrant plugin install fails when using vagrant built from source

### ISSUE THREAD

**Issue by AskAlice** [hashicorp/vagrant#12327]
I had to build vagrant from source to disable the checks for WSL in `platform.rb` so that I can use nested virtualization in WSL and the libvirt provider.

When installing vagrant-libvirt, i run into this error
```
alice@emu-pc:/mnt/c/users/alice/vagrant$ exec/vagrant plugin install vagrant-libvirt

You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Building native extensions. This could take a while...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

ERROR: Failed to build gem native extension.

    current directory: /home/alice/.vagrant.d/gems/2.7.0/gems/racc-1.5.2/ext/racc/cparse
/usr/bin/ruby2.7 -I /usr/lib/ruby/2.7.0 -r ./siteconf20210426-9946-15mfc9f.rb extconf.rb
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/source/git.rb:204:in `rescue in load_spec_files': https://github.com/hashicorp/vagrant-spec.git (at main@9057cd6) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/source/git.rb:200:in `load_spec_files'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/source/path.rb:105:in `local_specs'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/source/git.rb:168:in `specs'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/lazy_specification.rb:75:in `__materialize__'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/spec_set.rb:83:in `block in materialize'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'
        from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/source/path.rb:203:in `load_spec_files': The path `/home/alice/.vagrant.d/gems/2.7.0/bundler/gems/vagrant-spec-9057cd6e0ac2` does not exist. (Bundler::PathError)
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/source/git.rb:201:in `load_spec_files'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/source/path.rb:105:in `local_specs'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/source/git.rb:168:in `specs'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/lazy_specification.rb:75:in `__materialize__'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/spec_set.rb:83:in `block in materialize'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `map!'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/spec_set.rb:80:in `materialize'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/definition.rb:170:in `specs'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/definition.rb:237:in `specs_for'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/definition.rb:226:in `requested_specs'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:101:in `block in definition_method'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/runtime.rb:20:in `setup'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler.rb:149:in `setup'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
        from /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'
        from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'

extconf failed, exit code 1

Gem files will remain installed in /home/alice/.vagrant.d/gems/2.7.0/gems/racc-1.5.2 for inspection.
Results logged to /home/alice/.vagrant.d/gems/2.7.0/extensions/x86_64-linux/2.7.0/racc-1.5.2/gem_make.out
```

could anyone help me resolve this? I'm not sure how to approach this i'm not too familiar with ruby personally.

**Comment by chrisroberts** [comment]
Hi, sorry for the delay responding to this. This error message looks to be the underlying issue:

> /usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/source/git.rb:204:in `rescue in load_spec_files': https://github.com/hashicorp/vagrant-spec.git (at main@9057cd6) is not yet checked out. Run `bundle install` first. (Bundler::GitError)

Running a `bundle install` will fix the error.

Cheers!

**Comment by AskAlice** [comment]
@chrisroberts hell yes, I can test this now !
