### ISSUE TITLE
Vagrant-2.2.15: VBox VM is not booting up

### ISSUE THREAD

**Issue by pshelar** [hashicorp/vagrant#12325]
### Vagrant version
2.2.15

### Host operating system

Ubuntu 20.04

### Guest operating system

ubuntu 20.04
### Vagrantfile

```
https://github.com/magma/magma/blob/master/lte/gateway/Vagrantfile
```

### Debug output

```
root@pravin-XPS-8930:/mnt/ff/pravins/magma/lte/gateway# vagrant up magma_focal --provider=virtualbox | tee ub-prov2.txt
Bringing machine 'magma_focal' up with 'virtualbox' provider...
==> magma_focal: You assigned a static IP ending in ".1" to this machine.
==> magma_focal: This is very often used by the router and can cause the
==> magma_focal: network to not work properly. If the network doesn't work
==> magma_focal: properly, try changing this IP.
==> magma_focal: You assigned a static IP ending in ".1" to this machine.
==> magma_focal: This is very often used by the router and can cause the
==> magma_focal: network to not work properly. If the network doesn't work
==> magma_focal: properly, try changing this IP.
==> magma_focal: Checking if box 'ubuntu/focal64' version '20210415.0.0' is up to date...
==> magma_focal: Clearing any previously set forwarded ports...
==> magma_focal: Clearing any previously set network interfaces...
==> magma_focal: Preparing network interfaces based on configuration...
    magma_focal: Adapter 1: nat
    magma_focal: Adapter 2: hostonly
    magma_focal: Adapter 3: hostonly
==> magma_focal: Forwarding ports...
    magma_focal: 22 (guest) => 2222 (host) (adapter 1)
==> magma_focal: Running 'pre-boot' VM customizations...
==> magma_focal: Booting VM...
==> magma_focal: Waiting for machine to boot. This may take a few minutes...
    magma_focal: SSH address: 127.0.0.1:2222
    magma_focal: SSH username: vagrant
    magma_focal: SSH auth method: private key
==> magma_focal: Machine booted and ready!
==> magma_focal: Checking for guest additions in VM...
==> magma_focal: Setting hostname...
Traceback (most recent call last):
	120: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
	119: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:201:in `action'
	118: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:201:in `call'
	117: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/environment.rb:614:in `lock'
	116: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:215:in `block in action'
	115: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:246:in `action_raw'
	114: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	113: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	112: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	111: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	110: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	109: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	108: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	107: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/call.rb:53:in `call'
	106: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	105: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	104: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	103: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	102: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	101: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	100: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 99: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 98: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 97: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	 96: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 95: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/call.rb:53:in `call'
	 94: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	 93: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	 92: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	 91: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	 90: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 89: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 88: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 87: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 86: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 85: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/env_set.rb:19:in `call'
	 84: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 83: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	 82: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 81: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	 80: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 79: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/box_check_outdated.rb:93:in `call'
	 78: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 77: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/call.rb:53:in `call'
	 76: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	 75: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	 74: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	 73: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	 72: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 71: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 70: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 69: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/call.rb:53:in `call'
	 68: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	 67: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	 66: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	 65: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	 64: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 63: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 62: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 61: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/call.rb:53:in `call'
	 60: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	 59: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	 58: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	 57: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	 56: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 55: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 54: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 53: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	 52: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 51: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/clean_machine_folder.rb:26:in `call'
	 50: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 49: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/set_name.rb:50:in `call'
	 48: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 47: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
	 46: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 45: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/provision.rb:80:in `call'
	 44: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 43: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/env_set.rb:19:in `call'
	 42: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 41: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in `call'
	 40: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 39: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:52:in `call'
	 38: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 37: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/prepare_nfs_valid_ids.rb:12:in `call'
	 36: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 35: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
	 34: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 33: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
	 32: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 31: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/delayed.rb:19:in `call'
	 30: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 29: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
	 28: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 27: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/prepare_nfs_settings.rb:19:in `call'
	 26: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 25: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/set_default_nic_type.rb:64:in `call'
	 24: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 23: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/clear_network_interfaces.rb:26:in `call'
	 22: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 21: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/network.rb:123:in `call'
	 20: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 19: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/network_fix_ipv6.rb:41:in `call'
	 18: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 17: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/forward_ports.rb:31:in `call'
	 16: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	 15: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/set_hostname.rb:23:in `call'
	 14: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:282:in `guest'
	 13: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/guest.rb:34:in `detect!'
	 12: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/capability_host.rb:36:in `initialize_capabilities!'
	 11: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/capability_host.rb:122:in `autodetect_capability_host'
	 10: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/registry.rb:48:in `each'
	  9: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/registry.rb:48:in `each'
	  8: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/registry.rb:49:in `block in each'
	  7: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/capability_host.rb:128:in `block in autodetect_capability_host'
	  6: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/registry.rb:27:in `get'
	  5: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/plugin/v2/plugin.rb:143:in `block in guest'
	  4: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/guests/fedora/plugin.rb:10:in `block in <class:Plugin>'
	  3: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/guests/fedora/plugin.rb:10:in `require_relative'
	  2: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/guests/fedora/guest.rb:3:in `<top (required)>'
	  1: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/guests/fedora/guest.rb:4:in `<module:VagrantPlugins>'
/opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/guests/fedora/guest.rb:5:in `<module:GuestFedora>': uninitialized constant VagrantPlugins::GuestLinux::Guest (NameError)
```

### Expected behavior

VM shld boot up and provide ssh access.

### Actual behavior
stack trace from vagrant.

### Steps to reproduce

1. git clone https://github.com/magma/magma
2. cd magma/lte/gateway
3.  vagrant up magma_focal --provider=virtualbox

**Comment by pshelar** [comment]
FYI: downgrading to Vagrant-2.2.14 fixes the issue.

**Comment by soapy1** [comment]
Thanks for opening up an issue. This has been resolved by https://github.com/hashicorp/vagrant/pull/12275 and will be fixed in the next release of Vagrant.
