### ISSUE TITLE
Ruby cannot require `rexml/document.rb`

### ISSUE THREAD

**Issue by SpyTec** [hashicorp/vagrant#12333]
### Vagrant version

```
$ vagrant -v
Vagrant 2.2.9
```

### Ruby version
```
$ ruby --version
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
```

### Host operating system

Fedora Linux 34

### Guest operating system

CentOS Linux 8

### Debug output

https://gist.github.com/SpyTec/fda77b977f44ee69b9038a734ad78017

### Expected behavior

VM is created

### Actual behavior

Creation fails with
```
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x0000557c9b8dead8>
<internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- rexml/document (LoadError)
        from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action/start_domain.rb:2:in `<top (required)>'
        from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.1.2/lib/vagrant-libvirt/action.rb:50:in `block (2 levels) in action_up'
        from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/action/builtin/call.rb:47:in `call'
        from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
        from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/action/builtin/box_check_outdated.rb:92:in `call'
        from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
        from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/action/warden.rb:48:in `call'
        from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/action/builder.rb:149:in `call'
        from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/action/runner.rb:89:in `block in run'
        from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/util/busy.rb:19:in `busy'
        from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/action/runner.rb:89:in `run'
        from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/machine.rb:240:in `action_raw'
        from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/machine.rb:212:in `block in action'
        from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/environment.rb:613:in `lock'
        from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/machine.rb:198:in `call'
        from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/machine.rb:198:in `action'
        from /usr/share/vagrant/gems/gems/vagrant-2.2.9/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
```

### Steps to reproduce

1. Be on Fedora Linux 34
2. `$ vagrant init eurolinux-vagrant/centos-8`
3. `$ vagrant up`

**Comment by logomancer** [comment]
I was able to fix this by installing the `rubygem-rexml`package. The `rpm -qR` command shows no dependency on the `rexml` rubygem. This may be an F34 issue.

**Comment by SpyTec** [comment]
Fixed in Fedora as seen in the VZ logomancer linked (Thanks!)
