### ISSUE TITLE
Updating vagrant-libvirt from 0.3 to 0.4.1 with Vagrant 2.2.16 fails because new version cannot be "activated"

### ISSUE THREAD

**Issue by zimmski** [hashicorp/vagrant#12345]
### Expected behavior

Installation works like it did with 0.3.0

### Actual behavior

Installation fails with `/opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/specification.rb:2292:in `check_version_conflict': can't activate vagrant-libvirt-0.4.1, already activated vagrant-libvirt-0.3.0 (Gem::LoadError)`

### Steps to reproduce

1. Install a VM on openSUSE 15.2 with Vagrant 2.2.14 and vagrant-libvirt 0.3.0
2. Update the versions Vagrant to 2.2.16
3. Run `vagrant plugin expunge --local-only --force`
3. Update vagrant-libvirt to 0.4.1 using `vagrant plugin install --local`
3. See the following error

```
Installing the 'vagrant-libvirt --version '0.4.1'' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/specification.rb:2292:in `check_version_conflict': can't activate vagrant-libvirt-0.4.1, already activated vagrant-libvirt-0.3.0 (Gem::LoadError)
        from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/specification.rb:1414:in `activate'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/bundler.rb:751:in `block in activate_solution'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/bundler.rb:748:in `each'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/bundler.rb:748:in `activate_solution'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/bundler.rb:588:in `internal_install'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/bundler.rb:350:in `install'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/plugin/manager.rb:138:in `block in install_plugin'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/plugin/manager.rb:148:in `install_plugin'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/plugin/action/install_gem.rb:30:in `call'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/plugin/command/base.rb:14:in `action'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/plugin/command/install.rb:59:in `block in execute'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/plugin/command/install.rb:58:in `each'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/plugin/command/install.rb:58:in `execute'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/plugin/command/root.rb:66:in `execute'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/cli.rb:67:in `execute'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/environment.rb:290:in `cli'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/bin/vagrant:231:in `<main>'
```

and

with Vagrant 2.2.14 alone i see

```
Installing the 'vagrant-libvirt --version '0.4.1'' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies vagrant-libvirt (= 0.3.0) and vagrant-libvirt (= 0.4.1)
  Activated vagrant-libvirt-0.4.1
  which does not match conflicting dependency (= 0.3.0)

  Conflicting dependency chains:
    vagrant-libvirt (= 0.4.1), 0.4.1 activated

  versus:
    vagrant-libvirt (= 0.3.0)

  Gems matching vagrant-libvirt (= 0.3.0):
    vagrant-libvirt-0.3.0
 ```

### Host operating system

OS: openSUSE 15.2
Compiled against library: libvirt 6.0.0
Using library: libvirt 6.0.0
Using API: QEMU 6.0.0
Running hypervisor: QEMU 4.2.1

### Guest operating system

'generic/ubuntu2004' version '3.2.10'

### Already reported with the plugin project

Link to the plugin issue where the maintainer says that this is a problem of the plugin manager and not of the plugin itself https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1263

**Comment by zimmski** [comment]
Still a problem with Vagrant 2.2.18

**Comment by chrisroberts** [comment]
Hi there,

Would you please provide a debug gist so we can determine where the conflict is occurring. Are you also attempting to have the 0.3 version of the libvirt plugin installed globally while having the 0.4.1 version installed locally?

**Comment by electrofelix** [comment]
I suspect this is partly related to the issue #12567 is attempting to fix as well. When the bundler detects multiple instances of the same gem, it returns the first match when loading specifications rather than the one matching the version being looked for. So #12567 fix the underlying issue here in addition to #12521. I'm hoping to get approval to sign the CLA soon so would be worth the author testing to see if making the same change locally fixes the issue they bumped into?
