### ISSUE TITLE
Http basic auth not working with Artifactory

### ISSUE THREAD

**Issue by DariuszOstolski** [hashicorp/vagrant#12367]
### Vagrant version

Vagrant 2.2.16

### Host operating system

NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
VERSION_ID="18.04"

### Guest operating system

Linux

### Command

```sh
$ VAGRANT_LOG=info ~/private/vagrant box add https://*****:*****@localhost/artifactory/api/vagrant/vagrant-local/my-OS  --name my-EOS

```

### Debug output

```
 INFO global: Vagrant version: 2.2.16
 INFO global: Ruby version: 2.6.6
 INFO global: RubyGems version: 3.0.3
 INFO global: VAGRANT_USR_DIR="/tmp/.mount_vagranqqmVGV/usr"
 INFO global: VAGRANT_APPIMAGE_LD_LIBRARY_PATH="/tmp/.mount_vagranqqmVGV/usr/lib/:/tmp/.mount_vagranqqmVGV/usr/lib/i386-linux-gnu/:/tmp/.mount_vagranqqmVGV/usr/lib/x86_64-linux-gnu/:/tmp/.mount_vagranqqmVGV/usr/lib32/:/tmp/.mount_vagranqqmVGV/usr/lib64/:/tmp/.mount_vagranqqmVGV/lib/:/tmp/.mount_vagranqqmVGV/lib/i386-linux-gnu/:/tmp/.mount_vagranqqmVGV/lib/x86_64-linux-gnu/:/tmp/.mount_vagranqqmVGV/lib32/:/tmp/.mount_vagranqqmVGV/lib64/::/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/lib/i386-linux-gnu:/usr/local/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib:"
 INFO global: VAGRANT_PKG_CONFIG_PATH="/tmp/.mount_vagranqqmVGV/usr/lib/x86_64-linux-gnu/pkgconfig-int::/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig"
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/tmp/.mount_vagranqqmVGV"
 INFO global: VAGRANT_RUBYLIB="/tmp/.mount_vagranqqmVGV/usr/local/lib/site_ruby/2.6.0:/tmp/.mount_vagranqqmVGV/usr/local/lib/x86_64-linux-gnu/site_ruby:/tmp/.mount_vagranqqmVGV/usr/local/lib/site_ruby:/tmp/.mount_vagranqqmVGV/usr/lib/ruby/vendor_ruby/2.6.0:/tmp/.mount_vagranqqmVGV/usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.6.0:/tmp/.mount_vagranqqmVGV/usr/lib/ruby/vendor_ruby:/tmp/.mount_vagranqqmVGV/usr/lib/ruby/2.6.0:/tmp/.mount_vagranqqmVGV/usr/lib/x86_64-linux-gnu/ruby/2.6.0"
 INFO global: VAGRANT_LOG="info"
 INFO global: VAGRANT_BIN_DIR="/tmp/.mount_vagranqqmVGV/usr/bin"
 INFO global: VAGRANT_APPIMAGE="1"
 INFO global: VAGRANT_ROOT_DIR="/tmp/.mount_vagranqqmVGV"
 INFO global: VAGRANT_APPIMAGE_HOST_LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/lib/i386-linux-gnu:/usr/local/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib::/tmp/.mount_vagranqqmVGV/usr/lib/:/tmp/.mount_vagranqqmVGV/usr/lib/i386-linux-gnu/:/tmp/.mount_vagranqqmVGV/usr/lib/x86_64-linux-gnu/:/tmp/.mount_vagranqqmVGV/usr/lib32/:/tmp/.mount_vagranqqmVGV/usr/lib64/:/tmp/.mount_vagranqqmVGV/lib/:/tmp/.mount_vagranqqmVGV/lib/i386-linux-gnu/:/tmp/.mount_vagranqqmVGV/lib/x86_64-linux-gnu/:/tmp/.mount_vagranqqmVGV/lib32/:/tmp/.mount_vagranqqmVGV/lib64/:"
 WARN global: resolv replacement has not been enabled!
 INFO manager: Registered plugin: autocomplete command
 INFO manager: Registered plugin: box command
 INFO manager: Registered plugin: cap command
 INFO manager: Registered plugin: vagrant-cloud
 INFO manager: Registered plugin: destroy command
 INFO manager: Registered plugin: global-status command
 INFO manager: Registered plugin: halt command
 INFO manager: Registered plugin: help command
 INFO manager: Registered plugin: init command
 INFO manager: Registered plugin: list-commands command
 INFO manager: Registered plugin: vagrant-login
 INFO manager: Registered plugin: package command
 INFO manager: Registered plugin: plugin command
 INFO manager: Registered plugin: port command
 INFO manager: Registered plugin: powershell command
 INFO manager: Registered plugin: provider command
 INFO manager: Registered plugin: provision command
 INFO manager: Registered plugin: push command
 INFO manager: Registered plugin: rdp command
 INFO manager: Registered plugin: reload command
 INFO manager: Registered plugin: resume command
 INFO manager: Registered plugin: snapshot command
 INFO manager: Registered plugin: ssh command
 INFO manager: Registered plugin: ssh-config command
 INFO manager: Registered plugin: status command
 INFO manager: Registered plugin: suspend command
 INFO manager: Registered plugin: up command
 INFO manager: Registered plugin: upload command
 INFO manager: Registered plugin: validate command
 INFO manager: Registered plugin: version command
 INFO manager: Registered plugin: winrm command
 INFO manager: Registered plugin: winrm-config command
 INFO manager: Registered plugin: ssh communicator
 INFO manager: Registered plugin: winrm communicator
 INFO manager: Registered plugin: windows ssh communicator
 INFO manager: Registered plugin: Alpine guest
 INFO manager: Registered plugin: ALT Platform guest
 INFO manager: Registered plugin: Amazon Linux guest
 INFO manager: Registered plugin: Arch guest
 INFO manager: Registered plugin: Atomic Host guest
 INFO manager: Registered plugin: BSD-based guest
 INFO manager: Registered plugin: CentOS guest
 INFO manager: Registered plugin: CoreOS guest
 INFO manager: Registered plugin: Darwin guest
 INFO manager: Registered plugin: Debian guest
 INFO manager: Registered plugin: DragonFly BSD guest
 INFO manager: Registered plugin: Elementary guest
 INFO manager: Registered plugin: ESXi guest.
 INFO manager: Registered plugin: Fedora guest
 INFO manager: Registered plugin: FreeBSD guest
 INFO manager: Registered plugin: Funtoo guest
 INFO manager: Registered plugin: Gentoo guest
 INFO manager: Registered plugin: Haiku guest
 INFO manager: Registered plugin: Kali guest
 INFO manager: Registered plugin: Linux guest.
 INFO manager: Registered plugin: Mint guest
 INFO manager: Registered plugin: NetBSD guest
 INFO manager: Registered plugin: NixOS guest
 INFO manager: Registered plugin: OmniOS guest.
 INFO manager: Registered plugin: OpenBSD guest
 INFO manager: Registered plugin: OpenWrt guest
 INFO manager: Registered plugin: VMware Photon guest
 INFO manager: Registered plugin: PLD Linux guest
 INFO manager: Registered plugin: Red Hat Enterprise Linux guest
 INFO manager: Registered plugin: Slackware guest
 INFO manager: Registered plugin: SmartOS guest.
 INFO manager: Registered plugin: Solaris guest.
 INFO manager: Registered plugin: Solaris 11 guest.
 INFO manager: Registered plugin: SUSE guest
 INFO manager: Registered plugin: TinyCore Linux guest.
 INFO manager: Registered plugin: Trisquel guest
 INFO manager: Registered plugin: Ubuntu guest
 INFO manager: Registered plugin: Windows guest.
 INFO manager: Registered plugin: ALT Platform host
 INFO manager: Registered plugin: Arch host
 INFO manager: Registered plugin: BSD host
 INFO manager: Registered plugin: Mac OS X host
 INFO manager: Registered plugin: FreeBSD host
 INFO manager: Registered plugin: Gentoo host
 INFO manager: Registered plugin: Linux host
 INFO manager: Registered plugin: null host
 INFO manager: Registered plugin: Red Hat Enterprise Linux host
 INFO manager: Registered plugin: Slackware host
 INFO manager: Registered plugin: SUSE host
 INFO manager: Registered plugin: Void host
 INFO manager: Registered plugin: Windows host
 INFO manager: Registered plugin: kernel
 INFO manager: Registered plugin: kernel
 INFO manager: Registered plugin: docker-provider
 INFO manager: Registered plugin: Hyper-V provider
 INFO manager: Registered plugin: VirtualBox provider
 INFO manager: Registered plugin: ansible
 INFO manager: Registered plugin: CFEngine Provisioner
 INFO manager: Registered plugin: chef
 INFO manager: Registered plugin: container
 INFO manager: Registered plugin: docker
 INFO manager: Registered plugin: file
 INFO manager: Registered plugin: podman
 INFO manager: Registered plugin: puppet
 INFO manager: Registered plugin: salt
 INFO manager: Registered plugin: shell
 INFO manager: Registered plugin: atlas
 INFO manager: Registered plugin: ftp
 INFO manager: Registered plugin: heroku
 INFO manager: Registered plugin: local-exec
 INFO manager: Registered plugin: noop
 INFO manager: Registered plugin: NFS synced folders
 INFO manager: Registered plugin: RSync synced folders
 INFO manager: Registered plugin: SMB synced folders
 INFO vagrant: `vagrant` invoked: ["box", "add", "https://*****:*****@localhost/artifactory/api/vagrant/vagrant-local/my-OS", "--name", "my-OS"]
 INFO environment: Environment initialized (#<Vagrant::Environment:0x000055b2807577a8>)
 INFO environment:   - cwd: /home/user/simulator
 INFO environment: Home path: /home/user/.vagrant.d
 WARN environment: No local data path is set. Local data cannot be stored.
 INFO manager: Plugins:
 INFO manager: Loading plugins...
 INFO loader: Loading configuration in order: [:home, :root]
 INFO base: VBoxManage path: VBoxManage
 INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "--version"]
 INFO subprocess: Command not in installer, restoring original environment...
 INFO subprocess: Detected AppImage environment and request to external binary. Updating library path.
 INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_6_1
 INFO base: VBoxManage path: VBoxManage
 INFO base: VBoxManage path: VBoxManage
 INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_6_1
 INFO base: VBoxManage path: VBoxManage
 INFO loader: Set "47112571685820_machine_default" = []
 INFO loader: Loading configuration in order: [:home, :root, "47112571685820_machine_default"]
 WARN vagrantfile: Failed to locate  with version 
 WARN vagrantfile: Performing lookup with initial values  with version 
 INFO environment: Running hook: environment_plugins_loaded
 INFO runner: Running action: environment_plugins_loaded #<Vagrant::Action::Builder:0x000055b280ea1ce8>
 INFO environment: Running hook: environment_load
 INFO runner: Running action: environment_load #<Vagrant::Action::Builder:0x000055b281047cf0>
 INFO cli: CLI: [] "box" ["add", "https://*****:*****@localhost/artifactory/api/vagrant/vagrant-local/my-OS", "--name", "my-OS"]
 INFO host: Autodetecting host type for [#<Vagrant::Environment: /home/user/simulator>]
 INFO host: Detected: linux!
 INFO runner: Running action:  #<Vagrant::Action::Builder:0x000055b28114b610>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::BoxAdd:0x000055b281039c40>
 INFO environment: Running hook: authenticate_box_url
 INFO runner: Running action: authenticate_box_url #<Vagrant::Action::Builder:0x000055b281102410>
 INFO warden: Calling IN action: #<VagrantPlugins::CloudCommand::AddAuthentication:0x000055b280df5830>
 WARN authenticate-box-url: Removing access token from URL parameter.
 WARN authenticate-box-url: Authentication token not added as GET parameter.
 INFO warden: Calling OUT action: #<VagrantPlugins::CloudCommand::AddAuthentication:0x000055b280df5830>
 INFO box_add: Downloading box: https://*****:*****@localhost/artifactory/api/vagrant/vagrant-local/my-OS => /home/user/.vagrant.d/tmp/box9387f7e74bdfd93b36e5ca416568c940dcae2b23
 INFO environment: Running hook: authenticate_box_downloader
 INFO runner: Running action: authenticate_box_downloader #<Vagrant::Action::Builder:0x000055b2810b6498>
 INFO warden: Calling IN action: #<VagrantPlugins::CloudCommand::AddDownloaderAuthentication:0x000055b280e48e90>
 INFO warden: Calling OUT action: #<VagrantPlugins::CloudCommand::AddDownloaderAuthentication:0x000055b280e48e90>
 INFO environment: Running hook: authenticate_box_downloader
 INFO runner: Running action: authenticate_box_downloader #<Vagrant::Action::Builder:0x000055b280754670>
 INFO warden: Calling IN action: #<VagrantPlugins::CloudCommand::AddDownloaderAuthentication:0x000055b280fe0b18>
 INFO warden: Calling OUT action: #<VagrantPlugins::CloudCommand::AddDownloaderAuthentication:0x000055b280fe0b18>
 INFO downloader: HEAD: https://localhost/artifactory/api/vagrant/vagrant-local/my-OS
 INFO subprocess: Starting process: ["/usr/bin/curl", "-q", "-I", "--fail", "--location", "--max-redirs", "10", "--verbose", "--user-agent", "Vagrant/2.2.16 (+https://www.vagrantup.com; ruby2.6.6) ", "--continue-at", "-", "-u", "*****:*******", "-H", "Accept: application/json", "https://localhost/artifactory/api/vagrant/vagrant-local/my-OS"]
 INFO subprocess: Command not in installer, restoring original environment...
 INFO subprocess: Detected AppImage environment and request to external binary. Updating library path.
 INFO interface: output: Loading metadata for box 'https://*****:*****@localhost/artifactory/api/vagrant/vagrant-local/my-OS'
 INFO interface: output: ==> box: Loading metadata for box 'https://*****:*****@localhost/artifactory/api/vagrant/vagrant-local/my-OS'
==> box: Loading metadata for box 'https://*****:*****@localhost/artifactory/api/vagrant/vagrant-local/my-OS'
 INFO box_add: Downloading box: https://*****:*****@localhost/artifactory/api/vagrant/vagrant-local/my-OS => /home/user/.vagrant.d/tmp/box9387f7e74bdfd93b36e5ca416568c940dcae2b23
 INFO environment: Running hook: authenticate_box_downloader
 INFO runner: Running action: authenticate_box_downloader #<Vagrant::Action::Builder:0x000055b2817c40c8>
 INFO warden: Calling IN action: #<VagrantPlugins::CloudCommand::AddDownloaderAuthentication:0x000055b2818400b0>
 INFO warden: Calling OUT action: #<VagrantPlugins::CloudCommand::AddDownloaderAuthentication:0x000055b2818400b0>
 INFO environment: Running hook: authenticate_box_downloader
 INFO runner: Running action: authenticate_box_downloader #<Vagrant::Action::Builder:0x000055b28192f778>
 INFO warden: Calling IN action: #<VagrantPlugins::CloudCommand::AddDownloaderAuthentication:0x000055b28199b518>
 INFO warden: Calling OUT action: #<VagrantPlugins::CloudCommand::AddDownloaderAuthentication:0x000055b28199b518>
 INFO downloader: Downloader starting download: 
 INFO downloader:   -- Source: https://localhost/artifactory/api/vagrant/vagrant-local/my-OS
 INFO downloader:   -- Destination: /home/user/.vagrant.d/tmp/box9387f7e74bdfd93b36e5ca416568c940dcae2b23
 INFO subprocess: Starting process: ["/usr/bin/curl", "-q", "--fail", "--location", "--max-redirs", "10", "--verbose", "--user-agent", "Vagrant/2.2.16 (+https://www.vagrantup.com; ruby2.6.6) ", "--continue-at", "-", "-u", "*****:*******", "-H", "Accept: application/json", "--output", "/home/user/.vagrant.d/tmp/box9387f7e74bdfd93b36e5ca416568c940dcae2b23", "https://localhost/artifactory/api/vagrant/vagrant-local/my-OS"]
 INFO subprocess: Command not in installer, restoring original environment...
 INFO subprocess: Detected AppImage environment and request to external binary. Updating library path.
 INFO environment: Running hook: authenticate_box_url
 INFO runner: Running action: authenticate_box_url #<Vagrant::Action::Builder:0x000055b2810b2190>
 INFO warden: Calling IN action: #<VagrantPlugins::CloudCommand::AddAuthentication:0x000055b28153ff50>
 WARN authenticate-box-url: Removing access token from URL parameter.
 WARN authenticate-box-url: Authentication token not added as GET parameter.
 INFO warden: Calling OUT action: #<VagrantPlugins::CloudCommand::AddAuthentication:0x000055b28153ff50>
 INFO interface: output: Adding box 'my-OS' (v3.6.8) for provider: virtualbox
 INFO interface: output: ==> box: Adding box 'my-OS' (v3.6.8) for provider: virtualbox
==> box: Adding box 'my-OS' (v3.6.8) for provider: virtualbox
 INFO box_add: Downloading box: https://localhost/artifactory/api/vagrant/vagrant-local/my-OS-3.6.8.box => /home/user/.vagrant.d/tmp/box3bcf5d91095bb729aa71e6c368ef05a003f02533
 INFO environment: Running hook: authenticate_box_downloader
 INFO runner: Running action: authenticate_box_downloader #<Vagrant::Action::Builder:0x000055b2816871d8>
 INFO warden: Calling IN action: #<VagrantPlugins::CloudCommand::AddDownloaderAuthentication:0x000055b2816efb20>
 INFO warden: Calling OUT action: #<VagrantPlugins::CloudCommand::AddDownloaderAuthentication:0x000055b2816efb20>
 INFO environment: Running hook: authenticate_box_downloader
 INFO runner: Running action: authenticate_box_downloader #<Vagrant::Action::Builder:0x000055b2817d41a8>
 INFO warden: Calling IN action: #<VagrantPlugins::CloudCommand::AddDownloaderAuthentication:0x000055b281856d88>
 INFO warden: Calling OUT action: #<VagrantPlugins::CloudCommand::AddDownloaderAuthentication:0x000055b281856d88>
 INFO interface: detail: Downloading: https://localhost/artifactory/api/vagrant/vagrant-local/my-OS-3.6.8.box
 INFO interface: detail:     box: Downloading: https://localhost/artifactory/api/vagrant/vagrant-local/my-OS-3.6.8.box
    box: Downloading: https://localhost/artifactory/api/vagrant/vagrant-local/my-OS-3.6.8.box
 INFO downloader: Downloader starting download: 
 INFO downloader:   -- Source: https://localhost/artifactory/api/vagrant/vagrant-local/my-OS-3.6.8.box
 INFO downloader:   -- Destination: /home/user/.vagrant.d/tmp/box3bcf5d91095bb729aa71e6c368ef05a003f02533
 INFO subprocess: Starting process: ["/usr/bin/curl", "-q", "--fail", "--location", "--max-redirs", "10", "--verbose", "--user-agent", "Vagrant/2.2.16 (+https://www.vagrantup.com; ruby2.6.6) ", "--continue-at", "-", "--output", "/home/user/.vagrant.d/tmp/box3bcf5d91095bb729aa71e6c368ef05a003f02533", "https://localhost/artifactory/api/vagrant/vagrant-local/my-OS-3.6.8.box"]
 INFO subprocess: Command not in installer, restoring original environment...
 INFO subprocess: Detected AppImage environment and request to external binary. Updating library path.

 INFO interface: detail: Progress: 0% (Rate: 0*/s, Estimated time remaining: --:--:--)

 INFO interface: detail: Progress: 0% (Rate: 0*/s, Estimated time remaining: --:--:--)
Progress: 0% (Rate: 0*/s, Estimated time remaining: --:--:--) WARN downloader: Downloader exit code: 22
ERROR downloader: Exit code: 22

ERROR warden: Error occurred: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 401 Unauthorized
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Running hook: environment_unload
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x000055b2803c8d08>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::DownloaderError: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 401 Unauthorized>
ERROR vagrant: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 401 Unauthorized
ERROR vagrant: /tmp/.mount_vagranqqmVGV/usr/gembundle/gems/vagrant-2.2.16/lib/vagrant/util/downloader.rb:222:in `execute_curl'
/tmp/.mount_vagranqqmVGV/usr/gembundle/gems/vagrant-2.2.16/lib/vagrant/util/downloader.rb:113:in `download!'
/tmp/.mount_vagranqqmVGV/usr/gembundle/gems/vagrant-2.2.16/lib/vagrant/action/builtin/box_add.rb:482:in `download'
/tmp/.mount_vagranqqmVGV/usr/gembundle/gems/vagrant-2.2.16/lib/vagrant/action/builtin/box_add.rb:347:in `block in box_add'
/tmp/.mount_vagranqqmVGV/usr/gembundle/gems/vagrant-2.2.16/lib/vagrant/action/builtin/box_add.rb:339:in `each'
/tmp/.mount_vagranqqmVGV/usr/gembundle/gems/vagrant-2.2.16/lib/vagrant/action/builtin/box_add.rb:339:in `box_add'
/tmp/.mount_vagranqqmVGV/usr/gembundle/gems/vagrant-2.2.16/lib/vagrant/action/builtin/box_add.rb:292:in `add_from_metadata'
/tmp/.mount_vagranqqmVGV/usr/gembundle/gems/vagrant-2.2.16/lib/vagrant/action/builtin/box_add.rb:127:in `call'
/tmp/.mount_vagranqqmVGV/usr/gembundle/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
/tmp/.mount_vagranqqmVGV/usr/gembundle/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
/tmp/.mount_vagranqqmVGV/usr/gembundle/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
/tmp/.mount_vagranqqmVGV/usr/gembundle/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
/tmp/.mount_vagranqqmVGV/usr/gembundle/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
/tmp/.mount_vagranqqmVGV/usr/gembundle/gems/vagrant-2.2.16/plugins/commands/box/command/add.rb:78:in `execute'
/tmp/.mount_vagranqqmVGV/usr/gembundle/gems/vagrant-2.2.16/plugins/commands/box/command/root.rb:66:in `execute'
/tmp/.mount_vagranqqmVGV/usr/gembundle/gems/vagrant-2.2.16/lib/vagrant/cli.rb:67:in `execute'
/tmp/.mount_vagranqqmVGV/usr/gembundle/gems/vagrant-2.2.16/lib/vagrant/environment.rb:290:in `cli'
/tmp/.mount_vagranqqmVGV/usr/gembundle/gems/vagrant-2.2.16/bin/vagrant:231:in `<top (required)>'
/tmp/.mount_vagranqqmVGV/usr/gembundle/bin/vagrant:23:in `load'
/tmp/.mount_vagranqqmVGV/usr/gembundle/bin/vagrant:23:in `<main>'
 INFO interface: error: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 401 Unauthorized
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 401 Unauthorized
 INFO interface: Machine: error-exit ["Vagrant::Errors::DownloaderError", "An error occurred while downloading the remote file. The error\nmessage, if any, is reproduced below. Please fix this error and try\nagain.\n\nThe requested URL returned error: 401 Unauthorized"]


```

### Expected behavior

Download succeeds and box is added successfully
It also fails with ATLAS_TOKEN exported.

### Actual behavior

Box cannot be added locally
Its probably due to the fact the last command does not contain user and password:
```
 INFO subprocess: Starting process: ["/usr/bin/curl", "-q", "--fail", "--location", "--max-redirs", "10", "--verbose", "--user-agent", "Vagrant/2.2.16 (+https://www.vagrantup.com; ruby2.6.6) ", "--continue-at", "-", "--output", "/home/user/.vagrant.d/tmp/box3bcf5d91095bb729aa71e6c368ef05a003f02533", "https://localhost/artifactory/api/vagrant/vagrant-local/my-OS-3.6.8.box"]
```

Compare it with previous requests:
```
 INFO subprocess: Starting process: ["/usr/bin/curl", "-q", "--fail", "--location", "--max-redirs", "10", "--verbose", "--user-agent", "Vagrant/2.2.16 (+https://www.vagrantup.com; ruby2.6.6) ", "--continue-at", "-", "-u", "*****:*******", "-H", "Accept: application/json", "--output", "/home/user/.vagrant.d/tmp/box9387f7e74bdfd93b36e5ca416568c940dcae2b23", "https://localhost/artifactory/api/vagrant/vagrant-local/my-OS"]
```
### Steps to reproduce

1. Local artifactory
2. vagrant box add user and passowrd

**Comment by soapy1** [comment]
I think this may be resolved by setting the environment variable [`VAGRANT_SERVER_ACCESS_TOKEN_BY_URL`](https://www.vagrantup.com/docs/other/environmental-variables#vagrant_server_access_token_by_url)

**Comment by DariuszOstolski** [comment]
Hi,

Unfortunately I don't see any changes in download command:

` INFO subprocess: Starting process: ["/tmp/.mount_vagran1yopyR/usr/bin/curl", "-q", "--fail", "--location", "--max-redirs", "10", "--verbose", "--user-agent", "Vagrant/2.2.10 (+https://www.vagrantup.com; ruby2.6.2) ", "--continue-at", "-", "--output", "/home/dostolski/.vagrant.d/tmp/box3bcf5d91095bb729aa71e6c368ef05a003f02533", "https://localhost/artifactory/api/vagrant/vagrant-local/my-OS-3.6.8.box"]`

I've exported variable:
`
$ set | grep VAGRANT                                                                                                                                                                                                     
VAGRANT_SERVER_ACCESS_TOKEN_BY_URL=true
`

I can see that the same issue was already fixed and merged:
https://github.com/hashicorp/vagrant/pull/12278

Is it included in vagrant 2.2.16?

`
$ ~/bin/vagrant -v                                                                                                                                                                                                      
Vagrant 2.2.16
`

BR,
Dariusz

**Comment by soapy1** [comment]
Hey there,
this output is a little bit confusing. It looks like you are using an old version of Vagrant from the last snippet of debug output posted

> "--user-agent", "**Vagrant/2.2.10** (+https://www.vagrantup.com; ruby2.6.2) "

The fix for issue #12278 is [version 2.2.16](https://github.com/hashicorp/vagrant/blob/main/CHANGELOG.md#2216-april-29-2021). Please ensure that you don't have an outdated installation of Vagrant somewhere on your machine.

**Comment by DariuszOstolski** [comment]
Hi,

Thank you for your help so far. I didn't notice that version mismatch(I indeed had 2.2.10 version installed somewhere) and rerun vagrant command, here is the gist:

https://gist.githubusercontent.com/DariuszOstolski/c2d49650fa0b0fd3c89558ae4f41b452/raw/3d3e34359434cb97ab1f92f679519f940c20a414/gistfile1.txt

Still I cannot see any changes in the command and URL:
`
 INFO subprocess: Starting process: ["/usr/bin/curl", "-q", "--fail", "--location", "--max-redirs", "10", "--verbose", "--user-agent", "Vagrant/2.2.16 (+https://www.vagrantup.com; ruby2.6.6) ", "--continue-at", "-", "--output", "/home/user/.vagrant.d/tmp/box3bcf5d91095bb729aa71e6c368ef05a003f02533", "https://localhost/artifactory/api/vagrant/vagrant-local/my-EOS-3.6.8.box"]
`

I hope this gist will be more helpful to pinpoint this issue than my previous answer.

BR,
Dariusz

**Comment by soapy1** [comment]
Looking at this debug log the following lines pop out

```
WARN authenticate-box-url: Adding access token as GET parameter by user request
DEBUG client: No authentication token in environment or /home/user/.vagrant.d/data/vagrant_login_token
DEBUG client: No authentication token in environment or /home/user/.vagrant.d/data/vagrant_login_token
```

It looks like you need to set the `VAGRANT_CLOUD_TOKEN` to your [artifactory token](https://www.jfrog.com/confluence/display/JFROG/Vagrant+Repositories).

**Comment by DariuszOstolski** [comment]
Hi,

Thank you a lot for you help. Setting both variables `VAGRANT_SERVER_URL` and `ATLAS_TOKEN` solved the issue. The token itself was obtained using command:

`curl -uadmin:password "http://localhost:8080/artifactory/api/vagrant/auth"`

BR,
Dariusz
