### ISSUE TITLE
The index file more than doubles its size at every vagrant ssh

### ISSUE THREAD

**Issue by stefano-lodi** [hashicorp/vagrant#12369]
### Vagrant version
Vagrant 2.2.16
### Host operating system
Windows 10
### Guest operating system
ubuntu/bionic64
### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/bionic64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```

### Debug output

https://gist.github.com/stefano-lodi/41924e508f84c139063fa704d3a88a33
https://gist.github.com/stefano-lodi/cdbf3bf060a43c1cd6b106a4bde9d391

### Expected behavior
The vagrant ssh command should have logged me into the box.

### Actual behavior

An error was displayed:
```text
C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/json/common.rb:156:in `initialize': negative string size (or size too big) (ArgumentError)
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/json/common.rb:156:in `new'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/json/common.rb:156:in `parse'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/json/common.rb:335:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine_index.rb:320:in `unlocked_reload'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine_index.rb:152:in `block (2 levels) in include?'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine_index.rb:350:in `block in with_index_lock'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine_index.rb:348:in `open'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine_index.rb:348:in `with_index_lock'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine_index.rb:151:in `block in include?'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine_index.rb:150:in `include?'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/plugin/v2/command.rb:234:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/plugin/v2/command.rb:232:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/ssh/command.rb:46:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/cli.rb:67:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/environment.rb:290:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/bin/vagrant:231:in `<main>'
```

Meanwhile, in directory .vagrant.d\data\machine-index, I noticed the following repetitive behaviour:

1. a lock file was created, with an apparently automatically generated name
2. the lock file was deleted and the index file size doubled 

that was repeated a few times, until the index file reached size 1.05GB, and the error was displayed.

### Steps to reproduce

1. vagrant init ubuntu/bionic64
2. vagrant up --debug &> vagrant.log
3. vagrant ssh --debug &> vagrant-ssh.log

### References
 #9146

**Comment by chrisroberts** [comment]
@stefano-lodi If possible, could you provide two copies of the machine index file. One copy of it before you run the command, and then a second copy of it after you run the command and the size doubles. This would be extremely helpful for us to debug where this behavior may be originating from. Thanks!

**Comment by allisonlarson** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [new issue](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
