### ISSUE TITLE
EC_POINT_bn2point: point is not on curve (OpenSSL::PKey::EC::Point::Error)

### ISSUE THREAD

**Issue by pelcasandra** [hashicorp/vagrant#12383]
Following #12382, I'm trying now to use virtualbox as a provider, but I'm getting the following error on macOS 11.3.1 with vagrant 2.2.15 (I downgrade from 2.2.16 thinking it may solve this problem but it remains):

Using vagrant has been a frustrating experience somewhat. I had three different issues (#12382, #12375 and this), paid the vmware_desktop license, spent the last 3 days on trying to make it work having no success so far. 

```
Traceback (most recent call last):
	88: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/bin/vagrant:231:in `<main>'
	87: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/environment.rb:290:in `cli'
	86: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/cli.rb:67:in `execute'
	85: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/commands/reload/command.rb:40:in `execute'
	84: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
	83: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/plugin/v2/command.rb:232:in `each'
	82: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/plugin/v2/command.rb:243:in `block in with_target_vms'
	81: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/commands/reload/command.rb:42:in `block in execute'
	80: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:201:in `action'
	79: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:201:in `call'
	78: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/environment.rb:614:in `lock'
	77: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:215:in `block in action'
	76: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:246:in `action_raw'
	75: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	74: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	73: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	72: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	71: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	70: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	69: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	68: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/call.rb:53:in `call'
	67: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	66: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	65: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	64: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	63: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	62: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	61: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	60: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	59: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	58: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	57: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	56: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/call.rb:53:in `call'
	55: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	54: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	53: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	52: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	51: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	50: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	49: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	48: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	47: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	46: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/providers/virtualbox/action/discard_state.rb:15:in `call'
	45: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	44: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/call.rb:53:in `call'
	43: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	42: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	41: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	40: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	39: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	38: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	37: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	36: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	35: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	34: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/call.rb:43:in `call'
	33: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
	32: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
	31: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
	30: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
	29: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
	28: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/graceful_halt.rb:50:in `call'
	27: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:281:in `guest'
	26: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/communicators/ssh/communicator.rb:149:in `ready?'
	25: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/communicators/ssh/communicator.rb:432:in `connect'
	24: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/retryable.rb:17:in `retryable'
	23: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/communicators/ssh/communicator.rb:433:in `block in connect'
	22: from /opt/vagrant/embedded/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
	21: from /opt/vagrant/embedded/lib/ruby/2.6.0/timeout.rb:33:in `catch'
	20: from /opt/vagrant/embedded/lib/ruby/2.6.0/timeout.rb:33:in `catch'
	19: from /opt/vagrant/embedded/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
	18: from /opt/vagrant/embedded/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
	17: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/communicators/ssh/communicator.rb:467:in `block (2 levels) in connect'
	16: from /opt/vagrant/embedded/gems/2.2.15/gems/net-ssh-6.1.0/lib/net/ssh.rb:251:in `start'
	15: from /opt/vagrant/embedded/gems/2.2.15/gems/net-ssh-6.1.0/lib/net/ssh.rb:251:in `new'
	14: from /opt/vagrant/embedded/gems/2.2.15/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:90:in `initialize'
	13: from /opt/vagrant/embedded/gems/2.2.15/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:223:in `wait'
	12: from /opt/vagrant/embedded/gems/2.2.15/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:223:in `loop'
	11: from /opt/vagrant/embedded/gems/2.2.15/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:225:in `block in wait'
	10: from /opt/vagrant/embedded/gems/2.2.15/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:190:in `poll_message'
	 9: from /opt/vagrant/embedded/gems/2.2.15/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:190:in `loop'
	 8: from /opt/vagrant/embedded/gems/2.2.15/gems/net-ssh-6.1.0/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
	 7: from /opt/vagrant/embedded/gems/2.2.15/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:184:in `accept_kexinit'
	 6: from /opt/vagrant/embedded/gems/2.2.15/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:245:in `proceed!'
	 5: from /opt/vagrant/embedded/gems/2.2.15/gems/net-ssh-6.1.0/lib/net/ssh/transport/algorithms.rb:445:in `exchange_keys'
	 4: from /opt/vagrant/embedded/gems/2.2.15/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/abstract.rb:48:in `exchange_keys'
	 3: from /opt/vagrant/embedded/gems/2.2.15/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/abstract5656.rb:56:in `send_kexinit'
	 2: from /opt/vagrant/embedded/gems/2.2.15/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/ecdh_sha2_nistp256.rb:26:in `compute_shared_secret'
	 1: from /opt/vagrant/embedded/gems/2.2.15/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/ecdh_sha2_nistp256.rb:26:in `new'
/opt/vagrant/embedded/gems/2.2.15/gems/net-ssh-6.1.0/lib/net/ssh/transport/kex/ecdh_sha2_nistp256.rb:26:in `initialize': EC_POINT_bn2point: point is not on curve (OpenSSL::PKey::EC::Point::Error)
```

**Comment by pelcasandra** [comment]
Actuallt the same reported on #12375
