### ISSUE TITLE
Unable to login to vagrant via cli

### ISSUE THREAD

**Issue by byteshiva** [hashicorp/vagrant#12392]
unable to login vagrant from the command line.

```
vagrant cloud auth login 
In a moment we will ask for your username and password to HashiCorp's
Vagrant Cloud. After authenticating, we will store an access token locally on
disk. Your login details will be transmitted over a secure connection, and
are never stored on disk locally.

If you do not have an Vagrant Cloud account, sign up at
https://www.vagrantcloud.com

Vagrant Cloud username or email: byteshiva@gmail.com
Password (will be hidden): 
Token description (Defaults to "Vagrant login from mx-toshiba"): 
/opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:132:in `rescue in request': Vagrant Cloud request failed (VagrantCloud::Error::ClientError::RequestError)
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:129:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:192:in `authentication_token_create'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:75:in `block in login'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:167:in `with_error_handling'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:74:in `login'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/util.rb:69:in `client_login'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/login.rb:54:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/root.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/root.rb:73:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/cli.rb:67:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/environment.rb:290:in `cli'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/bin/vagrant:231:in `<main>'
/opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/expects.rb:13:in `response_call': Expected([200, 201, 204]) <=> Actual(403 Forbidden) (Excon::Error::Forbidden)
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/response_parser.rb:12:in `response_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:446:in `response'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:277:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:130:in `block in request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `block in with_connection'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `synchronize'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `with_connection'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:130:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:192:in `authentication_token_create'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:75:in `block in login'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:167:in `with_error_handling'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:74:in `login'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/util.rb:69:in `client_login'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/login.rb:54:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/root.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/root.rb:73:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/cli.rb:67:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/environment.rb:290:in `cli'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/bin/vagrant:231:in `<main>'
```
Am I missing something here?

**Comment by Yohnah** [comment]
See https://github.com/hashicorp/vagrant/issues/12390, it is the same issue

**Comment by chrisroberts** [comment]
Closing as a duplicate of #12390

https://github.com/hashicorp/vagrant/issues/12390#issuecomment-848039375

**Comment by byteshiva** [comment]
Still having the same issue

```
$vagrant cloud auth login --token asdasd
The token was successfully saved.

/opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:132:in `rescue in request': Vagrant Cloud request failed (VagrantCloud::Error::ClientError::RequestError)
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:129:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:227:in `authentication_token_validate'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:57:in `block in logged_in?'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:167:in `with_error_handling'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:56:in `logged_in?'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/login.rb:75:in `execute_token'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/login.rb:49:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/root.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/root.rb:73:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/cli.rb:67:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/environment.rb:290:in `cli'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/bin/vagrant:231:in `<main>'
/opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/expects.rb:13:in `response_call': Expected([200, 201, 204]) <=> Actual(302 Found) (Excon::Error::Found)
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/response_parser.rb:12:in `response_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:446:in `response'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:277:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/idempotent.rb:50:in `error_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/base.rb:17:in `error_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/base.rb:17:in `error_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:302:in `rescue in request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:222:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/idempotent.rb:50:in `error_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/base.rb:17:in `error_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/base.rb:17:in `error_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:302:in `rescue in request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:222:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:130:in `block in request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `block in with_connection'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `synchronize'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `with_connection'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:130:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:227:in `authentication_token_validate'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:57:in `block in logged_in?'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:167:in `with_error_handling'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:56:in `logged_in?'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/login.rb:75:in `execute_token'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/login.rb:49:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/root.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/root.rb:73:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/cli.rb:67:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/environment.rb:290:in `cli'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/bin/vagrant:231:in `<main>'
/opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/expects.rb:13:in `response_call': Expected([200, 201, 204]) <=> Actual(302 Found) (Excon::Error::Found)
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/response_parser.rb:12:in `response_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:446:in `response'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:277:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/idempotent.rb:50:in `error_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/base.rb:17:in `error_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/base.rb:17:in `error_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:302:in `rescue in request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:222:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:130:in `block in request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `block in with_connection'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `synchronize'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `with_connection'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:130:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:227:in `authentication_token_validate'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:57:in `block in logged_in?'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:167:in `with_error_handling'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:56:in `logged_in?'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/login.rb:75:in `execute_token'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/login.rb:49:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/root.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/root.rb:73:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/cli.rb:67:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/environment.rb:290:in `cli'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/bin/vagrant:231:in `<main>'
/opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/expects.rb:13:in `response_call': Expected([200, 201, 204]) <=> Actual(302 Found) (Excon::Error::Found)
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/response_parser.rb:12:in `response_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:446:in `response'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:277:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:130:in `block in request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `block in with_connection'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `synchronize'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `with_connection'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:130:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:227:in `authentication_token_validate'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:57:in `block in logged_in?'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:167:in `with_error_handling'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:56:in `logged_in?'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/login.rb:75:in `execute_token'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/login.rb:49:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/root.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/root.rb:73:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/cli.rb:67:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/environment.rb:290:in `cli'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/bin/vagrant:231:in `<main>'

```

**Comment by cheretbe** [comment]
Same here. Still can't login using `vagrant cloud auth`.
https://pastebin.com/nCYzb9yW
Same credentials work fine on https://app.vagrantup.com.

**Comment by sio** [comment]
I've encountered the same failure.

`https://vagrantcloud.com/api/v1/authenticate` responds with 403 Forbidden to correct login payload.

Setting environment variable `VAGRANT_SERVER_URL=https://app.vagrantup.com` allows for login to succeed. That means we are still experiencing the consequences of misconfiguration that caused #12390. @chrisroberts, this issue needs to be reopened

**Comment by sio** [comment]
This is CDN misconfiguration. POST requests are dropped by CloudFront.

#### Expected behavior

```
# curl -X POST -H "Content-type: application/json" -H "Accept: application/json" -iL -d '{"user":{"login":"baduser","password":"badpassword"}}' "https://app.vagrantup.com/api/v1/authenticate"
HTTP/1.1 401 Unauthorized
Server: Cowboy
Date: Wed, 26 May 2021 07:56:22 GMT
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: strict-origin-when-cross-origin
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache
Set-Cookie: _atlas_session_data=cGl4NEt5MDliV1hBRURyZzl5RFZtSnZwSk50RTNYaFBncGVYSjdUY1AzTXpmTWZ5R1k4WVVDaHN3eGZTcUJ5RzdFVlREZHk0enJuNXh1aCtQZHQ0Vmc9PS0tNzJ6UzBOcU94d0pFY2hYdEFqWHBaZz09--c0afdd6fb9a1ac3f1f3fc7d8f7a2a09d954cab43; path=/; expires=Fri, 25 Jun 2021 07:56:23 GMT; secure; HttpOnly
X-Request-Id: 29a359a9-98cc-4c2c-b7b3-5e6ae3e252e7
X-Runtime: 0.355706
Transfer-Encoding: chunked
Via: 1.1 vegur

{"errors":["Bad access token!"],"success":false}
```
#### Current behavior

```
# curl -X POST -H "Content-type: application/json" -H "Accept: application/json" -iL -d '{"user":{"login":"baduser","password":"badpassword"}}' "https://vagrantcloud.com/api/v1/authenticate"
HTTP/2 403
server: CloudFront
date: Wed, 26 May 2021 07:57:25 GMT
content-type: text/html
content-length: 1053
x-cache: Error from cloudfront
via: 1.1 015720ab3b3cbbc6f2312b46993e4bb7.cloudfront.net (CloudFront)
x-amz-cf-pop: CDG50-P2
x-amz-cf-id: sv2olYirBOHIKuK0r_IWHA-saL-fCzcMlJSi2jkZsW2JGQn6-pmtfw==

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
This distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: sv2olYirBOHIKuK0r_IWHA-saL-fCzcMlJSi2jkZsW2JGQn6-pmtfw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

**Comment by byteshiva** [comment]
> Do we need to open a separate issue for this? @byteshiva what do you think?

I've opened a new issue for this problem
