### ISSUE TITLE
Vagrant Login Fails via CLI - Still having the same issue

### ISSUE THREAD

**Issue by byteshiva** [hashicorp/vagrant#12397]
Still having the same issue

```
$vagrant cloud auth login --token asdasd
The token was successfully saved.

/opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:132:in `rescue in request': Vagrant Cloud request failed (VagrantCloud::Error::ClientError::RequestError)
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:129:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:227:in `authentication_token_validate'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:57:in `block in logged_in?'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:167:in `with_error_handling'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:56:in `logged_in?'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/login.rb:75:in `execute_token'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/login.rb:49:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/root.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/root.rb:73:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/cli.rb:67:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/environment.rb:290:in `cli'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/bin/vagrant:231:in `<main>'
/opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/expects.rb:13:in `response_call': Expected([200, 201, 204]) <=> Actual(302 Found) (Excon::Error::Found)
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/response_parser.rb:12:in `response_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:446:in `response'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:277:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/idempotent.rb:50:in `error_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/base.rb:17:in `error_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/base.rb:17:in `error_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:302:in `rescue in request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:222:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/idempotent.rb:50:in `error_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/base.rb:17:in `error_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/base.rb:17:in `error_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:302:in `rescue in request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:222:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:130:in `block in request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `block in with_connection'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `synchronize'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `with_connection'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:130:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:227:in `authentication_token_validate'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:57:in `block in logged_in?'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:167:in `with_error_handling'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:56:in `logged_in?'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/login.rb:75:in `execute_token'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/login.rb:49:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/root.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/root.rb:73:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/cli.rb:67:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/environment.rb:290:in `cli'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/bin/vagrant:231:in `<main>'
/opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/expects.rb:13:in `response_call': Expected([200, 201, 204]) <=> Actual(302 Found) (Excon::Error::Found)
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/response_parser.rb:12:in `response_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:446:in `response'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:277:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/idempotent.rb:50:in `error_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/base.rb:17:in `error_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/base.rb:17:in `error_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:302:in `rescue in request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:222:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:130:in `block in request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `block in with_connection'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `synchronize'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `with_connection'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:130:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:227:in `authentication_token_validate'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:57:in `block in logged_in?'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:167:in `with_error_handling'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:56:in `logged_in?'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/login.rb:75:in `execute_token'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/login.rb:49:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/root.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/root.rb:73:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/cli.rb:67:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/environment.rb:290:in `cli'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/bin/vagrant:231:in `<main>'
/opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/expects.rb:13:in `response_call': Expected([200, 201, 204]) <=> Actual(302 Found) (Excon::Error::Found)
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/middlewares/response_parser.rb:12:in `response_call'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:446:in `response'
	from /opt/vagrant/embedded/gems/2.2.16/gems/excon-0.81.0/lib/excon/connection.rb:277:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:130:in `block in request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `block in with_connection'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `synchronize'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:84:in `with_connection'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:130:in `request'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant_cloud-3.0.4/lib/vagrant_cloud/client.rb:227:in `authentication_token_validate'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:57:in `block in logged_in?'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:167:in `with_error_handling'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/client/client.rb:56:in `logged_in?'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/login.rb:75:in `execute_token'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/login.rb:49:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/auth/root.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/cloud/root.rb:73:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/cli.rb:67:in `execute'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/environment.rb:290:in `cli'
	from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/bin/vagrant:231:in `<main>'

```

_Originally posted by @byteshiva in https://github.com/hashicorp/vagrant/issues/12392#issuecomment-848435624_

**Comment by byteshiva** [comment]
It works now! I'm able to log in via vagrant CLI 


usage :
```
$ vagrant cloud auth login --token <<TOKEN >>
```

```
 $vagrant cloud auth login --debug 
 INFO global: Vagrant version: 2.2.16
 INFO global: Ruby version: 2.6.7
 INFO global: RubyGems version: 3.0.3.1
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/opt/vagrant/embedded"
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_EXECUTABLE="/opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/bin/vagrant"
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_LOG="debug"
 WARN global: resolv replacement has not been enabled!
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/communicators/ssh/plugin.rb
 INFO manager: Registered plugin: ssh communicator
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/communicators/winssh/plugin.rb
 INFO manager: Registered plugin: windows ssh communicator
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/2.2.16
..
.
.

.
 INFO interface: success: You are already logged in.
You are already logged in.
 INFO environment: Running hook: environment_unload
 INFO host: Autodetecting host type for [#<Vagrant::Environment: /home/siva>]
DEBUG host: Trying: suse
DEBUG host: Trying: redhat
DEBUG host: Trying: alt
DEBUG host: Trying: slackware
DEBUG host: Trying: void
DEBUG host: Trying: darwin
DEBUG host: Trying: arch
DEBUG host: Trying: freebsd
DEBUG host: Trying: gentoo
DEBUG host: Trying: windows
DEBUG host: Trying: linux
 INFO host: Detected: linux!
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:
```

**Comment by soapy1** [comment]
Hi there,

It looks like this has been resolved. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
