### ISSUE TITLE
vagrant ssh error

### ISSUE THREAD

**Issue by myysophia** [hashicorp/vagrant#12474]
### Vagrant version
vagrant_2.2.16_x86_64

### Host operating system

win 10

### Guest operating system

centos7

### Vagrantfile

```# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"

  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end

```

Please ensure the Vagrantfile provided is a minimal Vagrantfile which contains
only the required configuration to reproduce the behavior. Please note that if
your Vagrantfile contains an excess of configuration unrelated the the reported
issue, or is in a different format, we may be unable to assist with your issue.
Always start with a minimal Vagrantfile and include only the relevant configuration
to reproduce the reported behavior.

### Debug output

Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Steps to reproduce

1. vagrant up
`] ➤ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'centos/7'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: box_default_1627440816679_93627
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default:
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Rsyncing folder: /cygdrive/d/data/box/ => /vagrant
`

2.vagrant ssh
` ➤ vagrant ssh
D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/subprocess.rb:160:in `rescue in execute':  (216) (Vagrant::Util::Subprocess::LaunchError)
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/subprocess.rb:153:in `execute'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/subprocess.rb:22:in `execute'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/ssh.rb:99:in `exec'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builtin/ssh_exec.rb:39:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/check_running.rb:16:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/check_created.rb:16:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:246:in `action_raw'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:215:in `block in action'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:197:in `block in action'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:201:in `action'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/ssh/command.rb:66:in `block in execute'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/plugin/v2/command.rb:243:in `block in with_target_vms'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/plugin/v2/command.rb:232:in `each'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/ssh/command.rb:46:in `execute'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/cli.rb:67:in `execute'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/environment.rb:290:in `cli'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/bin/vagrant:231:in `<main>'
D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/childprocess-4.0.0/lib/childprocess/windows/process_builder.rb:89:in `create_process':  (216) (ChildProcess::LaunchError)
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/childprocess-4.0.0/lib/childprocess/windows/process_builder.rb:34:in `start'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/childprocess-4.0.0/lib/childprocess/windows/process.rb:70:in `launch_process'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/childprocess-4.0.0/lib/childprocess/abstract_process.rb:81:in `start'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/subprocess.rb:155:in `block in execute'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/safe_chdir.rb:26:in `block (2 levels) in safe_chdir'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/safe_chdir.rb:25:in `chdir'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/safe_chdir.rb:25:in `block in safe_chdir'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/safe_chdir.rb:24:in `synchronize'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/safe_chdir.rb:24:in `safe_chdir'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/subprocess.rb:154:in `execute'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/subprocess.rb:22:in `execute'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/ssh.rb:99:in `exec'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builtin/ssh_exec.rb:39:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/check_running.rb:16:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/check_created.rb:16:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:246:in `action_raw'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:215:in `block in action'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:197:in `block in action'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/machine.rb:201:in `action'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/ssh/command.rb:66:in `block in execute'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/plugin/v2/command.rb:243:in `block in with_target_vms'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/plugin/v2/command.rb:232:in `each'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/ssh/command.rb:46:in `execute'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/cli.rb:67:in `execute'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/environment.rb:290:in `cli'
        from D:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/bin/vagrant:231:in `<main>'
                                                                                                                                    `

3. virtualBox

![image](https://user-images.githubusercontent.com/25994521/127259840-9a2fc56a-d66d-467f-b54e-35f01af41475.png)

I have a question：Why are there two identical instances？

**After vagrant is reinstalled, an error is still reported**

**Comment by myysophia** [comment]
Oh ！moba can connect.  ^_^
![image](https://user-images.githubusercontent.com/25994521/127269650-590459dc-7539-42cf-aaec-435909438d25.png)

**Comment by chrisroberts** [comment]
Hi there,

Would you please provide the full debug output from the ssh command. This can be done by running:

```
vagrant ssh --debug
```

This will help us to determine the root cause of the error. Thanks!
