### ISSUE TITLE
Invalid Argument Error During vagrant up

### ISSUE THREAD

**Issue by jimbo8098** [hashicorp/vagrant#12500]
When running the following vagrant file, I receive an error while running `vagrant up --no-tty --provider virtualbox`. The error I receive when running my Azure CI which runs the `vagrant up` command above is:

```
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000,_netdev vagrant /vagrant

The error output from the command was:

: Invalid argument
```
When I do the same manually in the directory containing the required files I receive:
```
Bringing machine 'linux' up with 'virtualbox' provider...
Bringing machine 'windows' up with 'virtualbox' provider...
==> linux: Cloning VM...
==> linux: Matching MAC address for NAT networking...
==> linux: Checking if box 'ubuntu/focal64' version '20210818.0.0' is up to date...
==> linux: Setting the name of the VM: tests_linux_1629474286434_68208
==> linux: Clearing any previously set network interfaces...
==> linux: Preparing network interfaces based on configuration...
    linux: Adapter 1: nat
    linux: Adapter 2: bridged
==> linux: Forwarding ports...
    linux: 22 (guest) => 2222 (host) (adapter 1)
==> linux: Running 'pre-boot' VM customizations...
==> linux: Booting VM...
==> linux: Waiting for machine to boot. This may take a few minutes...
    linux: SSH address: 127.0.0.1:2222
    linux: SSH username: vagrant
    linux: SSH auth method: private key
    linux: Warning: Connection reset. Retrying...
    linux:
    linux: Vagrant insecure key detected. Vagrant will automatically replace
    linux: this with a newly generated keypair for better security.
    linux:
    linux: Inserting generated public key within guest...
    linux: Removing insecure key from the guest if it's present...
    linux: Key inserted! Disconnecting and reconnecting using new SSH key...
==> linux: Machine booted and ready!
==> linux: Checking for guest additions in VM...
==> linux: Configuring and enabling network interfaces...
==> linux: Mounting shared folders...
    linux: /vagrant => <azure-agent-dir>/_work/1/generic-server/tests
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000,_netdev vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: Invalid argument
```
I am able to run `vagrant ssh linux` to get onto the VM and I note that when I run the mount command above:
```
mount -t vboxsf -o uid=1000,gid=1000,_netdev vagrant /vagrant
```
I get the same error:
```
/sbin/mount.vboxsf: mounting failed with the error: Invalid argument
```
Even if I remove all -o options, I still get the same error.

On the VM, when I run modinfo, I can see the details of the module:
```
vagrant@ubuntu-focal:~$ modinfo vboxsf
filename:       /lib/modules/5.4.0-81-generic/kernel/virtualbox-guest/vboxsf.ko
version:        6.1.16_Ubuntu r140961
alias:          fs-vboxsf
license:        GPL and additional rights
author:         Oracle Corporation
description:    Oracle VM VirtualBox VFS Module for Host File System Access
srcversion:     EDA428598EF72D1C2215E6E
depends:        vboxguest
retpoline:      Y
name:           vboxsf
vermagic:       5.4.0-81-generic SMP mod_unload modversions
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:        4B:30:29:95:31:21:45:7B:57:53:EF:8E:6F:4B:C1:47:8A:67:E1:5B
sig_hashalgo:   sha512
signature:      D0:31:1B:BF:52:61:C5:0C:B3:58:E1:6B:73:3F:CA:33:D2:A6:EE:F0:
                68:42:43:99:3B:E6:A4:4F:70:63:9A:F2:68:12:0E:E6:4C:92:9B:DA:
                08:12:68:64:B1:77:F8:4E:3D:1D:99:72:42:B2:1B:7A:D6:D9:56:6E:
                F7:2A:BB:91:A0:D9:19:18:8F:CE:17:96:31:63:13:B2:81:10:FB:4E:
                E1:3B:F0:33:4B:76:EB:5B:71:B9:F9:7F:E3:BC:D5:89:D8:44:6D:0B:
                A0:FA:F2:D6:63:2A:F8:D7:10:0A:D7:7A:83:0C:74:7F:3A:F8:61:36:
                DA:33:46:62:63:B1:2A:AC:D7:4A:62:1C:31:D9:F5:B8:5F:C3:27:E7:
                01:CC:28:78:71:23:55:8D:F4:2F:F1:12:29:43:ED:08:18:21:93:96:
                1B:0A:A0:76:7F:62:E0:1A:12:1F:1E:BC:2C:68:BA:F9:A9:7B:CC:3C:
                3C:E2:5D:80:6F:34:C5:A4:7D:C5:54:F2:6A:61:C1:AE:8C:47:0A:B7:
                4C:07:6F:0D:AC:DD:C3:98:F1:91:D2:51:68:1A:B9:4E:08:98:22:1A:
                24:28:40:8B:6E:42:9D:B4:DC:3D:6E:C6:9D:B4:33:50:57:EB:90:F6:
                A1:83:FC:FD:04:29:9E:41:76:47:A8:D2:73:7E:BF:1E:6B:F5:AC:19:
                DF:B4:57:C1:97:7B:D8:1C:FD:7C:75:18:61:71:3D:0B:AF:49:51:F5:
                1E:39:A5:D1:FB:79:3A:C3:53:8D:12:A5:3A:05:76:AC:27:19:23:24:
                95:D2:AC:BA:C6:B3:4F:B6:60:C0:F5:82:A1:AB:3C:B1:9D:4C:AC:4A:
                0A:4F:DF:AF:EE:70:DB:6A:10:62:07:0D:18:10:CD:93:D8:74:C5:AD:
                BA:72:68:33:93:3E:4C:8E:56:79:C8:57:7F:6F:C2:F7:80:3B:CE:88:
                4D:19:F4:75:C0:B7:77:11:B1:35:AB:5A:51:C0:CA:2A:BF:FF:73:B3:
                99:BD:DD:95:1B:41:68:54:2F:6F:88:24:74:26:0B:8C:A3:3F:A9:67:
                8E:CD:4B:AB:BD:4F:85:B2:81:30:4A:D7:5A:6D:65:FF:7F:78:06:25:
                94:0C:8D:C2:B6:74:BC:9B:88:53:67:6F:11:86:8D:DD:DD:FC:6B:F9:
                42:A8:11:9A:74:1E:F1:0E:A9:56:C2:6F:00:2C:E2:B9:B7:28:65:55:
                06:4E:20:C8:8B:CC:17:6D:6A:15:BF:66:17:2F:DE:21:52:87:9E:42:
                5D:B8:65:38:94:B5:9D:E9:17:62:61:36:0C:D0:52:8D:F5:48:08:FF:
                04:C1:B3:67:85:03:02:91:5B:0E:15:69
parm:           follow_symlinks:Let host resolve symlinks rather than showing them (int)
```
`VBoxManage -v` shows:
```
6.1.26r145957
```
I experienced issues on an earlier version of Vagrant (2.2.17) but these were of a different nature (they were timeouts during box config) therefore I suspect that there is something happening in the current version.

The full stack trace is below:
```

/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/builder.rb:149:in `call'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/runner.rb:89:in `block in run'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/runner.rb:89:in `run'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/builder.rb:149:in `call'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/runner.rb:89:in `block in run'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/runner.rb:89:in `run'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine.rb:246:in `action_raw'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine.rb:215:in `block in action'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/environment.rb:614:in `lock'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine.rb:201:in `call'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine.rb:201:in `action'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
/opt/vagrant/embedded/gems/2.2.18/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

I will try downgrading to an older version to see if that solves the issue.

### Vagrant version

```
Installed Version: 2.2.18
Latest Version: 2.2.18

You're running an up-to-date version of Vagrant!
```

### Host operating system

Ubuntu 20.04.3 LTS (5.8.0-1040-azure)

### Guest operating system

ubuntu/focal64 
https://app.vagrantup.com/ubuntu/boxes/focal64/versions/20210818.0.0

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|

  config.vm.define "linux" do |linux|
    linux.vm.box = "ubuntu/focal64"
    linux.vm.box_version = "20210818.0.0"
    linux.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.linked_clone = true
      vb.memory = "1024"
   end
  end

  config.vm.define "windows" do |windows|
    windows.vm.box = "jborean93/WindowsServer2019"
    windows.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.linked_clone = true
      vb.memory = "1024"
   end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.groups = {
      "all" => {
        "upgrade_server" => "false",
        "admin_users" => [
          {
            "username" => "testuser",
            "password" => "testp@$$"
          }
        ]
      }
    }
    ansible.limit = "all"
    ansible.verbose = "-vvv"
    ansible.galaxy_role_file = "../requirements.yml"
  end
end
```

### Debug output

Debug with sensitive directory names redacted:

https://gist.github.com/jimbo8098/5125f3a9749015b63a35e59a95077f81

**Comment by jimbo8098** [comment]
The same error occurs if I use the following Vagrantfile, thus forgoing the provision:

```ruby
Vagrant.configure("2") do |config|

  config.vm.define "linux" do |linux|
    linux.vm.box = "ubuntu/focal64"
    linux.vm.box_version = "20210818.0.0"
    linux.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
   end
  end

  config.vm.define "windows" do |windows|
    windows.vm.box = "jborean93/WindowsServer2019"
    windows.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
   end
  end
end
```

**Comment by jimbo8098** [comment]
I've found a workaround by adding:

```ruby
linux.vm.synced_folder ".", "/vagrant", disabled: true
```
per https://www.vagrantup.com/docs/synced-folders/basic_usage .

**Comment by kaitlincart** [comment]
Hi,

Thank you for your feedback and recommendation, however, due to limited resources and our focus on Vagrant 3.0 we are unable to complete this work in the near future.

Thanks,
Kait
