### ISSUE TITLE
Vagrant failed to initialize at a very early stage: Json plugin Failing

### ISSUE THREAD

**Issue by brokencode64** [hashicorp/vagrant#12521]
### Vagrant version
Vagrant 2.2.16

### Host operating system
Fedora 34

### Guest operating system
Debian 10.10

### Environment Variables
```
VAGRANT_DEFAULT_PROVIDER=libvirt
VAGRANT_HOME=/storage/vagrant
```

### Vagrant Plugins Installed
- pkg-config (1.4.6, global)
- vagrant-libvirt (0.5.3, global)
- vagrant-mutate (1.2.0, global)

### Vagrantfile
```
Vagrant.configure("2") do |config|

  config.vm.define "jenkinsserver" do |jenkinsserver|
    jenkinsserver.vm.box_download_insecure = true
    jenkinsserver.vm.box = "brokencode/debian-10.10"
    jenkinsserver.vm.box_version = "1.0.0"
    jenkinsserver.vm.network "forwarded_port", guest: 8080, host: 8080
    jenkinsserver.vm.network "forwarded_port", guest: 8081, host: 8081
    jenkinsserver.vm.network "forwarded_port", guest: 9090, host: 9090
    jenkinsserver.vm.network "private_network", ip: "172.28.128.1", auto_config: false
    jenkinsserver.vm.hostname = "jenkinsserver"
    jenkinsserver.vm.provider "libvirt" do |v|
      v.uri = 'qemu+unix:///system'
      v.host = "jenkinsserver"
      v.memory = 2048
      v.cpus = 2
    end
  end
end

```

### Debug output
https://gist.github.com/brokencode64/3c7695e413aa13d73ed18aaa87122154

### Expected behavior
Vagrant should start up, then be able to `vagrant ssh`.

### Actual behavior
`Vagrant up` will work the first time, but after that any vagrant command will give the following output. The server itself works, I can login via virt-manager.

```
Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
Ignoring json-2.5.1 because its extensions are not built. Try: gem pristine json --version 2.5.1
Ignoring unf_ext-0.0.7.7 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.7
Vagrant failed to initialize at a very early stage:

The plugins failed to initialize correctly. This may be due to manual
modifications made within the Vagrant home directory. Vagrant can
attempt to automatically correct this issue by running:

  vagrant plugin repair

If Vagrant was recently updated, this error may be due to incompatible
versions of dependencies. To fix this problem please remove and re-install
all plugins. Vagrant can attempt to do this automatically by running:

  vagrant plugin expunge --reinstall

Or you may want to try updating the installed plugins to their latest
versions:

  vagrant plugin update

Error message given during initialization: can't activate json-2.1.0, already activated json-2.5.1
```

### Steps to reproduce
1. sudo dnf install -y vagrant --setopt=install_weak_deps=False
2. vagrant up
3. vagrant ssh

### Fixes tried so far
1. Tried completely removing vagrant's home
`sudo rm -rf /storage/vagrant/*`
2. Plugin repair
`vagrant plugin repair`
3. Reinstall all plugins
`vagrant plugin expunge --reinstall`

**Comment by brokencode64** [comment]
Completely purged ruby and vagrant, did an rvm implode and cleared vagrant home. Reinstalled hashicorp version of vagrant.

Followed steps for :
`/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': /opt/vagrant/embedded/lib64/libcrypto.so.1.1: version `OPENSSL_1_1_1b' not found (required by /lib64/libssh.so.4) - /home/xxx/.vagrant.d/gems/2.4.6/gems/ruby-libvirt-0.7.1/lib/_libvirt.so (LoadError)`

and 

`/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': /usr/lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b - /home/rbelgrave/.vagrant.d/gems/2.4.9/gems/ruby-libvirt-0.7.1/lib/_libvirt.so (LoadError)`

Listed on page:

https://github.com/vagrant-libvirt/vagrant-libvirt 

IMPORTANTLY: did not use `export CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib64"`
