### ISSUE TITLE
'with_target_vms' processes VMs that are 'not created'

### ISSUE THREAD

**Issue by paralllax** [hashicorp/vagrant#12535]
Hello All,

It seems a machine listed as `not created` from `vagrant status` will still get passed through `with_target_vms`, and subsequently error out on the following loop as it seems to expect `nil` but receives `:not created` [in `machine.rb`]

```
      # Delete out the nil entries.
      info.dup.each do |key, value|
        info.delete(key) if value.nil?
      end
```

In my case, a plugin called this function, however it seems the issue is a bug with vagrant. The command I ran was `vagrant hostmanager`. I am using the ovirt4 provider. 

### Vagrant version

`Vagrant 2.2.17`

### Host operating system

`CentOS Linux release 7.9.2009 (Core)`

### Guest operating system

`centos 6/7`

### Output

```
/opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/machine.rb:454:in `ssh_info': undefined method `each' for :not_created:Symbol (NoMethodError)
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/communicators/ssh/communicator.rb:399:in `connect'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/plugins/communicators/ssh/communicator.rb:149:in `ready?'
        from /home/users/user/.vagrant.d/gems/3.0.1/gems/vagrant-hostmanager-1.8.9/lib/vagrant-hostmanager/command.rb:33:in `block in execute'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/plugin/v2/command.rb:243:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/plugin/v2/command.rb:232:in `each'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
        from /home/users/user/.vagrant.d/gems/3.0.1/gems/vagrant-hostmanager-1.8.9/lib/vagrant-hostmanager/command.rb:30:in `execute'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/cli.rb:67:in `execute'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/lib/vagrant/environment.rb:290:in `cli'
        from /opt/vagrant/embedded/gems/2.2.17/gems/vagrant-2.2.17/bin/vagrant:231:in `<main>'
```

### Expected behavior

I presume the machine would get skipped

### Actual behavior

A machine in a `:not created` state seems to get passed through `with_target_vms`, which errors on `ssh_info`. Machines in the status list, listed prior succeed, it simply runs into the above error and crashes when processing a vm with the state `:not created`

### Steps to reproduce

1. Verify a VM in `vagrant status` shows as `not created`
2. invoke `with_target_vms`

The code where this is executed in the plugin can be found here: [hostmanager | command.rb - line 28](https://github.com/devopsgroup-io/vagrant-hostmanager/blob/2b75b7f00f4b929023c7d6e3cd70d75b334c560b/lib/vagrant-hostmanager/command.rb#L28)

**Comment by paralllax** [comment]
It seems I was terribly wrong, this was a bug with the provider. It was fixed by a wizard [here](https://github.com/myoung34/vagrant-ovirt4/pull/157).
