### ISSUE TITLE
 Facing issues while installing and running vagrant using qemu/KVM

### ISSUE THREAD

**Issue by odidev** [hashicorp/vagrant#12597]
### Vagrant version

Vagrant 2.2.20.dev (vagrant binary built from source)

### Host operating system

Ubuntu x64 machine

### Guest operating system

Ubuntu x64 machine

### Vagrantfile

```
Vagrant.configure("2") do |config|
  config.vm.box = "jalmagro/jessie64-pgsql-nginx"
end
```

### Expected behavior

Vagrant should install vagrant-libvert plugin without failure.

### Actual behavior

Vagrant fails to install vagrant-libvert plugin.

### Description

I am working with vagrant using libvert provider (for qemu/KVM) on the x64 Ubuntu platform. I have built vagrant binaries from source using below commands: 
~~~ 
$ sudo apt-get install –y ruby-bundler 
$ git clone https://github.com/hashicorp/vagrant.git  
$ cd /path/to/your/vagrant/clone  
$ bundle install 
$ bundle --binstubs exec 
~~~ 
This has successfully created vagrant binary in the ./exec/ directory. 

Now, following the documentation here: < https://ostechnix.com/how-to-use-vagrant-with-libvirt-kvm-provider/ >, I have installed vagrant-libvert plugin as below: 
~~~ 

 * To install KVM:

$ sudo apt install qemu qemu-kvm libvirt-clients libvirt-daemon-system virtinst bridge-utils 
$ sudo systemctl enable libvirtd 
$ sudo systemctl start libvirtd 
$ systemctl status libvirtd 

 * To install vagrant-libvert plugin:

$ sudo apt install qemu libvirt-daemon-system libvirt-clients libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev ruby-libvirt ebtables dnsmasq-base 
$ ./exec/vagrant plugin install vagrant-libvirt 
~~~ 
`./exec/vagrant plugin install vagrant-libvirt` command fails to build gem native extensions with the below error logs: 
~~~  
ERROR: Failed to build gem native extension. 

    current directory: /home/ubuntu/.vagrant.d/gems/2.7.0/gems/racc-1.6.0/ext/racc/cparse 

/usr/bin/ruby2.7 -I /usr/lib/ruby/2.7.0 -r ./siteconf20211123-196328-kfnq12.rb extconf.rb 

/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/source/git.rb:204:in `rescue in load_spec_files': https://github.com/hashicorp/vagrant-spec.git (at main@03d88fe) is not yet checked out. Run `bundle install` first. (Bundler::GitError) 
~~~ 

Please find the detailed logs here:  [vagrant_error_logs.txt](https://github.com/hashicorp/vagrant/files/7587828/vagrant_error_logs.txt)

I have already executed `bundle install` while creating vagrant binary, but still facing this issue. 

Also, if I use the vagrant binary from hashicorp website, I am successfully able to install vagrant-libvert plugin, but `./exec/vagrant up` command fails to recognize libvert provider with below error logs: 
~~~ 
The provider 'libvirt' could not be found, but was requested to 
back the machine 'default'. Please use a provider that exists. 

Vagrant knows about the following providers: hyperv, docker, virtualbox 
~~~ 

Can you please provide some pointers on why the binary built from source fails to install vagrant-libvert plugin, and why the binary from hashicorp website fails to recognize libvert as provider?

**Comment by electrofelix** [comment]
I maintain vagrant-libvirt, I'd suggest that you either follow what https://github.com/vagrant-libvirt/vagrant-libvirt-qa/blob/main/scripts/install.bash does for the binary install.

Generally the expectation is that if you are using vagrant from source, it's because you are working on a plugin and are using the plugin's Gemfile which will load the plugin into vagrant automatically.

If you really want to use vagrant from source, the following works for me:
```
git clone https://github.com/hashicorp/vagrant.git
cd vagrant
rvm install ruby-2.7
rvm gemset use --create ruby-2.7.0@vagrant
bundle config set --local path vendor/bundle
bundle install
bundle binstubs --path exec --all
vagrant plugin install vagrant-libvirt
```

**Comment by odidev** [comment]
@electrofelix , Thank you for the response.  

I have followed the above steps to install ruby via rvm, and I am able to install vagrant-libvirt successfully. I can run vagrant up successfully on my x64 Ubuntu machine. 

But I am facing issues on the AWS x64 Ubuntu (also on the Amazon-Linux) instance while executing `vagrant up --provider=libvirt` command. Following are the error logs: 
~~~ 
/home/odidev/.vagrant.d/gems/2.7.5/gems/fog-libvirt-0.9.0/lib/fog/libvirt/requests/compute/vm_action.rb:7:in `create': Call to virDomainCreateWithFlags failed: unsupported configuration: Domain requires KVM, but it is not available. Check that virtualization is enabled in the host BIOS, and host configuration is setup to load the kvm modules. (Libvirt::Error) 
~~~ 

I have already installed kvm and related modues via apt by installing the packages below: 
~~~ 
$ sudo apt install qemu qemu-kvm libvirt-clients libvirt-daemon-system virtinst bridge-utils 
$ sudo apt install qemu libvirt-daemon-system libvirt-clients libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev ruby-libvirt ebtables dnsmasq-base 
~~~ 

It seems KVM modules are not loaded in the AWS instances.  

The output of the command `grep kvm /proc/modules` shows nothing on the AWS instances.  

The output of lscpu is as below:
~~~
$ sudo lscpu | grep Virtualization
Virtualization type:             full
~~~

According to this old conversation on the AWS forum here: < https://forums.aws.amazon.com/thread.jspa?threadID=74338 >, it seems that since AWS instances are themselves ‘virtual machines’, we cannot create virtualization layers on the AWS virtual machines. 

If the above said is not correct in the AWS context, can you please suggest to me how I should install the kvm modules on the AWS instances? I have reinstalled kvm, restarted libvirtd service, but still could not install the kvm_intel or kvm_amd modules.  

Can you please provide some pointers on the same?

**Comment by electrofelix** [comment]
Unfortunately AFAIK AWS doesn't support nested virtualization, instead you have to use metal instances, while GCE and Azure allow for nesting (Azure appears to only allow this on specific types, GCE suggests it's specific CPUs need to be selected)
* https://www.markou.me/2020/05/which-azure-vm-sizes-support-nested-virtualization/
* https://cloud.google.com/compute/docs/instances/nested-virtualization/overview 

Otherwise I believe you can enable the qemu driver mode in vagrant-libvirt which will use full virtualization and can work even when no hypervisor is available.

* https://www.reddit.com/r/aws/comments/993zbz/nested_virtualization_within_ec2_need_advice/
* https://aws.amazon.com/blogs/compute/running-hyper-v-on-amazon-ec2-bare-metal-instances/
* https://www.reddit.com/r/aws/comments/eo85jr/ec2_instance_types_that_support_nested/

Otherwise the provided Vagrantfile can be modified to look like as follows:
```
Vagrant.configure("2") do |config|
  config.vm.box = "jalmagro/jessie64-pgsql-nginx"
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "qemu"
  end
end
```

Given the likely performance hit you may need to investigate what CPU you want to mimic based on https://ahelpme.com/howto/qemu-full-virtualization-cpu-emulations-enable-disable-cpu-flags-instruction-sets/ to see if you can get better performance

**Comment by odidev** [comment]
@electrofelix,  Thank you for the suggestions.  

I have tried configuring my Vagrantfile to use qemu driver, and it successfully created vagrant environment using provider as libvirt on the **`AWS x64 Ubuntu instance`**. 

On the **`Ubuntu ARM64 AWS instance`**, vagrant failed to install vagrant-libvirt due to **mini-portile2** plugin error. I have resolved that issue by adding mini-portile2 in the vagrant.gemspec file as below: 
~~~ 
s.add_dependency "mini_portile2", "~> 2.4.0" 
~~~ 
Then I installed qemu using `apt-get install qemu-user-static qemu-system-arm`, configured the Vagrantfile to use qemu driver, but `vagrant up` command failed with the below logs: 
~~~ 
Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: unsupported configuration: ACPI requires UEFI on this architecture 
~~~ 

I have also created an **m6g.metal instance for ARM64** and ran vagrant with libvirt provider and encountered the same issue. 

I referred to the vagrant-libvirt issue here < https://github.com/vagrant-libvirt/vagrant-libvirt/issues/966#issuecomment-919534827 >, and set the libvirt loader in the Vagrantfile as below: 
~~~ 
libvirt.loader = "/usr/share/edk2/aarch64/QEMU_EFI-silent-pflash.raw" 
~~~ 
It seems this .raw file is not present on my system. So, I set the loader as below as an alternative: 
~~~ 
libvirt.loader = “/usr/share/AAVMF/AAVMF_CODE.fd” 
~~~ 
Even this has not helped, and the error logs remain the same. 

Below is my Vagrantfile for ARM64 platform: 
~~~ 
Vagrant.configure("2") do |config| 
  config.vm.define "VagrantTesting" do 
    config.vm.box = "jalmagro/jessie64-pgsql-nginx" 
    config.vm.provider :libvirt do |libvirt| 
      libvirt.driver = "qemu" 
      libvirt.loader = “/usr/share/AAVMF/AAVMF_CODE.fd” 
    end 
  end 
end 
~~~ 

Can you please suggest to me what can be done here?

**Comment by odidev** [comment]
Hi Team, can you please review the error logs and suggest some pointers on the same.

**Comment by odidev** [comment]
Hi Team, a gentle reminder !!

**Comment by Dingoldine** [comment]
Commenting to bring some attention to this, experiencing the same issue without finding a workaround
