### ISSUE TITLE
Vagrant ssh stopped working after upgrading to 2.2.19

### ISSUE THREAD

**Issue by clubdeuce** [hashicorp/vagrant#12625]
Had a working machine with Parallels 17.1.1(51537) and Vagrant 2.2.18 on MacBook Pro M1, Monterey 12.1. Updated to Vagrant 2.2.19, and now `vagrant up` has :

```
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 10.211.55.66:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

`Vagrantfile`:

```# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "mpasternak/focal64-arm"

  # Dmatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "private_network", ip: "10.19.19.22"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```

**Comment by clubdeuce** [comment]
Seems to be upgrading from Parallels 16 to 17 acutally. Vagrant 2.2.19 and Parallels 16.5.2(50703) do work together.

**Comment by clubdeuce** [comment]
Nobody?

**Comment by ronanchilvers** [comment]
This is affecting us too. We're using vagrant 2.2.19 with Parallels 17.1.2. After the initial boot of the box (which works fine) we then can't `halt` or `up` the box anymore and we see connection failures. Here's a sample output from using `vagrant --debug`:

```
DEBUG global: ssh server version detected: 8.4
DEBUG global: ssh server supports deprecation of RSA SHA1, deprecating
DEBUG global: set RSA SHA1 deprecation on public key: f9:b3:35:6b:fe:53:05:70:1a:f4:1a:79:b2:a3:4d:e2
DEBUG global: set RSA SHA1 deprecation on private key: f9:b3:35:6b:fe:53:05:70:1a:f4:1a:79:b2:a3:4d:e2
DEBUG ssh: == Net-SSH connection debug-level log START ==
DEBUG ssh: D, [2022-05-10T09:49:30.427011 #25535] DEBUG -- net.ssh.transport.session[1068]: establishing connection to 10.211.55.6:22
D, [2022-05-10T09:49:40.428861 #25535] DEBUG -- net.ssh.transport.session[1068]: connection established
I, [2022-05-10T09:49:40.429229 #25535]  INFO -- net.ssh.transport.server_version[107c]: negotiating protocol version
D, [2022-05-10T09:49:40.429293 #25535] DEBUG -- net.ssh.transport.server_version[107c]: local is `SSH-2.0-Ruby/Net::SSH_6.1.0 x86_64-darwin19'
D, [2022-05-10T09:49:40.432850 #25535] DEBUG -- net.ssh.transport.server_version[107c]: remote is `SSH-2.0-OpenSSH_8.4p1 Debian-5'
W, [2022-05-10T09:49:40.433228 #25535]  WARN -- net.ssh.transport.algorithms[1090]: unsupported algorithm: `["rsa-sha2-256", "rsa-sha2-512"]'
I, [2022-05-10T09:49:40.433773 #25535]  INFO -- net.ssh.transport.algorithms[1090]: sending KEXINIT
D, [2022-05-10T09:49:40.435073 #25535] DEBUG -- socket[10a4]: queueing packet nr 0 type 20 len 796
D, [2022-05-10T09:49:40.435238 #25535] DEBUG -- socket[10a4]: sent 800 bytes
D, [2022-05-10T09:49:40.435407 #25535] DEBUG -- socket[10a4]: read 1056 bytes
D, [2022-05-10T09:49:40.435618 #25535] DEBUG -- socket[10a4]: received packet nr 0 type 20 len 1052
I, [2022-05-10T09:49:40.435696 #25535]  INFO -- net.ssh.transport.algorithms[1090]: got KEXINIT from server
I, [2022-05-10T09:49:40.436034 #25535]  INFO -- net.ssh.transport.algorithms[1090]: negotiating algorithms
D, [2022-05-10T09:49:40.436289 #25535] DEBUG -- net.ssh.transport.algorithms[1090]: negotiated:
* kex: ecdh-sha2-nistp521
* host_key: ssh-ed25519
* encryption_server: aes256-ctr
* encryption_client: aes256-ctr
* hmac_client: hmac-sha2-512-etm@openssh.com
* hmac_server: hmac-sha2-512-etm@openssh.com
* compression_client: none
* compression_server: none
* language_client: 
* language_server: 
D, [2022-05-10T09:49:40.436326 #25535] DEBUG -- net.ssh.transport.algorithms[1090]: exchanging keys
D, [2022-05-10T09:49:40.442574 #25535] DEBUG -- socket[10a4]: queueing packet nr 1 type 30 len 148
D, [2022-05-10T09:49:40.442658 #25535] DEBUG -- socket[10a4]: sent 152 bytes
D, [2022-05-10T09:49:40.447836 #25535] DEBUG -- socket[10a4]: read 312 bytes
D, [2022-05-10T09:49:40.447884 #25535] DEBUG -- socket[10a4]: received packet nr 1 type 31 len 292
D, [2022-05-10T09:49:40.450994 #25535] DEBUG -- socket[10a4]: queueing packet nr 2 type 21 len 20
D, [2022-05-10T09:49:40.451020 #25535] DEBUG -- socket[10a4]: sent 24 bytes
D, [2022-05-10T09:49:40.451120 #25535] DEBUG -- socket[10a4]: received packet nr 2 type 21 len 12
D, [2022-05-10T09:49:40.451675 #25535] DEBUG -- net.ssh.authentication.session[10b8]: beginning authentication of `vagrant'
D, [2022-05-10T09:49:40.451696 #25535] DEBUG -- socket[10a4]: using encrypt-then-mac
D, [2022-05-10T09:49:40.451732 #25535] DEBUG -- socket[10a4]: queueing packet nr 3 type 5 len 32
D, [2022-05-10T09:49:40.451752 #25535] DEBUG -- socket[10a4]: sent 100 bytes
D, [2022-05-10T09:49:40.451905 #25535] DEBUG -- socket[10a4]: read 100 bytes
D, [2022-05-10T09:49:40.451975 #25535] DEBUG -- socket[10a4]: received packet nr 3 type 6 len 32
D, [2022-05-10T09:49:40.452028 #25535] DEBUG -- net.ssh.authentication.session[10b8]: trying none
D, [2022-05-10T09:49:40.452068 #25535] DEBUG -- socket[10a4]: using encrypt-then-mac
D, [2022-05-10T09:49:40.452086 #25535] DEBUG -- socket[10a4]: queueing packet nr 4 type 50 len 48
D, [2022-05-10T09:49:40.452103 #25535] DEBUG -- socket[10a4]: sent 116 bytes
D, [2022-05-10T09:49:40.459739 #25535] DEBUG -- socket[10a4]: read 100 bytes
D, [2022-05-10T09:49:40.459897 #25535] DEBUG -- socket[10a4]: received packet nr 4 type 51 len 32
D, [2022-05-10T09:49:40.459931 #25535] DEBUG -- net.ssh.authentication.session[10b8]: allowed methods: publickey,password
D, [2022-05-10T09:49:40.459955 #25535] DEBUG -- net.ssh.authentication.methods.none[10cc]: none failed
D, [2022-05-10T09:49:40.459977 #25535] DEBUG -- net.ssh.authentication.session[10b8]: trying publickey
D, [2022-05-10T09:49:40.460437 #25535] DEBUG -- net.ssh.authentication.agent[10e0]: connecting to ssh-agent
D, [2022-05-10T09:49:40.460499 #25535] DEBUG -- net.ssh.authentication.agent[10e0]: sending agent request 1 len 47

DEBUG ssh: == Net-SSH connection debug-level log END ==
ERROR warden: Error occurred: can't modify frozen String: ""
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::HandleForwardedPortCollisions:0x00007fc4dca965c0>
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: can't modify frozen String: ""
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: can't modify frozen String: ""
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00007fc4ca2205d8>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
ERROR warden: Error occurred: can't modify frozen String: ""
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: can't modify frozen String: ""
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00007fc4d9e8ae68>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
ERROR warden: Error occurred: can't modify frozen String: ""
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: can't modify frozen String: ""
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00007fc4ca1d18e8>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00007fc4ca1f9758>
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00007fc4dcb777c8>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: can't modify frozen String: ""
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: can't modify frozen String: ""
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: can't modify frozen String: ""
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: can't modify frozen String: ""
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: can't modify frozen String: ""
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: can't modify frozen String: ""
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00007fc4ca11d398>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-e703c4d6f4c5897a120a5443755c6ad9
 INFO environment: Running hook: environment_unload
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00007fc4ca2422c8>
/opt/vagrant/embedded/gems/2.2.19/gems/net-ssh-6.1.0/lib/net/ssh/buffer.rb:147:in `append': can't modify frozen String: "" (FrozenError)
	from /opt/vagrant/embedded/gems/2.2.19/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:211:in `read_packet'
	from /opt/vagrant/embedded/gems/2.2.19/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:221:in `send_and_wait'
	from /opt/vagrant/embedded/gems/2.2.19/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:105:in `negotiate!'
	from /opt/vagrant/embedded/gems/2.2.19/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:68:in `connect'
	from /opt/vagrant/embedded/gems/2.2.19/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:204:in `agent'
	from /opt/vagrant/embedded/gems/2.2.19/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:113:in `each_identity'
	from /opt/vagrant/embedded/gems/2.2.19/gems/net-ssh-6.1.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
	from /opt/vagrant/embedded/gems/2.2.19/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:86:in `block in authenticate'
	from /opt/vagrant/embedded/gems/2.2.19/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:72:in `each'
	from /opt/vagrant/embedded/gems/2.2.19/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:72:in `authenticate'
	from /opt/vagrant/embedded/gems/2.2.19/gems/net-ssh-6.1.0/lib/net/ssh.rb:255:in `start'
	from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/communicators/ssh/communicator.rb:467:in `block (2 levels) in connect'
	from /opt/vagrant/embedded/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
	from /opt/vagrant/embedded/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
	from /opt/vagrant/embedded/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	from /opt/vagrant/embedded/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	from /opt/vagrant/embedded/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/communicators/ssh/communicator.rb:433:in `block in connect'
	from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/util/retryable.rb:17:in `retryable'
	from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/communicators/ssh/communicator.rb:432:in `connect'
	from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/communicators/ssh/communicator.rb:87:in `block in wait_for_ready'
	from /opt/vagrant/embedded/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
	from /opt/vagrant/embedded/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
	from /opt/vagrant/embedded/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	from /opt/vagrant/embedded/lib/ruby/2.7.0/timeout.rb:33:in `catch'
	from /opt/vagrant/embedded/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/communicators/ssh/communicator.rb:63:in `wait_for_ready'
	from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'
```

**Comment by eleleung** [comment]
I have also come across this issue when upgrading to Parallels 17. Am running Vagrant 2.2.19

**Comment by ronanchilvers** [comment]
In our case, we tracked the problem down to a custom SSH agent running on the machine. The communication between (presumably) the net::ssh library and the ssh-agent failed. Switching back to gnupg or ssh-agent resolved the problem.

**Comment by m0zgen** [comment]
Hi, I have the same problems, when we can expect fixes or etc from Vagrant?

Switching back to gnupg or ssh-agent not is actual variant for me.(
