### ISSUE TITLE
vagrant up does not work

### ISSUE THREAD

**Issue by S-Osman4** [hashicorp/vagrant#12706]
vagrant version 2.2.19
oracle virtual box version 6.0.24
i get this error below when i vagrant up
```
Traceback (most recent call last):
        9: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/bin/vagrant:194:in `<main>'
        8: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/bin/vagrant:194:in `new'
        7: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/environment.rb:178:in `initialize'
        6: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/environment.rb:984:in `process_configured_plugins'
        5: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/environment.rb:957:in `find_configured_plugins'
        4: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/environment.rb:957:in `each'
        3: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/environment.rb:959:in `block in find_configured_plugins'
        2: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/vagrantfile.rb:187:in `machine_config'
        1: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.7.0/json/common.rb:156:in `parse'
C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.7.0/json/common.rb:156:in `parse': 783: unexpected token at '' (JSON::ParserError)
```
what causes it or how do i solve it

**Comment by S-Osman4** [comment]
not yet...let's wait some more

**Comment by nyukers** [comment]
You can downgrade vagrant version for testing your case.

**Comment by berndschatz** [comment]
Have you any (outdated) plugins installed ? 

~~~
vagrant plugin list
~~~

**Comment by S-Osman4** [comment]
@berndschatz  thank you for your response
i have ``` vagrant-vbguest (0.30.0, global)``` and
```vagrant vbguest --status``` reports gives me the same error as above.

**Comment by S-Osman4** [comment]
@nyukers thank you for you response
do you suggest i uninstall the current version before downloading an older version?

**Comment by soapy1** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
