### ISSUE TITLE
vagrant plugin install vagrant-vbguest breaks form 2.2.18 to 2.2.19

### ISSUE THREAD

**Issue by idhugoid** [hashicorp/vagrant#12789]
Trying to install the vagrant-vbguest plugin fails on 2.2.19, but works on 2.2.18 

### Vagrant version
2.2.19

### Host operating system
Debian 11

```
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
/usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/bundler.rb:855:in `find_all': can't modify frozen Gem::Dependency: <Gem::Dependency type=:runtime name="net-ssh" requirements="< 7.0.0, >= 2.6.5"> (FrozenError)
	from /usr/lib/ruby/vendor_ruby/rubygems/resolver/composed_set.rb:54:in `block in find_all'
	from /usr/lib/ruby/vendor_ruby/rubygems/resolver/composed_set.rb:53:in `map'
	from /usr/lib/ruby/vendor_ruby/rubygems/resolver/composed_set.rb:53:in `find_all'
	from /usr/lib/ruby/vendor_ruby/rubygems/resolver.rb:203:in `find_possible'
	from /usr/lib/ruby/vendor_ruby/rubygems/resolver.rb:228:in `search_for'
	from /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:11:in `block in search_for'
	from /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
	from /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:10:in `search_for'
	from /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:779:in `possibilities_for_requirement'
	from /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
	from /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
	from /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:727:in `activate_new_spec'
	from /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
	from /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:254:in `process_topmost_state'
	from /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:182:in `resolve'
	from /usr/lib/ruby/vendor_ruby/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:43:in `resolve'
	from /usr/lib/ruby/vendor_ruby/rubygems/resolver.rb:190:in `resolve'
	from /usr/lib/ruby/vendor_ruby/rubygems/request_set.rb:411:in `resolve'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/bundler.rb:586:in `internal_install'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/bundler.rb:350:in `install'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/plugin/manager.rb:138:in `block in install_plugin'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/plugin/manager.rb:148:in `install_plugin'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/environment.rb:1014:in `block in process_configured_plugins'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/environment.rb:1005:in `each'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/environment.rb:1005:in `process_configured_plugins'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/environment.rb:178:in `initialize'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/bin/vagrant:194:in `new'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/bin/vagrant:194:in `<top (required)>'
	from /usr/bin/vagrant:25:in `load'
	from /usr/bin/vagrant:25:in `<main>'

```

**Comment by ptomulik** [comment]
As a workaround one may put this to a file under ``/etc/apt/preferences.d/``, for example
```
# /etc/apt/preferences.d/blacklist-buggy-versions.pref
Package: vagrant
Pin: version 2.2.19+dfsg-1
Pin-Priority: 99

Package: vagrant
Pin: version 2.2.19
Pin-Priority: 99
```

then 

```shell
sudo apt update
```
and, once uninstalled, the buggy version shall not install again.
