### ISSUE TITLE
 `scan': invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by iiDestiny** [hashicorp/vagrant#12814]
### Vagrant version
2.2.19

### Host operating system
macbook pro m1 max

### Guest operating system

bento/ubuntu-20.04-arm64 + parallels-desktop

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.require_version ">= 2.2.19"

Vagrant.configure(2) do |config|

class VagrantPlugins::ProviderVirtualBox::Action::Network
  def dhcp_server_matches_config?(dhcp_server, config)
    true
  end
end

  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.hostname = "www.mmogah.local"
  config.vm.define "mmo-host"
  config.vm.box = "bento/ubuntu-20.04"

  config.vm.provider "parallels" do |vb|
    config.vm.box = "bento/ubuntu-20.04-arm64"
  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = true

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "forwarded_port", guest: 80, host: 8080, id: "nginx-http", auto_correct: true
  config.vm.network "forwarded_port", guest: 443, host: 8443, id: "nginx-https", auto_correct: true
  config.vm.network "forwarded_port", guest: 6081, host: 6084, id: "varnish", auto_correct: true
  
  if config.vm.provider "vmware_desktop"
    config.vm.network "private_network"
  else
    config.vm.network "private_network", ip: "192.168.56.10", auto_correct: true
  end
  
  config.ssh.shell="bash"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # DELETE the mount_options: ["rw","vers=3","udp","nolock"] if have issues starting
  
  #Rsync for majority of files 1 way. dev machine to vm. NFS for 2 way sync. any DB migrates etc. 
  # Checking platfom
  if Vagrant::Util::Platform.windows?
  
  #To use nfs do ENV='nfs' vagrant up 
  #alias vagrant='ENV=nfs vagrant' 
  if ENV['ENV'] = 'nfs' 

       if Vagrant::Util::Platform.windows? then
          unless Vagrant.has_plugin?("vagrant-winnfsd")
            raise  Vagrant::Errors::VagrantError.new, "vagrant-winnfsd plugin is missing. Please install it using 'vagrant plugin install vagrant-winnfsd' and rerun 'vagrant up'"
          end
       end 

    #config.vm.synced_folder '.', "/var/www", type: "nfs", mount_options: %w{rw,async,fsc,nolock,vers=3,tcp,rsize=32768,wsize=32768,hard,noatime,actimeo=2}
	
	#Uncomment this to run npm or other intensive tasks once. 
	config.vm.synced_folder ".", "/var/www", type: "rsync",
	rsync__exclude: [".git/", "/node_modules/*", "/vendors/*"]
		
    else
	#Windows SMB Make sure run vagrant up as an administrator window- https://www.vagrantup.com/docs/synced-folders/smb
    config.vm.synced_folder ".", "/var/www", mount_options: ["mfsymlinks,dir_mode=0775,file_mode=0664,vers=3.0"], type: "smb", owner: 'vagrant', group: 'www-data'
	
    end
	config.vm.provision :file do |file|
    file.source = "local-playbook.yml"
    file.destination = "/tmp/local-playbook.yml"
	end
  
  config.vm.provision :file do |file|
    file.source = "composer.json"
    file.destination = "/tmp/composer.json"
  end

  config.vm.provision :file do |file|
    file.source = "composer.lock"
    file.destination = "/tmp/composer.lock"
  end
  
  #set permissions and non synced files
  config.vm.provision "shell",
  inline: "sudo chmod 777 /var/www
  mv /tmp/local-playbook.yml /var/www/local-playbook.yml
  mv /tmp/composer.json /var/www/composer.json
  mv /tmp/composer.lock /var/www/composer.lock
  mkdir -p -m 777 /var/www/App/Runtime
  "    
	config.vm.provision "shell", inline: "sudo supervisorctl restart all || true", run: 'always'
	
  elsif Vagrant::Util::Platform.linux?
    config.vm.synced_folder ".", "/var/www", mount_options: ["rw", "tcp", "nolock", "noacl", "async"], type: "nfs", nfs_udp: false, nfs_version: 4
	config.vm.provision "shell", inline: "sudo supervisorctl restart all || true", run: 'always'
  else
    config.vm.synced_folder ".", "/var/www"
	config.vm.provision "shell", inline: "sudo supervisorctl restart all || true", run: 'always'
  end
  
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.name = "mmo-vm"
    vb.memory = "4096"
    vb.cpus = 2
  end
end
```

### Debug output

```
Traceback (most recent call last):
	14: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/bin/vagrant:231:in `<main>'
	13: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/environment.rb:290:in `cli'
	12: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/cli.rb:67:in `execute'
	11: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/commands/halt/command.rb:30:in `execute'
	10: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
	 9: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/plugin/v2/command.rb:232:in `each'
	 8: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/plugin/v2/command.rb:243:in `block in with_target_vms'
	 7: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/commands/halt/command.rb:31:in `block in execute'
	 6: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:186:in `action'
	 5: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:657:in `check_cwd'
	 4: from (eval):9:in `warn'
	 3: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/ui.rb:368:in `format_message'
	 2: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/ui.rb:368:in `tap'
	 1: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/ui.rb:369:in `block in format_message'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/ui.rb:369:in `scan': invalid byte sequence in US-ASCII (ArgumentError)
```

### Expected behavior

Normal start

### Actual behavior

What actually happened?

### Steps to reproduce

```
$ vagrant up
```

**Comment by iiDestiny** [comment]
@evanphx @wayneeseguin @topfunky @hornbeck 

Is it related to the file directory name?
