### ISSUE TITLE
requirement.rb:108:in `parse': Illformed requirement ["v202112.19.0"] (Gem::Requirement::BadRequirementError)

### ISSUE THREAD

**Issue by onknows** [hashicorp/vagrant#12848]
### Vagrant version

First saw this error using 2.2.13 then upgraded to latest version 2.3.0. The error is still there.

### Host operating system

Ubuntu 18.04

### Guest operating system

I am using Vagrant box `bento/ubuntu-18.04` version `v202112.19.0`

### Vagrantfile

```ruby
Vagrant.configure(2) do |config|
  config.vm.define 'ubuntu' do |cfg|
    cfg.vm.box = 'bento/ubuntu-18.04'
    cfg.vm.box_version = 'v202112.19.0'
    cfg.vm.provider 'virtualbox' do |vb|
      vb.gui = false
      vb.memory = 1024
    end
  end
end
```

### Debug output

https://gist.github.com/onknows/1956f1d20c8afe1a7c9f32ee0ea510e8

### Expected behavior

Vagrant up each time

### Actual behavior

Error message on all vagrant commands

```bash
[myuser:~/git/ok/ok/ansible-dev/tmp] [2.5.3] master(+257/-256)* 1 ± vagrant up
Traceback (most recent call last):
	16: from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/bin/vagrant:211:in `<main>'
	15: from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/bin/vagrant:211:in `new'
	14: from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/environment.rb:189:in `initialize'
	13: from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/environment.rb:1008:in `process_configured_plugins'
	12: from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/environment.rb:981:in `find_configured_plugins'
	11: from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/environment.rb:981:in `each'
	10: from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/environment.rb:983:in `block in find_configured_plugins'
	 9: from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/vagrantfile.rb:238:in `machine_config'
	 8: from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/vagrantfile.rb:202:in `block in machine_config'
	 7: from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/box_collection.rb:278:in `find'
	 6: from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/box_collection.rb:278:in `map'
	 5: from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/box_collection.rb:279:in `block in find'
	 4: from /opt/vagrant/embedded/gems/2.3.0/gems/vagrant-2.3.0/lib/vagrant/box_collection.rb:279:in `new'
	 3: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/requirement.rb:140:in `initialize'
	 2: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/requirement.rb:140:in `map!'
	 1: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/requirement.rb:140:in `block in initialize'
/opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/requirement.rb:108:in `parse': Illformed requirement ["v202112.19.0"] (Gem::Requirement::BadRequirementError)
[myuser:~/git/ok/ok/ansible-dev/tmp] [2.5.3] master(+257/-256)* 1 ± 
```

### Steps to reproduce

1. Create Vagrant file as shown above
2. Execute any vagrant command

**Comment by chrisroberts** [comment]
Hi there,

The `v` just needs to be removed from the start of the version number defined. The value should be `202112.19.0`.

Marking this as a documentation issue so we properly rescue out the error and show a helpful message.
