### ISSUE TITLE
Ubuntu 22.04 + LXC: Malformed version number string 5.0.0~git2209-g5a7b9ce67

### ISSUE THREAD

**Issue by indrisepos** [hashicorp/vagrant#12846]
After the Ubuntu 20.04 -> 22.04 upgrade, the LXC boxes do not work. In Ubutnu 20.04, LXC had version 4.0.12, in 22.04 it was 5.0.0~git2209-g5a7b9ce67, which cannot be accepted in the error message. The version number 5.0.0~git2209-g5a7b9ce67 is really strange, but I think it shouldn't cause such an error. I tried with three different LXC boxes, it gave the same error message. See the full debug message and trace at ### Debug output.

### Vagrant version

$ vagrant -v
Vagrant 2.2.14  # I have already tried with version 2.3.0

$ lxc-info --version
5.0.0~git2209-g5a7b9ce67

### Host operating system

Ubuntu 22.04

### Vagrantfile

```ruby
#!/usr/bin/env ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.provider 'lxc'
    config.vm.box = 'indrisepos/lxc-999-focal'
    #config.vm.box = "hibox/focal64"
    #config.vm.box = "isc/lxc-ubuntu-20.04"

end
```

### Debug output

$ vagrant up
Bringing machine 'default' up with 'lxc' provider...
==> default: Importing base box 'indrisepos/lxc-999-focal'...
Traceback (most recent call last):
	29: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
	28: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `action'
	27: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `call'
	26: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/environment.rb:613:in `lock'
	25: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:215:in `block in action'
	24: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:246:in `action_raw'
	23: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
	22: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
	21: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
	20: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
	19: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	18: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	17: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	16: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/call.rb:53:in `call'
	15: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
	14: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
	13: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
	12: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
	11: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	10: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 9: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 8: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	 7: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 6: from /home/andras/.vagrant.d/gems/2.6.6/gems/vagrant-lxc-1.4.3/lib/vagrant-lxc/action/handle_box_metadata.rb:43:in `call'
	 5: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 4: from /home/andras/.vagrant.d/gems/2.6.6/gems/vagrant-lxc-1.4.3/lib/vagrant-lxc/action/create.rb:28:in `call'
	 3: from /home/andras/.vagrant.d/gems/2.6.6/gems/vagrant-lxc-1.4.3/lib/vagrant-lxc/driver.rb:219:in `supports_new_config_format'
	 2: from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/version.rb:203:in `new'
	 1: from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/version.rb:203:in `new'
/opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/version.rb:212:in `initialize': Malformed version number string 5.0.0~git2209-g5a7b9ce67 (ArgumentError)

### References

- https://github.com/hashicorp/vagrant/issues/10663
- https://packages.ubuntu.com/jammy/lxc

**Comment by AlexeyDemidov** [comment]
It is possible to modify [vagrant-lxc][1] code at [lib/vagrant-lxc/driver/cli.rb#L32][2] to modify version string returned by `lxc-create --version` called by this code.

[2]:https://github.com/fgrehm/vagrant-lxc/blob/ff58ecd5f2278f0e3314db1fb0a7862dc61ad5d1/lib/vagrant-lxc/driver/cli.rb#L32

[1]:https://github.com/fgrehm/vagrant-lxc
