### ISSUE TITLE
Vagrant error

### ISSUE THREAD

**Issue by Johnyartifice** [hashicorp/vagrant#12928]
# Installed the newest version of Vagrant and VirtualBox several times. Still getting this error.

$ vagrant up
C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/childprocess-4.1.0/lib/childprocess/windows/process_builder.rb:44:in `encode!': "\\xC3" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to UTF-16LE (Encoding::UndefinedConversionError)
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/childprocess-4.1.0/lib/childprocess/windows/process_builder.rb:44:in `to_wide_string'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/childprocess-4.1.0/lib/childprocess/windows/process_builder.rb:67:in `create_environment_pointer'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/childprocess-4.1.0/lib/childprocess/windows/process_builder.rb:28:in `start'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/childprocess-4.1.0/lib/childprocess/windows/process.rb:70:in `launch_process'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/childprocess-4.1.0/lib/childprocess/abstract_process.rb:81:in `start'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/subprocess.rb:155:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/safe_chdir.rb:26:in `block (2 levels) in safe_chdir'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/safe_chdir.rb:25:in `chdir'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/safe_chdir.rb:25:in `block in safe_chdir'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/safe_chdir.rb:24:in `synchronize'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/safe_chdir.rb:24:in `safe_chdir'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/subprocess.rb:154:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/subprocess.rb:22:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/powershell.rb:191:in `version'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/powershell.rb:212:in `validate_install!'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/powershell.rb:113:in `execute_cmd'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/platform.rb:82:in `block in windows_admin?'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/platform.rb:84:in `windows_admin?'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/plugins/providers/hyperv/provider.rb:20:in `usable?'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/environment.rb:378:in `block in default_provider'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/registry.rb:49:in `block in each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/registry.rb:48:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/registry.rb:48:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/environment.rb:364:in `default_provider'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/environment.rb:968:in `guess_provider'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/environment.rb:980:in `find_configured_plugins'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/environment.rb:1008:in `process_configured_plugins'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/environment.rb:189:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/bin/vagrant:211:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/bin/vagrant:211:in `<main>'

**Comment by Johnyartifice** [comment]
https://github.com/hashicorp/vagrant/issues/12121
