### ISSUE TITLE
Vagrant versions 2.3.1 to 2.3.4 do not work on macOS 10.14 Mojave

### ISSUE THREAD

**Issue by lesinigo** [hashicorp/vagrant#12997]
### Debug output

```
[luca:~] $ vagrant version
Traceback (most recent call last):
	25: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/bin/vagrant:211:in `<main>'
	24: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/bin/vagrant:211:in `new'
	23: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/environment.rb:189:in `initialize'
	22: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/environment.rb:998:in `process_configured_plugins'
	21: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/environment.rb:817:in `vagrantfile'
	20: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/environment.rb:817:in `new'
	19: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/vagrantfile.rb:31:in `initialize'
	18: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/config/loader.rb:200:in `load'
	17: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/config/v2/loader.rb:21:in `finalize'
	16: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/config/v2/root.rb:46:in `finalize!'
	15: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/registry.rb:48:in `each'
	14: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/registry.rb:48:in `each'
	13: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/registry.rb:49:in `block in each'
	12: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/registry.rb:27:in `get'
	11: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/plugins/kernel_v2/plugin.rb:39:in `block in <class:Plugin>'
	10: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 9: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 8: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/plugins/kernel_v2/config/vm.rb:15:in `<top (required)>'
	 7: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 6: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 5: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/protobufs/proto/protostructure_pb.rb:4:in `<top (required)>'
	 4: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 3: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 2: from /opt/vagrant/embedded/gems/2.3.1/gems/google-protobuf-3.21.7-x86_64-darwin/lib/google/protobuf.rb:49:in `<top (required)>'
	 1: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': dlopen(/opt/vagrant/embedded/gems/2.3.1/gems/google-protobuf-3.21.7-x86_64-darwin/lib/google/2.7/protobuf_c.bundle, 9): no suitable image found.  Did find: (LoadError)
	/opt/vagrant/embedded/gems/2.3.1/gems/google-protobuf-3.21.7-x86_64-darwin/lib/google/2.7/protobuf_c.bundle: cannot load 'protobuf_c.bundle' (load command 0x80000034 is unknown)
	/opt/vagrant/embedded/gems/2.3.1/gems/google-protobuf-3.21.7-x86_64-darwin/lib/google/2.7/protobuf_c.bundle: cannot load 'protobuf_c.bundle' (load command 0x80000034 is unknown) - /opt/vagrant/embedded/gems/2.3.1/gems/google-protobuf-3.21.7-x86_64-darwin/lib/google/2.7/protobuf_c.bundle
	26: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/bin/vagrant:211:in `<main>'
	25: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/bin/vagrant:211:in `new'
	24: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/environment.rb:189:in `initialize'
	23: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/environment.rb:998:in `process_configured_plugins'
	22: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/environment.rb:817:in `vagrantfile'
	21: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/environment.rb:817:in `new'
	20: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/vagrantfile.rb:31:in `initialize'
	19: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/config/loader.rb:200:in `load'
	18: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/config/v2/loader.rb:21:in `finalize'
	17: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/config/v2/root.rb:46:in `finalize!'
	16: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/registry.rb:48:in `each'
	15: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/registry.rb:48:in `each'
	14: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/registry.rb:49:in `block in each'
	13: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/registry.rb:27:in `get'
	12: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/plugins/kernel_v2/plugin.rb:39:in `block in <class:Plugin>'
	11: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	10: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 9: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/plugins/kernel_v2/config/vm.rb:15:in `<top (required)>'
	 8: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 7: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 6: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/protobufs/proto/protostructure_pb.rb:4:in `<top (required)>'
	 5: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 4: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 3: from /opt/vagrant/embedded/gems/2.3.1/gems/google-protobuf-3.21.7-x86_64-darwin/lib/google/protobuf.rb:48:in `<top (required)>'
	 2: from /opt/vagrant/embedded/gems/2.3.1/gems/google-protobuf-3.21.7-x86_64-darwin/lib/google/protobuf.rb:51:in `rescue in <top (required)>'
	 1: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- google/protobuf_c (LoadError)
```

### Expected behavior

Vagrant should have worked correctly or the installation DMG should have warned me that my macOS version is not compatibile or some part of [the documentation](https://developer.hashicorp.com/vagrant/docs) should have warned about the incompatibility.

### Actual behavior

I tried all vagrant versions from 2.3.1 up to the current 2.3.3 and none of them worked, so I had to revert to 2.3.0.

#### Vagrant version

2.3.1, 2.3.2, 2.3.3 installed from the official DMG files

#### Host operating system

macOS Mojave 10.14.6

#### Guest operating system

I'd like to have one running ;-)

#### Steps to reproduce

1. get a macOS 10.14 system
2. clean up any previous vagrant setup (use `uninstall.tool` from the dmg and also `sudo rm -rf ~/.vagrant.d` just to be safe)
3. install Vagrant >= 2.3.1 
4. try `vagrant version` or just any other command and see it failing

Repeat the above with Vagrant 2.3.0 and it will happily work.

#### Vagrantfile

Not needed to reproduce the problem

**Comment by BenceSzalai** [comment]
I've just faced the same issue. Same macOS version. Downgraded to 2.2.19 (my previous version) and it works again fine.

My error message/stack trace is exactly the same, so I won't add noise. Just wanted to say it is not an isolated case.

**Comment by kom177** [comment]
I've noticed it for Vagrant 2.3.2 and MacOS 10.13 High Sierra. Version 2.3.0 works fine.

**Comment by bombaywalla** [comment]
Same issue.  Same error.  Trying to install Version 2.3.3 on High Sierra 10.13.6.

**Comment by peterdd** [comment]
Same issue. I downgraded to 2.3.0 on High Sierra 10.13.6 to make it work again.

**Comment by kom177** [comment]
Version 2.3.4 doesn't work on High Sierra 10.13.6.

```
192:drupal-r4d kom$ vagrant up
Traceback (most recent call last):
	2: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/bin/vagrant:111:in `<main>'
	1: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- vagrant (LoadError)
	12: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/bin/vagrant:111:in `<main>'
	11: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
	10: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
	 9: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
	 8: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant.rb:54:in `<top (required)>'
	 7: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 6: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 5: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/protobufs/proto/vagrant_server/server_pb.rb:4:in `<top (required)>'
	 4: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 3: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 2: from /opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/protobuf.rb:49:in `<top (required)>'
	 1: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': dlopen(/opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/2.7/protobuf_c.bundle, 9): no suitable image found.  Did find: (LoadError)
	/opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/2.7/protobuf_c.bundle: cannot load 'protobuf_c.bundle' (load command 0x80000034 is unknown)
	/opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/2.7/protobuf_c.bundle: cannot load 'protobuf_c.bundle' (load command 0x80000034 is unknown) - /opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/2.7/protobuf_c.bundle
	13: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/bin/vagrant:111:in `<main>'
	12: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
	11: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
	10: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
	 9: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant.rb:54:in `<top (required)>'
	 8: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 7: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 6: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/protobufs/proto/vagrant_server/server_pb.rb:4:in `<top (required)>'
	 5: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 4: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 3: from /opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/protobuf.rb:48:in `<top (required)>'
	 2: from /opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/protobuf.rb:51:in `rescue in <top (required)>'
	 1: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- google/protobuf_c (LoadError)
```

**Comment by najdamohamad** [comment]
same error on high sierra , downgraded to 2.3.0 it worked fine

**Comment by jpgelinas** [comment]
Same issue with Vagrant 2.3.4 on Arch Linux. I had downgraded vagrant to keep it working in last months but now ... older vagrant does not work with virtualbox 7 so had to upgrade.

**Comment by glaszig** [comment]
macos 10.14.6.

only gonna upgrade if somebody will [sponsor me a new machine](https://frame.work/products/laptop-12-gen-intel).

```
❯ vagrant --version
Vagrant 2.3.4
❯ vagrant
Traceback (most recent call last):
  2: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/bin/vagrant:111:in `<main>'
  1: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- vagrant (LoadError)
  12: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/bin/vagrant:111:in `<main>'
  11: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
  10: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
   9: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
   8: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant.rb:54:in `<top (required)>'
   7: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
   6: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
   5: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/protobufs/proto/vagrant_server/server_pb.rb:4:in `<top (required)>'
   4: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
   3: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
   2: from /opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/protobuf.rb:49:in `<top (required)>'
   1: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': dlopen(/opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/2.7/protobuf_c.bundle, 9): no suitable image found.  Did find: (LoadError)
  /opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/2.7/protobuf_c.bundle: cannot load 'protobuf_c.bundle' (load command 0x80000034 is unknown)
  /opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/2.7/protobuf_c.bundle: cannot load 'protobuf_c.bundle' (load command 0x80000034 is unknown) - /opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/2.7/protobuf_c.bundle
  13: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/bin/vagrant:111:in `<main>'
  12: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
  11: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
  10: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
   9: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant.rb:54:in `<top (required)>'
   8: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
   7: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
   6: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/protobufs/proto/vagrant_server/server_pb.rb:4:in `<top (required)>'
   5: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
   4: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
   3: from /opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/protobuf.rb:48:in `<top (required)>'
   2: from /opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/protobuf.rb:51:in `rescue in <top (required)>'
   1: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- google/protobuf_c (LoadError)
```

**Comment by peterdd** [comment]
My updated vagrant.rb for 2.3.0 as Hashicorp changed things on 2023-01-23 and still no release compatible with older macs.

```bash
brew uninstall vagrant
brew install vagrant.rb
```

vagrant.rb based on official homebrew vagrant 2.3.0 cask: https://github.com/Homebrew/homebrew-cask/blob/3a4bcb843227eec3b25aad3605bda50f00190230/Casks/vagrant.rb
```ruby
cask "vagrant" do
  version "2.3.0"
  #sha256 "65a5fee8bcfa4bbd3be444efbcd997110a49f5ccc1fffc4457c0110ab51adecb"
  # new since 2023-01-23: https://status.hashicorp.com/incidents/xbbwr755y78b
  sha256 "dfcb08ee37a197c091d0d13f52a4cf55b98d24466063934032530959259fcd89"

  url "https://releases.hashicorp.com/vagrant/#{version}/vagrant_#{version}_darwin_amd64.dmg",
      verified: "hashicorp.com/vagrant/"
  name "Vagrant"
  desc "Development environment"
  homepage "https://www.vagrantup.com/"

  livecheck do
    url "https://github.com/hashicorp/vagrant"
    strategy :git
  end

  pkg "vagrant.pkg"

  uninstall script:  {
              executable: "uninstall.tool",
              input:      ["Yes"],
              sudo:       true,
            },
            pkgutil: "com.vagrant.vagrant"

  zap trash: "~/.vagrant.d"
end
```
