### ISSUE TITLE
protobuf_c.bundle: cannot load 'protobuf_c.bundle' (load command 0x80000034 is unknown) on Mac Os X < 10.15

### ISSUE THREAD

**Issue by markovanderpuil** [hashicorp/vagrant#13131]
---
name: Bug Report protobuf_c.bundle: cannot load 'protobuf_c.bundle' (load command 0x80000034 is unknown) on Mac Os X < 10.15
about: Vagrant releases 2.3.1 to 2.3.4 Have this issue which makes vagrant inoperable on older Mac Os X versions. Especially those developers working on Intel stuff are sometimes stuck on lower Mac Os X versions.
labels: "waiting-intake"
---

### Expected behavior

```
$vagrant status
Current machine states:
default                   poweroff (virtualbox)
```
### Actual behavior

```
$vagrant status
Traceback (most recent call last):
	2: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/bin/vagrant:111:in `<main>'
	1: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- vagrant (LoadError)
	12: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/bin/vagrant:111:in `<main>'
	11: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
	10: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
	 9: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
	 8: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant.rb:54:in `<top (required)>'
	 7: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 6: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 5: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/protobufs/proto/vagrant_server/server_pb.rb:4:in `<top (required)>'
	 4: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 3: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 2: from /opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/protobuf.rb:49:in `<top (required)>'
	 1: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': dlopen(/opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/2.7/protobuf_c.bundle, 9): no suitable image found.  Did find: (LoadError)
	/opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/2.7/protobuf_c.bundle: cannot load 'protobuf_c.bundle' (load command 0x80000034 is unknown)
	/opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/2.7/protobuf_c.bundle: **cannot load 'protobuf_c.bundle' (load command 0x80000034 is unknown)** - /opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/2.7/protobuf_c.bundle
	13: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/bin/vagrant:111:in `<main>'
	12: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:147:in `require'
	11: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `rescue in require'
	10: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:158:in `require'
	 9: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant.rb:54:in `<top (required)>'
	 8: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 7: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 6: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/protobufs/proto/vagrant_server/server_pb.rb:4:in `<top (required)>'
	 5: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 4: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 3: from /opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/protobuf.rb:48:in `<top (required)>'
	 2: from /opt/vagrant/embedded/gems/2.3.4/gems/google-protobuf-3.21.11-x86_64-darwin/lib/google/protobuf.rb:51:in `rescue in <top (required)>'
	 1: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- google/protobuf_c (LoadError)
```
#### Vagrant version

2.3.1 up to and including 2.3.4

#### Host operating system

Mac Os X  Mojave
10.14.6

#### Guest operating system

all

#### Steps to reproduce

1. On any Mac Os X machine with Os X < 10.15
2. install vagrant 2.3.1 - 2.3.4
3. run vagrant

#### Vagrantfile

any

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this issue. This will be resolved in the next release of Vagrant, with the last related modification to resolve this found in #13138.

Cheers!
