### ISSUE TITLE
Vagrant 2.3.5 - `<module:CommandServe>': uninitialized constant VagrantPlugins::CommandServe::Hashicorp (NameError)

### ISSUE THREAD

**Issue by somera** [hashicorp/vagrant#13164]
### Expected behavior

Vagrant 2.3.5 should work after installation. Vagrant 2.3.4 was working fine.

### Actual behavior

```
C:\Users\rafal>vagrant -version
C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/plugins/commands/serve/command.rb:6:in `<module:CommandServe>': uninitialized constant VagrantPlugins::CommandServe::Hashicorp (NameError)

    SDK = Hashicorp::Vagrant::Sdk
          ^^^^^^^^^
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/plugins/commands/serve/command.rb:4:in `<module:VagrantPlugins>'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/plugins/commands/serve/command.rb:3:in `<top (required)>'
        from <internal:C:/Program Files (x86)/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/Program Files (x86)/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/plugins/commands/serve/plugin.rb:12:in `block in <class:Plugin>'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/cli.rb:102:in `block (2 levels) in help'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/registry.rb:49:in `block in each'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/registry.rb:48:in `each'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/registry.rb:48:in `each'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/cli.rb:96:in `block in help'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/3.1.0/optparse.rb:1102:in `initialize'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant.rb:27:in `initialize'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/cli.rb:84:in `new'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/cli.rb:84:in `help'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/cli.rb:53:in `execute'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/lib/vagrant/environment.rb:301:in `cli'
        from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.5/bin/vagrant:248:in `<main>'
```
Currently I'm back to 2.3.4.

#### Vagrant version

2.3.5

#### Host operating system

Windows 11 Pro 22H2 22621.1702

**Comment by Larswa** [comment]
Seeing the same thing here ... same setup and with 2.3.5

**Comment by Dubu-Q** [comment]
same error on windows11

**Comment by neggert** [comment]
Same on an M2 Mac
