### ISSUE TITLE
Not able to resolve dependencies when trying to install vagrant-libvirt

### ISSUE THREAD

**Issue by santosh** [hashicorp/vagrant#13510]
### Debug output

https://gist.github.com/santosh/918b3553021052324b7972c607fdbcce

### Expected behavior

Plugin should have installed without any error.

### Actual behavior

Received this error in red:

Full log has been linked in above sections.

```
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies rake (= 13.1.0) and rake (= 13.2.1)
  Activated rake-13.2.1
  which does not match conflicting dependency (= 13.1.0)

  Conflicting dependency chains:
    rake (= 13.2.1), 13.2.1 activated

  versus:
    rake (= 13.1.0)

  Gems matching rake (= 13.1.0):
    rake-13.1.0
```

#### Vagrant version

Vagrant 2.4.1

#### Host operating system

Arch Linux

#### Guest operating system

debian/bookworm64

#### Steps to reproduce

1. Try to install vagrant libvirt plugin using the command: `vagrant plugin install vagrant-libvirt`
2. Wait until it fails due to dependency resolution.

#### Vagrantfile

```ruby
# Determine host adpater for bridging in BRIDGE mode
def get_bridge_adapter()
  return %x{ip route | grep default | head -n 1 | awk '{ print $5 }'}.chomp
end

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_check_update = false
  config.vm.network :public_network, dev: get_bridge_adapter()

  config.vm.define "triton" do |node|  # the string provided here appears in vagrant status
    node.vm.hostname = "triton"  # This appears in your router's host listing, and in the VM itself

    # Provider-specific configuration so you can fine-tune various
    # backing providers for Vagrant. These expose provider-specific options.
    node.vm.provider "libvirt" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end
  end
end
```

**Comment by jayache80** [comment]
If anyone needs a workaround in the meantime, this unblocked me:

    export VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1
    vagrant plugin install vagrant-libvirt

**Comment by automationGod111** [comment]
> If anyone needs a workaround in the meantime, this unblocked me:
> 
> ```
> export VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1
> vagrant plugin install vagrant-libvirt
> ```


This worked for me!

**Comment by AlexRuiz7** [comment]
Having a similar problem with `logger`

```rb
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies logger (= 1.6.0) and logger (= 1.6.1)
  Activated logger-1.6.1
  which does not match conflicting dependency (= 1.6.0)

  Conflicting dependency chains:
    logger (= 1.6.1), 1.6.1 activated

  versus:
    logger (= 1.6.0)

  Gems matching logger (= 1.6.0):
    logger-1.6.0
```

Using `VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1` raised other problems [[issue](https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1830)]:

```rb
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/3.3.0/rubygems/specification.rb:2245:in `raise_if_conflicts': Unable to activate fog-core-2.6.0, because excon-0.112.0 conflicts with excon (~> 1.0) (Gem::ConflictError)
	from /opt/vagrant/embedded/lib/ruby/3.3.0/rubygems/specification.rb:1383:in `activate'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/bundler.rb:769:in `block in activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/bundler.rb:766:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/bundler.rb:766:in `activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/bundler.rb:606:in `internal_install'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/bundler.rb:358:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/plugin/manager.rb:141:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/plugin/manager.rb:151:in `install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/plugins/commands/plugin/action/install_gem.rb:33:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/action/builder.rb:183:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/action/runner.rb:104:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/util/busy.rb:22:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/action/runner.rb:104:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/plugins/commands/plugin/command/base.rb:17:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/plugins/commands/plugin/command/install.rb:73:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/plugins/commands/plugin/command/install.rb:72:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/plugins/commands/plugin/command/install.rb:72:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/plugins/commands/plugin/command/root.rb:69:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/cli.rb:67:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/lib/vagrant/environment.rb:319:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.2/bin/vagrant:258:in `<main>'

```

**Comment by chrisroberts** [comment]
Closing this as the 2.4.3 release included fixes related to this. 

Cheers!
