### ISSUE TITLE
Issue with Salt Provisioner Bootstrap in Vagrant - HTTP 404 Error

### ISSUE THREAD

**Issue by gstamatov-gl** [hashicorp/vagrant#13522]
I’m encountering an error when using the Salt provisioner in Vagrant. It appears that the bootstrap script fails with a 404 Not Found error, potentially due to a missing or outdated URL for downloading the Salt bootstrap script.

Configuration:

	•	Vagrant Version: 2.4.1
	•	Bootstrap Options Used: -F -c /tmp stable

Error Message:

```
Bootstrapping Salt... (this may take a while)
/opt/vagrant/embedded/lib/ruby/3.1.0/open-uri.rb:364:in `open_http': 404 Not Found (OpenURI::HTTPError)
from /opt/vagrant/embedded/lib/ruby/3.1.0/open-uri.rb:741:in `buffer_open'
from /opt/vagrant/embedded/lib/ruby/3.1.0/open-uri.rb:212:in `block in open_loop'
from /opt/vagrant/embedded/lib/ruby/3.1.0/open-uri.rb:210:in `catch'
from /opt/vagrant/embedded/lib/ruby/3.1.0/open-uri.rb:210:in `open_loop'
from /opt/vagrant/embedded/lib/ruby/3.1.0/open-uri.rb:151:in `open_uri'
from /opt/vagrant/embedded/lib/ruby/3.1.0/open-uri.rb:721:in `open'
from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/provisioners/salt/bootstrap_downloader.rb:57:in `download'
from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/provisioners/salt/bootstrap_downloader.rb:36:in `verify_sha256'
from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/provisioners/salt/bootstrap_downloader.rb:28:in `get_bootstrap_script'

**Comment by gstamatov-gl** [comment]
This merge request fix the problem
https://github.com/hashicorp/vagrant/pull/13517/files

**Comment by ScriptAutomate** [comment]
Creating a backlink so it appears in the PR: https://github.com/hashicorp/vagrant/pull/13517
