### ISSUE TITLE
config.ssh.private_key_path error with passphrase based private keys

### ISSUE THREAD

**Issue by tunix** [hashicorp/vagrant#1591]
Hey There,

I'm manipulating the Vagrantfile for our project to reflect running users' details. My usage scenario is like this:
- User clones github repository
- Initiates `vagrant up`
- Vagrant gets username and private key location and sets `config.ssh.username` and `config.ssh.private_key_path`
- When the user logs in via `vagrant ssh`, he logs in with his own username and SSH keys on the host machine. (so `config.ssh.private_key_path` shows /Users/tunix/.ssh/id_rsa on my host for instance)

My sample Vagrant file is like this:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'etc'

user = Etc.getlogin
rsa_key = File.expand_path('~') + '/.ssh/id_rsa'
dsa_key = File.expand_path('~') + '/.ssh/id_dsa'

if FileTest.exists?(rsa_key)
    key = rsa_key
elsif  FileTest.exists?(dsa_key)
    key = dsa_key
end

Vagrant.configure("2") do |config|
    # Every Vagrant virtual environment requires a box to build off of.
    config.vm.box = "precise64"

    # setting hostname according to username
    config.vm.hostname = user

    # only set username if private ssh key exists..
    if key
        config.ssh.username = user
        config.ssh.private_key_path = key
    end

    ...
```

However I receive the following error during `vagrant up`:

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'precise64'...
[default] Matching MAC address for NAT networking...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Available bridged network interfaces:
1) en0: Wi-Fi (AirPort)
2) p2p0
What interface should the network bridge to? 1
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] Running any VM customizations...
[default] Booting VM...
[default] Waiting for VM to boot. This can take a few minutes.
[default] Forcing shutdown of VM...
[default] Destroying VM and associated drives...
/Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/key_factory.rb:77:in `read': Could not parse PKey: no start line (ArgumentError)
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/key_factory.rb:77:in `load_data_private_key'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/key_factory.rb:42:in `load_private_key'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/authentication/key_manager.rb:214:in `block in load_identities'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/authentication/key_manager.rb:207:in `map'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/authentication/key_manager.rb:207:in `load_identities'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/authentication/key_manager.rb:100:in `each_identity'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/authentication/session.rb:78:in `block in authenticate'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/authentication/session.rb:65:in `each'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh/authentication/session.rb:65:in `authenticate'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.6.6/lib/net/ssh.rb:190:in `start'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/communicators/ssh/communicator.rb:198:in `block (2 levels) in connect'
    from /Applications/Vagrant/embedded/lib/ruby/1.9.1/timeout.rb:68:in `timeout'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/communicators/ssh/communicator.rb:185:in `block in connect'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/retryable.rb:17:in `retryable'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/communicators/ssh/communicator.rb:184:in `connect'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/communicators/ssh/communicator.rb:38:in `ready?'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/boot.rb:26:in `block in wait_for_boot'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/boot.rb:25:in `times'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/boot.rb:25:in `wait_for_boot'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/boot.rb:17:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/customize.rb:31:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/sane_defaults.rb:45:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/set_hostname.rb:16:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/forward_ports.rb:31:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/network.rb:105:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/clear_network_interfaces.rb:26:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/share_folders.rb:20:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/clear_shared_folders.rb:12:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/prepare_nfs_settings.rb:11:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/nfs.rb:28:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/prune_nfs_exports.rb:15:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:106:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/env_set.rb:19:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/provision.rb:45:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:13:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/set_name.rb:35:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/call.rb:51:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/call.rb:51:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/call.rb:51:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/call.rb:57:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builder.rb:109:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/runner.rb:61:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/machine.rb:129:in `action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/commands/up/command.rb:37:in `block in execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plugin/v2/command.rb:182:in `block in with_target_vms'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plugin/v2/command.rb:180:in `each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/plugin/v2/command.rb:180:in `with_target_vms'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/plugins/commands/up/command.rb:32:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/cli.rb:46:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/environment.rb:408:in `cli'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/bin/vagrant:75:in `<top (required)>'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `load'
    from /Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
```

I believe this occurs because my SSH private key is passphrase based?

**Comment by pjcvijay** [comment]
Replaced "#{vagrant_home}/insecure_private_key" with below line in  /puphpet/vagrant/Vagrantfile-local file:
"#{dir}/puphpet/files/dot/ssh/insecure_private_key"

Here is the full code:

if File.file?(customKey)
    config.ssh.private_key_path = [
      customKey,
      "#{dir}/puphpet/files/dot/ssh/insecure_private_key"
    ]

This solution worked for me.
