### ISSUE TITLE
VAGRANT_HOME special characters don't work

### ISSUE THREAD

**Issue by lfbittencourt** [hashicorp/vagrant#2113]
After some hours, I figured out that Vagrant can't unpackage boxes to VAGRANT_HOME when Windows (7) username has special characters like "é". Debugging, I've seen that if username is Pelé, for example, Vagrant attempts move the file to something like C:/Users/Pel\0xE9/.vagrant.d/tmp, causing a "failed writing body" error.

I know that a username like that is weird and I still can set another value to VAGRANT_HOME, but seems like a little bug to me.

**Comment by byronkingz** [comment]
+1

**Comment by aovchinn** [comment]
+1

```
C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/plugins/providers/virtualbox/driver/version_5_0.rb:582:in `read_state': invalid byte sequence in UTF-8 (ArgumentError)
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/plugins/providers/virtualbox/provider.rb:101:in `state'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/machine.rb:514:in `state'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/machine.rb:145:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/vagrantfile.rb:79:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/vagrantfile.rb:79:in `machine'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/environment.rb:700:in `machine'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/plugin/v2/command.rb:213:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/plugin/v2/command.rb:212:in `map'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/plugin/v2/command.rb:212:in `with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/plugins/commands/reload/command.rb:37:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/cli.rb:54:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/environment.rb:275:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/bin/vagrant:151:in `<main>'
```

**Comment by mb-shirtigo** [comment]
For me the following worked:

1.) Go to c:\Users
2.) Create a symlink/junction from c:\Users\<special_character> --> c:\Users\<newfolder>
3.) set VAGRANT_HOME "C:/users/<newfolder>"
4.) restart windows
5.) start cmd and go to the c:\Users\<newfolder>
6.) execute "vagrant up"
