### ISSUE TITLE
Corrupt plugins.json crashes Vagrant

### ISSUE THREAD

**Issue by silkyboy** [hashicorp/vagrant#2603]
When i try to install vagrant i have problem like this:

```
C:/HashiCorp/Vagrant/embedded/lib/ruby/1.9.1/json/common.rb:148:in `parse': 746: unexpected token at '' (JSON::ParserError)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/1.9.1/json/common.rb:148:in `parse'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:740:in `load_plugins'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/lib/vagrant/environment.rb:132:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/bin/vagrant:74:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.3.4/bin/vagrant:74:in `<top (required)>'
        from C:/HashiCorp/Vagrant/bin//../embedded/../embedded/gems/bin/vagrant:23:in `load'
        from C:/HashiCorp/Vagrant/bin//../embedded/../embedded/gems/bin/vagrant:23:in `<main>'
```

I tried reinstal vBox, reinstal Vagrant, change version of vagrant and nothing helps. IM working on Windows 7 64bit. Please help

**Comment by Phil-Mwago** [comment]
No one says where that folder is
