### ISSUE TITLE
Vagrant 1.5.1 errors with opscode_ubuntu-12.04_chef-provisionerless.box

### ISSUE THREAD

**Issue by sbarber** [hashicorp/vagrant#3250]
Not sure where to put this. It's an issue with one of the current bento baseboxes. This basebox is also used by test-kitchen, where I first encountered the error. This box works just fine with Vagrant 1.4.X 

```
~ » vagrant box add https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box --name opscode-ubuntu-12.04
==> box: Adding box 'opscode-ubuntu-12.04' (v0) for provider:
    box: Downloading: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
/Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/version.rb:191:in `initialize': Malformed version number string virtualbox (ArgumentError)
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:273:in `new'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:273:in `block (2 levels) in find'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:270:in `map'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:270:in `block in find'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:416:in `block in with_collection_lock'
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:415:in `with_collection_lock'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:263:in `find'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:81:in `block in add'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:148:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:148:in `block (3 levels) in add'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:429:in `with_temp_dir'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:130:in `block (2 levels) in add'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:429:in `with_temp_dir'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:111:in `block in add'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:416:in `block in with_collection_lock'
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:415:in `with_collection_lock'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:100:in `add'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/builtin/box_add.rb:332:in `box_add'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/builtin/box_add.rb:125:in `add_direct'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/builtin/box_add.rb:105:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/builder.rb:116:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/runner.rb:69:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/runner.rb:69:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/box/command/add.rb:77:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/box/command/root.rb:61:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/cli.rb:42:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/environment.rb:248:in `cli'
    from /Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.5.1/bin/vagrant:158:in `<main>'
```

Other baseboxes don't seem to have this issue.

**Comment by timmc** [comment]
This also fixed my "SSL read: error:00000000:lib(0):func(0):reason(0), errno 104" error when downloading that image, weirdly enough.
