### ISSUE TITLE
vagrant share does not work

### ISSUE THREAD

**Issue by pdaether** [hashicorp/vagrant#3275]
If i try the new `vagrant share` feature i always get the following error:

```
The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.
```

On the Website https://vagrantcloud.com/shares the link appears, but it does not work.

Here is the debug output:

```
==> default: Checking authentication and authorization...
 INFO interface: output: Creating Vagrant Share session...
 INFO interface: output: ==> default: Creating Vagrant Share session...
==> default: Creating Vagrant Share session...
 INFO api: /api/v1/shares
DEBUG api: API payload: {"share":{"http_port":8080,"https_port":null,"ports":[8080,2222]}}
DEBUG api: Response: {"expired":false,"has_private_key":false,"name":"shining-horse-4184","http_port":8080,"https_port":null,"ssh_port":null,"ssh_username":null,"ports":[8080,2222],"expired_at":null,"created_at":"2014-03-20T07:41:04.781Z","private_key_password":true,"use_key_once":true}
 INFO interface: detail: Share will be at: shining-horse-4184
 INFO interface: detail:     default: Share will be at: shining-horse-4184
    default: Share will be at: shining-horse-4184
 INFO helper: Executing proxy: ["-share", "-name", "shining-horse-4184", "-target", "127.0.0.1", "-server", "register.vagrantshare.com:8000", "-port", "8080", "-port", "8080", "-port", "2222"]
 INFO subprocess: Starting process: ["/Users/username/.vagrant.d/gems/gems/vagrant-share-1.0.1/localbin/proxy_darwin_amd64", "-share", "-name", "shining-horse-4184", "-target", "127.0.0.1", "-server", "register.vagrantshare.com:8000", "-port", "8080", "-port", "8080", "-port", "2222"]
DEBUG subprocess: Command not in installer, not touching env vars.
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: proxy:1395301264,log,[INFO] Restricting ports to: [8080 8080 2222]
proxy:1395301264,log,[DEBUG] proxy: Connecting to mux server at register.vagrantshare.com:8000
DEBUG helper: Proxy message: ["log", "[INFO] Restricting ports to: [8080 8080 2222]"]
DEBUG helper: Proxy message: ["log", "[DEBUG] proxy: Connecting to mux server at register.vagrantshare.com:8000"]
DEBUG subprocess: stdout: proxy:1395301340,log,[ERR] proxy: Failed to start sharing: Failed to connect to mux server: dial tcp 54.236.96.102:8000: operation timed out
DEBUG helper: Proxy message: ["log", "[ERR] proxy: Failed to start sharing: Failed to connect to mux server: dial tcp 54.236.96.102:8000: operation timed out"]
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31924
DEBUG subprocess: Exit status: 1
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x0000010235c890>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::Share::Errors::ProxyExit: The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.>
ERROR vagrant: The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.
ERROR vagrant: /Users/username/.vagrant.d/gems/gems/vagrant-share-1.0.1/lib/vagrant-share/activate.rb:1323:in `block in execute'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/plugin/v2/command.rb:200:in `block in with_target_vms'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/plugin/v2/command.rb:194:in `each'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/plugin/v2/command.rb:194:in `with_target_vms'
/Users/username/.vagrant.d/gems/gems/vagrant-share-1.0.1/lib/vagrant-share/activate.rb:1120:in `execute'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/cli.rb:42:in `execute'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.5.0/lib/vagrant/environment.rb:244:in `cli'
/Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.5.0/bin/vagrant:147:in `<main>'
 INFO interface: error: The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.
The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.
 INFO interface: Machine: error-exit ["VagrantPlugins::Share::Errors::ProxyExit", "The sharing proxy exited with a non-zero exit status! This represents\nan erroneous exit and likely a bug. Please report this issue."]
```

Telnet to register.vagrantshare.com:8000 doesn't work either.

By the way, the beta of vagrantcloud.com looks very promising! Great work!

**Comment by walkingtroughunknownlands** [comment]
So this is official that vagrant WON'T share when 8000 and 8001 are blocked? I have same issue it seems. I have reported it GH-7768
