### ISSUE TITLE
Cannot add a box from local filesystem if path contains spaces

### ISSUE THREAD

**Issue by ajbonner** [hashicorp/vagrant#3276]
This is similar (although doesn't appear to be the same) as #3132 and my issue also reported by @beelbrecht in that issue. Personally I am encountering this problem on OSX 10.9.2.

``` bash
➜  A Dir  pwd
/Users/aaron/A Dir
➜  A Dir  vagrant --version
Vagrant 1.5.1
➜  A Dir  vagrant box add --name my_test_box vmware_fusion.box
/Applications/Vagrant/embedded/lib/ruby/2.0.0/uri/common.rb:176:in `split': bad URI(is not URI?): file:///Users/aaron/A Dir/vmware_fusion.box (URI::InvalidURIError)
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/uri/common.rb:211:in `parse'
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/uri/common.rb:747:in `parse'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/builtin/box_add.rb:448:in `metadata_url?'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/builtin/box_add.rb:76:in `block in call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/builtin/box_add.rb:74:in `map'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/builtin/box_add.rb:74:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/builder.rb:116:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/runner.rb:69:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/action/runner.rb:69:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/box/command/add.rb:77:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/box/command/root.rb:61:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/cli.rb:42:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/environment.rb:248:in `cli'
    from /Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.5.1/bin/vagrant:158:in `<main>'
```

However when doing it from a directory not containing spaces

``` bash
➜  ~  pwd
/Users/aaron
➜  ~  vagrant box add --name my_test_box vmware_fusion.box
==> box: Adding box 'my_test_box' (v0) for provider:
    box: Downloading: file:///Users/aaron/vmware_fusion.box
==> box: Successfully added box 'my_test_box' (v0) for 'vmware_fusion'!
```

**Comment by gm90** [comment]
Replacing spaces with %20 worked for me. May be of use for anybody else that stumbles across this page.
