### ISSUE TITLE
[1.5.2] undefined method `to_sym' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/vagrant#3381]
I have some error trying to run my previous 1.5.1 vagrant box.

```
Bringing machine 'master' up with 'virtualbox' provider...
==> master: Box 'lmayorga1980/centos6-64' could not be found. Attempting to find and install...
    master: Box Provider: virtualbox
    master: Box Version: >= 0
==> master: Loading metadata for box 'lmayorga1980/centos6-64'
    master: URL: https://vagrantcloud.com/lmayorga1980/centos6-64
==> master: Adding box 'lmayorga1980/centos6-64' (v0.1.0) for provider: virtualbox
    master: Downloading: https://vagrantcloud.com/lmayorga1980/centos6-64/version/1/provider/virtualbox.box
==> master: Successfully added box 'lmayorga1980/centos6-64' (v0.1.0) for 'virtualbox'!
/Applications/Vagrant/embedded/gems/gems/vagrant-1.5.2/plugins/kernel_v2/config/vm.rb:581:in `block in validate': undefined method `to_sym' for nil:NilClass (NoMethodError)
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.2/plugins/kernel_v2/config/vm.rb:552:in `each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.2/plugins/kernel_v2/config/vm.rb:552:in `validate'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.2/lib/vagrant/config/v2/root.rb:68:in `block in validate'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.2/lib/vagrant/config/v2/root.rb:64:in `each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.2/lib/vagrant/config/v2/root.rb:64:in `validate'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.2/lib/vagrant/action/builtin/config_validate.rb:15:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.2/lib/vagrant/action/builtin/call.rb:57:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.2/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.2/lib/vagrant/action/builder.rb:116:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.2/lib/vagrant/action/runner.rb:69:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.2/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.2/lib/vagrant/action/runner.rb:69:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.2/lib/vagrant/machine.rb:157:in `action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.5.2/lib/vagrant/batch_action.rb:72:in `block (2 levels) in run'
    from /Users/lmo0/.vagrant.d/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
    from /Users/lmo0/.vagrant.d/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

**Comment by agustisanchez** [comment]
Bug is still in Vagrant v.1.7.4 .
