### ISSUE TITLE
No gems found matching "vagrant-share"

### ISSUE THREAD

**Issue by jperry** [hashicorp/vagrant#3764]
Occasionally getting this network failure when installing plugins.  We only started seeing this after upgrading to 1.6.0 x64.  We are running on ubuntu 12.04.

```
[16:42:26][Execute vagrant:plugins] Bundler, the underlying system Vagrant uses to install plugins,
[16:42:26][Execute vagrant:plugins] reported an error. The error is shown below. These errors are usually
[16:42:26][Execute vagrant:plugins] caused by misconfigured plugin installations or transient network
[16:42:26][Execute vagrant:plugins] issues. The error from Bundler is:
[16:42:26][Execute vagrant:plugins] 
[16:42:26][Execute vagrant:plugins] Net::HTTPNotFound: No gems found matching "vagrant-share" "1.0.0" nil
[16:42:26][Execute vagrant:plugins] 
[16:42:26]
[Execute vagrant:plugins] RuntimeError: Command failed with status (1): [vagrant plugin install --plugin-source htt...]

Stacktrace:
/home/build/.rvm/gems/ruby-2.1.0@global/gems/rake-10.1.1/lib/rake/file_utils.rb:54:in `block in create_shell_runner'
/home/build/.rvm/gems/ruby-2.1.0@global/gems/rake-10.1.1/lib/rake/file_utils.rb:45:in `call'
/home/build/.rvm/gems/ruby-2.1.0@global/gems/rake-10.1.1/lib/rake/file_utils.rb:45:in `sh'
/home/build/.rvm/gems/ruby-2.1.0@global/gems/rake-10.1.1/lib/rake/file_utils_ext.rb:37:in `sh'
tasks/vagrant.rake:71:in `block (2 levels) in <top (required)>'
```

**Comment by snafoo972** [comment]
I also received this error the first time I tried to install.  Second time it worked fine.  Maybe try in fresh vm to repro.  I dunno.

**Comment by dalvaren** [comment]
Just try again worked for me... thanks, @snafoo972

**Comment by tknerr** [comment]
See also #6097
