### ISSUE TITLE
Vagrant package command error. Vagrant 1.6.2. OS X 10.7.5

### ISSUE THREAD

**Issue by nicktgr15** [hashicorp/vagrant#3827]
Hi,

I'm trying to use the package command

```
vagrant package --base packagename 
```

and I get the following error. I'm using Vagrant 1.6.2 on OS X 10.7.5.

```
/Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/machine.rb:251:in `id=': undefined method `join' for nil:NilClass (NoMethodError)
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/machine.rb:432:in `state'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/providers/virtualbox/action/created.rb:11:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/action/builder.rb:116:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/action/runner.rb:66:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/action/runner.rb:66:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/action/builtin/call.rb:43:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/action/builder.rb:116:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/action/runner.rb:66:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/action/runner.rb:66:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/machine.rb:196:in `action_raw'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/machine.rb:173:in `block in action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/environment.rb:434:in `lock'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/machine.rb:161:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/machine.rb:161:in `action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/package/command.rb:83:in `package_vm'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/package/command.rb:66:in `package_base'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/package/command.rb:42:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/cli.rb:42:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/environment.rb:252:in `cli'
    from /Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.6.2/bin/vagrant:166:in `<main>'
```

Thanks

**Comment by ahrenstein** [comment]
I'm seeing this issue on OS X 10.10.1 with Vagrant 1.7.2

I'm using the command: vagrant package --base dev-box --output developer-box
where dev-box is the name I get from "VBoxManage list vms" and developer-box is a different name as per gimox's instructions above.
