### ISSUE TITLE
'Waiting for machine to boot' hangs infinitely with docker it seems

### ISSUE THREAD

**Issue by thasmo** [hashicorp/vagrant#3951]
Here's the `vagrant up` output:

```
vagrant up --provider="docker"
Bringing machine 'web' up with 'docker' provider...
==> web: Docker host is required. One will be created if necessary...
    web: Docker host VM is already ready.
==> web: Syncing folders to the host VM...
    web: Mounting shared folders...
    web: /var/lib/docker/docker_1401651400_54593 => S:/Project/vagrant.box.docker
    web: /mnt/docker_build_603722914fecf466e785c9616bf1119c => S:/Project/vagrant.box.docker
==> web: Building the container from a Dockerfile...
    web: Image: aea2aa043cab
==> web: Warning: When using a remote Docker host, forwarded ports will NOT be
==> web: immediately available on your machine. They will still be forwarded on
==> web: the remote machine, however, so if you have a way to access the remote
==> web: machine, then you should be able to access those ports there. This is
==> web: not an error, it is only an informational message.
==> web: Creating the container...
    web:   Name: vagrantboxdocker_web_1401652661
    web:  Image: aea2aa043cab
    web: Volume: /var/lib/docker/docker_1401651400_54593:/vagrant
    web:   Port: 2222:22
    web:
    web: Container created: 1489f2bc61cca231
==> web: Starting container...
==> web: Waiting for machine to boot. This may take a few minutes...
```

Although it seems the docker container is already up and running after some minutes, Vagrant never reports the machine has booted.

I'm using a custom Vagrantfile for the Docker host VM:

```
Vagrant.configure(2) do |config|
  config.vm.box = 'phusion/ubuntu-14.04-amd64'

  config.vm.provider 'virtualbox' do |provider|
    provider.gui = false
    provider.name = 'DOCKER'
    provider.customize ['modifyvm', :id, '--cpus', 2]
    provider.customize ['modifyvm', :id, '--acpi', 'on']
    provider.customize ['modifyvm', :id, '--memory', 4096]
    provider.customize ['modifyvm', :id, '--cpuexecutioncap', '100']
    provider.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    provider.customize ['modifyvm', :id, '--natdnsproxy1', 'on']
  end

  ['vmware_fusion', 'vmware_workstation'].each do |vmware|
    config.vm.provider vmware do |provider|
      provider.gui = false
      provider.vmx['displayName'] = 'DOCKER'
      provider.vmx['numvcpus'] = 2
      provider.vmx['memsize'] = 4096
    end
  end

  if Dir.glob("#{File.dirname(__FILE__)}/.vagrant/machines/default/*/id").empty?
    command = 'wget -q -O - https://get.docker.io/gpg | apt-key add -;' \
      'echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list;' \
      'apt-get update -qq; apt-get install -q -y --force-yes lxc-docker; '

    command << 'usermod -a -G docker vagrant; '
    config.vm.provision :shell, :inline => command
  end
end
```

I've tried to create a Docker container twice, and both times the container needs some time to get built and created/booted, but Vagrant didn't confirm it in the end.

**Comment by andreychernih** [comment]
Having this as well with `phusion/baseimage` and `has_ssh = true`. It reproduces intermittently - sometimes works, sometimes hangs, but the container is always up and running so I just do `Ctrl-C` and run `vagrant provision` manually.

**Comment by winglian** [comment]
I'm still seeing this issue intermittently. Also sometimes seeing this error too.

```
==> varnish: Starting container...
==> varnish: Waiting for machine to boot. This may take a few minutes...
/opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/packet_stream.rb:204:in `poll_next_packet': padding error, need 2852117049 block 16 (Net::SSH::Exception)
	from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/packet_stream.rb:90:in `next_packet'
	from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:178:in `block in poll_message'
	from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:173:in `loop'
	from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:173:in `poll_message'
	from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:460:in `dispatch_incoming_packets'
	from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:221:in `preprocess'
	from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
	from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
	from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
	from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
	from /opt/vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:269:in `wait'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/communicators/ssh/communicator.rb:576:in `shell_execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/communicators/ssh/communicator.rb:215:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/communicators/ssh/communicator.rb:312:in `connect'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/communicators/ssh/communicator.rb:209:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/communicators/ssh/communicator.rb:135:in `ready?'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/docker/provider.rb:153:in `state'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/docker/provider.rb:134:in `ssh_info'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:405:in `ssh_info'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/docker/communicator.rb:135:in `container_ssh_command'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/docker/communicator.rb:28:in `ready?'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/plugin/v2/communicator.rb:61:in `block in wait_for_ready'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/plugin/v2/communicator.rb:59:in `wait_for_ready'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'
```

**Comment by jonasdagefoerde** [comment]
Same issue with my setup:

* vagrant 1.7.2 on Mac OS
* VirtualBox 4.3.2

Vagrant always stops at:
```
Waiting for machine to boot. This may take a few minutes...
````
...but is working properly. The only problem: I need to start my containers in sequence. The second container never gets set up and started wenn running `<vagrant up --no-parallel>`.

I use the `<coreos-alpha>` vagrant box and `<phusion/baseimage:0.9.13>` docker image with `<has_ssh = true>`.

DockerHostVagrantFile
```
# -*- mode: ruby -*-
require 'fileutils'
Vagrant.require_version ">= 1.6.3"
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|  

  config.vm.box = "coreos-%s" % $update_channel
  config.vm.box_url = "http://%s.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json" % $update_channel

  config.vm.provision "docker" 
  config.vm.provision "shell", inline:
    "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"
 
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port",
    guest: 8080, host: 8080
 
  config.vm.provider :virtualbox do |vb|
    vb.name = "core-01"
  end

  config.vm.define "core-01" do |config|
    config.vm.hostname = "core-01-host"

    ip = "172.17.8.100"
    config.vm.network :private_network, ip: ip

    # Enable NFS for sharing the project home folder on the host machine into the coreos-vagrant guest VM
    config.vm.synced_folder ".", "/app", id: "core", :nfs => true, :mount_options => ['nolock,vers=3,udp']
  end
end
```

Dockerfile
```
FROM phusion/baseimage:0.9.13

# update linux libs
RUN apt-get update

RUN rm -f /etc/service/sshd/down
RUN /etc/my_init.d/00_regen_ssh_host_keys.sh

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

COPY ./busy.sh /app/busy.sh
 
CMD ["bash"]
```

**Comment by JonathanRRogers** [comment]
I am also seeing intermittent hangs while "waiting for machine to boot". I'm using Vagrant 1.7.2 and a custom VirtualBox image with sshd enabled on OSX. As andreychernih suggested above, I can simply kill the hanging "vagrant up" command and immediately run "vagrant provision" and everything's fine.

**Comment by tzolov** [comment]
+1 for reopening and fixing this

**Comment by mlong168** [comment]
Has this issue been fixed? I experience this with version 1.7.4 and the "has_ssh - true" option is set.

**Comment by gdhbashton** [comment]
+1

**Comment by thanandorn** [comment]
:+1: would love to see this one gone

**Comment by alex-moreno** [comment]
+1

**Comment by jametsi** [comment]
This problem has been bugging me for two years already. I'm using a custom virtualbox dockerhost on osx (but this also happens on windows), my vagrant version is 1.8.1. 

Very often the vagrant up gets stuck on "Waiting for machine to boot" despite vagrant ssh working well. I can also run vagrant provision successfully immediately after I have killed the vagrant up with ctrl-c.

Here's debug output from a successful vagrant up: https://gist.github.com/jametsi/d1216bc95f57dc6ac317

And here's the output from a failed attempt: https://gist.github.com/jametsi/baa4de946bed12fdbaa9

**Comment by nirvana-msu** [comment]
+!

**Comment by agusti-t** [comment]
+1. Issue still there.
