### ISSUE TITLE
VMware VM stuck on "Verifying vmnet devices are healthy..."

### ISSUE THREAD

**Issue by jtreminio** [hashicorp/vagrant#4050]
Here's the dump:

```
==> default: Verifying vmnet devices are healthy...
 INFO subprocess: Starting process: ["/Users/jtreminio/.vagrant.d/gems/gems/vagrant-vmware-fusion-2.4.1/bin/vagrant_vmware_desktop_sudo_helper_wrapper_darwin_amd64", "verify-vmnet", "/var/folders/b_/hxscxnfn35z7cbmn6frmp2x80000gn/T/vagrant-sudo-helper20140617-60422-sy086z"]
DEBUG subprocess: Command not in installer, not touching env vars.
 INFO subprocess: Command is setuid/setgid, clearing DYLD_LIBRARY_PATH
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr:  INFO global: Vagrant version: 1.6.2
 INFO global: Ruby version: 2.0.0
 INFO global: RubyGems version: 2.0.14
 INFO global: VAGRANT_EXECUTABLE="/Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.6.2/bin/vagrant"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/Applications/Vagrant/bin/../embedded"
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_DETECTED_OS="Darwin"
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_INTERNAL_BUNDLERIZED="1"
 INFO global: VAGRANT_LOG="debug"
DEBUG subprocess: stderr:  INFO global: VAGRANT_DEFAULT_PROVIDER="vmware_fusion"
 INFO global: Plugins:
DEBUG subprocess: stderr:  INFO global:   - builder = 3.2.2
 INFO global:   - bundler = 1.6.2
 INFO global:   - excon = 0.37.0
 INFO global:   - multipart-post = 2.0.0
 INFO global:   - faraday = 0.9.0
DEBUG subprocess: stderr:  INFO global:   - formatador = 0.2.5
 INFO global:   - mime-types = 2.3
 INFO global:   - net-ssh = 2.9.1
 INFO global:   - net-scp = 1.1.2
 INFO global:   - fog-core = 1.22.0
 INFO global:   - multi_json = 1.10.1
 INFO global:   - fog-json = 1.0.0
 INFO global:   - fog-brightbox = 0.0.2
DEBUG subprocess: stderr:  INFO global:   - ipaddress = 0.8.0
 INFO global:   - mini_portile = 0.6.0
 INFO global:   - nokogiri = 1.6.2.1
 INFO global:   - fog = 1.22.1
 INFO global:   - json = 1.8.1
 INFO global:   - log4r = 1.1.10
 INFO global:   - rest-client = 1.6.7
 INFO global:   - vagrant-digitalocean = 0.5.5
DEBUG subprocess: stderr:  INFO global:   - vagrant-login = 1.0.1
 INFO global:   - vagrant-parallels = 1.1.0
 INFO global:   - vagrant-rackspace = 0.1.7
 INFO global:   - vagrant-share = 1.1.0
 INFO global:   - vagrant-vmware-fusion = 2.4.1
 INFO global:   - vagrant-vmware-workstation = 2.4.1
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/box/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: box command
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/destroy/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: destroy command
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/global-status/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: global-status command
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/halt/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: halt command
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/help/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: help command
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/init/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: init command
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/list-commands/plugin.rb
 INFO manager: Registered plugin: list-commands command
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/package/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: package command
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/plugin/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: plugin command
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/provision/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: provision command
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/rdp/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: rdp command
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/reload/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: reload command
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/resume/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: resume command
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/ssh/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: ssh command
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/ssh_config/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: ssh-config command
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/status/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: status command
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/suspend/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: suspend command
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/up/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: up command
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/commands/version/plugin.rb
 INFO manager: Registered plugin: version command
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/communicators/ssh/plugin.rb
 INFO manager: Registered plugin: ssh communicator
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/communicators/winrm/plugin.rb
 INFO manager: Registered plugin: winrm communicator
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/arch/plugin.rb
 INFO manager: Registered plugin: Arch guest
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/coreos/plugin.rb
 INFO manager: Registered plugin: CoreOS guest
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/darwin/plugin.rb
 INFO manager: Registered plugin: Darwin guest
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/debian/plugin.rb
 INFO manager: Registered plugin: Debian guest
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/esxi/plugin.rb
 INFO manager: Registered plugin: ESXi guest.
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/fedora/plugin.rb
 INFO manager: Registered plugin: Fedora guest
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/freebsd/plugin.rb
 INFO manager: Registered plugin: FreeBSD guest
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/funtoo/plugin.rb
 INFO manager: Registered plugin: Funtoo guest
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/gentoo/plugin.rb
 INFO manager: Registered plugin: Gentoo guest
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/linux/plugin.rb
 INFO manager: Registered plugin: Linux guest.
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/mint/plugin.rb
 INFO manager: Registered plugin: Mint guest
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/netbsd/plugin.rb
 INFO manager: Registered plugin: NetBSD guest
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/omnios/plugin.rb
 INFO manager: Registered plugin: OmniOS guest.
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/openbsd/plugin.rb
 INFO manager: Registered plugin: OpenBSD guest
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/pld/plugin.rb
 INFO manager: Registered plugin: PLD Linux guest
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/redhat/plugin.rb
 INFO manager: Registered plugin: RedHat guest
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/smartos/plugin.rb
 INFO manager: Registered plugin: SmartOS guest.
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/solaris/plugin.rb
 INFO manager: Registered plugin: Solaris guest.
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/solaris11/plugin.rb
 INFO manager: Registered plugin: Solaris 11 guest.
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/suse/plugin.rb
 INFO manager: Registered plugin: SUSE guest
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/tinycore/plugin.rb
 INFO manager: Registered plugin: TinyCore Linux guest.
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/ubuntu/plugin.rb
 INFO manager: Registered plugin: Ubuntu guest
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/guests/windows/plugin.rb
 INFO manager: Registered plugin: Windows guest.
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/hosts/arch/plugin.rb
 INFO manager: Registered plugin: Arch host
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/hosts/bsd/plugin.rb
 INFO manager: Registered plugin: BSD host
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/hosts/darwin/plugin.rb
 INFO manager: Registered plugin: Mac OS X host
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/hosts/freebsd/plugin.rb
 INFO manager: Registered plugin: FreeBSD host
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/hosts/gentoo/plugin.rb
 INFO manager: Registered plugin: Gentoo host
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/hosts/linux/plugin.rb
 INFO manager: Registered plugin: Linux host
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/hosts/null/plugin.rb
 INFO manager: Registered plugin: null host
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/hosts/opensuse/plugin.rb
 INFO manager: Registered plugin: OpenSUSE host
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/hosts/redhat/plugin.rb
 INFO manager: Registered plugin: Red Hat host
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/hosts/slackware/plugin.rb
 INFO manager: Registered plugin: Slackware host
DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/hosts/windows/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: Windows host
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/kernel_v1/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: kernel
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/kernel_v2/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: kernel
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/providers/docker/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: docker-provider
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/providers/hyperv/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: Hyper-V provider
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/providers/virtualbox/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: VirtualBox provider
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/provisioners/ansible/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: ansible
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/provisioners/cfengine/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: CFEngine Provisioner
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/provisioners/chef/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: chef
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/provisioners/docker/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: docker
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/provisioners/file/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: file
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/provisioners/puppet/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: puppet
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/provisioners/salt/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: salt
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/provisioners/shell/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: shell
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/synced_folders/nfs/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: NFS synced folders
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/synced_folders/rsync/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: RSync synced folders
DEBUG subprocess: stderr: DEBUG global: Loading core plugin: /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/synced_folders/smb/plugin.rb
DEBUG subprocess: stderr:  INFO manager: Registered plugin: SMB synced folders
DEBUG subprocess: stderr:  INFO global: Loading plugins!
DEBUG subprocess: stderr:  INFO manager: Registered plugin: vagrant-login
DEBUG subprocess: stderr:  INFO manager: Registered plugin: vagrant-share
DEBUG subprocess: stderr:  INFO manager: Registered plugin: DigitalOcean
DEBUG subprocess: stderr:  INFO manager: Registered plugin: RackSpace Cloud
DEBUG subprocess: stderr:  INFO manager: Registered plugin: VMware Workstation Provider
DEBUG subprocess: stderr:  INFO manager: Registered plugin: vagrant-parallels
DEBUG subprocess: stderr:  INFO manager: Registered plugin: VMware Fusion Provider
DEBUG subprocess: stderr:  INFO vmware_driver: VMX file:
 INFO vmware_driver: Looking for VMware Fusion: /Applications/VMware Fusion.app
DEBUG subprocess: stderr:  INFO vmware_driver: VMware Fusion path: #<Pathname:/Applications/VMware Fusion.app>
DEBUG subprocess: stderr: DEBUG vmware_driver: service starter path: /Applications/VMware Fusion.app/Contents/Library/Open VMware Fusion Services
DEBUG vmware_driver: vmnet-cli path: /Applications/VMware Fusion.app/Contents/Library/vmnet-cli
DEBUG subprocess: stderr:  INFO vmware:sudo_helper: Calling command: verify-vmnet
 INFO vmware_driver: Starting services starter and waiting for them to start...
DEBUG subprocess: stderr:  INFO vmware_driver: Killing vmnet-natd if it is alive...
DEBUG subprocess: stderr:  INFO subprocess: Starting process: ["/usr/bin/pkill", "vmnet-natd"]
DEBUG subprocess: stderr: DEBUG subprocess: Command not in installer, not touching env vars.
DEBUG subprocess: stderr: DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 1
DEBUG subprocess: stderr:  INFO subprocess: Starting process: ["/Applications/VMware Fusion.app/Contents/Library/vmnet-cli", "--start"]
DEBUG subprocess: stderr: DEBUG subprocess: Command not in installer, not touching env vars.
DEBUG subprocess: stderr: DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: DEBUG subprocess: stdout: Enabled hostonly virtual adapter on vmnet1
Started DHCP service on vmnet1
Enabled hostonly virtual adapter on vmnet2
Started DHCP service on vmnet2
Enabled hostonly virtual adapter on vmnet3
Started DHCP service on vmnet3
Enabled hostonly virtual adapter on vmnet4
Started DHCP service on vmnet4
Started NAT service on vmnet8
Enabled hostonly virtual adapter on vmnet8
Started DHCP service on vmnet8
Started all configured services on all networks
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999
DEBUG subprocess: Exit status: 0
DEBUG subprocess: stderr:  INFO subprocess: Starting process: ["/Applications/VMware Fusion.app/Contents/Library/vmnet-cli", "--status"]
DEBUG subprocess: stderr: DEBUG subprocess: Command not in installer, not touching env vars.
DEBUG subprocess: stderr: DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: DEBUG subprocess: stdout: DHCP service on vmnet1 is running
Hostonly virtual adapter on vmnet1 is enabled
DHCP service on vmnet2 is running
Hostonly virtual adapter on vmnet2 is enabled
DHCP service on vmnet3 is running
Hostonly virtual adapter on vmnet3 is enabled
DHCP service on vmnet4 is running
Hostonly virtual adapter on vmnet4 is enabled
DHCP service on vmnet8 is running
NAT service on vmnet8 is running
Hostonly virtual adapter on vmnet8 is enabled
All the services configured on all the networks are running
DEBUG subprocess: stderr: DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: stderr: DEBUG subprocess: Exit status: 0
DEBUG subprocess: stderr:  INFO vmware_driver: vmnet devices appear healthy!
DEBUG vmware_driver: Beginning to verify routing of devices...
 INFO vmware_driver: Starting services starter and waiting for them to start...
DEBUG subprocess: stderr:  INFO vmware_driver: Killing vmnet-natd if it is alive...
DEBUG subprocess: stderr:  INFO subprocess: Starting process: ["/usr/bin/pkill", "vmnet-natd"]
DEBUG subprocess: stderr: DEBUG subprocess: Command not in installer, not touching env vars.
DEBUG subprocess: stderr: DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0

------------

INFO vmware_driver: vmnet devices appear healthy!
DEBUG vmware_driver: Beginning to verify routing of devices...
 INFO vmware_driver: Starting services starter and waiting for them to start...
 INFO vmware_driver: Killing vmnet-natd if it is alive...
 INFO subprocess: Starting process: ["/usr/bin/pkill", "vmnet-natd"]
DEBUG subprocess: Command not in installer, not touching env vars.
DEBUG subprocess: Selecting on IO
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
/Applications/Vagrant/embedded/gems/gems/log4r-1.1.10/lib/log4r/repository.rb:65:in `block (2 levels) in reassign_any_children': Interrupt
    from /Applications/Vagrant/embedded/gems/gems/log4r-1.1.10/lib/log4r/repository.rb:63:in `each'
    from /Applications/Vagrant/embedded/gems/gems/log4r-1.1.10/lib/log4r/repository.rb:63:in `block in reassign_any_children'
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
    from /Applications/Vagrant/embedded/gems/gems/log4r-1.1.10/lib/log4r/repository.rb:62:in `reassign_any_children'
    from /Applications/Vagrant/embedded/gems/gems/log4r-1.1.10/lib/log4r/logger.rb:68:in `deal_with_inheritance'
    from /Applications/Vagrant/embedded/gems/gems/log4r-1.1.10/lib/log4r/logger.rb:36:in `initialize'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/util/subprocess.rb:34:in `new'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/util/subprocess.rb:34:in `initialize'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/util/subprocess.rb:22:in `new'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/util/subprocess.rb:22:in `execute'
    from /Users/jtreminio/.vagrant.d/gems/gems/vagrant-vmware-fusion-2.4.1/lib/vagrant-vmware-fusion/driver.rb:1129:in `block in with_network_services'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/lib/vagrant/util/retryable.rb:17:in `retryable'
    from /Users/jtreminio/.vagrant.d/gems/gems/vagrant-vmware-fusion-2.4.1/lib/vagrant-vmware-fusion/driver.rb:1101:in `with_network_services'
    from /Users/jtreminio/.vagrant.d/gems/gems/vagrant-vmware-fusion-2.4.1/lib/vagrant-vmware-fusion/driver.rb:808:in `privileged_verify_vmnet'
    from /Users/jtreminio/.vagrant.d/gems/gems/vagrant-vmware-fusion-2.4.1/lib/vagrant-vmware-fusion/sudo_helper_cli.rb:89:in `command_verify_vmnet'
    from /Users/jtreminio/.vagrant.d/gems/gems/vagrant-vmware-fusion-2.4.1/lib/vagrant-vmware-fusion/sudo_helper_cli.rb:57:in `call'
    from /Users/jtreminio/.vagrant.d/gems/gems/vagrant-vmware-fusion-2.4.1/lib/vagrant-vmware-fusion/sudo_helper_cli.rb:57:in `run'
    from /Users/jtreminio/.vagrant.d/gems/gems/vagrant-vmware-fusion-2.4.1/bin/vagrant_vmware_desktop_sudo_helper:19:in `<encoded>'
    from /Users/jtreminio/.vagrant.d/gems/gems/vagrant-vmware-fusion-2.4.1/bin/vagrant_vmware_desktop_sudo_helper:38:in `RGLoader_load'
    from /Users/jtreminio/.vagrant.d/gems/gems/vagrant-vmware-fusion-2.4.1/bin/vagrant_vmware_desktop_sudo_helper:38:in `<main>'
```

I omitted some parts to conserve space, please let me know if more information is required and I'll post ASAP.

VMware was working previously, I have not changed anything that I recall.

**Comment by nlundquist** [comment]
This is an ongoing issue with the paid VMWare integration. Is this is level of support I can expect from Hashicorps commercial products?

**Comment by mashpie** [comment]
__Workaround__: changed to a setup __without__ private_networking... after struggling over and over again.

```
$vagrant up --debug
```

kept complaining

```
 INFO global: Vagrant version: 1.7.2
 INFO global: Ruby version: 2.0.0
 INFO global: RubyGems version: 2.0.14
 INFO global: VAGRANT_EXECUTABLE="/opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/opt/vagrant/bin/../embedded"
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_DETECTED_OS="Darwin"
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_INTERNAL_BUNDLERIZED="1"
 INFO global: VAGRANT_LOG="debug"
 INFO global: Plugins:
 INFO global:   - bundler = 1.7.11
 INFO global:   - json = 1.8.2
 INFO global:   - mime-types = 1.25.1
 INFO global:   - rdoc = 4.2.0
 INFO global:   - rest-client = 1.6.8
 INFO global:   - vagrant-hostsupdater = 0.0.11
 INFO global:   - vagrant-share = 1.1.3
 INFO global:   - vagrant-triggers = 0.5.0
 INFO global:   - vagrant-vmware-fusion = 3.2.6
```

[...]

```
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: /sbin/ifdown eth1 2> /dev/null (sudo=true)
DEBUG ssh: stderr: stdin: is not a tty

DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
```

[until canceling]

(why ifdown, when not configured...?)

so I tried same box without private ip and ffffffflllllluuup... box is up'n running, nfs mounts are working. Thanks to https://github.com/smdahlen/vagrant-hostmanager there is no need for private ips at the moment

**Comment by alkemann** [comment]
I am having this same issue now. Endless SSH keep alives

**Comment by nitsh** [comment]
I'm having this issue on VMWare Fusion. I had VirtualBox first but I've uninstalled it while I still had few vagrants running. Now, I have VMWare but I'm seeing this issue. Restarting doesn't seem to help.
