### ISSUE TITLE
ed25519 ssh keys are not compatible with vagrant

### ISSUE THREAD

**Issue by indeyets** [hashicorp/vagrant#4367]
whenever my ssh-agent has active ed25519 key I get error similar to this if I try to start/stop the VM. it becomes troublesome, as ed25519 becomes my main ssh-key type these days

```
/Applications/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/openssl.rb:146:in `read_keyblob': curve name mismatched (`Ϲ���������'�N��qC��x�e�F8' with `') (Net::SSH::Exception)
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/buffer.rb:263:in `read_keyblob'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/buffer.rb:239:in `read_key'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/authentication/agent/socket.rb:97:in `block in identities'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/authentication/agent/socket.rb:96:in `times'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/authentication/agent/socket.rb:96:in `identities'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/authentication/key_manager.rb:104:in `each_identity'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/authentication/session.rb:79:in `block in authenticate'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/authentication/session.rb:66:in `each'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh/authentication/session.rb:66:in `authenticate'
    from /Applications/Vagrant/embedded/gems/gems/net-ssh-2.9.1/lib/net/ssh.rb:206:in `start'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/plugins/communicators/ssh/communicator.rb:352:in `block (2 levels) in connect'
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/plugins/communicators/ssh/communicator.rb:331:in `block in connect'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/retryable.rb:17:in `retryable'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/plugins/communicators/ssh/communicator.rb:330:in `connect'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/plugins/communicators/ssh/communicator.rb:116:in `ready?'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:231:in `guest'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/graceful_halt.rb:50:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builder.rb:116:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/call.rb:43:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builder.rb:116:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/call.rb:53:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/plugins/providers/virtualbox/action/discard_state.rb:15:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builder.rb:116:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builtin/call.rb:53:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/warden.rb:34:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/builder.rb:116:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `block in run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/util/busy.rb:19:in `busy'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/action/runner.rb:66:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:196:in `action_raw'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:173:in `block in action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/environment.rb:434:in `lock'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/machine.rb:161:in `action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/plugins/commands/halt/command.rb:31:in `block in execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/plugin/v2/command.rb:220:in `each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/plugins/commands/halt/command.rb:30:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/cli.rb:42:in `execute'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/lib/vagrant/environment.rb:252:in `cli'
    from /Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.6.3/bin/vagrant:166:in `<main>'
```

**Comment by titanous** [comment]
I just ran into this, Vagrant v1.7.2 silently hangs when trying to ssh during `vagrant up` with an Ed25519 key available. This might be fixed by net-ssh/net-ssh#193?

**Comment by rabbbit** [comment]
Still a problem with Vagrant 2.0.1

Fixed with:

```
    sudo gem install rbnacl -v 4.0.2 -i /opt/vagrant/embedded/gems
    sudo gem install bcrypt_pbkdf -i /opt/vagrant/embedded/gems
    sudo gem install rbnacl-libsodium -i /opt/vagrant/embedded/gems
```

:|

**Comment by dansimau** [comment]
According to this net-ssh report:
https://github.com/net-ssh/net-ssh/issues/478

ed25519 support is available just by installing the above gems.

**Comment by utkonos** [comment]
This is still a problem. I have even installed all three of those gems, but I still get the same error and can't use ed25519.

$ gem list

*** LOCAL GEMS ***

bcrypt_pbkdf (1.0.0)
net-ssh (4.2.0)
rbnacl (4.0.2)
rbnacl-libsodium (1.0.15.1)

I'm on a macOS laptop.

**Comment by rabbbit** [comment]
I have since learnt that Vagrant ships with it's own ruby, so a way better way of doing it is:

```
    sudo gem install rbnacl -v 4.0.2 -i /opt/vagrant/embedded/gems
    sudo gem install bcrypt_pbkdf -i /opt/vagrant/embedded/gems
    sudo gem install rbnacl-libsodium -i /opt/vagrant/embedded/gems
```

**Comment by utkonos** [comment]
After running those three commands, I am still unable to use ed25519. Now there are more errors:

Ignoring bcrypt_pbkdf-1.0.0 because its extensions are not built.  Try: gem pristine bcrypt_pbkdf --version 1.0.0
Ignoring rbnacl-libsodium-1.0.15.1 because its extensions are not built.  Try: gem pristine rbnacl-libsodium --version 1.0.15.1

Also, you may have noticed that the rbnacl-libsodium install brings in version 5.0 of rbnacl.

Does someone have a complete answer to this question? Also, why, if Vagrant has its own embedded gems, does it not include the correct gems to support ed25519? Why do these threads keep getting shut and closed by the maintainers? @mitchellh ?
