### ISSUE TITLE
Running vagrant 1.7.0 without arguments generates "vagrant-share can't be installed without vagrant-login" error

### ISSUE THREAD

**Issue by jweissig** [hashicorp/vagrant#4923]
Tested on CentOS 6.5 x86_64 using rpm package, and Ubuntu 12.04 i386 using deb package, both have the same `vagrant-share can't be installed without vagrant-login (RuntimeError)` (see below). Tested fresh installs and upgrades to vagrant_1.7.0_i686.deb from vagrant_1.6.5_i686.deb, both methods give the same error.

```
[~]$ vagrant --version
Vagrant 1.7.0
```

Running `vagrant` without any arguments or using `vagrant --help` generates the following error message:

```
[~]$ vagrant 
/opt/vagrant/embedded/gems/gems/vagrant-share-1.1.2/lib/vagrant-share/activate.rb:8:in `rescue in <encoded>': vagrant-share can't be installed without vagrant-login (RuntimeError)
    from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.2/lib/vagrant-share/activate.rb:5:in `<encoded>'
    from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.2/lib/vagrant-share/activate.rb:16:in `RGLoader_load'
    from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.2/lib/vagrant-share/activate.rb:16:in `<top (required)>'
    from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.2/lib/vagrant-share.rb:23:in `require'
    from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.2/lib/vagrant-share.rb:23:in `block in <class:Plugin>'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/cli.rb:75:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/cli.rb:75:in `block (2 levels) in help'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/registry.rb:48:in `block in each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/registry.rb:47:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/registry.rb:47:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/cli.rb:69:in `block in help'
    from /opt/vagrant/embedded/lib/ruby/2.0.0/optparse.rb:885:in `initialize'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/cli.rb:57:in `new'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/cli.rb:57:in `help'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/cli.rb:32:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/environment.rb:301:in `cli'
    from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.0/bin/vagrant:174:in `<main>'
```

Here's a listing of `/opt/vagrant/embedded/gems/gems/`

```
$ ls -1 /opt/vagrant/embedded/gems/gems/
akami-1.2.2
builder-3.2.2
bundler-1.7.9
celluloid-0.16.0
childprocess-0.5.5
erubis-2.7.0
ffi-1.9.6
gssapi-1.0.3
gyoku-1.2.2
hashicorp-checkpoint-0.1.4
hitimes-1.2.2
httpclient-2.5.3.3
httpi-0.9.7
i18n-0.6.11
listen-2.7.12
little-plugger-1.1.3
log4r-1.1.10
logging-1.8.2
mime-types-1.25.1
mime-types-2.4.3
mini_portile-0.6.0
multi_json-1.10.1
netrc-0.9.0
net-scp-1.1.2
net-sftp-2.1.2
net-ssh-2.9.1
nokogiri-1.6.3.1
nori-1.1.5
rack-1.5.2
rb-fsevent-0.9.4
rb-inotify-0.9.5
rb-kqueue-0.2.3
rest-client-1.6.8
rest-client-1.7.2
rubyntlm-0.1.1
savon-0.9.5
timers-4.0.1
uuidtools-2.1.5
vagrant-1.7.0
vagrant-share-1.1.2
wasabi-1.0.0
wdm-0.1.0
winrm-1.1.3
```

The expected output after running `vagrant` on 1.6.5:

```
[~]$ vagrant
Usage: vagrant [options] <command> [<args>]

    -v, --version                    Print the version and exit.
    -h, --help                       Print this help.

Common commands:
     box             manages boxes: installation, removal, etc.
     connect         connect to a remotely shared Vagrant environment
     destroy         stops and deletes all traces of the vagrant machine
     global-status   outputs status Vagrant environments for this user
     halt            stops the vagrant machine
     help            shows the help for a subcommand
     init            initializes a new Vagrant environment by creating a Vagrantfile
     login           log in to Vagrant Cloud
     package         packages a running vagrant environment into a box
     plugin          manages plugins: install, uninstall, update, etc.
     provision       provisions the vagrant machine
     rdp             connects to machine via RDP
     reload          restarts vagrant machine, loads new Vagrantfile configuration
     resume          resume a suspended vagrant machine
     share           share your Vagrant environment with anyone in the world
     ssh             connects to machine via SSH
     ssh-config      outputs OpenSSH valid configuration to connect to the machine
     status          outputs status of the vagrant machine
     suspend         suspends the machine
     up              starts and provisions the vagrant environment
     version         prints current and latest Vagrant version

For help on any individual command run `vagrant COMMAND -h`

Additional subcommands are available, but are either more advanced
or not commonly used. To see all subcommands, run the command
`vagrant list-commands`.
```

Vagrant seems to be working, because running vagrant status, on existing config files, works:

```
[e42]$ vagrant status

Current machine states:
web                       running (virtualbox)
db                        running (virtualbox)
file                      running (virtualbox)
nagios                    running (virtualbox)
```

**Comment by bizmate** [comment]
I was experiencing the problem where after a vagrant suspend the VM was paused on VBox so I have dowloaded the latest vagrant installer 1.7.2 hoping it would fix this but it results in being not created in vagrant still

based on a comment from above, I have downgraded virtualbox to 4.3.18
The host is win7 pro

Now that i have run vagrant up again i see my machine is being provisioned but all the other VMs have been set to Aborted.

Now instead of 'not created' as soon as I suspend i see  'aborted'
Looks like it is still a bit messy

**Comment by ferventcoder** [comment]
I'm seeing this with 1.6.5...

**Comment by theanalyst** [comment]
Facing the same in 1.6.3 with vagrant-share 1.1.3 and vagrant-login 1.0.1

**Comment by mrjcleaver** [comment]
Saw this on Mac 10.0.1, Chef-DK-0.5.1, Vagrant 1.6.5, when doing vagrant provision 
````
vagrant plugin install vagrant-share
vagrant plugin install vagrant-login
brew cask install vagrant
````

Then caused:
````
Bundler, the underlying system used to manage Vagrant plugins,
is reporting that a plugin or its dependency can't be found.
This is usually caused by manual tampering with the 'plugins.json'
file in the Vagrant home directory. To fix this error, please
remove that file and reinstall all your plugins using `vagrant
plugin install`.
/opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/resolver.rb:368:in `resolve': Could not find gem 'vagrant-login (>= 0) ruby' in the gems available on this machine. (Bundler::GemNotFound)
````

And doing  vagrant plugin install vagrant-login
or  vagrant plugin uninstall vagrant-login

Then just gives me the same issue, over and over :(

**Comment by mrjcleaver** [comment]
Ah https://github.com/mitchellh/vagrant/issues/5270 says it was rolled into core. (Couldn't you leave it in existence as a nil package?)

**Comment by razbakov** [comment]
I've got this problem after running 

```
vagrant plugin install vagrant-nfs_guest
```

**Comment by razbakov** [comment]
This helped me:

```
~/.vagrant.d/plugins.json
```
