### ISSUE TITLE
Ruby error running vagrant package box

### ISSUE THREAD

**Issue by gradha** [hashicorp/vagrant#4960]
Following the instructions of https://docs.vagrantup.com/v2/boxes/base.html I have reached the state where I package the box. I try to run the following but it fails:

```
$ vagrant package --base=debian_four_32bit --output=something.box --vagrantfile=Vagrantfile 
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:153:in `action': wrong number of arguments (2 for 1) (ArgumentError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:83:in `package_vm'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:66:in `package_base'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:42:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/cli.rb:42:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:301:in `cli'
    from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.1/bin/vagrant:174:in `<main>'
```

As far as I can see this is a similar or the same error as https://groups.google.com/forum/#!searchin/vagrant-up/package/vagrant-up/WZZ1_ivbRP4/4n7y4CDRXaIJ but I can't get the package command to work in any way, passing less arguments. This is the content of the Vagrantfile:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian_four_32bit"
  config.vm.base_mac = "080027A417F9"
end
```

I'm running vagrant 1.7.1 on osx with virtualbox 4.2.24.

**Comment by renatomefidf** [comment]
Hello All,

It is now working on 1.7.2 package, I just confirmed it!

**Comment by rcsavage** [comment]
Double confirmation.  Where was 1.7.2 all my life?!  LOL.
