### ISSUE TITLE
Vagrant up errors

### ISSUE THREAD

**Issue by insidetheeye** [hashicorp/vagrant#5024]
Running Vagrant 1.6.5 on mac OSX 10.8.2

Nothing but errors when trying to run vagrant. Example:

```
Pringless-MacBook-Pro-2:f_bizzaro_Naboo pringles$ vagrant up web
Bringing machine 'web' up with 'virtualbox' provider...
/Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:450:in `initialize': Permission denied - /Users/pringles/.vagrant.d/data/lock.machine-action-a8e77c3bbc3c2ac60005d7eba23c62fd.lock (Errno::EACCES)
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:450:in `open'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:450:in `block in lock'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:474:in `lock'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:449:in `lock'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in `action'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

```

This previously wasn't an issue and now I can't seem to bring up anything.

**Comment by zamrokk** [comment]
👍

**Comment by wploey** [comment]
good!

**Comment by LukSimoes** [comment]
how solve this in windows?
