### ISSUE TITLE
vagrant (1.7.1) up failed with http hosted box. Env windows + cygwin (babun)

### ISSUE THREAD

**Issue by pouicr** [hashicorp/vagrant#5032]
I tried to create a machine from a http hosted box but it failed.

VagrantFile:

``` ruby
config.vm.box = "https://xxx.yyy.fr/iii/oooo/uuuu/boxes/staging/vbox/boot2docker.box"
```

error:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'https://xxx.yyy.fr/iii/oooo/uuuu/boxes/staging/vbox/boot2docker.box' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'https://xxx.yyy.fr/iii/oooo/uuuu/boxes/staging/vbox/boot2docker.box' (v0) for provider: virtualbox
    default: Downloading: https://xxx.yyy.fr/iii/oooo/uuuu/boxes/staging/vbox/boot2docker.box
    default:
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir': No such file or directory - C:/Utilisateurs/zzzzz/.vagrant.d/boxes/https-VAGRANTCOLON--VAGRANTSLASH--VAGRANTSLASH-xxx.yyyy-VAGRANTSLASH-iiiii-VAGRANTSLASH-oooo-VAGRANTSLASH-uuuu-VAGRANTSLASH-boxes-VAGRANTSLASH-staging-VAGRANTSLASH-vbox-VAGRANTSLASH-boot2docker.box (Errno::ENOENT)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:203:in `each'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/pathname.rb:556:in `mkpath'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/box_collection.rb:158:in `block (3 levels) in add'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/box_collection.rb:436:in `with_temp_dir'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/box_collection.rb:131:in `block (2 levels) in add'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/box_collection.rb:436:in `with_temp_dir'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/box_collection.rb:112:in `block in add'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/box_collection.rb:423:in `block in with_collection_lock'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/box_collection.rb:422:in `with_collection_lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/box_collection.rb:101:in `add'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/box_add.rb:337:in `box_add'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/box_add.rb:130:in `add_direct'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/box_add.rb:106:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/handle_box.rb:79:in `handle_box'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/handle_box.rb:42:in `block in call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/handle_box.rb:36:in `synchronize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/handle_box.rb:36:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:212:in `action_raw'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:189:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:516:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:176:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:176:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

It is working on linux.

Doing:

```
vagrant box add --name pouette https://xxx.yyy.fr/iii/oooo/uuuu/boxes/staging/vbox/boot2docker.box
```

And modifying vagrantfile to use "pouette" instead is working fine.

**Comment by pouicr** [comment]
Sorry I missed your comment!

My mistake, I was missing the box name which is required I guess. 
The good way the one you wrote

Thx
