### ISSUE TITLE
changing the a windows hostname takes forever when graceful_halt_timeout is set

### ISSUE THREAD

**Issue by rgl** [hashicorp/vagrant#8486]
### Vagrant version
1.9.2

### Host operating system
Windows 10

### Guest operating system
Windows Server 2016

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
    config.vm.box = "windows-2016-amd64"
    config.vm.define "windows-domain-controller"
    config.vm.hostname = "dc"
    config.vm.graceful_halt_timeout = 60*60 # 60 minutes.
    ...
```

### Debug output
It keeps stuck at:
```
INFO subprocess: Command not in installer, restoring original environment...                                                                                            
INFO winrmshell: Attempting to connect to WinRM...                                                                                                                      
INFO winrmshell:   - Host: 127.0.0.1                                                                                                                                    
INFO winrmshell:   - Port: 2200                                                                                                                                         
INFO winrmshell:   - Username: vagrant                                                                                                                                  
INFO winrmshell:   - Transport: plaintext                                                                                                                               
INFO winrm: WinRM is ready!                                                                                                                                             
INFO guest: Execute capability: change_host_name [#<Vagrant::Machine: windows-domain-controller (VagrantPlugins::ProviderVirtualBox::Provider)>, "dc"] (windows)        
```

### Expected behavior
The hostname change should be quick. In fact, when I login into the machine, the hostname is already changed; so, it seems that only an explicit reboot is needed.

### Actual behavior
It takes forever to change.

**Comment by rgl** [comment]
BTW, this also happens with vagrant 1.9.3.

**Comment by carslen** [comment]
Same issue here with Vagrant 2.01 and a Windows Server 2016 box.

```
## AppWindows
  config.vm.define 'appWin1', autostart: true do |appWin1|
    appWin1.vm.box = "WindowsServer2016"
    appWin1.vm.box_url = 'file://./Boxes/WindowsServer2016/w2k16-2.box'
    appWin1.vm.communicator = "winrm"
    appWin1.vm.hostname = 'appWin1'
    appWin1.vm.graceful_halt_timeout = 600
    appWin1.vm.guest = :windows
    appWin1.vm.network "forwarded_port", guest: 3389, host: 3390, auto_correct: true
    appWin1.vm.network "private_network", ip: "192.168.56.101", virtualbox__intnet: "iBISS"
    appWin1.vm.provision "shell", path: "ConfigureRemotingForAnsible.ps1" 
    appWin1.vm.provision "shell", path: "VolumeSetting.ps1"

    appWin1.vm.provider "virtualbox" do |vbappWin1|
      vbappWin1.cpus = 1
      vbappWin1.memory = 2048
      # Customize the name of VM in VirtualBox manager UI:
      vbappWin1.name = "TM1 Appserver 01"
      vbappWin1.customize [ 'storagectl', :id, '--name', 'SATA', '--portcount', '3' ]
      file_on_disk = "appWin1D.vmdk"
      unless File.exists?(file_on_disk)
        vbappWin1.customize [ 'createmedium', 'disk', '--filename', 'appWin1D.vmdk', '--format', "vmdk", '--size', '51200' ]
      end
      vbappWin1.customize [ 'storageattach', :id, '--storagectl', 'SATA', '--port', '1', '--device', '0', '--type', 'hdd', '--medium', file_on_disk ]
      vbappWin1.customize [ 'storageattach', :id, '--storagectl', 'SATA', '--port', '2', '--device', '0', '--type', 'dvddrive', '--medium', 'emptydrive' ]
    end
    appWin1.vm.synced_folder ".", "C:/vagrant", disabled: true
    appWin1.vm.synced_folder "C:/Users/username/git/iBISS/", "C:/Ansible"
  end
```

Hostname is set in VM and required reboot is done, but vagrant stucks. See attached debug.
[vagrant.log](https://github.com/hashicorp/vagrant/files/1582007/vagrant.log)

**Comment by ch3lmi** [comment]
Same issue with Vagrant 2.0.1 and Windows 10 1709 (latest version).

`Vagrant.configure(2)` do |config|
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.boot_timeout = 600
  config.vm.graceful_halt_timeout = 600
  config.vm.hostname = "win101709"

  config.vm.network :forwarded_port, guest: 3389, host: 3389
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true

end`

**Comment by ajpaul25** [comment]
I've gotten around this issue by modifying [plugins/guests/windows/cap/change_host_name.rb](https://github.com/hashicorp/vagrant/blob/master/plugins/guests/windows/cap/change_host_name.rb).  I replaced the sleep(sleep_timeout) line with code borrowed from [plugins/guests/windows/cap/reboot.rb](https://github.com/hashicorp/vagrant/blob/master/plugins/guests/windows/cap/reboot.rb).  The current code will simply sleep for the entire value of config.vm.graceful_halt_timeout.  Ideally, I think the ChangeHostName module would reference the Reboot module.  I expect that this issue affects all versions of windows.  I can confirm that it affects Windows Server 2012r2.

```Ruby
module VagrantPlugins
  module GuestWindows
    module Cap
      module ChangeHostName

        def self.change_host_name(machine, name)
          change_host_name_and_wait(machine, name, machine.config.vm.graceful_halt_timeout)
        end

        def self.change_host_name_and_wait(machine, name, sleep_timeout)
          # If the configured name matches the current name, then bail
          # We cannot use %ComputerName% because it truncates at 15 chars
          return if machine.communicate.test("if ([System.Net.Dns]::GetHostName() -eq '#{name}') { exit 0 } exit 1")
          
          # Rename and reboot host if rename succeeded
          script = <<-EOH
            $computer = Get-WmiObject -Class Win32_ComputerSystem
            $retval = $computer.rename("#{name}").returnvalue
            if ($retval -eq 0) {
              shutdown /r /t 5 /f /d p:4:1 /c "Vagrant Rename Computer"
            }
            exit $retval
          EOH

          machine.communicate.execute(
            script,
            error_class: Errors::RenameComputerFailed,
            error_key: :rename_computer_failed)

          # Don't continue until the machine has shutdown and rebooted
          # sleep(sleep_timeout)
		  
          # borrowed from reboot.rb
          script = File.expand_path("../../scripts/reboot_detect.ps1", __FILE__)
          script = File.read(script)
          while machine.communicate.execute(script, error_check: false) != 0
            sleep 10
          end
		  
          # This re-establishes our symbolic links if they were
          # created between now and a reboot
          machine.communicate.execute("net use", error_check: false)
        end
      end
    end
  end
end

```

**Comment by ch3lmi** [comment]
brilliant, thanks ajpaul25 !

I've implemented this in my latest custom image and works flawlessly.

**Comment by ajpaul25** [comment]
I've updated the code to reference :wait_for_reboot instead of copying the code and submitted a pull request #9578.

**Comment by ajpaul25** [comment]
Looks like the test is failing on travis.  I'm not super-strong with Ruby unit testing.  I'll try to keep hacking at it, but I'd appreciate if anyone could check it out to see if I'm missing something simple.    Here's the error:

>   1) VagrantPlugins::GuestWindows::Cap::ChangeHostName .change_host_name changes the hostname
     Failure/Error: described_class.change_host_name_and_wait(machine, 'newhostname')
       #<Double "machine"> received unexpected message :guest with (no args)
     # ./plugins/guests/windows/cap/change_host_name.rb:31:in `change_host_name_and_wait'
     # ./test/unit/plugins/guests/windows/cap/change_host_name_test.rb:37:in `block (3 levels) in <top (required)>'

**Comment by briancain** [comment]
Hi @ajpaul25 - I've left a review on your PR. Thanks!
