### ISSUE TITLE
`insert_public_key': uninitialized constant VagrantPlugins::CommunicatorWinSSH::Communicator

### ISSUE THREAD

**Issue by drywolf** [hashicorp/vagrant#8941]
### Vagrant version
1.9.8

### Host operating system
Ubuntu 16.04

### Guest operating system
Windows 7

### Vagrantfile
```ruby
require_relative 'ie-box-automation-plugin'
require_relative 'switch-to-winrm-plugin'

fs_type = "nfs"

Vagrant.configure(2) do |config|

    #config.vm.box = ENV['VAGRANT_SYS_IMAGE'] || "Microsoft/EdgeOnWindows10"
    config.vm.box = "Win7"
    config.vm.hostname = "j2v8-win32-x64"

    # source: https://github.com/danielmenezesbr/modernie-winrm
    config.vm.boot_timeout = 5000

    config.vm.guest = :windows

    config.ssh.username = "IEUser"
    config.ssh.password = "Passw0rd!"
    config.ssh.insert_key = true

    config.vm.box_check_update = false

    config.vm.provider "virtualbox" do |v|
        v.name = "j2v8.win32.x64"
        v.memory = 8192
        v.cpus = 4
    end

    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder "../../", "C:/j2v8"

    config.vm.provision "file", source: "./tools", destination: "c:/users/IEUser"
    config.vm.provision "winrm", type: "ie_box_automation"

    #config.vm.provision :switch_to_winrm

    config.vm.provision "install-python", type:"shell", inline: "C:/j2v8/docker/win32/install.python.ps1"
    config.vm.provision "install-vsc++", type:"shell", inline: "C:/j2v8/docker/win32/install.vscpp.ps1"
    config.vm.provision "install-cmake", type:"shell", inline: "C:/j2v8/docker/win32/install.cmake.ps1"
    config.vm.provision "install-jdk", type:"shell", inline: "C:/j2v8/docker/win32/install.jdk.ps1"
    config.vm.provision "install-maven", type:"shell", inline: "C:/j2v8/docker/win32/install.maven.ps1"

end
```
### Debug output
```
==> default: Running provisioner: file...
    default:
    default: Inserting generated public key within guest...
/opt/vagrant/embedded/gems/gems/vagrant-1.9.8/plugins/guests/windows/cap/public_key.rb:8:in `insert_public_key': uninitialized constant VagrantPlugins::CommunicatorWinSSH::Communicator (NameError)
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/capability_host.rb:111:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/capability_host.rb:111:in `capability'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/guest.rb:43:in `capability'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/plugins/communicators/ssh/communicator.rb:187:in `ready?'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/lib/vagrant/machine.rb:262:in `guest'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/plugins/provisioners/file/provisioner.rb:37:in `expand_guest_path'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/plugins/provisioners/file/provisioner.rb:7:in `block in provision'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/plugins/provisioners/file/provisioner.rb:5:in `tap'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.8/plugins/provisioners/file/provisioner.rb:5:in `provision'
```

### Expected behavior
I am trying to use ssh to remotely run a command in the guest VM with `vagrant ssh -c`.
Vagrant tells that for this feature a ssh key must be installed on the guest VM.
When I enable the feature via `config.ssh.insert_key = true` in the Vagrantfile, then the above exception occurs when I `vagrant up` the machine.

I also already tried several other ways to communicate with the Win7 guest, but everything has failed so far. Is there an officially supported way to communicate from a Linux host to a Windows guest ?

### Actual behavior
See error log above

**Comment by ferrarimarco** [comment]
This also occurs in Vagrant 2.0.0
