### ISSUE TITLE
vagrant up convert encode error:ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)

### ISSUE THREAD

**Issue by chenyingqiao** [hashicorp/vagrant#8979]
```
lerko@lerko-PC:~/Documents/vagrant$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'dev_12301'...
/usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/util/subprocess.rb:28:in `encode': "\xE5" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/util/subprocess.rb:28:in `block in initialize'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/util/subprocess.rb:28:in `map'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/util/subprocess.rb:28:in `initialize'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/util/subprocess.rb:22:in `new'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/util/subprocess.rb:22:in `execute'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/providers/virtualbox/driver/base.rb:430:in `block in raw'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/providers/virtualbox/driver/base.rb:429:in `raw'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/providers/virtualbox/driver/base.rb:367:in `block in execute'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/util/retryable.rb:17:in `retryable'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/providers/virtualbox/driver/base.rb:362:in `execute'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/providers/virtualbox/driver/version_5_1.rb:318:in `import'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/providers/virtualbox/action/import.rb:53:in `import'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/providers/virtualbox/action/import.rb:13:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/providers/virtualbox/action/prepare_clone_snapshot.rb:17:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/builtin/prepare_clone.rb:15:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/providers/virtualbox/action/customize.rb:40:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/machine.rb:225:in `action_raw'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/machine.rb:200:in `block in action'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/environment.rb:533:in `lock'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `action'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

My system is Linux's Chinese system

*ruby version*
```
lerko@lerko-PC:~/Documents/vagrant$ ruby -v
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
```
*vagrant version*

```
Vagrant 1.9.1
```

**Comment by briancain** [comment]
Hi @chenyingqiao - can you please upgrade to the latest version of vagrant and let us know if you still experience this error? Thank you!

**Comment by chenyingqiao** [comment]
@briancain 
When I upgraded to 2.0.0, I didn't make any of the above mistakes
thanks

**Comment by briancain** [comment]
Thanks then! I'll go ahead and close this if it did not happen on the latest version.

**Comment by rahimbn** [comment]
i have the same prblm bro and my vagrant is 2.2.6. the last version actually
