### ISSUE TITLE
Can't run vagrant after install from source

### ISSUE THREAD

**Issue by hemna** [hashicorp/vagrant#8989]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
stack@linux-3n06:~/vagrant> vagrant --version
/opt/rubies/ruby-2.3.5/lib64/ruby/2.3.0/rubygems.rb:241:in `bin_path': can't find gem vagrant (>= 0.a) (Gem::GemNotFoundException)
	from /home/stack/.gem/ruby/2.3.5/bin/vagrant:22:in `<main>'

### Host operating system
stack@linux-3n06:~/vagrant> cat /etc/issue
Welcome to openSUSE Leap 42.2 - Kernel \r (\l).

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
should have gotten the version

### Actual behavior
stack@linux-3n06:~/vagrant> vagrant --version
/opt/rubies/ruby-2.3.5/lib64/ruby/2.3.0/rubygems.rb:241:in `bin_path': can't find gem vagrant (>= 0.a) (Gem::GemNotFoundException)
	from /home/stack/.gem/ruby/2.3.5/bin/vagrant:22:in `<main>'
### Steps to reproduce
1. Install ruby-install
2. run ruby-install ruby 2.3.5
3. install chruby
4. chruby 2.3.5
5. git clone https://github.com/mitchellh/vagrant.git
6. bundle install
7. vagrant --version

### OUTPUT
```
stack@linux-3n06:~/vagrant> gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2.1
  - RUBY VERSION: 2.3.5 (2017-09-14 patchlevel 376) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/stack/.gem/ruby/2.3.5
  - USER INSTALLATION DIRECTORY: /home/stack/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /opt/rubies/ruby-2.3.5/bin/ruby
  - EXECUTABLE DIRECTORY: /home/stack/.gem/ruby/2.3.5/bin
  - SPEC CACHE DIRECTORY: /home/stack/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /opt/rubies/ruby-2.3.5/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/stack/.gem/ruby/2.3.5
     - /opt/rubies/ruby-2.3.5/lib64/ruby/gems/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/stack/.gem/ruby/2.3.5/bin
     - /opt/rubies/ruby-2.3.5/lib64/ruby/gems/2.3.0/bin
     - /opt/rubies/ruby-2.3.5/bin
     - /home/stack/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/games

stack@linux-3n06:~/vagrant> gem list

*** LOCAL GEMS ***

bigdecimal (1.2.8)
bundle (0.0.1)
bundler (1.15.4)
did_you_mean (1.0.0)
io-console (0.4.5)
json (1.8.3.1)
minitest (5.8.5)
net-telnet (0.1.1)
power_assert (0.2.6)
psych (2.1.0.1)
rake (10.4.2)
rdoc (4.2.1)
test-unit (3.1.5)


stack@linux-3n06:~/vagrant> bundle install
The latest bundler is 1.16.0.pre.2, but you are currently running 1.15.4.
To update, run `gem install bundler --pre`
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Fetching https://github.com/mitchellh/vagrant-spec.git
Fetching rake 12.0.0
Installing rake 12.0.0
Fetching public_suffix 3.0.0
Installing public_suffix 3.0.0
Fetching builder 3.2.3
Installing builder 3.2.3
Using bundler 1.15.4
Fetching ffi 1.9.18
Installing ffi 1.9.18 with native extensions
Fetching safe_yaml 1.0.4
Installing safe_yaml 1.0.4
Fetching diff-lcs 1.3
Installing diff-lcs 1.3
Fetching unf_ext 0.0.7.4
Installing unf_ext 0.0.7.4 with native extensions
Fetching erubis 2.7.0
Installing erubis 2.7.0
Fetching fake_ftp 0.1.1
Installing fake_ftp 0.1.1
Fetching hashdiff 0.3.6
Installing hashdiff 0.3.6
Fetching hashicorp-checkpoint 0.1.4
Installing hashicorp-checkpoint 0.1.4
Fetching httpclient 2.8.3
Installing httpclient 2.8.3
Fetching i18n 0.8.0
Installing i18n 0.8.0
Fetching rb-fsevent 0.10.2
Installing rb-fsevent 0.10.2
Fetching ruby_dep 1.3.1
Installing ruby_dep 1.3.1
Fetching little-plugger 1.1.4
Installing little-plugger 1.1.4
Fetching log4r 1.1.10
Installing log4r 1.1.10
Fetching multi_json 1.12.2
Installing multi_json 1.12.2
Fetching mime-types-data 3.2016.0521
Installing mime-types-data 3.2016.0521
Fetching net-ssh 4.1.0
Installing net-ssh 4.1.0
Fetching netrc 0.11.0
Installing netrc 0.11.0
Fetching nori 2.6.0
Installing nori 2.6.0
Fetching rspec-support 3.5.0
Installing rspec-support 3.5.0
Fetching rubyntlm 0.6.2
Installing rubyntlm 0.6.2
Fetching rubyzip 1.2.1
Installing rubyzip 1.2.1
Fetching thor 0.18.1
Installing thor 0.18.1
Fetching wdm 0.1.1
Installing wdm 0.1.1 with native extensions
Fetching addressable 2.5.2
Installing addressable 2.5.2
Fetching gyoku 1.3.1
Installing gyoku 1.3.1
Fetching childprocess 0.6.3
Installing childprocess 0.6.3
Fetching gssapi 1.2.0
Installing gssapi 1.2.0
Fetching rb-inotify 0.9.10
Installing rb-inotify 0.9.10
Fetching rb-kqueue 0.2.5
Installing rb-kqueue 0.2.5
Fetching crack 0.4.3
Installing crack 0.4.3
Fetching unf 0.1.4
Installing unf 0.1.4
Fetching logging 2.2.2
Installing logging 2.2.2
Fetching mime-types 3.1
Installing mime-types 3.1
Fetching net-scp 1.2.1
Installing net-scp 1.2.1
Fetching net-sftp 2.1.2
Installing net-sftp 2.1.2
Fetching rspec-core 3.5.4
Installing rspec-core 3.5.4
Fetching rspec-expectations 3.5.0
Installing rspec-expectations 3.5.0
Fetching rspec-mocks 3.5.0
Installing rspec-mocks 3.5.0
Fetching listen 3.1.5
Installing listen 3.1.5
Fetching webmock 1.24.6
Installing webmock 1.24.6
Fetching domain_name 0.5.20170404
Installing domain_name 0.5.20170404
Fetching winrm 2.2.3
Installing winrm 2.2.3
Fetching rspec-its 1.2.0
Installing rspec-its 1.2.0
Fetching rspec 3.5.0
Installing rspec 3.5.0
Fetching http-cookie 1.0.3
Installing http-cookie 1.0.3
Fetching winrm-fs 1.0.2
Installing winrm-fs 1.0.2
Using vagrant-spec 0.0.1 from https://github.com/mitchellh/vagrant-spec.git (at master@e623a56)
Fetching rest-client 2.0.2
Installing rest-client 2.0.2
Fetching winrm-elevated 1.1.0
Installing winrm-elevated 1.1.0
Using vagrant 2.0.0 from source at `.`
Bundle complete! 7 Gemfile dependencies, 55 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
stack@linux-3n06:~/vagrant> vagrant --version
/opt/rubies/ruby-2.3.5/lib64/ruby/2.3.0/rubygems.rb:241:in `bin_path': can't find gem vagrant (>= 0.a) (Gem::GemNotFoundException)
	from /home/stack/.gem/ruby/2.3.5/bin/vagrant:22:in `<main>'


stack@linux-3n06:~/vagrant> gem list

*** LOCAL GEMS ***

addressable (2.5.2)
bigdecimal (1.2.8)
builder (3.2.3)
bundle (0.0.1)
bundler (1.15.4)
childprocess (0.6.3)
crack (0.4.3)
did_you_mean (1.0.0)
diff-lcs (1.3)
domain_name (0.5.20170404)
erubis (2.7.0)
fake_ftp (0.1.1)
ffi (1.9.18)
gssapi (1.2.0)
gyoku (1.3.1)
hashdiff (0.3.6)
hashicorp-checkpoint (0.1.4)
http-cookie (1.0.3)
httpclient (2.8.3)
i18n (0.8.0)
io-console (0.4.5)
json (1.8.3.1)
listen (3.1.5)
little-plugger (1.1.4)
log4r (1.1.10)
logging (2.2.2)
mime-types (3.1)
mime-types-data (3.2016.0521)
minitest (5.8.5)
multi_json (1.12.2)
net-scp (1.2.1)
net-sftp (2.1.2)
net-ssh (4.1.0)
net-telnet (0.1.1)
netrc (0.11.0)
nori (2.6.0)
power_assert (0.2.6)
psych (2.1.0.1)
public_suffix (3.0.0)
rake (12.0.0, 10.4.2)
rb-fsevent (0.10.2)
rb-inotify (0.9.10)
rb-kqueue (0.2.5)
rdoc (4.2.1)
rest-client (2.0.2)
rspec (3.5.0)
rspec-core (3.5.4)
rspec-expectations (3.5.0)
rspec-its (1.2.0)
rspec-mocks (3.5.0)
rspec-support (3.5.0)
ruby_dep (1.3.1)
rubyntlm (0.6.2)
rubyzip (1.2.1)
safe_yaml (1.0.4)
test-unit (3.1.5)
thor (0.18.1)
unf (0.1.4)
unf_ext (0.0.7.4)
wdm (0.1.1)
webmock (1.24.6)
winrm (2.2.3)
winrm-elevated (1.1.0)
winrm-fs (1.0.2)
stack@linux-3n06:~/vagrant>
stack@linux-3n06:~/vagrant>
stack@linux-3n06:~/vagrant> bundle list
Gems included by the bundle:
  * addressable (2.5.2)
  * builder (3.2.3)
  * bundler (1.15.4)
  * childprocess (0.6.3)
  * crack (0.4.3)
  * diff-lcs (1.3)
  * domain_name (0.5.20170404)
  * erubis (2.7.0)
  * fake_ftp (0.1.1)
  * ffi (1.9.18)
  * gssapi (1.2.0)
  * gyoku (1.3.1)
  * hashdiff (0.3.6)
  * hashicorp-checkpoint (0.1.4)
  * http-cookie (1.0.3)
  * httpclient (2.8.3)
  * i18n (0.8.0)
  * listen (3.1.5)
  * little-plugger (1.1.4)
  * log4r (1.1.10)
  * logging (2.2.2)
  * mime-types (3.1)
  * mime-types-data (3.2016.0521)
  * multi_json (1.12.2)
  * net-scp (1.2.1)
  * net-sftp (2.1.2)
  * net-ssh (4.1.0)
  * netrc (0.11.0)
  * nori (2.6.0)
  * public_suffix (3.0.0)
  * rake (12.0.0)
  * rb-fsevent (0.10.2)
  * rb-inotify (0.9.10)
  * rb-kqueue (0.2.5)
  * rest-client (2.0.2)
  * rspec (3.5.0)
  * rspec-core (3.5.4)
  * rspec-expectations (3.5.0)
  * rspec-its (1.2.0)
  * rspec-mocks (3.5.0)
  * rspec-support (3.5.0)
  * ruby_dep (1.3.1)
  * rubyntlm (0.6.2)
  * rubyzip (1.2.1)
  * safe_yaml (1.0.4)
  * thor (0.18.1)
  * unf (0.1.4)
  * unf_ext (0.0.7.4)
  * vagrant (2.0.0)
  * vagrant-spec (0.0.1 e623a56)
  * wdm (0.1.1)
  * webmock (1.24.6)
  * winrm (2.2.3)
  * winrm-elevated (1.1.0)
  * winrm-fs (1.0.2)
```

**Comment by chrisroberts** [comment]
When using bundler you will generally need to prefix your command with `bundle exec` to use the local bundle (and not the system gems):

```
$ bundle exec vagrant --version
```

Cheers!
