### ISSUE TITLE
Vagrant Push not working with Windows 10

### ISSUE THREAD

**Issue by thiagomajesk** [hashicorp/vagrant#9046]
Hi, I'm trying to use vagrant push do run a Cake (C# Make) script with:

```ruby
config.push.define "local-exec" do |push|
  push.script = "../scripts/build.sh" # or "../scripts/build.ps1"
end
```

But I'm getting the following error:

```
 vagrant push
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/util/subprocess.rb:146:in `rescue in execute':  (193) (Vagrant::Util::Subprocess::LaunchError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/util/subprocess.rb:139:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/util/subprocess.rb:22:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/pushes/local-exec/push.rb:72:in `execute_subprocess!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/pushes/local-exec/push.rb:51:in `execute!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/pushes/local-exec/push.rb:45:in `execute_script!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/pushes/local-exec/push.rb:14:in `push'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:688:in `push'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/commands/push/command.rb:28:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:308:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/bin/vagrant:138:in `<main>'
```

**Comment by briancain** [comment]
Hi @thiagomajesk - have you confirmed that there isn't an issue with your build script? The stacktrace to me makes me think that there might of been an error in the script, and the subprocess that executed it threw an exception when the script failed.

**Comment by thiagomajesk** [comment]
@briancain Hi!
My code is not that different from the one in the [docs](https://www.vagrantup.com/docs/push/local-exec.html). (I got the same error for inline and file scripts)

```ruby
config.push.define "local-exec" do |push|
    push.inline = <<-SCRIPT
      echo "Hello Push!"
    SCRIPT
end
```

**Comment by briancain** [comment]
Ok! Thanks. I'll get this labeled up then. :)
