### ISSUE TITLE
Bundler error

### ISSUE THREAD

**Issue by srininsa** [hashicorp/vagrant#9052]
I have installing Vagrant 1.7.3 (for compatibility reasons) with chef version 0.9.0 on Windows 7 Enterprise platform

Trying to run Vagrant on command line, getting the following error:

```
Bundler, the underlying system used to manage Vagrant plugins,
is reporting that a plugin or its dependency can't be found.
This is usually caused by manual tampering with the 'plugins.json'
file in the Vagrant home directory. To fix this error, please
remove that file and reinstall all your plugins using `vagrant
plugin install`.
C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/resolver.rb:3
47:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'vag
rant-berkshelf (= 4.1.0) x86-mingw32' in any of the gem sources listed in your G
emfile or available on this machine. (Bundler::GemNotFound)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/
resolver.rb:325:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/
resolver.rb:325:in `verify_gemfile_dependencies_are_found!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/
resolver.rb:198:in `start'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/
resolver.rb:182:in `resolve'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/
definition.rb:200:in `resolve'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/
definition.rb:140:in `specs'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/
definition.rb:185:in `specs_for'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant.r
b:76:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kern
el_require.rb:135:in `require'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kern
el_require.rb:135:in `rescue in require'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kern
el_require.rb:144:in `require'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.3/bin/vagrant:1
05:in `<main>'
```

Please help.

Thanks in advance.
Srini

**Comment by betogrun** [comment]
Hi @srininsa , 

Did chef install vagrant from git? In this case make sure to run `bundle install` in order to install all the necessary gems.
You can find the steps here: https://www.vagrantup.com/docs/installation/source.html

**Comment by srininsa** [comment]
Hi @betogrun ,

Thanks for the help, I had to reinstall bundler and then run bundle install to solved the issue.

Thanks again @betogrun .
