### ISSUE TITLE
vagrant-aws plugin install error

### ISSUE THREAD

**Issue by maocorte** [hashicorp/vagrant#9053]
Hello, i have the following error when i try to install `vagrant-aws` plugin
```Mauros-MacBook-Pro:ec2 mcortellazzi$ vagrant plugin install vagrant-aws
Installing the 'vagrant-aws' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate json-2.1.0, already activated json-1.8.1 (Gem::LoadError)
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1276:in `activate'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/bundler.rb:357:in `block in activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/bundler.rb:354:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/bundler.rb:354:in `activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/bundler.rb:279:in `internal_install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/bundler.rb:104:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/plugin/manager.rb:72:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/action/install_gem.rb:29:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/command/install.rb:31:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/plugin/command/root.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:308:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/bin/vagrant:127:in `<main>'
Mauros-MacBook-Pro:ec2 mcortellazzi$ vagrant -v
Vagrant 1.9.3
Mauros-MacBook-Pro:ec2 mcortellazzi$ ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
Mauros-MacBook-Pro:ec2 mcortellazzi$ gem -v
2.6.13
```

My mac os is `Sierra 10.12.6`, vagrant version is `1.9.3`, ruby version is `2.4.2p198` and gem version is `2.6.13`.
Am I missing something?
Thank you for your help.

**Comment by maocorte** [comment]
Updating Vagrant to version `2.0.0` solved my issue
