### ISSUE TITLE
"undefined local variable" with Vagrant 2.0.0 on CentOS 7.4

### ISSUE THREAD

**Issue by vhosakot** [hashicorp/vagrant#9055]
### Vagrant version
```
# vagrant -v
Vagrant 2.0.0
```
### Host operating system
CentOS 7.4
```
# cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core) 
```
### Guest operating system
CentOS 7.3 (box version 1707.01)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "1707.01"
  config.ssh.username = vagrant
  config.ssh.password = vagrant
end
```
### Expected behavior
No errors.

### Actual behavior
```
# vagrant up
/root/Vagrantfile:7:in `block in <top (required)>': undefined local variable or method `vagrant' for main:Object (NameError)
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:125:in `block (2 levels) in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:119:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:119:in `block in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:116:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:116:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:810:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:810:in `vagrantfile'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:556:in `host'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:214:in `block in action_runner'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:33:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:543:in `hook'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:792:in `unload'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/bin/vagrant:141:in `ensure in <main>'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/bin/vagrant:141:in `<main>'

# vagrant status
/root/Vagrantfile:7:in `block in <top (required)>': undefined local variable or method `vagrant' for main:Object (NameError)
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:125:in `block (2 levels) in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:119:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:119:in `block in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:116:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:116:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:810:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:810:in `vagrantfile'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:556:in `host'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:214:in `block in action_runner'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:33:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:543:in `hook'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:792:in `unload'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/bin/vagrant:141:in `ensure in <main>'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/bin/vagrant:141:in `<main>'

# vagrant version
Installed Version: 2.0.0
Latest Version: 2.0.0
You're running an up-to-date version of Vagrant!
/root/Vagrantfile:7:in `block in <top (required)>': undefined local variable or method `vagrant' for main:Object (NameError)
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:125:in `block (2 levels) in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:119:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:119:in `block in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:116:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:116:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:810:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:810:in `vagrantfile'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:556:in `host'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:214:in `block in action_runner'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:33:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:543:in `hook'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:792:in `unload'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/bin/vagrant:141:in `<main>'
```

Provider is VirtualBox 5.1.28:

```
# virtualbox --help | grep Virtual
Oracle VM VirtualBox Manager 5.1.28

# VBoxManage --version
5.1.28r117968
```
### Steps to reproduce
See "Actual behavior" above.

### Workaround
Adding quotes around `vagrant` in the Vagrantfile worked.
Changing
```
  config.ssh.username = vagrant
  config.ssh.password = vagrant
```
to
```
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
```
worked.

**Comment by sethvargo** [comment]
Ruby does not support bare words. If you are using a string, you need to surround it with quotes. The error is as-expected. There is no variable named `vagrant`.

**Comment by vhosakot** [comment]
Thanks for the info @sethvargo.  Would it be possible for vagrant to print a better, shorter, understandable error than the following errors deep from the underlying programming language (Ruby in this case)?
```
# vagrant up
/root/Vagrantfile:7:in `block in <top (required)>': undefined local variable or method `vagrant' for main:Object (NameError)
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:125:in `block (2 levels) in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:119:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:119:in `block in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:116:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:116:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:810:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:810:in `vagrantfile'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:556:in `host'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:214:in `block in action_runner'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:33:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:543:in `hook'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:792:in `unload'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/bin/vagrant:141:in `ensure in <main>'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/bin/vagrant:141:in `<main>'
```

**Comment by cifranix** [comment]
Ensure that double-quotes wrap the username and password like so: 

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
