### ISSUE TITLE
Vagrant Share ResourceNotFound 404 error

### ISSUE THREAD

**Issue by bubblemedialtd** [hashicorp/vagrant#9130]
### Vagrant version
v1.8.5

### Host operating system
Mac OS X 10.12.6 

### Guest operating system
Laravel Homestead

### Vagrantfile
```# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION = "2"
confDir = $confDir ||= File.expand_path("~/.homestead")

homesteadYamlPath = confDir + "/Homestead.yaml"
homesteadJsonPath = confDir + "/Homestead.json"
afterScriptPath = confDir + "/after.sh"
aliasesPath = confDir + "/aliases"

require File.expand_path(File.dirname(__FILE__) + '/scripts/homestead.rb')

Vagrant.require_version '>= 1.8.4'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if File.exist? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "~/.bash_aliases"
    end

    if File.exist? homesteadYamlPath then
        settings = YAML::load(File.read(homesteadYamlPath))
    elsif File.exist? homesteadJsonPath then
        settings = JSON.parse(File.read(homesteadJsonPath))
    end

    Homestead.configure(config, settings)

    if File.exist? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath, privileged: false
    end

    if defined? VagrantPlugins::HostsUpdater
        config.hostsupdater.aliases = settings['sites'].map { |site| site['map'] }
    end
end
```
### Issue
When running ```vagrant share``` the following is experienced.

```Michaels-MacBook-Pro:Homestead michaelflanagan$ vagrant share
==> default: Detecting network information for machine...
    default: Local machine address: 192.168.10.10
    default: Local HTTP port: 443
    default: Local HTTPS port: 443
==> default: Checking authentication and authorization...
==> default: Creating Vagrant Share session...
/opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/restclient/abstract_response.rb:48:in `return!': 404 Resource Not Found (RestClient::ResourceNotFound)
	from /opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/restclient/request.rb:269:in `process_result'
	from /opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/restclient/request.rb:212:in `block in transmit'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/net/http.rb:853:in `start'
	from /opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/restclient/request.rb:206:in `transmit'
	from /opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/restclient/request.rb:68:in `execute'
	from /opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/restclient/request.rb:35:in `execute'
	from /opt/vagrant/embedded/gems/gems/rest-client-1.6.9/lib/restclient.rb:74:in `post'
	from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.5/lib/vagrant-share/activate.rb:67:in `create_share'
	from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.5/lib/vagrant-share/activate.rb:1317:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/v2/command.rb:235:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/v2/command.rb:229:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/v2/command.rb:229:in `with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-share-1.1.5/lib/vagrant-share/activate.rb:1178:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:302:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/bin/vagrant:174:in `<main>'```

**Comment by briancain** [comment]
Hi @bubblemedialtd - do you still get this error if you upgrade to the latest version of Vagrant? Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
