### ISSUE TITLE
JSON::ParserError cached_synced_folders

### ISSUE THREAD

**Issue by jakedowns** [hashicorp/vagrant#9264]
### Vagrant version
v2.0.1

### Host operating system
Windows 10 [10.0.16299.98] 64-bit

### Guest operating system
debian/stretch64

### Vagrantfile
```ruby
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "debian/stretch64"

    config.vm.network "private_network", type: "dhcp"

    # config.vm.synced_folder "./src/", "/var/www", type: "nfs" #, mount_options: ['rw', 'tcp', 'fsc' ,'actimeo=1']
    # config.vm.synced_folder "./src/", "/var/www", type: "smb"
    config.vm.synced_folder "./src/", "/var/www", type: "smb", mount_options: ["vers=3.02","mfsymlinks"]
    # config.vm.synced_folder "./src/", "/var/www"
    config.vm.synced_folder "./src/ansible-local", "/vagrant", disabled: false #true

    config.ssh.forward_agent = true

    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
    # Use eth1 IP from vm
    config.hostmanager.ip_resolver = proc do |vm, resolving_vm|
      if vm.id
        `VBoxManage guestproperty get #{vm.id} "/VirtualBox/GuestInfo/Net/1/V4/IP"`.split()[1]
      end
    end

    config.vm.provider :virtualbox do |vb|
        vb.customize [
            "modifyvm", :id,
            "--memory", "4096", # "2048",
            "--ioapic", "on",
            "--rtcuseutc", "on",
            "--natdnshostresolver1", "on",
        ]
    end
end
```

### Debug output
```
C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/json/common.rb:156:in `parse': 751: unexpected token at '' (JSON::ParserError)
  from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/json/common.rb:156:in `parse'
  from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/mixin_synced_folders.rb:236:in `cached_synced_folders'
```
https://gist.github.com/jakedowns/eac5e3ae1a011628adf14769fcc499f3

### Expected behavior
Vagrant Up without errors

### Actual behavior
Vagrant Up with this error

**Comment by chrisroberts** [comment]
Does this error persist after running a `vagrant destroy` and then `vagrant up`?

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
