### ISSUE TITLE
`vagrant package` returns `uninitialized constant` error.

### ISSUE THREAD

**Issue by zilti** [hashicorp/vagrant#9303]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 2.0.1

### Host operating system
OpenSuSE Tumbleweed

### Console Error
```
zilti@Desktop:~/projects/vagrantboxes> vagrant package --base vagrant-mageia-6
/usr/share/vagrant/plugins/providers/virtualbox/action/package_setup_folders.rb:8:in `<module:Action>': uninitialized constant Vagrant::Action::General::PackageSetupFolders (NameError)
        from /usr/share/vagrant/plugins/providers/virtualbox/action/package_setup_folders.rb:7:in `<module:ProviderVirtualBox>'
        from /usr/share/vagrant/plugins/providers/virtualbox/action/package_setup_folders.rb:6:in `<module:VagrantPlugins>'
        from /usr/share/vagrant/plugins/providers/virtualbox/action/package_setup_folders.rb:5:in `<top (required)>'
        from /usr/lib64/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib64/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/vagrant/plugins/providers/virtualbox/action.rb:157:in `block (2 levels) in action_package'
        from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-1.9.7/lib/vagrant/action/builtin/call.rb:47:in `call'
        from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-1.9.7/lib/vagrant/action/warden.rb:34:in `call'
        from /usr/share/vagrant/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
        from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-1.9.7/lib/vagrant/action/warden.rb:34:in `call'
        from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-1.9.7/lib/vagrant/action/builder.rb:116:in `call'
        from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-1.9.7/lib/vagrant/action/runner.rb:66:in `block in run'
        from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-1.9.7/lib/vagrant/util/busy.rb:19:in `busy'
        from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-1.9.7/lib/vagrant/action/runner.rb:66:in `run'
        from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-1.9.7/lib/vagrant/machine.rb:227:in `action_raw'
        from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-1.9.7/lib/vagrant/machine.rb:202:in `block in action'
        from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-1.9.7/lib/vagrant/environment.rb:597:in `lock'
        from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-1.9.7/lib/vagrant/machine.rb:188:in `call'
        from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-1.9.7/lib/vagrant/machine.rb:188:in `action'
        from /usr/share/vagrant/plugins/commands/package/command.rb:90:in `package_vm'
        from /usr/share/vagrant/plugins/commands/package/command.rb:70:in `package_base'
        from /usr/share/vagrant/plugins/commands/package/command.rb:43:in `execute'
        from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-1.9.7/lib/vagrant/cli.rb:42:in `execute'
        from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-1.9.7/lib/vagrant/environment.rb:274:in `cli'
        from /usr/lib64/ruby/gems/2.4.0/gems/vagrant-1.9.7/bin/vagrant:122:in `<top (required)>'
        from /usr/bin/vagrant:23:in `load'
        from /usr/bin/vagrant:23:in `<main>'
```

**Comment by briancain** [comment]
Hi @zilti - I see from the issue you mentioned you're using Vagrant 2.0.1, but your debug log says 1.9.7...are you also experiencing this on 2.0.1? Thanks!

**Comment by zilti** [comment]
Yes. When I first reported it, I tested it on 1.9.7, as the log shows. Someone on IRC told me it is an outdated version, so I updated to 2.0.1 but encountered the exact same problem.
