### ISSUE TITLE
vagrant 2.0.2 can not establish SSH connection to VM

### ISSUE THREAD

**Issue by vinod-990** [hashicorp/vagrant#9448]
Hi,

### Vagrant version
```
○ → vagrant -v
Vagrant 2.0.2
```
### Host operating system
```
○ → cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"
```
### Guest operating system
```
> cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.4 (Maipo)
```
### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.ssh.default.username = "tru-one"
  config.ssh.default.private_key_path = "id_dsa.truone"
```

### vagrant up rhel-custom-590
```
==> rhel-custom-590: Waiting for machine to boot. This may take a few minutes...
    rhel-custom-590: SSH address: 127.0.0.1:2200
    rhel-custom-590: SSH username: tru-one
    rhel-custom-590: SSH auth method: private key
    rhel-custom-590: Warning: Connection reset. Retrying...
    rhel-custom-590: Warning: Remote connection disconnect. Retrying...
    rhel-custom-590: Warning: Connection reset. Retrying...
    rhel-custom-590: Warning: Remote connection disconnect. Retrying...
    rhel-custom-590: Warning: Connection reset. Retrying...
    rhel-custom-590: Warning: Remote connection disconnect. Retrying...
    rhel-custom-590: Warning: Connection reset. Retrying...
    rhel-custom-590: Warning: Remote connection disconnect. Retrying...
    rhel-custom-590: Warning: Connection reset. Retrying...
    rhel-custom-590: Warning: Remote connection disconnect. Retrying...
    rhel-custom-590: Warning: Connection reset. Retrying...
/opt/vagrant/embedded/gems/gems/net-ssh-4.2.0/lib/net/ssh/transport/openssl.rb:74:in `ssh_do_verify': uninitialized constant OpenSSL::Digest::DSS1 (NameError)
        from /opt/vagrant/embedded/gems/gems/net-ssh-4.2.0/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:206:in `verify_signature'
        from /opt/vagrant/embedded/gems/gems/net-ssh-4.2.0/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:69:in `exchange_keys'
        from /opt/vagrant/embedded/gems/gems/net-ssh-4.2.0/lib/net/ssh/transport/algorithms.rb:381:in `exchange_keys'
        from /opt/vagrant/embedded/gems/gems/net-ssh-4.2.0/lib/net/ssh/transport/algorithms.rb:201:in `proceed!'
        from /opt/vagrant/embedded/gems/gems/net-ssh-4.2.0/lib/net/ssh/transport/algorithms.rb:149:in `accept_kexinit'
        from /opt/vagrant/embedded/gems/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
        from /opt/vagrant/embedded/gems/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:188:in `loop'
        from /opt/vagrant/embedded/gems/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:188:in `poll_message'
        from /opt/vagrant/embedded/gems/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:225:in `block in wait'
        from /opt/vagrant/embedded/gems/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:223:in `loop'
        from /opt/vagrant/embedded/gems/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:223:in `wait'
        from /opt/vagrant/embedded/gems/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:88:in `initialize'
        from /opt/vagrant/embedded/gems/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `new'
        from /opt/vagrant/embedded/gems/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `start'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/communicators/ssh/communicator.rb:409:in `block (2 levels) in connect'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/communicators/ssh/communicator.rb:383:in `block in connect'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/util/retryable.rb:17:in `retryable'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/communicators/ssh/communicator.rb:382:in `connect'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/communicators/ssh/communicator.rb:83:in `block in wait_for_ready'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/communicators/ssh/communicator.rb:61:in `wait_for_ready'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'
```

The issue appeared after the update from vagrant 2.0.1 to 2.0.2. I tried to rollback and all is OK, so the issue is actual only for vagrant 2.0.2

Here is the difference between 2.0.1 and 2.0.2:
```
vagrant 2.0.1:
± |master ?:1 ✗| → ll /opt/vagrant/embedded/lib/libssl.so*
-r-xr-xr-x 1 root root 513976 Nov  2 02:10 /opt/vagrant/embedded/lib/libssl.so
-r-xr-xr-x 1 root root 513976 Nov  2 02:10 /opt/vagrant/embedded/lib/libssl.so.1.0.0

vagrant 2.0.2:
± |master ?:1 ✗| → ll /opt/vagrant/embedded/lib/libssl.so*
-rwxr-xr-x 1 root root 525731 Jan 29 19:46 /opt/vagrant/embedded/lib/libssl.so
-rwxr-xr-x 1 root root 525731 Jan 29 19:46 /opt/vagrant/embedded/lib/libssl.so.1.1
```

net -ssh-4.2.0 still uses DSS1 algorithm, but libssl.so.1.1 does not support it. I tried to patch /opt/vagrant/embedded/gems/gems/net-ssh-4.2.0/lib/net/ssh/transport/openssl.rb to use SHA1 insted of DSS1 and the issue has gone ( https://github.com/net-ssh/net-ssh/issues/503 )

It looks like the dependency issue in vagrant-2.0.2. Could you please shed the light on the issue?

**Comment by briancain** [comment]
Hi, it looks like this has been fixed upstream in net-ssh. Once they've cut a new release, we'll update our dependency in Vagrant and get this fixed. Thanks!

**Comment by briancain** [comment]
Moving into a "secondary" milestone. We will bring in this issue and update our dependency on net-ssh once 5.0.0 gets out of beta.

**Comment by aston-r** [comment]
@briancain 
It is finally released: https://github.com/net-ssh/net-ssh/releases/tag/v5.0.0

**Comment by briancain** [comment]
Thanks @aston-r , we'll get it out soon in an upcoming release!!

**Comment by punkrokk** [comment]
Is there a work around for this?
