### ISSUE TITLE
Cannot install winrm plugin in Vagrant 2.0.1 with VirtualBox 5.2.6 r120293

### ISSUE THREAD

**Issue by petkaze** [hashicorp/vagrant#9475]
### Vagrant version
2.0.1

### Host operating system
Fedora 27

### Guest operating system
win-7-professional-i386-nocm

### Vagrantfile
Not used yet, trying to install a plugin so that I can run the Vagrantfile...

### Expected behavior
I give the following command:
vagrant plugin install winrm
I expect this to install the winrm plugin.

### Actual behavior
The above command fails with the following output:
Installing the 'winrm' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies json (= 2.0.4) and json (= 2.1.0)
  Activated json-2.1.0
  which does not match conflicting dependency (= 2.0.4)

  Conflicting dependency chains:
    json (= 2.1.0), 2.1.0 activated

  versus:
    json (= 2.0.4)

  Gems matching json (= 2.0.4):
    json-2.0.4

### Steps to reproduce
See above.

**Comment by briancain** [comment]
Hi @petkaze - You should not have to install the winrm plugin as it is now fully integrated into Vagrant itself. The actual error you are seeing is likely from installing the [rubygem winrm](https://rubygems.org/gems/winrm/versions/1.8.1). Thanks!

**Comment by petkaze** [comment]
Hi @briancain 

Thanks for looking at this. That is kind of strange, since I get this error when I run vagrant up:

```
windows-vm git:(master) ✗ vagrant up
/home/peter/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- winrm (LoadError)
	from /home/peter/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/vagrant/gems/gems/vagrant-2.0.1/plugins/communicators/winrm/shell.rb:9:in `block in <top (required)>'
	from /usr/share/vagrant/gems/gems/vagrant-2.0.1/lib/vagrant/util/silence_warnings.rb:8:in `silence!'
	from /usr/share/vagrant/gems/gems/vagrant-2.0.1/plugins/communicators/winrm/shell.rb:8:in `<top (required)>'
	from /usr/share/vagrant/gems/gems/vagrant-2.0.1/plugins/communicators/winrm/communicator.rb:6:in `require_relative'
	from /usr/share/vagrant/gems/gems/vagrant-2.0.1/plugins/communicators/winrm/communicator.rb:6:in `<top (required)>'
	from /home/peter/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/peter/.rvm/rubies/ruby-2.4.2/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/vagrant/gems/gems/vagrant-2.0.1/plugins/communicators/winrm/plugin.rb:15:in `block in <class:Plugin>'
	from /usr/share/vagrant/gems/gems/vagrant-2.0.1/lib/vagrant/registry.rb:27:in `get'
	from /usr/share/vagrant/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:248:in `communicate'
	from /usr/share/vagrant/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:140:in `initialize'
	from /usr/share/vagrant/gems/gems/vagrant-2.0.1/lib/vagrant/vagrantfile.rb:79:in `new'
	from /usr/share/vagrant/gems/gems/vagrant-2.0.1/lib/vagrant/vagrantfile.rb:79:in `machine'
	from /usr/share/vagrant/gems/gems/vagrant-2.0.1/lib/vagrant/environment.rb:733:in `machine'
	from /usr/share/vagrant/gems/gems/vagrant-2.0.1/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
	from /usr/share/vagrant/gems/gems/vagrant-2.0.1/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
	from /usr/share/vagrant/gems/gems/vagrant-2.0.1/lib/vagrant/plugin/v2/command.rb:186:in `each'
	from /usr/share/vagrant/gems/gems/vagrant-2.0.1/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
	from /usr/share/vagrant/gems/gems/vagrant-2.0.1/plugins/commands/up/command.rb:87:in `execute'
	from /usr/share/vagrant/gems/gems/vagrant-2.0.1/lib/vagrant/cli.rb:42:in `execute'
	from /usr/share/vagrant/gems/gems/vagrant-2.0.1/lib/vagrant/environment.rb:308:in `cli'
	from /usr/share/vagrant/gems/gems/vagrant-2.0.1/bin/vagrant:138:in `<top (required)>'
	from /usr/share/vagrant/gems/bin/vagrant:23:in `load'
	from /usr/share/vagrant/gems/bin/vagrant:23:in `<main>'
```

## Vagrant file contents
```
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "opentable/win-7-professional-i386-nocm"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```

That error led me to believe that I needed to install winrm. Is there something else that is missing then?

**Comment by briancain** [comment]
Are you running Vagrant from source?
