### ISSUE TITLE
configure_networks.rb:23:in `[]': no implicit conversion from nil to integer (TypeError)

### ISSUE THREAD

**Issue by Cylindric** [hashicorp/vagrant#9513]
### Vagrant version
Vagrant 2.0.2

### Host operating system
macOS High Sierra (10.13.3)

### Guest operating system
Centos (geerlingguy/centos7)

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.network "public_network", bridge: "en4: USB 10/100/1000 LAN"
	config.vm.synced_folder ".", "/vagrant", disabled: true

	config.vm.provider "virtualbox" do |vb|
		vb.memory = "512"
		vb.linked_clone = true
	end


	config.vm.define "router", autostart: true do |srv|
		srv.vm.box = "geerlingguy/centos7"
		srv.vm.network "private_network", adapter: "1", type: "dhcp"
		srv.vm.network "public_network",  adapter: "2", type: "dhcp"
		srv.vm.network "forwarded_port", guest: 22, host: 2222
		srv.vm.provider "virtualbox" do |vb|
			vb.name = "Router"
			vb.customize ["modifyvm", :id, "--nic1", "nat"]
			vb.customize ["modifyvm", :id, "--natpf1", "vagrantssh,tcp,,2222,,22"]
		end
	end

end
```

### Debug output
https://gist.github.com/Cylindric/f65f853419c57f97d0733b86ec2eb294

### Expected behavior
New vm should be created with two NICs, first one NAT, second one public, with a port forwarded from 2222 to 22.

### Actual behavior
The vm is created, and seems to be configured because SSH connects, but then it shuts itself down and dumps a ruby error.

### Steps to reproduce
1. ```vagrant up```

### References
none

---

I realise that the end effect of this config can be achieved without the custom messing about with NIC types and manual port forwarding, but the actual result I'm looking for is a machine with 4 NICs, none of which are the required NAT one with port-forwarding, as I'm building a test-environment router.

nic1 - bridged to the real network via my machine
nic2 - private "production" network
nic3 - private "staging" network
nic4 - private "develop" network
nic5 - temporary NAT network just so vagrant will SSH to provision

So I want to create a 5th temporary NIC so the vagrant provisioning works, and I can afterwards remove.

```
UAC00007:Vagrant mhanford$ vagrant destroy -f router && vagrant up router
==> router: VM not created. Moving on...
Bringing machine 'router' up with 'virtualbox' provider...
==> router: Cloning VM...
==> router: Matching MAC address for NAT networking...
==> router: Checking if box 'geerlingguy/centos7' is up to date...
==> router: Setting the name of the VM: Router
==> router: Clearing any previously set network interfaces...
==> router: Available bridged network interfaces:
1) en4: USB 10/100/1000 LAN
2) en0: Wi-Fi (AirPort)
3) awdl0
4) en1: Thunderbolt 1
5) en2: Thunderbolt 2
6) bridge0
==> router: When choosing an interface, it is usually the one that is
==> router: being used to connect to the internet.
    router: Which interface should the network bridge to? 1
==> router: Available bridged network interfaces:
1) en4: USB 10/100/1000 LAN
2) en0: Wi-Fi (AirPort)
3) awdl0
4) en1: Thunderbolt 1
5) en2: Thunderbolt 2
6) bridge0
==> router: When choosing an interface, it is usually the one that is
==> router: being used to connect to the internet.
    router: Which interface should the network bridge to? 1
==> router: Preparing network interfaces based on configuration...
    router: Adapter 1: nat
    router: Adapter 2: bridged
    router: Adapter 1: hostonly
    router: Adapter 2: bridged
==> router: Forwarding ports...
    router: 22 (guest) => 2222 (host) (adapter 1)
    router: VirtualBox adapter #1 not configured as "NAT". Skipping port
    router: forwards on this adapter.
    router: 22 (guest) => 2222 (host) (adapter 1)
    router: VirtualBox adapter #1 not configured as "NAT". Skipping port
    router: forwards on this adapter.
==> router: Running 'pre-boot' VM customizations...
==> router: Booting VM...
==> router: Waiting for machine to boot. This may take a few minutes...
    router: SSH address: 127.0.0.1:2222
    router: SSH username: vagrant
    router: SSH auth method: private key
    router: 
    router: Vagrant insecure key detected. Vagrant will automatically replace
    router: this with a newly generated keypair for better security.
    router: 
    router: Inserting generated public key within guest...
    router: Removing insecure key from the guest if it's present...
    router: Key inserted! Disconnecting and reconnecting using new SSH key...
==> router: Machine booted and ready!
==> router: Checking for guest additions in VM...
==> router: Configuring and enabling network interfaces...
==> router: Forcing shutdown of VM...
==> router: Destroying VM and associated drives...
/opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/guests/redhat/cap/configure_networks.rb:23:in `[]': no implicit conversion from nil to integer (TypeError)
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/guests/redhat/cap/configure_networks.rb:23:in `block in configure_networks'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/guests/redhat/cap/configure_networks.rb:22:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/guests/redhat/cap/configure_networks.rb:22:in `with_index'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/guests/redhat/cap/configure_networks.rb:22:in `configure_networks'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/capability_host.rb:111:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/capability_host.rb:111:in `capability'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/guest.rb:43:in `capability'
```

**Comment by Cylindric** [comment]
Actually, this seems to happen in less complicated setups than this too.  I just pared my config down to find the lowest-failing example, and this fails:


```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.synced_folder ".", "/vagrant", disabled: true
	config.vm.box = "geerlingguy/centos7"
	config.vm.network "private_network", adapter: "2", type: "dhcp"
end
```

The vm is created with NIC1 being the default generated NAT interface, with the correct 2222:22 port forwarding, and the SSH connects fine during the "up", but then crashes with the original error.

It seems forcing _any_ adapters to  a specific ID, breaks everything. If I leave off the `adapter: "2"`, it builds fine, and I end up with the same two adapters:

* Adapter 1: NAT
* Adapter 2: Host-only Adapter, 'vboxnet0'

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
