### ISSUE TITLE
C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/providers/virtualbox/driver/version_5_0.rb:388:in `split': invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by ferenczy** [hashicorp/vagrant#9549]
I have just upgraded Vagrant from the version 1.9.1 to the 2.0.2 (32 bit) and I got the following error when running the `vagrant up` command:

    C:/Program Files (x86)/Vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/providers/virtualbox/driver/version_5_0.rb:388:in `split': invalid byte sequence in UTF-8 (ArgumentError)

I did some investigation and I have found out that before even attempting to start a VM, Vagrant is listing details of all VMs registered in VirtualBox (which is my provider):

    VBoxManage list vms
    VBoxManage showvminfo <vm-guid> --machinereadable
    VBoxManage showvminfo <another-vm-guid> --machinereadable
    ...

In my case, Vagrant crashed after getting the info of the second VM registered in Virtualbox, so I have executed the command `VBoxManage showvminfo <another-vm-guid> --machinereadable` manually and I have found out that I had a **description field in Virtualbox VM's settings written in Czech language** there. So I have just changed it so it contains only ASCII characters and after the next attempt to run `vagrant up`, it successfully started my VM.

Just a note: that "invalid" description had the VM not even managed by Vagrant. Vagrant is trying to get the VM information for all VMs registered in Virtualbox, for some reason.

### Host operating system
Windows 7 Ultimate 64-bit

### Guest operating system
Ubuntu 14.04.5

**Comment by LordFPL** [comment]
Same here for information : 
```
C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/providers/virtualbox/driver/version_5_0.rb:388:in `split': invalid byte sequence in UTF-8 (ArgumentError)
```

**Comment by zach007** [comment]
hi , would you please tell me how to change vm info manually , i got this error -> i have change my internet  drive and I think it cause this problem .

**Comment by broomerr** [comment]
You will have this error if  you have path to image files of registered VM (inside virtualbox) in non latin alphabet.
That could be image which you NOT start, but it just present in Virtualbox. Inside Virtualbox those VM will just perfectly run. So this problem is not  for Virtualbox, but for Vagrant/Ruby.

So current workaround is:
1. to check ALL images in Virtualbox
2. and correct all paths which has non-latin/strange symbols. Optionally you could just remove such image.

As mentioned above you could check properties with:
```
VBoxManage list vms
VBoxManage showvminfo <vm-guid> --machinereadable

```
