### ISSUE TITLE
Command `vagrant up` dependency error on macOS

### ISSUE THREAD

**Issue by universonic** [hashicorp/vagrant#9599]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

Vagrant 2.0.3

### Host operating system
This is the operating system that you run locally.

macOS High Sierra 10.13.3

### Guest operating system
This is the operating system you run in the virtual machine.

RHEL 7.4.

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

$script = <<SCRIPT
echo "Applying Post-provision Script..."
cp /shared/config/universonic.repo /etc/yum.repos.d/
yum -y install yum-utils
yum-config-manager --disable \*
yum-config-manager --enable rhel-7-server-rpms --enable rhel-7-server-optional-rpms \
  --enable rhel-7-server-extras-rpms --enable rhel-7-fast-datapath-rpms \
  --enable rhel-7-server-ose-3.7-rpms --enable rhel-server-rhscl-7-rpms
yum -y install atomic-openshift-clients && yum -y upgrade
nmcli conn add type bridge ifname br-dataplane con-name br-dataplane
nmcli conn modify br-dataplane bridge.stp no
nmcli conn modify br-dataplane ipv4.method manual ipv4.address "172.23.1.10/24" ipv4.gateway "172.23.1.1"
nmcli conn add type bridge-slave ifname eth1 master br-dataplane
nmcli conn modify br-dataplane ipv4.never-default true
nmcli conn modify br-dataplane ipv6.never-default true
nmcli conn up br-dataplane
yum -y install docker && echo '{"bridge":"br-dataplane","insecure-registries":["172.30.0.0/16"]}' > /etc/docker/daemon.json
systemctl daemon-reload && systemctl enable docker
cat >> /etc/hosts <<EOF
172.23.1.1  kamikaze.local kamikaze
172.23.1.10 openshift.local openshift
EOF
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.define :openshift do |guest|
    guest.vm.box = "universonic/rhel-7.4"
    guest.vm.provision "shell", inline: $script
    guest.vm.hostname = "openshift.local"
    guest.vm.provider :parallels do |v|
        v.name = "OpenShift Standalone"
        v.memory = 8192
        v.cpus = 4
        v.update_guest_tools = true
    end
    guest.vm.network "private_network", ip: "172.23.1.10", auto_config: false
    guest.vm.synced_folder "/Volumes/YAMAKAZE/RPMS/", "/shared/", owner: "root", group: "root"
  end
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
(NO DEBUG)

### Expected behavior
It should simply boot up my VM.

### Actual behavior
What actually happened?

Output:
```bash
[universonic@KAMIKAZE openshift]$ vagrant up
/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': incompatible library version - /Users/universonic/.vagrant.d/gems/2.4.3/gems/nokogiri-1.8.2/lib/nokogiri/nokogiri.bundle (LoadError)
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/universonic/.vagrant.d/gems/2.4.3/gems/nokogiri-1.8.2/lib/nokogiri.rb:32:in `rescue in <top (required)>'
	from /Users/universonic/.vagrant.d/gems/2.4.3/gems/nokogiri-1.8.2/lib/nokogiri.rb:28:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/universonic/.vagrant.d/gems/2.4.3/gems/vagrant-parallels-1.7.8/lib/vagrant-parallels/driver/base.rb:2:in `<top (required)>'
	from /Users/universonic/.vagrant.d/gems/2.4.3/gems/vagrant-parallels-1.7.8/lib/vagrant-parallels/driver/meta.rb:4:in `require_relative'
	from /Users/universonic/.vagrant.d/gems/2.4.3/gems/vagrant-parallels-1.7.8/lib/vagrant-parallels/driver/meta.rb:4:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/universonic/.vagrant.d/gems/2.4.3/gems/vagrant-parallels-1.7.8/lib/vagrant-parallels/provider.rb:16:in `usable?'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/vagrantfile.rb:138:in `machine_config'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/vagrantfile.rb:45:in `machine'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:694:in `machine'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/plugin/v2/command.rb:186:in `each'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/plugins/commands/up/command.rb:87:in `execute'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/cli.rb:46:in `execute'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/environment.rb:269:in `cli'
	from /opt/vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/bin/vagrant:151:in `<main>'

```

### Steps to reproduce
1. Just simply try to boot up any VMs with `vagrant up`

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by universonic** [comment]
Besides, it worked fine when I was using Vagrant 2.0.2

**Comment by briancain** [comment]
@universonic - can you run the plugin expunge command (this will remove all currently installed plugins) and reinstall your plugins to see if that fixes your issue?

```
vagrant plugin expunge
```

Thanks!

**Comment by mediaessenz** [comment]
I had the same problem and `vagrant plugin expunge` solves it!

**Comment by universonic** [comment]
Problem solved. Thanks a lot @briancain .
