### ISSUE TITLE
Bad URI exception for valid URI in v2.0.4

### ISSUE THREAD

**Issue by sebastiaanluca** [hashicorp/vagrant#9725]
### Vagrant version
2.0.4 (2.0.3 had a similar issue IIRC)

### Host operating system
macOS 10.12.6

### Guest operating system
https://vagrantcloud.com/laravel/homestead

### Vagrantfile
Default Homestead installation that works in Vagrant v2.0.2.

### Debug output
https://gist.github.com/sebastiaanluca/dfb6bc20aec18c42675e65910cc67c23

### Expected behavior
The virtual machine should boot.

### Actual behavior
It doesn't, but throws an exception saying the Homestead URI is a bad URI. https://vagrantcloud.com/laravel/homestead works just fine? Also works without a hitch in Vagrant v2.0.2.

```
/opt/vagrant/embedded/lib/ruby/2.4.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): https://vagrantcloud.com/laravel/homestead (URI::InvalidURIError)
	from /opt/vagrant/embedded/lib/ruby/2.4.0/uri/rfc3986_parser.rb:73:in `parse'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/uri/common.rb:231:in `parse'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/plugins/commands/login/middleware/add_authentication.rb:38:in `block in call'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/plugins/commands/login/middleware/add_authentication.rb:37:in `map!'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/plugins/commands/login/middleware/add_authentication.rb:37:in `call'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/environment.rb:510:in `hook'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/box_collection.rb:312:in `call'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/box_collection.rb:312:in `block (3 levels) in find'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/box_collection.rb:302:in `each'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/box_collection.rb:302:in `block (2 levels) in find'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/box_collection.rb:295:in `each'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/box_collection.rb:295:in `block in find'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/box_collection.rb:448:in `block in with_collection_lock'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/box_collection.rb:447:in `with_collection_lock'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/box_collection.rb:271:in `find'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/vagrantfile.rb:168:in `block in machine_config'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/vagrantfile.rb:202:in `machine_config'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/vagrantfile.rb:45:in `machine'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/environment.rb:700:in `machine'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/plugin/v2/command.rb:186:in `each'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/plugins/commands/up/command.rb:87:in `execute'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/cli.rb:54:in `execute'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/environment.rb:275:in `cli'
	from /opt/vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/bin/vagrant:151:in `<main>'
```

### Steps to reproduce
1. `vagrant up`

### References
Might be related to https://github.com/hashicorp/vagrant/issues/9582. At least that was the error I was getting with v2.0.3.

**Comment by chrisroberts** [comment]
@sebastiaanluca Can you provide a minimal Vagrantfile that reproduces this issue? Thanks!

**Comment by sebastiaanluca** [comment]
The [Vagrantfile I use](https://gist.github.com/sebastiaanluca/826bb7324344a61deeab90dde99d79bf) is just a default Homestead config with a minor adjustment to point to the correct bash aliases file, etc. As the VM/Homestead works on v2.0.2, I assume the issue has nothing to do with Homestead itself. Unless compatibility got lost during the minor upgrade.

To test:

1. `composer require laravel/homestead --dev`
2. `php vendor/bin/homestead make`
3. _Optionally_ tweak the `Homestead.yaml` file so it works for your environment
4. `vagrant up`
