### ISSUE TITLE
Vagrant crashes when a path to a local basebox contains non-ASCII characters

### ISSUE THREAD

**Issue by dmromanov** [hashicorp/vagrant#9745]
### Vagrant version
2.0.4, 2.1.2

### Host operating system
Ubuntu 18.04 LTS 64bit

### Guest operating system
CentOS 6

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "package.box"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.56.101"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder ".", "/var/www/<cut out>",
  :owner => "www-data",
  :group => "www-data",
  :mount_options => ["dmode=777","fmode=777"]

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:

   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     # vb.gui = true

     # Customize the amount of memory on the VM:
     vb.name = "<cut out>"
     vb.memory = "1024"
     vb.cpus = 4
   end

  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```

### Debug output
https://gist.github.com/dmromanov/9e1633725e4282273cab3a9dd0e8b3db

### Expected behavior
Virtual machine should start normally

### Actual behavior
Vagrant crashed with an error
```
/opt/vagrant/embedded/lib/ruby/2.4.0/uri/rfc3986_parser.rb:21:in `split': URI must be ascii only "file:///home/dmromanov/\u0414\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u044B/\u0420\u0430\u0431\u043E\u0442\u0430/project/package.box" (URI::InvalidURIError)
	from /opt/vagrant/embedded/lib/ruby/2.4.0/uri/rfc3986_parser.rb:73:in `parse'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/uri/common.rb:231:in `parse'
...
```

### Steps to reproduce
1. Place a project in a directory. Path to the directory must contain non-ASCII (e.g. cyrillic) characters.
2. Place a custom basebox to the project directory
3. Run `vagrant up`

### References
No.

**Comment by Glutexo** [comment]
Confirmed on macOS. Got the same error running `vagrant box add`

**Comment by briancain** [comment]
Hey there @dmromanov - This seems to have been fixed in a previous version of Vagrant. I just tested this using the package `2.2.2` on a Ubuntu 18.04 host, with the path you had in your debug log, and Vagrant was able to add  the Vagrant box without issue:

```
Bringing machine 'ubuntu' up with 'virtualbox' provider...
==> ubuntu: Box '/home/vagrant/Документы/Работа/debian-9.5.virtualbox.box' could not be found. Attempting to find and install...
    ubuntu: Box Provider: virtualbox
    ubuntu: Box Version: >= 0
==> ubuntu: Box file was not detected as metadata. Adding it directly...
==> ubuntu: Adding box '/home/vagrant/Документы/Работа/debian-9.5.virtualbox.box' (v0) for provider: virtualbox
    ubuntu: Unpacking necessary files from: file:///home/vagrant/%D0%94%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B/%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0/debian-9.5.virtualbox.box
==> ubuntu: Successfully added box '/home/vagrant/Документы/Работа/debian-9.5.virtualbox.box' (v0) for 'virtualbox'!
==> ubuntu: Importing base box '/home/vagrant/Документы/Работа/debian-9.5.virtualbox.box'...
```

Thanks!
