### ISSUE TITLE
vagrant up fails

### ISSUE THREAD

**Issue by balazs-endresz** [hashicorp/vagrant#981]
After a system restart I started getting this error for all my vagrant boxes, even after manually upgrading to vagrant 1.0.3, virtualbox-4.1_4.1.16-78094 and to Ubuntu 12 as well. Halting, destroying doesn't make any difference, and creating completely new ones produce this error too.

Any help would be very much appreciated.

```
[default] Clearing any previously set forwarded ports...
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "ed617cff-3bd9-47e1-ac31-f51fe478a4dd", "--machinereadable"]
 INFO warden: Calling action: #<Vagrant::Action::Env::Set:0xb6ddca78>
 INFO warden: Calling action: #<Vagrant::Action::VM::CheckPortCollisions:0xb6ddca50>
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "ed617cff-3bd9-47e1-ac31-f51fe478a4dd", "--machinereadable"]
 INFO subprocess: Starting process: ["VBoxManage", "list", "vms"]
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "249c44d6-33df-43b5-915d-2be9a356fdd1", "--machinereadable"]
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "34ad0a1f-53b3-437a-830a-37d2b31a1df8", "--machinereadable"]
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "34ad0a1f-53b3-437a-830a-37d2b31a1df8", "--machinereadable"]
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "34ad0a1f-53b3-437a-830a-37d2b31a1df8", "--machinereadable"]
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["showvminfo", "34ad0a1f-53b3-437a-830a-37d2b31a1df8", "--machinereadable"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["showvminfo", "34ad0a1f-53b3-437a-830a-37d2b31a1df8", "--machinereadable"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["showvminfo", "34ad0a1f-53b3-437a-830a-37d2b31a1df8", "--machinereadable"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["showvminfo", "34ad0a1f-53b3-437a-830a-37d2b31a1df8", "--machinereadable"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["showvminfo", "34ad0a1f-53b3-437a-830a-37d2b31a1df8", "--machinereadable"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["showvminfo", "34ad0a1f-53b3-437a-830a-37d2b31a1df8", "--machinereadable"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["showvminfo", "34ad0a1f-53b3-437a-830a-37d2b31a1df8", "--machinereadable"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::VBoxManageError: There was an error executing the following command with VBoxManage:

["showvminfo", "34ad0a1f-53b3-437a-830a-37d2b31a1df8", "--machinereadable"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.>
ERROR vagrant: There was an error executing the following command with VBoxManage:

["showvminfo", "34ad0a1f-53b3-437a-830a-37d2b31a1df8", "--machinereadable"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR vagrant: /usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/driver/virtualbox_base.rb:278:in `execute'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/util/retryable.rb:14:in `retryable'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/driver/virtualbox_base.rb:268:in `execute'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/driver/virtualbox_4_1.rb:207:in `read_forwarded_ports'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/driver/virtualbox_4_1.rb:375:in `read_used_ports'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/driver/virtualbox_4_1.rb:368:in `each'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/driver/virtualbox_4_1.rb:368:in `read_used_ports'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/action/vm/check_port_collisions.rb:29:in `call'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/action/warden.rb:33:in `call'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/action/env/set.rb:16:in `call'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/action/warden.rb:33:in `call'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/action/vm/clear_forwarded_ports.rb:13:in `call'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/action/warden.rb:33:in `call'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/action/vm/clean_machine_folder.rb:17:in `call'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/action/warden.rb:33:in `call'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/action/vm/check_accessible.rb:18:in `call'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/action/warden.rb:33:in `call'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/action/general/validate.rb:13:in `call'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/action/warden.rb:33:in `call'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/action/general/check_virtualbox.rb:23:in `call'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/action/warden.rb:33:in `call'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/action/builder.rb:92:in `call'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/action/runner.rb:49:in `run'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/util/busy.rb:19:in `busy'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/action/runner.rb:49:in `run'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/vm.rb:192:in `run_action'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/vm.rb:152:in `start'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/command/up.rb:28:in `execute'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/command/base.rb:116:in `with_target_vms'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/command/base.rb:111:in `each'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/command/base.rb:111:in `with_target_vms'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/command/up.rb:24:in `execute'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/cli.rb:42:in `execute'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/lib/vagrant/environment.rb:167:in `cli'
/usr/lib/ruby/gems/1.8/gems/vagrant-1.0.3/bin/vagrant:43
/usr/local/bin/vagrant:19:in `load'
/usr/local/bin/vagrant:19
 INFO interface: error: There was an error executing the following command with VBoxManage:

["showvminfo", "34ad0a1f-53b3-437a-830a-37d2b31a1df8", "--machinereadable"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
There was an error executing the following command with VBoxManage:

["showvminfo", "34ad0a1f-53b3-437a-830a-37d2b31a1df8", "--machinereadable"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
```

**Comment by relaxnow** [comment]
@balazs-endresz thank you for that last comment! That made me wake up and actually read the path to the missing save file and see that it's for an entirely different VM than the one I'm trying to boot.
