### ISSUE TITLE
After update to 2.1.1: monitor.rb:187:in `lock': can't be called from trap context (ThreadError)

### ISSUE THREAD

**Issue by ArminVieweg** [hashicorp/vagrant#9920]
After I've updated 2.0.x to 2.1.1 I can perform a `vagrant up` but then commands like `ssh` or `halt` does not work anymore. They do no response until I interupt them manually (ctrl+c). Then I get this error message:

```
C:\Dev\vagrant>vagrant ssh
C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/monitor.rb:187:in `lock': can't be called from trap context (ThreadError)

        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/monitor.rb:187:in `mon_enter'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/ui.rb:323:in `format_message'
        from (eval):9:in `warn'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:59:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/util/busy.rb:49:in `block in fire_callbacks'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/util/busy.rb:49:in `each'
C:\Dev\vagrant> from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/util/busy.rb:33:in `block (2 levels) in register'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/util/subprocess.rb:170:in `select'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/util/subprocess.rb:170:in `execute'

        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/util/subprocess.rb:22:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/util/powershell.rb:85:in `execute_cmd'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/util/platform.rb:112:in `block (2 levels) in windows_hyperv_enabled?'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/util/platform.rb:110:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/util/platform.rb:110:in `block in windows_hyperv_enabled?'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/util/platform.rb:116:in `windows_hyperv_enabled?'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/providers/virtualbox/action/check_virtualbox.rb:19:in `call'
C:\Dev\vagrant> from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/machine.rb:239:in `action_raw'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/machine.rb:208:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/machine.rb:190:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/machine.rb:194:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/ssh/command.rb:66:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/plugin/v2/command.rb:238:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/plugin/v2/command.rb:232:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/ssh/command.rb:46:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/cli.rb:54:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/environment.rb:275:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/bin/vagrant:156:in `<main>'
```
I've already reinstalled vagrant (using choco on Windows 10) and performed a `plugin expunge --reinstall`. I have no clue how to solve this :(

The machine itself runs. Just can't stop it anymore (from CLI). Commands like status still work, btw.

Thanks!

### Vagrant version
2.1.1

### Host operating system
Windows 10

### Guest operating system
https://app.vagrantup.com/ArminVieweg/boxes/ubuntu-xenial64-lamp

### Vagrantfile
https://github.com/ArminVieweg/ubuntu-xenial64-lamp/blob/master/Vagrantfile

**Comment by ArminVieweg** [comment]
Hm. I've tested the same settings on a different PC. Here it works. But the latest Windows feature updates are on this device not installed yet. 

Also, I did not use "choco" to install it. I try to install it without chocolatey.

**Comment by ArminVieweg** [comment]
Okay. It seems that Vagrant is just not able to get installed using any package management (under Windows only). Tested scoop.sh and chocolatey.

After uninstalling it (using choco) and install it (manually from msi installer), it works like charm.
